import Mathlib

universe u

open CategoryTheory TopologicalSpace

instance : HasSeparator AddCommGrpCat.{u} where
  hasSeparator := by
    use AddCommGrpCat.of (ULift ℤ)
    intro A B f g h; simp_all only [ObjectProperty.singleton_iff, AddCommGrpCat.ext_iff,
      AddCommGrpCat.hom_comp, AddMonoidHom.coe_comp, Function.comp_apply, forall_eq',
      ULift.forall]
    intro x; specialize h (AddCommGrpCat.ofHom
      (AddMonoidHom.mk' (fun y => y • x) fun y z => by simp only [add_smul])) 1; aesop

instance : IsGrothendieckAbelian.{u} AddCommGrpCat.{u} where

instance (X : TopCat.{u}) : Abelian.{u} (TopCat.Sheaf AddCommGrpCat.{u} X) :=
  inferInstanceAs (Abelian (CategoryTheory.Sheaf _ _))

instance (X : TopCat.{u}) : IsGrothendieckAbelian.{u} (TopCat.Sheaf AddCommGrpCat.{u} X) :=
  inferInstanceAs (IsGrothendieckAbelian (CategoryTheory.Sheaf _ _))

/-- DO NOT PROVE — axiom -/
theorem FlasqueVanishing (X : TopCat.{u}) (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (h : ∀ {U V : TopologicalSpace.Opens X} (i : U ⟶ V),
      CategoryTheory.Epi (F.val.map i.op))
    (n : ℕ) :
    Subsingleton (CategoryTheory.Sheaf.H F (n + 1)) := by
  admit

/-- For an irreducible Noetherian space X of positive dimension, vanishing
    of H^n for n > dim X follows from vanishing on all lower-dimensional spaces.

    Hartshorne Steps 3–5:
    - Step 3: By Prop 2.9 (cohomology commutes with direct limits on Noetherian spaces),
      reduce to finitely generated subsheaves F_α
    - Step 4: By induction on # generators, reduce to F generated by a single section
      s ∈ F(U). Then F is a quotient of Z_U. The kernel R is supported on a closed
      subset of dimension < dim X.
    - Step 5: For Z_U, use the short exact sequence 0 → Z_U → Z → Z_Y → 0
      where Y = X \ U. The constant sheaf Z is flasque on irreducible X
      (FlasqueVanishing applies). Z_Y is supported on Y with dim Y < dim X.

    Uses FlasqueVanishing (admitted axiom) and the fact that on an irreducible space,
    the constant sheaf Z has surjective (epi) restriction maps. -/
theorem grothendieck_vanishing_irreducible_pos
    (X : TopCat.{u}) [TopologicalSpace.NoetherianSpace X] [IrreducibleSpace X]
    (n : ℕ) (hn : n > topologicalKrullDim X)
    (hpos : topologicalKrullDim X > 0)
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (ih : ∀ (Y : TopCat.{u}) [TopologicalSpace.NoetherianSpace Y]
      (G : TopCat.Sheaf AddCommGrpCat.{u} Y),
      topologicalKrullDim Y < topologicalKrullDim X →
      n > topologicalKrullDim Y →
      Subsingleton (Sheaf.H G n)) :
    Subsingleton (Sheaf.H F n) := by
  sorry
