-- Harmonic `generalize_proofs` tactic
import Mathlib

universe u

open CategoryTheory TopologicalSpace Abelian Limits Opposite

instance : HasSeparator AddCommGrpCat.{u} where
  hasSeparator := by
    use AddCommGrpCat.of (ULift ℤ)
    intro A B f g h
    simp_all only [ObjectProperty.singleton_iff, AddCommGrpCat.ext_iff,
      AddCommGrpCat.hom_comp, AddMonoidHom.coe_comp, Function.comp_apply, forall_eq',
      ULift.forall]
    intro x
    specialize h (AddCommGrpCat.ofHom
      (AddMonoidHom.mk' (fun y => y • x) fun y z => by simp only [add_smul])) 1
    aesop

instance : IsGrothendieckAbelian.{u} AddCommGrpCat.{u} where

instance (X : TopCat.{u}) : Abelian.{u} (TopCat.Sheaf AddCommGrpCat.{u} X) :=
  inferInstanceAs (Abelian (CategoryTheory.Sheaf _ _))

instance (X : TopCat.{u}) : IsGrothendieckAbelian.{u} (TopCat.Sheaf AddCommGrpCat.{u} X) :=
  inferInstanceAs (IsGrothendieckAbelian (CategoryTheory.Sheaf _ _))

/-- Irreducible positive-dimension vanishing (Hartshorne III.2.7, Steps 3-5).
    For an irreducible Noetherian X of dim ≥ 1, H^n(X, F) = 0 for n > dim X.

    The proof uses NOETHERIAN INDUCTION, not the ClosedImmersionSES approach.
    The ClosedImmersionSES approach fails because the kernel K = ker(F → i_*i^*F)
    has support closure(X \ Z) = X for irreducible X, so K cannot be transferred
    to a smaller-dimensional space.

    Instead, following Hartshorne's proof:
    Step 3: Reduce to finitely generated F via direct limits (Proposition 2.9).
    Step 4: F generated by single section s ∈ F(U). Then F = quotient of Z_U.
    Step 5: Z_U has vanishing cohomology because Z (constant sheaf) is flasque
            on irreducible X, and Z_Y for closed Y has cohomology on Y (dim < n).

    Alternative approach: Use the IH which applies to ALL spaces of smaller dim.
    For any proper closed Z ⊊ X, form the SES 0 → K → F → i_*i^*F → 0.
    The pushforward vanishes by IH. For the kernel: K has zero stalks on Z,
    but supp(K) might be all of X. The key is to use a DIFFERENT decomposition.

    The cleanest approach: show H^n(X, F) = 0 by showing that the Ext group
    Ext(Z', F, n) = 0 where Z' is the constant sheaf. Since Z' is flasque on
    irreducible X, H^n(X, Z') = 0. Use the injective dimension of F relative
    to the cohomological dimension.

    Actually, the simplest correct approach: for any F on irreducible X with dim ≥ 1,
    use the SES 0 → K → F → i_*i^*F → 0 with Z a POINT (0-dim closed subset).
    Then dim Z = 0, so H^n(Z, i^*F) = 0 for n ≥ 1 (by IH or dim 0 vanishing).
    PushforwardHVanishing: H^n(X, i_*i^*F) = 0.
    For K: K has zero stalks at the chosen point z. Apply IrreduciblePosVanishing
    recursively to K with a DIFFERENT point z'. After iterating over enough points,
    the kernel has zero stalks everywhere, hence is the zero sheaf, hence H^n = 0.

    This works because X is Noetherian: the chain of kernels eventually stabilizes
    (by noetherian induction on the set of nonzero-stalk points).

    CRITICAL REALIZATION: We can iterate the ClosedImmersionSES with SINGLE POINTS.
    Each iteration removes one point from the nonzero-stalk locus. On a Noetherian
    space, the descending chain of closed sets (complements of zero-stalk loci)
    stabilizes, giving a kernel with zero stalks everywhere.

    But wait: for irreducible X, removing a single point z from X gives X \ {z}
    which is dense open, and the kernel K still has support = X. The closure of
    the nonzero-stalk locus doesn't decrease!

    The correct approach must use the THEORY OF SUPPORTS or Hartshorne Steps 3-5.

    Simplest formal approach: use well-founded induction on the support.
    Let P(W) = "for all F with supp(F) ⊆ W, H^n(X, F) = 0".
    P(∅): trivial (zero sheaf).
    P(W): for proper closed Z ⊆ W, decompose via Z to get K with supp(K) ⊆ W \ Z.
          If W is irreducible, W \ Z is dense in W... still doesn't decrease.

    FINAL RESOLUTION: The IrreduciblePosVanishing proof needs the FULL Hartshorne
    argument. The simplest formal path is to use that for any sheaf F on irreducible X,
    F admits a filtration 0 ⊆ F₁ ⊆ F₂ ⊆ ... ⊆ F with F_{i+1}/F_i supported on
    proper closed subsets.

    The KEY OBSERVATION: for the constant sheaf A on irreducible X, A is flasque,
    so H^n(X, A) = 0 for n ≥ 1. For any F, the generic stalk F_η gives a map
    F → A_η (constant sheaf with value F_η). The kernel and cokernel of this map
    have PROPER SUPPORT (supported where F → F_η is not an iso, which is a proper
    closed subset for locally constant sheaves near η).

    This is the approach from Stacks Project Tag 01X9 (Noetherian induction).
-/
set_option maxHeartbeats 3200000 in
set_option synthInstance.maxHeartbeats 80000 in
theorem IrreduciblePosVanishing
    (X : TopCat.{u}) [NoetherianSpace X] [IrreducibleSpace X]
    (n : ℕ) (hn : n > topologicalKrullDim X) (hpos : topologicalKrullDim X > 0)
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (ih : ∀ (Y : TopCat.{u}) [NoetherianSpace Y]
      (G : TopCat.Sheaf AddCommGrpCat.{u} Y),
      topologicalKrullDim Y < topologicalKrullDim X →
      n > topologicalKrullDim Y →
      Subsingleton (Sheaf.H G n)) :
    Subsingleton (Sheaf.H F n) := by
  sorry
