/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.CliffordRestriction
import McKayConjecture.CharacterTriple.ProjectiveIrreducible
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.TensorProduct.Basis
import Mathlib.RepresentationTheory.Irreducible
import Mathlib.RepresentationTheory.Submodule
import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.SimpleModule.Basic

/-!
# Irreducibility of associated projective tensor products

Let `P` be a projective representation associated with a character triple
`(A, X, θ)`, and let `Q` have the inverse factor set and be trivial on `X`.
The cancelled tensor product is an honest representation of `A`.  This file
proves that it is irreducible exactly when `Q` is projectively irreducible.

The main linear-algebra input is Burnside's density theorem over `ℂ`: the
algebra generated by a finite-dimensional irreducible group representation is
the full endomorphism algebra.  It implies that every subspace of `V ⊗ Z`
stable under the irreducible action on `V` is `V ⊗ S` for a unique subspace
`S ≤ Z`.
-/

noncomputable section

open scoped MonoidAlgebra TensorProduct

universe u v w

namespace McKayConjecture
namespace CharacterTriple

namespace Representation

variable {G : Type u} [Group G]
variable {V : Type v} [AddCommGroup V] [Module ℂ V]

/-- Burnside density for a finite-dimensional irreducible complex
representation: its group algebra acts as every linear endomorphism. -/
theorem asAlgebraHom_surjective_of_isIrreducible
    (ρ : Representation ℂ G V) [ρ.IsIrreducible]
    [Module.Finite ℂ V] :
    Function.Surjective ρ.asAlgebraHom := by
  let D := Module.End ℂ[G] ρ.asModule
  letI : Module.Finite D ρ.asModule :=
    Module.Finite.of_restrictScalars_finite ℂ D ρ.asModule
  have hschur :
      Function.Surjective (algebraMap ℂ D) :=
    (IsSimpleModule.algebraMap_end_bijective_of_isAlgClosed
      (A := ℂ[G]) (V := ρ.asModule) ℂ).2
  intro e
  let eM : Module.End ℂ ρ.asModule :=
    ρ.asModuleEquiv.symm.toLinearMap ∘ₗ
      e ∘ₗ ρ.asModuleEquiv.toLinearMap
  let f : Module.End D ρ.asModule :=
    { toFun := eM
      map_add' := eM.map_add
      map_smul' := by
        intro d m
        obtain ⟨c, rfl⟩ := hschur d
        change eM (c • m) = c • eM m
        exact eM.map_smul c m }
  obtain ⟨r, hr⟩ :=
    Module.Finite.toModuleEnd_moduleEnd_surjective
      (R := ℂ[G]) (M := ρ.asModule) f
  refine ⟨r, ?_⟩
  apply LinearMap.ext
  intro x
  have hx := DFunLike.congr_fun hr (ρ.asModuleEquiv.symm x)
  have hx' := congrArg ρ.asModuleEquiv hx
  simpa [D, f, eM] using hx'

end Representation

namespace TensorProduct

variable {K : Type u} [Field K]
variable {V : Type v} {Z : Type w}
variable [AddCommGroup V] [Module K V]
variable [AddCommGroup Z] [Module K Z]

/-- The copy of `V ⊗ S` inside `V ⊗ Z`, defined as the range of the
canonical tensor map induced by `S.subtype`. -/
def rightTensorSubmodule (V : Type v)
    [AddCommGroup V] [Module K V] (S : Submodule K Z) :
    Submodule K (V ⊗[K] Z) :=
  LinearMap.range (S.subtype.lTensor V)

/-- A pure tensor belongs to `V ⊗ S` when its right factor belongs to `S`. -/
theorem tmul_mem_rightTensorSubmodule
    (S : Submodule K Z) (v : V) {z : Z} (hz : z ∈ S) :
    v ⊗ₜ[K] z ∈ rightTensorSubmodule V S := by
  refine ⟨v ⊗ₜ[K] (⟨z, hz⟩ : S), ?_⟩
  simp

/-- A pair of endomorphisms preserves `V ⊗ S` whenever the second
endomorphism preserves `S`. -/
theorem map_mem_rightTensorSubmodule
    (S : Submodule K Z) (f : Module.End K V) (g : Module.End K Z)
    (hg : ∀ ⦃z : Z⦄, z ∈ S → g z ∈ S)
    ⦃t : V ⊗[K] Z⦄ (ht : t ∈ rightTensorSubmodule V S) :
    TensorProduct.map f g t ∈ rightTensorSubmodule V S := by
  obtain ⟨t, rfl⟩ := ht
  induction t using TensorProduct.induction_on with
  | zero =>
      simp
  | tmul v z =>
      exact tmul_mem_rightTensorSubmodule S (f v) (hg z.property)
  | add x y hx hy =>
      simpa only [map_add] using
        (rightTensorSubmodule V S).add_mem hx hy

/-- A nonzero pure tensor can belong to `V ⊗ S` only when its right factor
belongs to `S`. -/
theorem mem_of_tmul_mem_rightTensorSubmodule
    (S : Submodule K Z) {v : V} (hv : v ≠ 0) {z : Z}
    (ht : v ⊗ₜ[K] z ∈ rightTensorSubmodule V S) :
    z ∈ S := by
  obtain ⟨φ, hφ⟩ := Module.Projective.exists_dual_eq_one K hv
  obtain ⟨t, ht⟩ := ht
  have hslice (u : V ⊗[K] S) :
      TensorProduct.lid K Z
          (φ.rTensor Z (S.subtype.lTensor V u)) =
        ((TensorProduct.lid K S (φ.rTensor S u) : S) : Z) := by
    induction u using TensorProduct.induction_on with
    | zero =>
        simp
    | tmul x y =>
        simp
    | add x y hx hy =>
        simp only [map_add, hx, hy]
        rfl
  let s : S :=
    TensorProduct.lid K S (φ.rTensor S t)
  have hs : (s : Z) = z := by
    rw [← hslice t, ht]
    simp [hφ]
  rw [← hs]
  exact s.property

/-- Dimension of the canonical copy of `V ⊗ S`. -/
theorem finrank_rightTensorSubmodule
    [Module.Finite K V] [Module.Finite K Z]
    (S : Submodule K Z) :
    Module.finrank K (rightTensorSubmodule V S) =
      Module.finrank K V * Module.finrank K S := by
  rw [rightTensorSubmodule]
  rw [LinearMap.finrank_range_of_inj
    (Module.Flat.lTensor_preserves_injective_linearMap
      S.subtype S.subtype_injective)]
  exact Module.finrank_tensorProduct

/-- For a nonzero first factor, `V ⊗ S` is zero exactly when `S` is zero. -/
theorem rightTensorSubmodule_eq_bot_iff
    [Nontrivial V] [Module.Finite K V] [Module.Finite K Z]
    (S : Submodule K Z) :
    rightTensorSubmodule V S = ⊥ ↔ S = ⊥ := by
  rw [← Submodule.finrank_eq_zero,
    finrank_rightTensorSubmodule, Nat.mul_eq_zero]
  simp [Module.finrank_pos.ne']

/-- For a nonzero finite-dimensional first factor, `V ⊗ S` is the whole
tensor product exactly when `S` is the whole second factor. -/
theorem rightTensorSubmodule_eq_top_iff
    [Nontrivial V] [Module.Finite K V] [Module.Finite K Z]
    (S : Submodule K Z) :
    rightTensorSubmodule V S = ⊤ ↔ S = ⊤ := by
  constructor
  · intro h
    apply Submodule.eq_top_of_finrank_eq
    have hdim :
        Module.finrank K (rightTensorSubmodule V S) =
          Module.finrank K (V ⊗[K] Z) := by
      rw [h]
      simp
    rw [finrank_rightTensorSubmodule,
      Module.finrank_tensorProduct] at hdim
    exact Nat.eq_of_mul_eq_mul_left Module.finrank_pos hdim
  · intro h
    apply Submodule.eq_top_of_finrank_eq
    rw [finrank_rightTensorSubmodule,
      Module.finrank_tensorProduct, h]
    simp

/-- Stability under every endomorphism of the first tensor factor. -/
def IsStableUnderFirstEndomorphisms
    (M : Submodule K (V ⊗[K] Z)) : Prop :=
  ∀ (f : Module.End K V) ⦃t : V ⊗[K] Z⦄,
    t ∈ M → TensorProduct.map f LinearMap.id t ∈ M

/-- If a subspace of `V ⊗ Z` is stable under every endomorphism of the
nonzero finite-dimensional first factor, then it is exactly `V ⊗ S` for a
subspace `S ≤ Z`. -/
theorem exists_eq_rightTensorSubmodule
    [Nontrivial V] [Module.Finite K V]
    (M : Submodule K (V ⊗[K] Z))
    (hM : IsStableUnderFirstEndomorphisms M) :
    ∃ S : Submodule K Z, M = rightTensorSubmodule V S := by
  classical
  obtain ⟨v₀ : V, hv₀⟩ := exists_ne (0 : V)
  obtain ⟨φ₀, hφ₀⟩ := Module.Projective.exists_dual_eq_one K hv₀
  let S : Submodule K Z :=
    M.comap (TensorProduct.mk K V Z v₀)
  refine ⟨S, le_antisymm ?_ ?_⟩
  · intro t ht
    let b := Module.Free.chooseBasis K V
    obtain ⟨c, hc⟩ :=
      TensorProduct.eq_repr_basis_left (ℬ := b) t
    rw [← hc]
    apply Submodule.sum_mem
    intro i hi
    have hci : c i ∈ S := by
      change v₀ ⊗ₜ[K] c i ∈ M
      let e : Module.End K V :=
        LinearMap.smulRight (b.coord i) v₀
      have he := hM e ht
      have heq :
          TensorProduct.map e LinearMap.id t =
            v₀ ⊗ₜ[K] c i := by
        rw [← hc]
        simp only [Finsupp.sum, map_sum, TensorProduct.map_tmul,
          e, LinearMap.smulRight_apply, LinearMap.id_apply,
          b.coord_apply, b.repr_self_apply]
        rw [Finset.sum_eq_single i]
        · simp
        · intro j hj hji
          simp [hji]
        · intro hnot
          exact (hnot hi).elim
      rwa [heq] at he
    exact tmul_mem_rightTensorSubmodule S (b i) hci
  · intro t ht
    obtain ⟨t, rfl⟩ := ht
    induction t using TensorProduct.induction_on with
    | zero =>
        simp
    | tmul v z =>
        change v ⊗ₜ[K] (z : Z) ∈ M
        have hz : v₀ ⊗ₜ[K] (z : Z) ∈ M := z.property
        let e : Module.End K V :=
          LinearMap.smulRight φ₀ v
        have he := hM e hz
        simpa [e, hφ₀] using he
    | add x y hx hy =>
        simpa only [map_add] using M.add_mem hx hy

end TensorProduct

namespace ProjectiveRepresentation

variable {A : Type u} [Group A]
variable {V Z : Type}
variable [AddCommGroup V] [Module ℂ V]
variable [AddCommGroup Z] [Module ℂ Z]

/-- The honest representation obtained by tensoring two projective
representations with inverse factor sets. -/
def cancelTensorRepresentation
    (P : ProjectiveRepresentation ℂ A V)
    (Q : ProjectiveRepresentation ℂ A Z)
    (hPQ : P.HasInverseFactorSet Q) :
    Representation ℂ A (V ⊗[ℂ] Z) :=
  linearRepresentationOfAction
    (P.cancelTensorLinearAction Q hPQ)

@[simp]
theorem cancelTensorRepresentation_apply
    (P : ProjectiveRepresentation ℂ A V)
    (Q : ProjectiveRepresentation ℂ A Z)
    (hPQ : P.HasInverseFactorSet Q) (a : A) :
    P.cancelTensorRepresentation Q hPQ a =
      TensorProduct.map (P.operator a) (Q.operator a) :=
  rfl

end ProjectiveRepresentation

namespace AssociatedProjectiveRepresentation

variable {A : Type u} [Finite A] [Group A]
variable {T : CharacterTriple A}
variable {V Z : Type}
variable [AddCommGroup V] [Module ℂ V]
  [Module.Finite ℂ V] [Nontrivial V]
variable [AddCommGroup Z] [Module ℂ Z]
variable {P : ProjectiveRepresentation ℂ A V}

/-- On the normal subgroup, cancellation acts only through the irreducible
associated representation on the first tensor factor. -/
theorem cancelTensorRepresentation_normal
    (R : AssociatedProjectiveRepresentation T V P)
    (Q : ProjectiveRepresentation ℂ A Z)
    (hQ : P.HasInverseFactorSet Q)
    (htriv : Q.IsTrivialOnNormal T)
    (x : T.normalSubgroup) :
    P.cancelTensorRepresentation Q hQ (x : A) =
      TensorProduct.map (R.restriction x) LinearMap.id := by
  rw [ProjectiveRepresentation.cancelTensorRepresentation_apply,
    R.restriction_apply, htriv x]
  rfl

/-- Every subrepresentation of the cancelled tensor representation is, as a
normal-subgroup module, `V ⊗ S` for a subspace `S ≤ Z`. -/
theorem subrepresentation_exists_eq_rightTensorSubmodule
    [Module.Finite ℂ Z]
    (R : AssociatedProjectiveRepresentation T V P)
    (Q : ProjectiveRepresentation ℂ A Z)
    (hQ : P.HasInverseFactorSet Q)
    (htriv : Q.IsTrivialOnNormal T)
    (L : Subrepresentation
      (P.cancelTensorRepresentation Q hQ)) :
    ∃ S : Submodule ℂ Z,
      L.toSubmodule = TensorProduct.rightTensorSubmodule V S := by
  apply TensorProduct.exists_eq_rightTensorSubmodule
  intro f t ht
  let ρN : Representation ℂ T.normalSubgroup V :=
    linearRepresentationOfAction R.restriction
  letI : ρN.IsIrreducible :=
    CliffordRestriction.isIrreducible_of_simple R.fdRestriction
  obtain ⟨r, hr⟩ :=
    Representation.asAlgebraHom_surjective_of_isIrreducible ρN f
  let ρTensor : Representation ℂ T.normalSubgroup (V ⊗[ℂ] Z) :=
    ρN.tprod 1
  have hnormal :
      ∀ (x : T.normalSubgroup) ⦃y : V ⊗[ℂ] Z⦄,
        y ∈ L.toSubmodule → ρTensor x y ∈ L.toSubmodule := by
    intro x y hy
    have hLy := L.apply_mem_toSubmodule (x : A) hy
    rw [R.cancelTensorRepresentation_normal Q hQ htriv x] at hLy
    exact hLy
  have hrmem :
      ρTensor.asAlgebraHom r t ∈ L.toSubmodule :=
    ρTensor.asAlgebraHom_mem_of_forall_mem
      L.toSubmodule hnormal t ht r
  have haction :
      ρTensor.asAlgebraHom r =
        TensorProduct.map (ρN.asAlgebraHom r) LinearMap.id := by
    apply LinearMap.ext
    intro y
    refine TensorProduct.induction_on y ?_ ?_ ?_
    · simp
    · intro v z
      exact Representation.smul_tprod_one_asModule ρN r v z
    · intro x y hx hy
      simpa only [map_add] using congrArg₂ (· + ·) hx hy
  rw [haction, hr] at hrmem
  exact hrmem

/-- A `Q`-stable subspace of the multiplicity factor produces a
subrepresentation of the cancelled tensor representation. -/
def rightTensorSubrepresentation
    (Q : ProjectiveRepresentation ℂ A Z)
    (hQ : P.HasInverseFactorSet Q)
    (S : Submodule ℂ Z) (hS : Q.IsStable S) :
    Subrepresentation (P.cancelTensorRepresentation Q hQ) where
  toSubmodule := TensorProduct.rightTensorSubmodule V S
  apply_mem_toSubmodule a t ht := by
    rw [ProjectiveRepresentation.cancelTensorRepresentation_apply]
    exact TensorProduct.map_mem_rightTensorSubmodule
      (V := V) (Z := Z) S
      (P.operator a : Module.End ℂ V)
      (Q.operator a : Module.End ℂ Z)
      (hS a) ht

omit [Finite A] [Module.Finite ℂ V] [Nontrivial V] in
@[simp]
theorem rightTensorSubrepresentation_toSubmodule
    (Q : ProjectiveRepresentation ℂ A Z)
    (hQ : P.HasInverseFactorSet Q)
    (S : Submodule ℂ Z) (hS : Q.IsStable S) :
    (rightTensorSubrepresentation Q hQ S hS).toSubmodule =
      TensorProduct.rightTensorSubmodule V S :=
  rfl

omit [Finite A] [Module.Finite ℂ V] in
/-- If a subrepresentation has underlying normal-isotypic subspace `V ⊗ S`,
then `S` is stable under the projective multiplicity action. -/
theorem isStable_of_subrepresentation_eq_rightTensorSubmodule
    (Q : ProjectiveRepresentation ℂ A Z)
    (hQ : P.HasInverseFactorSet Q)
    (L : Subrepresentation (P.cancelTensorRepresentation Q hQ))
    (S : Submodule ℂ Z)
    (hL : L.toSubmodule =
      TensorProduct.rightTensorSubmodule V S) :
    Q.IsStable S := by
  intro a z hz
  obtain ⟨v₀ : V, hv₀⟩ := exists_ne (0 : V)
  have ht :
      v₀ ⊗ₜ[ℂ] z ∈ L.toSubmodule := by
    rw [hL]
    exact TensorProduct.tmul_mem_rightTensorSubmodule S v₀ hz
  have hact := L.apply_mem_toSubmodule a ht
  rw [ProjectiveRepresentation.cancelTensorRepresentation_apply,
    TensorProduct.map_tmul, hL] at hact
  apply TensorProduct.mem_of_tmul_mem_rightTensorSubmodule
    S (v := P.operator a v₀) ?_ hact
  exact fun hzero ↦ hv₀ ((P.operator a).injective (by simpa using hzero))

/-- The central structural theorem for an associated projective
representation: after cancellation, tensor irreducibility is exactly
projective irreducibility of the multiplicity factor. -/
theorem cancelTensorRepresentation_isIrreducible_iff
    [Module.Finite ℂ Z]
    (R : AssociatedProjectiveRepresentation T V P)
    (Q : ProjectiveRepresentation ℂ A Z)
    (hQ : P.HasInverseFactorSet Q)
    (htriv : Q.IsTrivialOnNormal T) :
    (P.cancelTensorRepresentation Q hQ).IsIrreducible ↔
      Q.IsIrreducible := by
  constructor
  · intro hTensor
    let ρ := P.cancelTensorRepresentation Q hQ
    have hsimple : IsSimpleModule ℂ[A] ρ.asModule :=
      (Representation.irreducible_iff_isSimpleModule_asModule ρ).mp
        hTensor
    letI : IsSimpleModule ℂ[A] ρ.asModule := hsimple
    letI : Nontrivial ρ.asModule :=
      IsSimpleModule.nontrivial ℂ[A] ρ.asModule
    letI : Nontrivial (V ⊗[ℂ] Z) :=
      ρ.asModuleEquiv.injective.nontrivial
    have htensorPos :
        0 < Module.finrank ℂ (V ⊗[ℂ] Z) :=
      Module.finrank_pos
    rw [Module.finrank_tensorProduct] at htensorPos
    have hZpos : 0 < Module.finrank ℂ Z :=
      Nat.pos_of_mul_pos_left htensorPos
    letI : Nontrivial Z :=
      Module.nontrivial_of_finrank_pos hZpos
    refine ⟨inferInstance, ?_⟩
    intro S hS
    let L : Subrepresentation ρ :=
      rightTensorSubrepresentation Q hQ S hS
    letI : ρ.IsIrreducible := hTensor
    obtain hL | hL := IsSimpleOrder.eq_bot_or_eq_top L
    · left
      have hsub :=
        congrArg Subrepresentation.toSubmodule hL
      change TensorProduct.rightTensorSubmodule V S = ⊥ at hsub
      exact
        (TensorProduct.rightTensorSubmodule_eq_bot_iff S).mp hsub
    · right
      have hsub :=
        congrArg Subrepresentation.toSubmodule hL
      change TensorProduct.rightTensorSubmodule V S = ⊤ at hsub
      exact
        (TensorProduct.rightTensorSubmodule_eq_top_iff S).mp hsub
  · intro hProjective
    letI : Nontrivial Z := hProjective.1
    let ρ := P.cancelTensorRepresentation Q hQ
    have htensorPos :
        0 < Module.finrank ℂ (V ⊗[ℂ] Z) := by
      rw [Module.finrank_tensorProduct]
      exact Nat.mul_pos Module.finrank_pos Module.finrank_pos
    letI : Nontrivial (V ⊗[ℂ] Z) :=
      Module.nontrivial_of_finrank_pos htensorPos
    letI : Nontrivial (Subrepresentation ρ) :=
      ⟨⟨⊥, ⊤, fun h ↦
        bot_ne_top (congrArg Subrepresentation.toSubmodule h)⟩⟩
    refine ⟨fun L ↦ ?_⟩
    obtain ⟨S, hL⟩ :=
      R.subrepresentation_exists_eq_rightTensorSubmodule
        Q hQ htriv L
    have hS : Q.IsStable S :=
      isStable_of_subrepresentation_eq_rightTensorSubmodule
        Q hQ L S hL
    obtain hbot | htop := hProjective.2 S hS
    · left
      apply Subrepresentation.ext
      change L.toSubmodule = ⊥
      rw [hL]
      exact
        (TensorProduct.rightTensorSubmodule_eq_bot_iff S).mpr
          hbot
    · right
      apply Subrepresentation.ext
      change L.toSubmodule = ⊤
      rw [hL]
      exact
        (TensorProduct.rightTensorSubmodule_eq_top_iff S).mpr
          htop

end AssociatedProjectiveRepresentation

end CharacterTriple
end McKayConjecture
