/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.RingTheory.IntegralClosure.IsIntegral.Basic
import Mathlib.RingTheory.RootsOfUnity.Complex
import McKayConjecture.CharacterTriple.FiniteFactorNormalization

/-!
# An integral lattice for a finite complex projective representation

The determinant-normalized factor of a finite-dimensional complex
projective representation takes values in the finite group of roots of
unity of order the dimension.  Adjoining those roots to `ℤ` gives a
finite integral coefficient ring inside `ℂ`.

For a finite group, the span over this coefficient ring of the orbit of
a complex basis is a finitely generated full lattice.  The projective
multiplication law shows directly that every normalized projective
operator preserves this lattice.  Thus no matrix-entry integrality
assumption is needed.
-/

noncomputable section

universe u v w

namespace McKayConjecture
namespace CharacterTriple

open Module Polynomial

/-- The complex values of the `n`th roots of unity. -/
def finiteRootValues (n : ℕ) : Set ℂ :=
  Set.range fun z : rootsOfUnity n ℂ ↦
    (((z : rootsOfUnity n ℂ) : ℂˣ) : ℂ)

/-- The cyclotomic coefficient ring generated over `ℤ` by all complex
`n`th roots of unity. -/
def FiniteRootCoefficientRing (n : ℕ) : Subalgebra ℤ ℂ :=
  Algebra.adjoin ℤ (finiteRootValues n)

namespace FiniteRootCoefficientRing

variable (n : ℕ) [NeZero n]

/-- An `n`th root of unity, regarded as an element of the cyclotomic
coefficient ring. -/
def root (z : rootsOfUnity n ℂ) :
    FiniteRootCoefficientRing n :=
  ⟨((z : ℂˣ) : ℂ),
    Algebra.subset_adjoin (Set.mem_range_self z)⟩

@[simp]
theorem root_coe (z : rootsOfUnity n ℂ) :
    ((root n z : FiniteRootCoefficientRing n) : ℂ) =
      ((z : ℂˣ) : ℂ) :=
  rfl

/-- Every complex `n`th root of unity is integral over `ℤ`. -/
theorem root_isIntegral (z : rootsOfUnity n ℂ) :
    IsIntegral ℤ (((z : rootsOfUnity n ℂ) : ℂˣ) : ℂ) := by
  have hz :
      (((z : rootsOfUnity n ℂ) : ℂˣ) : ℂ) ^ n = 1 :=
    congrArg (fun u : ℂˣ ↦ (u : ℂ)) z.property
  exact
    IsIntegral.of_pow (NeZero.pos n)
      (hz ▸ isIntegral_one)

/-- The cyclotomic coefficient ring is finite as a `ℤ`-module. -/
theorem moduleFinite :
    Module.Finite ℤ (FiniteRootCoefficientRing n) := by
  apply Algebra.finite_adjoin_of_finite_of_isIntegral
  · exact Set.finite_range _
  · rintro _ ⟨z, rfl⟩
    exact root_isIntegral n z

attribute [local instance] moduleFinite

/-- A complex root of unity as a unit of the cyclotomic coefficient
ring. -/
def rootUnit (z : rootsOfUnity n ℂ) :
    (FiniteRootCoefficientRing n)ˣ where
  val := root n z
  inv := root n z⁻¹
  val_inv := by
    apply Subtype.ext
    simp [root]
  inv_val := by
    apply Subtype.ext
    simp [root]

@[simp]
theorem rootUnit_val (z : rootsOfUnity n ℂ) :
    ((rootUnit n z :
        (FiniteRootCoefficientRing n)ˣ) :
      FiniteRootCoefficientRing n) =
      root n z :=
  rfl

/-- Multiplicative inclusion of the finite complex coefficient group
in the cyclotomic coefficient ring. -/
def rootUnitHom :
    rootsOfUnity n ℂ →*
      (FiniteRootCoefficientRing n)ˣ where
  toFun := rootUnit n
  map_one' := by
    apply Units.ext
    apply Subtype.ext
    simp [rootUnit, root]
  map_mul' z w := by
    apply Units.ext
    apply Subtype.ext
    simp [rootUnit, root]

@[simp]
theorem rootUnitHom_apply
    (z : rootsOfUnity n ℂ) :
    rootUnitHom n z = rootUnit n z :=
  rfl

end FiniteRootCoefficientRing

namespace ProjectiveRepresentation

variable {G : Type u} {V : Type v} {ι : Type w}
variable [Group G] [Finite G]
variable [AddCommGroup V] [Module ℂ V]
variable [Module.Finite ℂ V] [Nontrivial V]
variable [Finite ι]

private instance projectiveFinrankNeZero :
    NeZero (Module.finrank ℂ V) :=
  ⟨finrank_pos.ne'⟩

variable
  (P : ProjectiveRepresentation ℂ G V)
  (b : Basis ι ℂ V)

/-- A generator of the integral lattice: a basis vector acted on by a
determinant-normalized projective operator. -/
def integralLatticeGenerator (x : G × ι) : V :=
  P.finiteFactorNormalize.operator x.1 (b x.2)

/-- The cyclotomic-order lattice generated by the finite projective
operator orbit of a complex basis. -/
def integralLattice :
    Submodule
      (FiniteRootCoefficientRing (Module.finrank ℂ V)) V :=
  Submodule.span
    (FiniteRootCoefficientRing (Module.finrank ℂ V))
    (Set.range (P.integralLatticeGenerator b))

theorem integralLattice_moduleFinite :
    Module.Finite
      (FiniteRootCoefficientRing (Module.finrank ℂ V))
      (P.integralLattice b) :=
  Module.Finite.span_of_finite
    (FiniteRootCoefficientRing (Module.finrank ℂ V))
    (Set.finite_range (P.integralLatticeGenerator b))

theorem basis_mem_integralLattice (i : ι) :
    b i ∈ P.integralLattice b := by
  have hgenerator :
      P.integralLatticeGenerator b (1, i) ∈
        P.integralLattice b :=
    Submodule.subset_span (Set.mem_range_self (1, i))
  have hnormalized :
      P.finiteFactorNormalize.operator 1 = 1 :=
    P.finiteFactorNormalize_isNormalized
  rw [integralLatticeGenerator, hnormalized] at hgenerator
  simpa using hgenerator

/-- The integral lattice is full: its complex span is the entire
representation space. -/
theorem complex_span_integralLattice :
    Submodule.span ℂ (P.integralLattice b : Set V) = ⊤ := by
  apply top_unique
  rw [← b.span_eq, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  exact
    Submodule.subset_span
      (P.basis_mem_integralLattice b i)

/-- A normalized projective operator, restricted to scalars in the
cyclotomic coefficient ring. -/
def integralOperator (g : G) :
    V →ₗ[FiniteRootCoefficientRing (Module.finrank ℂ V)] V :=
  P.finiteFactorNormalize.operator g
    |>.toLinearMap
    |>.restrictScalars
      (FiniteRootCoefficientRing (Module.finrank ℂ V))

/-- Every determinant-normalized projective operator preserves the
integral lattice. -/
theorem integralOperator_mem
    (g : G) {x : V}
    (hx : x ∈ P.integralLattice b) :
    P.integralOperator g x ∈ P.integralLattice b := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨⟨h, i⟩, rfl⟩
      let z : rootsOfUnity (Module.finrank ℂ V) ℂ :=
        P.finiteFactorSet g h
      have hgenerator :
          P.integralLatticeGenerator b (g * h, i) ∈
            P.integralLattice b :=
        Submodule.subset_span
          (Set.mem_range_self (g * h, i))
      have hsmul :
          FiniteRootCoefficientRing.root
              (Module.finrank ℂ V) z •
            P.integralLatticeGenerator b (g * h, i) ∈
              P.integralLattice b :=
        (P.integralLattice b).smul_mem _ hgenerator
      have hmul :=
        congrArg
          (fun f : V ≃ₗ[ℂ] V ↦ f (b i))
          (P.finiteFactorNormalize.map_mul g h)
      have hoperator :
          P.integralOperator g
              (P.integralLatticeGenerator b (h, i)) =
            FiniteRootCoefficientRing.root
                (Module.finrank ℂ V) z •
              P.integralLatticeGenerator b (g * h, i) := by
        change
          P.finiteFactorNormalize.operator g
              (P.finiteFactorNormalize.operator h (b i)) =
            (((z :
                rootsOfUnity (Module.finrank ℂ V) ℂ) :
              ℂˣ) : ℂ) •
              P.finiteFactorNormalize.operator (g * h) (b i)
        simpa only [
          LinearEquiv.mul_apply,
          scalarLinearEquiv_apply,
          finiteFactorSet_coe,
          z] using hmul
      rw [hoperator]
      exact hsmul
  | zero =>
      simpa using (P.integralLattice b).zero_mem
  | add x y _ _ hx hy =>
      simpa using (P.integralLattice b).add_mem hx hy
  | smul r x _ hx =>
      simpa using (P.integralLattice b).smul_mem r hx

/-- The normalized projective operator as an endomorphism of the
integral lattice itself. -/
def integralLatticeEndomorphism (g : G) :
    Module.End
      (FiniteRootCoefficientRing (Module.finrank ℂ V))
      (P.integralLattice b) :=
  (P.integralOperator g).domRestrict
    (P.integralLattice b) |>.codRestrict
      (P.integralLattice b)
      (fun x ↦ P.integralOperator_mem b g x.property)

@[simp]
theorem integralLatticeEndomorphism_apply
    (g : G) (x : P.integralLattice b) :
    (P.integralLatticeEndomorphism b g x : V) =
      P.finiteFactorNormalize.operator g x :=
  rfl

end ProjectiveRepresentation

end CharacterTriple
end McKayConjecture
