/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import McKayConjecture.Character.BrauerInductionArithmetic
import McKayConjecture.Character.ElementaryBrauerInductionReduction

/-!
# The elementary-induction coefficient lattice

An elementary induced irreducible character has a completely explicit
coefficient vector: its coordinate at `χ` is the restriction multiplicity
of the inducing character in `χ|_E`.  This file packages the integral span
of those vectors as a subgroup of the free coefficient lattice on
irreducible characters.

It proves that denominator-one Brauer induction is exactly the assertion
that this subgroup is the full coefficient lattice.  It also converts the
standard prime-power congruence argument into an exact criterion for Brauer
induction, using `BrauerInductionArithmetic`.
-/

noncomputable section

open scoped BigOperators

namespace McKayConjecture
namespace ClassFunction

variable {G : Type} [Group G] [Finite G]

noncomputable local instance brauerCoefficientFintypeG :
    Fintype G :=
  Fintype.ofFinite _

noncomputable local instance brauerCoefficientFintypeIrr :
    Fintype (IrreducibleCharacter G) :=
  Fintype.ofFinite _

/-- The integral irreducible-character coefficient vector of one
elementary induced character. -/
def elementaryInductionCoefficient
    (t : ElementaryInductionTerm G) :
    IrreducibleCharacter G → ℤ :=
  fun χ =>
    (CliffordCorrespondence.restrictionMultiplicity
      t.subgroup.subtype t.character χ : ℤ)

/-- The elementary induced class function has the explicit restriction-
multiplicity coefficient vector. -/
theorem inducedClassFunction_eq_integerCharacterCombination_coefficient
    (t : ElementaryInductionTerm G) :
    t.inducedClassFunction =
      IrreducibleCharacter.integerCharacterCombination
        (elementaryInductionCoefficient t) := by
  apply
    eq_integerCharacterCombination_of_normalizedPairing_eq_int
  intro χ
  change
    normalizedPairing
        (induce t.subgroup t.character.toClassFunction)
        χ.toClassFunction =
      (CliffordCorrespondence.restrictionMultiplicity
        t.subgroup.subtype t.character χ : ℂ)
  have hchar :
      t.character.toClassFunction =
        FDRep.characterClassFunction
          t.character.realization := by
    ext s
    exact
      (congrFun t.character.realization_character s).symm
  rw [hchar,
    ← InductionCharacter.ind_characterClassFunction_eq_induce,
    CliffordCorrespondence.normalizedPairing_inducedCharacter_eq_restrictionMultiplicity]

/-- Integral linear combination of the coefficient vectors of elementary
induced characters. -/
def elementaryCoefficientLinearMap :
    (ElementaryInductionTerm G →₀ ℤ) →ₗ[ℤ]
      (IrreducibleCharacter G → ℤ) :=
  Finsupp.linearCombination ℤ elementaryInductionCoefficient

/-- The lattice integrally generated by elementary induced characters,
written inside the free coefficient group on irreducible characters. -/
def elementaryInductionLattice :
    AddSubgroup (IrreducibleCharacter G → ℤ) :=
  (LinearMap.range
    (elementaryCoefficientLinearMap (G := G))).toAddSubgroup

omit [Finite G] in
/-- Membership in the elementary-induction lattice is witnessed by a
finitely supported integral coefficient family. -/
theorem mem_elementaryInductionLattice_iff
    (v : IrreducibleCharacter G → ℤ) :
    v ∈ elementaryInductionLattice (G := G) ↔
      ∃ c : ElementaryInductionTerm G →₀ ℤ,
        elementaryCoefficientLinearMap c = v := by
  rfl

/-- Applying the character-combination map to an elementary coefficient
combination recovers the corresponding sum of induced class functions. -/
theorem elementaryInductionCombination_eq_integerCharacterCombination
    (c : ElementaryInductionTerm G →₀ ℤ) :
    elementaryInductionCombination c =
      IrreducibleCharacter.integerCharacterCombination
        (elementaryCoefficientLinearMap c) := by
  apply
    eq_integerCharacterCombination_of_normalizedPairing_eq_int
  intro χ
  rw [elementaryInductionCombination]
  simp only [map_sum, LinearMap.sum_apply, map_smul,
    LinearMap.smul_apply, smul_eq_mul]
  rw [elementaryCoefficientLinearMap,
    Finsupp.linearCombination_apply]
  change
    (∑ t ∈ c.support,
      (c t : ℂ) *
        normalizedPairing t.inducedClassFunction
          χ.toClassFunction) =
      ((c.sum fun t a =>
        a • elementaryInductionCoefficient t) χ : ℂ)
  have hpair :
      ∀ t : ElementaryInductionTerm G,
        normalizedPairing t.inducedClassFunction
            χ.toClassFunction =
          (elementaryInductionCoefficient t χ : ℂ) := by
    intro t
    rw [
      inducedClassFunction_eq_integerCharacterCombination_coefficient,
      IrreducibleCharacter.normalizedPairing_integerCharacterCombination_irreducible]
  simp_rw [hpair]
  simp only [Finsupp.sum, Finset.sum_apply, Pi.smul_apply,
    smul_eq_mul, Int.cast_sum, Int.cast_mul]

/-- The coefficient vector of one irreducible character. -/
def irreducibleCoefficient
    (χ : IrreducibleCharacter G) :
    IrreducibleCharacter G → ℤ := by
  classical
  exact Pi.single χ 1

/-- The integral character combination of an irreducible basis vector is
the corresponding irreducible character. -/
theorem integerCharacterCombination_irreducibleCoefficient
    (χ : IrreducibleCharacter G) :
    IrreducibleCharacter.integerCharacterCombination
        (irreducibleCoefficient χ) =
      χ.toClassFunction := by
  classical
  rw [IrreducibleCharacter.integerCharacterCombination,
    Finset.sum_eq_single χ]
  · simp [irreducibleCoefficient]
  · intro ψ _hψ hne
    simp [irreducibleCoefficient, hne]
  · simp

/-- Denominator-one Brauer induction is equivalent to every irreducible
basis vector lying in the elementary-induction coefficient lattice. -/
theorem hasElementaryBrauerInduction_iff_irreducibleCoefficient_mem :
    HasElementaryBrauerInduction (G := G) ↔
      ∀ χ : IrreducibleCharacter G,
        irreducibleCoefficient χ ∈
          elementaryInductionLattice (G := G) := by
  constructor
  · intro hind χ
    obtain ⟨c, hc⟩ := hind χ
    have hclass :
        elementaryInductionCombination c =
          χ.toClassFunction := by
      simpa using hc.symm
    refine
      (mem_elementaryInductionLattice_iff
        (G := G) (irreducibleCoefficient χ)).mpr
        ⟨c, ?_⟩
    apply integerCharacterCombination_injective
    rw [← elementaryInductionCombination_eq_integerCharacterCombination,
      hclass,
      ← integerCharacterCombination_irreducibleCoefficient]
  · intro hmem χ
    obtain ⟨c, hc⟩ :=
      (mem_elementaryInductionLattice_iff
        (G := G) (irreducibleCoefficient χ)).mp
        (hmem χ)
    refine ⟨c, ?_⟩
    norm_num only [Int.cast_one, one_smul]
    rw [elementaryInductionCombination_eq_integerCharacterCombination,
      hc, integerCharacterCombination_irreducibleCoefficient]

/-- Every coefficient vector is the sum of its coordinates times the
irreducible basis vectors. -/
theorem sum_smul_irreducibleCoefficient
    (v : IrreducibleCharacter G → ℤ) :
    (∑ χ : IrreducibleCharacter G,
        v χ • irreducibleCoefficient χ) =
      v := by
  classical
  funext ψ
  rw [Finset.sum_apply, Finset.sum_eq_single ψ]
  · simp [irreducibleCoefficient]
  · intro χ _hχ hne
    simp [irreducibleCoefficient, hne]
  · simp

/-- Brauer induction is equivalent to the elementary-induction lattice
being the full coefficient lattice. -/
theorem hasElementaryBrauerInduction_iff_lattice_eq_top :
    HasElementaryBrauerInduction (G := G) ↔
      elementaryInductionLattice (G := G) = ⊤ := by
  rw [hasElementaryBrauerInduction_iff_irreducibleCoefficient_mem]
  constructor
  · intro h
    apply top_unique
    intro v _hv
    rw [← sum_smul_irreducibleCoefficient v]
    exact
      AddSubgroup.sum_mem _ fun χ _hχ =>
        AddSubgroup.zsmul_mem _
          (h χ) (v χ)
  · intro h χ
    rw [h]
    trivial

/-- Exact arithmetic criterion for denominator-one Brauer induction:
every coefficient vector need only be congruent to the elementary-
induction lattice modulo every prime power. -/
theorem hasElementaryBrauerInduction_of_mod_prime_power_coefficients
    (hcongr :
      ∀ (p : ℕ), p.Prime → ∀ n : ℕ,
        ∀ v : IrreducibleCharacter G → ℤ,
          ∃ w ∈ elementaryInductionLattice (G := G),
            ∃ y : IrreducibleCharacter G → ℤ,
              v = w + p ^ n • y) :
    HasElementaryBrauerInduction (G := G) := by
  haveI :
      AddGroup.FG (IrreducibleCharacter G → ℤ) :=
    Module.Finite.iff_addGroup_fg.mp inferInstance
  rw [hasElementaryBrauerInduction_iff_lattice_eq_top]
  exact
    addSubgroup_eq_of_congruent_mod_prime_powers
      (elementaryInductionLattice (G := G))
      ⊤
      le_top
      (by
        intro p hp n v _hv
        exact hcongr p hp n v)

end ClassFunction
end McKayConjecture
