/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.InnerOrbitReduction

/-!
# Extending character equivariance from generators

Let `N ◁ G`, let `H ≤ G`, and let `M ◁ H` map into `N`.  If `H` is
generated by `M` and a subgroup `A`, then an equivalence

`Irr_{p'}(N) ≃ Irr_{p'}(M)`

is `H`-equivariant as soon as it is `A`-equivariant.  Indeed, elements of
`M` act by inner automorphisms on both sides and hence act trivially.

This elementary lemma is the precise passage from layer-Sylow-normalizer
equivariance to equivariance under the full layer intermediate.
-/

noncomputable section

universe u

namespace McKayConjecture
namespace PPrimeIrreducibleCharacter

variable {G : Type u} [Group G]
variable (N H : Subgroup G) [N.Normal]
variable (M A : Subgroup H) [M.Normal]
variable (p : ℕ)

/-- Equivariance under a generating subgroup extends across a normal
subgroup acting by inner automorphisms on both character spaces. -/
theorem equivariant_of_normal_sup_eq_top
    (hMN : M.map H.subtype ≤ N)
    (hsup : M ⊔ A = ⊤)
    (e :
      PPrimeIrreducibleCharacter N p ≃
        PPrimeIrreducibleCharacter M p)
    (he :
      ∀ (a : A)
        (θ : PPrimeIrreducibleCharacter N p),
        e (((a : H) : G) • θ) =
          (a : H) • e θ)
    (h : H)
    (θ : PPrimeIrreducibleCharacter N p) :
    e ((h : G) • θ) = h • e θ := by
  have hh : h ∈ M ⊔ A := by
    rw [hsup]
    exact Subgroup.mem_top h
  obtain ⟨m, hm, a, ha, hma⟩ :=
    Subgroup.mem_sup_of_normal_left.mp hh
  let mM : M := ⟨m, hm⟩
  let aA : A := ⟨a, ha⟩
  have hmN : (((mM : M) : H) : G) ∈ N := by
    apply hMN
    exact
      ⟨(mM : H), mM.property, rfl⟩
  have hfactor : (mM : H) * (aA : H) = h :=
    hma
  calc
    e ((h : G) • θ) =
        e (((((mM : H) * (aA : H)) : H) : G) • θ) := by
      rw [hfactor]
    _ =
        e (((((mM : M) : H) : G) *
          (((aA : A) : H) : G)) • θ) :=
      rfl
    _ =
        e ((((mM : M) : H) : G) •
          ((((aA : A) : H) : G) • θ)) := by
      rw [mul_smul]
    _ = e ((((aA : A) : H) : G) • θ) := by
      rw [normalSubgroup_smul_eq
        N p ⟨(((mM : M) : H) : G), hmN⟩]
    _ = (aA : H) • e θ :=
      he aA θ
    _ = (mM : H) • ((aA : H) • e θ) := by
      rw [normalSubgroup_smul_eq M p mM]
    _ = ((mM : H) * (aA : H)) • e θ := by
      rw [mul_smul]
    _ = h • e θ := by
      rw [hfactor]

end PPrimeIrreducibleCharacter
end McKayConjecture
