/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.ClassFunctionPairing
import McKayConjecture.Character.Gallagher
import McKayConjecture.Character.GlaubermanCyclicFusion
import McKayConjecture.GroupTheory.FiniteDualOrthogonality

/-!
# Character orthogonality on a cyclic generator coset

Let `K` be a normal `p`-complement in a finite group generated by `K`
and a cyclic `p`-subgroup `P`. If an irreducible character of `K`
extends irreducibly to the whole group, the bilinear norm of any such
extension on the coset of the chosen generator of `P` is exactly
`|K|`.

The proof is a finite Fourier argument on `G ⧸ K`. Gallagher's
injectivity theorem says that all quotient-linear twists of the
extension are distinct. Orthogonality of irreducible characters and
orthogonality of the finite complex dual of `G ⧸ K` then isolate the
single generator coset.
-/

noncomputable section

open scoped BigOperators

namespace McKayConjecture

variable {G : Type} [Group G] [Finite G]
variable (K P : Subgroup G) [K.Normal]
variable [IsCyclic P]
variable {p : ℕ} [Fact p.Prime]

/-- The bilinear norm of an irreducible extension on the chosen
generator coset is the order of the normal kernel. -/
theorem cyclicExtension_generatorCoset_bilinearNorm
    [Fintype K]
    (hK : GroupTheory.IsPPrimeGroup p K)
    (hP : IsPGroup p P)
    (hgenerate : K ⊔ P = ⊤)
    (θ : PInvariantPPrimeIrreducibleCharacter K P p)
    (chi : IrreducibleCharacter G)
    (hchi :
      IrreducibleCharacter.IsExtensionAlong
        K.subtype θ.1.1 chi) :
    ∑ k : K,
        chi.values
          (((cyclicSubgroupGenerator P : P) : G) * (k : G)) *
        chi.values
          ((((cyclicSubgroupGenerator P : P) : G) * (k : G))⁻¹) =
      (Nat.card K : ℂ) := by
  classical
  letI : Fintype G := Fintype.ofFinite G
  let Q : Type := G ⧸ K
  let e : Q ≃* P :=
    (cyclicCoprimeKernel_isComplement'
      K P hK hP hgenerate).symm.QuotientMulEquiv
  letI : CommGroup P := IsCyclic.commGroup
  letI : CommGroup Q :=
    e.toMonoidHom.commGroupOfInjective e.injective
  let qK : G →* Q := QuotientGroup.mk' K
  letI : Fintype Q := Fintype.ofFinite Q
  letI : Fintype (Q →* ℂˣ) := Fintype.ofFinite _
  have hinflate_one :
      IrreducibleCharacter.inflateLinearCharacter K
          (1 : Q →* ℂˣ) =
        1 := by
    apply MonoidHom.ext
    intro x
    simp [IrreducibleCharacter.inflateLinearCharacter]
  have hpair :
      ∀ beta : Q →* ℂˣ,
        ClassFunction.normalizedPairing chi.toClassFunction
          (IrreducibleCharacter.twist
            (IrreducibleCharacter.inflateLinearCharacter K beta)
            chi).toClassFunction =
          if beta = 1 then 1 else 0 := by
    intro beta
    by_cases hb : beta = 1
    · subst beta
      rw [hinflate_one, IrreducibleCharacter.twist_one]
      simp
    · simp only [hb, ↓reduceIte]
      apply
        ClassFunction.normalizedPairing_irreducible_eq_zero_of_ne
      intro heq
      apply hb
      apply
        IrreducibleCharacter.quotientTwistExtension_injective hchi
      apply Subtype.ext
      change
        IrreducibleCharacter.twist
            (IrreducibleCharacter.inflateLinearCharacter K beta) chi =
          IrreducibleCharacter.twist
            (IrreducibleCharacter.inflateLinearCharacter K 1) chi
      rw [hinflate_one,
        IrreducibleCharacter.twist_one]
      exact heq.symm
  have hweighted :
      ∑ beta : Q →* ℂˣ,
          (beta (qK
            ((cyclicSubgroupGenerator P : P) : G)) : ℂ) *
            ClassFunction.normalizedPairing chi.toClassFunction
              (IrreducibleCharacter.twist
                (IrreducibleCharacter.inflateLinearCharacter K beta)
                chi).toClassFunction =
        1 := by
    simp_rw [hpair]
    rw [Finset.sum_eq_single (1 : Q →* ℂˣ)]
    · simp
    · intro beta _ hb
      simp [hb]
    · simp
  have hweighted' :
      ∑ beta : Q →* ℂˣ,
          (beta (qK
            ((cyclicSubgroupGenerator P : P) : G)) : ℂ) *
            ((Nat.card G : ℂ)⁻¹ *
              ∑ x : G,
                chi.values x *
                  ((beta (qK x⁻¹) : ℂ) *
                    chi.values x⁻¹)) =
        1 := by
    change
      ∑ beta : Q →* ℂˣ,
          (beta (qK
            ((cyclicSubgroupGenerator P : P) : G)) : ℂ) *
            ((Nat.card G : ℂ)⁻¹ *
              ∑ x : G,
                chi.values x *
                  (IrreducibleCharacter.twist
                    (IrreducibleCharacter.inflateLinearCharacter
                      K beta) chi).values x⁻¹) =
        1 at hweighted
    simpa only [IrreducibleCharacter.twist_values,
      IrreducibleCharacter.inflateLinearCharacter_apply] using
        hweighted
  have hrearrange :
      (∑ beta : Q →* ℂˣ,
          (beta (qK
            ((cyclicSubgroupGenerator P : P) : G)) : ℂ) *
            ((Nat.card G : ℂ)⁻¹ *
              ∑ x : G,
                chi.values x *
                  ((beta (qK x⁻¹) : ℂ) *
                    chi.values x⁻¹))) =
        (Nat.card G : ℂ)⁻¹ *
          ∑ x : G,
            chi.values x * chi.values x⁻¹ *
              ∑ beta : Q →* ℂˣ,
                (beta
                  (qK ((cyclicSubgroupGenerator P : P) : G) *
                    (qK x)⁻¹) : ℂ) := by
    calc
      _ = (Nat.card G : ℂ)⁻¹ *
          ∑ beta : Q →* ℂˣ,
            ∑ x : G,
              (beta (qK
                ((cyclicSubgroupGenerator P : P) : G)) : ℂ) *
                (chi.values x *
                  ((beta (qK x⁻¹) : ℂ) *
                    chi.values x⁻¹)) := by
              rw [Finset.mul_sum]
              apply Finset.sum_congr rfl
              intro beta _
              rw [Finset.mul_sum]
              rw [Finset.mul_sum, Finset.mul_sum]
              apply Finset.sum_congr rfl
              intro x _
              ring
      _ = (Nat.card G : ℂ)⁻¹ *
          ∑ x : G,
            ∑ beta : Q →* ℂˣ,
              (beta (qK
                ((cyclicSubgroupGenerator P : P) : G)) : ℂ) *
                (chi.values x *
                  ((beta (qK x⁻¹) : ℂ) *
                    chi.values x⁻¹)) := by
              rw [Finset.sum_comm]
      _ = _ := by
              congr 1
              apply Finset.sum_congr rfl
              intro x _
              rw [Finset.mul_sum]
              apply Finset.sum_congr rfl
              intro beta _
              simp only [map_inv, map_mul, Units.val_mul,
                Units.val_inv_eq_inv_val]
              ring
  rw [hrearrange] at hweighted'
  have hdual (x : G) :
      (∑ beta : Q →* ℂˣ,
          (beta
            (qK ((cyclicSubgroupGenerator P : P) : G) *
              (qK x)⁻¹) : ℂ)) =
        if qK x =
            qK ((cyclicSubgroupGenerator P : P) : G)
          then (Nat.card Q : ℂ)
          else 0 := by
    by_cases hx :
        qK x =
          qK ((cyclicSubgroupGenerator P : P) : G)
    · simp only [hx, if_pos]
      simpa using
        (sum_complexUnitCharacters_apply_one
          (A := Q))
    · simp only [hx, if_false]
      apply sum_complexUnitCharacters_apply_eq_zero
      intro hone
      apply hx
      have :
          qK ((cyclicSubgroupGenerator P : P) : G) =
            qK x := by
        exact (mul_inv_eq_one.mp hone)
      exact this.symm
  simp_rw [hdual] at hweighted'
  let generator : G :=
    ((cyclicSubgroupGenerator P : P) : G)
  let fiber :=
    {x : G // qK x = qK generator}
  let fiberEquiv : K ≃ fiber := {
    toFun k := by
      refine ⟨generator * (k : G), ?_⟩
      rw [map_mul, show qK (k : G) = 1 from
        (QuotientGroup.eq_one_iff (k : G)).mpr k.2,
        mul_one]
    invFun x := by
      refine
        ⟨generator⁻¹ * (x : G), ?_⟩
      apply
        (QuotientGroup.eq_one_iff
          (generator⁻¹ * (x : G))).mp
      change qK (generator⁻¹ * (x : G)) = 1
      rw [map_mul, map_inv, x.property]
      simp
    left_inv k := by
      apply Subtype.ext
      simp
    right_inv x := by
      apply Subtype.ext
      simp
  }
  have hfiber :
      (∑ x : G,
          if qK x = qK generator
            then chi.values x * chi.values x⁻¹
            else 0) =
        ∑ k : K,
          chi.values (generator * (k : G)) *
            chi.values (generator * (k : G))⁻¹ := by
    calc
      _ =
          ∑ x ∈
              Finset.univ.filter
                (fun x : G ↦ qK x = qK generator),
            chi.values x * chi.values x⁻¹ := by
              symm
              exact
                Finset.sum_filter
                  (fun x : G ↦ qK x = qK generator)
                  (fun x : G ↦
                    chi.values x * chi.values x⁻¹)
      _ =
          ∑ x : fiber,
            chi.values (x : G) *
              chi.values (x : G)⁻¹ := by
              exact
                Finset.sum_subtype
                  (Finset.univ.filter
                    (fun x : G ↦
                      qK x = qK generator))
                  (by simp)
                  (fun x : G ↦
                    chi.values x * chi.values x⁻¹)
      _ = _ := by
        exact
          (Equiv.sum_comp fiberEquiv
            (fun x : fiber ↦
              chi.values (x : G) *
                chi.values (x : G)⁻¹)).symm
  change
    (Nat.card G : ℂ)⁻¹ *
        (∑ x : G,
          chi.values x * chi.values x⁻¹ *
            (if qK x = qK generator
              then (Nat.card Q : ℂ)
              else 0)) =
      1 at hweighted'
  have hfactor :
      (∑ x : G,
          chi.values x * chi.values x⁻¹ *
            if qK x = qK generator
              then (Nat.card Q : ℂ)
              else 0) =
        (Nat.card Q : ℂ) *
          ∑ x : G,
            if qK x = qK generator
              then chi.values x * chi.values x⁻¹
              else 0 := by
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro x _
    by_cases hx : qK x = qK generator <;>
      simp [hx]
    ring
  rw [hfactor, hfiber] at hweighted'
  have hcard :
      Nat.card G =
        Nat.card K * Nat.card Q := by
    calc
      Nat.card G =
          Nat.card K * Nat.card P :=
        (cyclicCoprimeKernel_isComplement'
          K P hK hP hgenerate).card_mul.symm
      _ = Nat.card K * Nat.card Q := by
        rw [Nat.card_congr e.toEquiv]
  have hKne : (Nat.card K : ℂ) ≠ 0 := by
    exact_mod_cast (Nat.card_pos : 0 < Nat.card K).ne'
  have hQne : (Nat.card Q : ℂ) ≠ 0 := by
    exact_mod_cast (Nat.card_pos : 0 < Nat.card Q).ne'
  rw [hcard, Nat.cast_mul] at hweighted'
  field_simp [hKne, hQne] at hweighted'
  simpa [generator] using hweighted'

/-- The determinant-normalized cyclic extension satisfies the
generator-coset bilinear norm formula. -/
theorem determinantNormalizedCyclicExtension_generatorCoset_bilinearNorm
    [Fintype K]
    (hK : GroupTheory.IsPPrimeGroup p K)
    (hP : IsPGroup p P)
    (hgenerate : K ⊔ P = ⊤)
    (θ : PInvariantPPrimeIrreducibleCharacter K P p) :
    ∑ k : K,
        (determinantNormalizedCyclicExtensionCharacter
          K P hK hP hgenerate θ).values
            (((cyclicSubgroupGenerator P : P) : G) * (k : G)) *
        (determinantNormalizedCyclicExtensionCharacter
          K P hK hP hgenerate θ).values
            ((((cyclicSubgroupGenerator P : P) : G) * (k : G))⁻¹) =
      (Nat.card K : ℂ) :=
  cyclicExtension_generatorCoset_bilinearNorm
    K P hK hP hgenerate θ
      (determinantNormalizedCyclicExtensionCharacter
        K P hK hP hgenerate θ)
      (determinantNormalizedCyclicExtensionCharacter_isExtension
        K P hK hP hgenerate θ)

end McKayConjecture
