/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.CyclicExtensionAlong
import McKayConjecture.Character.ExtensionEquivalenceTransport
import McKayConjecture.GroupTheory.InvariantSubgroupAutomorphism
import Mathlib.Algebra.Group.ConjFinite

/-!
# Good elements for an invariant normal character

Let `N ◁ A`, let `θ ∈ Irr(N)`, and let `q ∈ A / N`.  The subgroup
`cyclicOverQuotientElement N q` is the inverse image of `⟨q⟩`, while
`goodElementCentralizer N q` is the inverse image of `C_{A/N}(q)`.  The
latter normalizes the former and hence acts on its irreducible characters.

The quotient element `q` is `θ`-good when every extension of `θ` to the
inverse image of `⟨q⟩` is invariant under that action.  This is Gallagher's
definition.  Defining the primary predicate on `A / N` makes replacement
inside a normal coset literal rather than a later quotient-coherence
obligation.

No invariance hypothesis on `θ` is built into the definition.  The usual
conjugacy-invariance theorem assumes it explicitly.
-/

noncomputable section

universe u

namespace McKayConjecture
namespace IrreducibleCharacter

variable {A : Type u} [Group A]
variable (N : Subgroup A) [N.Normal]

/-- The inverse image in `A` of the cyclic subgroup generated by
`q ∈ A / N`.  For `q = aN`, this is the usual subgroup `N⟨a⟩`. -/
abbrev cyclicOverQuotientElement (q : A ⧸ N) : Subgroup A :=
  (Subgroup.zpowers q).comap (QuotientGroup.mk' N)

/-- The inverse image in `A` of `C_{A/N}(q)`. -/
abbrev goodElementCentralizer (q : A ⧸ N) : Subgroup A :=
  (Subgroup.centralizer ({q} : Set (A ⧸ N))).comap
    (QuotientGroup.mk' N)

/-- The inverse-image model of `N⟨a⟩` agrees with the subgroup generated
by `N` and `a`. -/
theorem cyclicOverQuotientElement_mk_eq (a : A) :
    cyclicOverQuotientElement N (QuotientGroup.mk' N a) =
      N ⊔ Subgroup.zpowers a := by
  change
    (Subgroup.zpowers (QuotientGroup.mk' N a)).comap
        (QuotientGroup.mk' N) = _
  rw [← (QuotientGroup.mk' N).map_zpowers a,
    Subgroup.comap_map_eq, QuotientGroup.ker_mk', sup_comm]

/-- The normal subgroup is contained in every cyclic-over-`N` subgroup. -/
theorem normal_le_cyclicOverQuotientElement (q : A ⧸ N) :
    N ≤ cyclicOverQuotientElement N q := by
  intro n hn
  change QuotientGroup.mk' N n ∈ Subgroup.zpowers q
  have hnq : QuotientGroup.mk' N n = 1 :=
    (QuotientGroup.eq_one_iff n).mpr hn
  rw [hnq]
  exact (Subgroup.zpowers q).one_mem

/-- The preimage of the quotient centralizer normalizes the preimage of
the cyclic quotient subgroup. -/
theorem goodElementCentralizer_le_normalizer_cyclicOver
    (q : A ⧸ N) :
    goodElementCentralizer N q ≤
      Subgroup.normalizer (cyclicOverQuotientElement N q : Set A) := by
  intro d hd
  rw [Subgroup.mem_normalizer_iff]
  intro x
  have hdCentralizes :
      QuotientGroup.mk' N d ∈
        Subgroup.centralizer
          (Subgroup.zpowers q : Set (A ⧸ N)) := by
    rw [Subgroup.zpowers_eq_closure, Subgroup.centralizer_closure]
    exact hd
  have conjugate_mem
      {e y : A}
      (he :
        QuotientGroup.mk' N e ∈
          Subgroup.centralizer
            (Subgroup.zpowers q : Set (A ⧸ N)))
      (hy : y ∈ cyclicOverQuotientElement N q) :
      e * y * e⁻¹ ∈ cyclicOverQuotientElement N q := by
    change
      QuotientGroup.mk' N (e * y * e⁻¹) ∈
        Subgroup.zpowers q
    have hcomm :=
      (Subgroup.mem_centralizer_iff.mp he)
        (QuotientGroup.mk' N y) hy
    rw [map_mul, map_mul, map_inv, ← hcomm]
    simpa using hy
  constructor
  · exact fun hx => conjugate_mem hdCentralizes hx
  · intro hx
    have hdInvCentralizes :
        QuotientGroup.mk' N d⁻¹ ∈
          Subgroup.centralizer
            (Subgroup.zpowers q : Set (A ⧸ N)) := by
      simpa using
        (Subgroup.centralizer
          (Subgroup.zpowers q : Set (A ⧸ N))).inv_mem
            hdCentralizes
    have h := conjugate_mem hdInvCentralizes hx
    simpa [mul_assoc] using h

/-- The canonical inclusion `N → N⟨q⟩`. -/
abbrev cyclicOverInclusion (q : A ⧸ N) :
    N →* cyclicOverQuotientElement N q :=
  Subgroup.inclusion (normal_le_cyclicOverQuotientElement N q)

/-- The quotient-centralizer preimage, regarded as a subgroup of the
normalizer of `N⟨q⟩`. -/
abbrev goodElementCentralizerInclusionNormalizer (q : A ⧸ N) :
    goodElementCentralizer N q →*
      Subgroup.normalizer
        (cyclicOverQuotientElement N q : Set A) :=
  Subgroup.inclusion
    (goodElementCentralizer_le_normalizer_cyclicOver N q)

/-- Conjugation of `N⟨q⟩` by the preimage of `C_{A/N}(q)`. -/
abbrev goodElementAction (q : A ⧸ N) :
    goodElementCentralizer N q →*
      MulAut (cyclicOverQuotientElement N q) :=
  (cyclicOverQuotientElement N q).normalizerMonoidHom.comp
    (goodElementCentralizerInclusionNormalizer N q)

@[simp]
theorem goodElementAction_apply_coe
    (q : A ⧸ N)
    (d : goodElementCentralizer N q)
    (x : cyclicOverQuotientElement N q) :
    ((goodElementAction N q d x :
        cyclicOverQuotientElement N q) : A) =
      (d : A) * (x : A) * (d : A)⁻¹ :=
  rfl

/-- The extensions of `θ` to the inverse image of `⟨q⟩`. -/
def CyclicOverExtensions
    (θ : IrreducibleCharacter N) (q : A ⧸ N) :=
  {η : IrreducibleCharacter (cyclicOverQuotientElement N q) //
    IsExtensionAlong (cyclicOverInclusion N q) θ η}

/-- Character invariance in smul notation, evaluated on ambient
conjugation of the normal subgroup. -/
theorem values_conjNormal_eq_of_smul_eq
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    (b : A) (n : N) :
    θ.values (MulAut.conjNormal b n) = θ.values n := by
  have h := congrArg
    (fun χ : IrreducibleCharacter N => χ.values n)
    (hinvariant b⁻¹)
  have he :
      (MulAut.conjNormal (H := N) b⁻¹).symm =
        MulAut.conjNormal (H := N) b := by
    ext x
    simp only [MulAut.conjNormal_symm_apply,
      MulAut.conjNormal_apply, inv_inv]
  simpa only [conjBy_values, he] using h

/-- An invariant normal character has an extension to every cyclic-over-`N`
subgroup.  In particular, the good-element predicate is not vacuous. -/
theorem nonempty_cyclicOverExtensions
    [Finite A]
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    (q : A ⧸ N) :
    Nonempty (CyclicOverExtensions N θ q) := by
  let U := cyclicOverQuotientElement N q
  let f : N →* U := cyclicOverInclusion N q
  have hf : Function.Injective f := by
    intro x y h
    apply Subtype.ext
    exact congrArg (fun z : U => (z : A)) h
  have hfRange : f.range = N.subgroupOf U := by
    ext x
    constructor
    · rintro ⟨n, rfl⟩
      exact n.2
    · intro hx
      exact ⟨⟨x.1, hx⟩, Subtype.ext rfl⟩
  have hfRangeNormal : f.range.Normal := by
    rw [hfRange]
    infer_instance
  let π : U →* Subgroup.zpowers q :=
    (((QuotientGroup.mk' N).domRestrict U).codRestrict
      (Subgroup.zpowers q) (fun x => x.2))
  have hπKer : π.ker = f.range := by
    rw [hfRange]
    ext x
    simp only [MonoidHom.mem_ker, Subgroup.mem_subgroupOf]
    constructor
    · intro hx
      have hx' : QuotientGroup.mk' N (x : A) = 1 :=
        congrArg Subtype.val hx
      exact (QuotientGroup.eq_one_iff (x : A)).mp hx'
    · intro hx
      apply Subtype.ext
      exact (QuotientGroup.eq_one_iff (x : A)).mpr hx
  have hcyclic : IsCyclic (U ⧸ f.range) := by
    letI : IsCyclic (Subgroup.zpowers q) :=
      Subgroup.isCyclic_zpowers q
    letI : IsCyclic π.range := Subgroup.isCyclic π.range
    letI : IsCyclic (U ⧸ π.ker) :=
      isCyclic_of_surjective
        (QuotientGroup.quotientKerEquivRange π).symm
        (QuotientGroup.quotientKerEquivRange π).symm.surjective
    exact isCyclic_of_surjective
      (QuotientGroup.quotientMulEquivOfEq hπKer)
      (QuotientGroup.quotientMulEquivOfEq hπKer).surjective
  let action : U →* MulAut N :=
    (MulAut.conjNormal : A →* MulAut N).comp U.subtype
  obtain ⟨η, hη⟩ :=
    exists_extensionAlong_of_injective_cyclic_range
      f hf hfRangeNormal hcyclic action
      (fun k n => by
        apply Subtype.ext
        rfl)
      θ
      (fun k n =>
        values_conjNormal_eq_of_smul_eq
          N θ hinvariant (k : A) n)
  exact ⟨⟨η, hη⟩⟩

/-- Gallagher's predicate that `q ∈ A / N` is `θ`-good: every extension
of `θ` to `N⟨q⟩` is invariant under the preimage of `C_{A/N}(q)`. -/
def IsGoodQuotientElement
    (θ : IrreducibleCharacter N) (q : A ⧸ N) : Prop :=
  ∀ η : CyclicOverExtensions N θ q,
    ∀ d : goodElementCentralizer N q,
      goodElementAction N q d • η.1 = η.1

/-- Ambient-element form of Gallagher's good-element predicate. -/
def IsGoodElement
    (θ : IrreducibleCharacter N) (a : A) : Prop :=
  IsGoodQuotientElement N θ (QuotientGroup.mk' N a)

/-- The ambient predicate depends only on the quotient element. -/
theorem isGoodElement_iff_of_quotient_eq
    (θ : IrreducibleCharacter N) {a b : A}
    (h :
      QuotientGroup.mk' N a =
        QuotientGroup.mk' N b) :
    IsGoodElement N θ a ↔ IsGoodElement N θ b := by
  rw [IsGoodElement, IsGoodElement, h]

/-- Left multiplication by an element of `N` preserves goodness. -/
theorem isGoodElement_left_mul_iff
    (θ : IrreducibleCharacter N) (a : A)
    {n : A} (hn : n ∈ N) :
    IsGoodElement N θ (n * a) ↔
      IsGoodElement N θ a := by
  apply isGoodElement_iff_of_quotient_eq N θ
  rw [map_mul]
  have hnq : QuotientGroup.mk' N n = 1 :=
    (QuotientGroup.eq_one_iff n).mpr hn
  rw [hnq, one_mul]

/-- Right multiplication by an element of `N` preserves goodness. -/
theorem isGoodElement_right_mul_iff
    (θ : IrreducibleCharacter N) (a : A)
    {n : A} (hn : n ∈ N) :
    IsGoodElement N θ (a * n) ↔
      IsGoodElement N θ a := by
  apply isGoodElement_iff_of_quotient_eq N θ
  rw [map_mul]
  have hnq : QuotientGroup.mk' N n = 1 :=
    (QuotientGroup.eq_one_iff n).mpr hn
  rw [hnq, mul_one]

/-- Conjugation of an element of `A / N`, written using an ambient lift. -/
abbrev conjugateQuotientElement
    (b : A) (q : A ⧸ N) : A ⧸ N :=
  QuotientGroup.mk' N b * q * (QuotientGroup.mk' N b)⁻¹

/-- Ambient conjugation maps the cyclic-over-`N` subgroup of `q` onto
that of its conjugate. -/
theorem map_cyclicOverQuotientElement_conj_eq
    (b : A) (q : A ⧸ N) :
    (cyclicOverQuotientElement N q).map (MulAut.conj b) =
      cyclicOverQuotientElement
        N (conjugateQuotientElement N b q) := by
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    change
      QuotientGroup.mk' N (b * y * b⁻¹) ∈
        Subgroup.zpowers
          (QuotientGroup.mk' N b * q *
            (QuotientGroup.mk' N b)⁻¹)
    have hyMap :=
      Subgroup.apply_coe_mem_map
        (MulAut.conj
          (QuotientGroup.mk' N b)).toMonoidHom
        (Subgroup.zpowers q)
        ⟨QuotientGroup.mk' N y, hy⟩
    rw [(MulAut.conj
      (QuotientGroup.mk' N b)).toMonoidHom.map_zpowers q]
      at hyMap
    simpa [MulAut.conj_apply] using hyMap
  · intro hx
    refine ⟨b⁻¹ * x * b, ?_, ?_⟩
    · change
        QuotientGroup.mk' N (b⁻¹ * x * b) ∈
          Subgroup.zpowers q
      have hxMap :=
        Subgroup.apply_coe_mem_map
          (MulAut.conj
            (QuotientGroup.mk' N b)⁻¹).toMonoidHom
          (Subgroup.zpowers
            (conjugateQuotientElement N b q))
          ⟨QuotientGroup.mk' N x, hx⟩
      rw [(MulAut.conj
        (QuotientGroup.mk' N b)⁻¹).toMonoidHom.map_zpowers
          (conjugateQuotientElement N b q)]
        at hxMap
      simpa [conjugateQuotientElement,
        MulAut.conj_apply, mul_assoc] using hxMap
    · simp [MulAut.conj_apply, mul_assoc]

/-- Ambient conjugation maps the quotient-centralizer preimage of `q`
onto that of its conjugate. -/
theorem map_goodElementCentralizer_conj_eq
    (b : A) (q : A ⧸ N) :
    (goodElementCentralizer N q).map (MulAut.conj b) =
      goodElementCentralizer
        N (conjugateQuotientElement N b q) := by
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    change
      QuotientGroup.mk' N (b * y * b⁻¹) ∈
        Subgroup.centralizer
          ({conjugateQuotientElement N b q} :
            Set (A ⧸ N))
    rw [Subgroup.mem_centralizer_singleton_iff]
    have hmap :=
      congrArg
        (MulAut.conj (QuotientGroup.mk' N b))
        (Subgroup.mem_centralizer_singleton_iff.mp hy)
    simpa [conjugateQuotientElement,
      MulAut.conj_apply] using hmap
  · intro hx
    refine ⟨b⁻¹ * x * b, ?_, ?_⟩
    · change
        QuotientGroup.mk' N (b⁻¹ * x * b) ∈
          Subgroup.centralizer ({q} : Set (A ⧸ N))
      rw [Subgroup.mem_centralizer_singleton_iff]
      have hmap :=
        congrArg
          (MulAut.conj (QuotientGroup.mk' N b)⁻¹)
          (Subgroup.mem_centralizer_singleton_iff.mp hx)
      simpa [conjugateQuotientElement,
        MulAut.conj_apply, mul_assoc] using hmap
    · simp [MulAut.conj_apply, mul_assoc]

/-- Conjugation equivalence between the two cyclic-over-`N` subgroups. -/
def cyclicOverConjugationEquiv
    (b : A) (q : A ⧸ N) :
    cyclicOverQuotientElement N q ≃*
      cyclicOverQuotientElement
        N (conjugateQuotientElement N b q) :=
  ((MulAut.conj b).subgroupMap
      (cyclicOverQuotientElement N q)).trans
    (MulEquiv.subgroupCongr
      (map_cyclicOverQuotientElement_conj_eq N b q))

/-- Conjugation equivalence between the two quotient-centralizer
preimages. -/
def goodElementCentralizerConjugationEquiv
    (b : A) (q : A ⧸ N) :
    goodElementCentralizer N q ≃*
      goodElementCentralizer
        N (conjugateQuotientElement N b q) :=
  ((MulAut.conj b).subgroupMap
      (goodElementCentralizer N q)).trans
    (MulEquiv.subgroupCongr
      (map_goodElementCentralizer_conj_eq N b q))

@[simp]
theorem cyclicOverConjugationEquiv_apply_coe
    (b : A) (q : A ⧸ N)
    (x : cyclicOverQuotientElement N q) :
    ((cyclicOverConjugationEquiv N b q x :
        cyclicOverQuotientElement
          N (conjugateQuotientElement N b q)) : A) =
      b * (x : A) * b⁻¹ :=
  rfl

@[simp]
theorem goodElementCentralizerConjugationEquiv_apply_coe
    (b : A) (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    ((goodElementCentralizerConjugationEquiv N b q d :
        goodElementCentralizer
          N (conjugateQuotientElement N b q)) : A) =
      b * (d : A) * b⁻¹ :=
  rfl

/-- Conjugation transport commutes with the inclusion of `N`. -/
theorem cyclicOverConjugationEquiv_inclusion_commutes
    (b : A) (q : A ⧸ N) :
    (cyclicOverConjugationEquiv N b q).toMonoidHom.comp
        (cyclicOverInclusion N q) =
      (cyclicOverInclusion
        N (conjugateQuotientElement N b q)).comp
        (MulAut.conjNormal b).toMonoidHom := by
  ext n
  rfl

/-- The cyclic-over-`N` conjugation equivalence intertwines the two
quotient-centralizer actions. -/
theorem cyclicOverConjugationEquiv_goodElementAction
    (b : A) (q : A ⧸ N)
    (d : goodElementCentralizer N q)
    (x : cyclicOverQuotientElement N q) :
    cyclicOverConjugationEquiv N b q
        (goodElementAction N q d x) =
      goodElementAction
        N (conjugateQuotientElement N b q)
        (goodElementCentralizerConjugationEquiv N b q d)
        (cyclicOverConjugationEquiv N b q x) := by
  apply Subtype.ext
  change
    b * ((d : A) * (x : A) * (d : A)⁻¹) * b⁻¹ =
      (b * (d : A) * b⁻¹) *
        (b * (x : A) * b⁻¹) *
          (b * (d : A) * b⁻¹)⁻¹
  simp [mul_assoc]

@[simp]
theorem goodElementAction_symm_apply_coe
    (q : A ⧸ N) (d : goodElementCentralizer N q)
    (x : cyclicOverQuotientElement N q) :
    (((goodElementAction N q d).symm x :
      cyclicOverQuotientElement N q) : A) =
      (d : A)⁻¹ * (x : A) * (d : A) := by
  change (d : A)⁻¹ * (x : A) * (d : A)⁻¹⁻¹ = _
  rw [inv_inv]

/-- Pullback along conjugation intertwines the two good-element actions. -/
theorem comap_goodElementAction_smul_conjugation
    (b : A) (q : A ⧸ N)
    (η : IrreducibleCharacter
      (cyclicOverQuotientElement N (conjugateQuotientElement N b q)))
    (d : goodElementCentralizer N q) :
    (goodElementAction N (conjugateQuotientElement N b q)
        (goodElementCentralizerConjugationEquiv N b q d) • η).comap
          (cyclicOverConjugationEquiv N b q) =
      goodElementAction N q d •
        η.comap (cyclicOverConjugationEquiv N b q) := by
  apply IrreducibleCharacter.ext
  funext x
  change η.values
      ((goodElementAction N (conjugateQuotientElement N b q)
        (goodElementCentralizerConjugationEquiv N b q d)).symm
          (cyclicOverConjugationEquiv N b q x)) =
    η.values (cyclicOverConjugationEquiv N b q
      ((goodElementAction N q d).symm x))
  congr 1
  apply Subtype.ext
  simp only [goodElementAction_symm_apply_coe,
    cyclicOverConjugationEquiv_apply_coe,
    goodElementCentralizerConjugationEquiv_apply_coe]
  simp [mul_assoc]

/-- Goodness is preserved by ambient conjugation when `θ` is invariant. -/
theorem IsGoodQuotientElement.conj
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    {q : A ⧸ N}
    (hq : IsGoodQuotientElement N θ q)
    (b : A) :
    IsGoodQuotientElement N θ
      (conjugateQuotientElement N b q) := by
  intro η dTarget
  let eU := cyclicOverConjugationEquiv N b q
  let eD := goodElementCentralizerConjugationEquiv N b q
  let dSource : goodElementCentralizer N q := eD.symm dTarget
  have hθComap :
      θ.comap (MulAut.conjNormal b) = θ := by
    apply IrreducibleCharacter.ext
    funext n
    have h := congrArg (fun χ : IrreducibleCharacter N => χ.values n)
      (hinvariant b⁻¹)
    have he :
        (MulAut.conjNormal (H := N) b⁻¹).symm =
          MulAut.conjNormal (H := N) b := by
      ext x
      simp only [MulAut.conjNormal_symm_apply,
        MulAut.conjNormal_apply, inv_inv]
    simpa only [comap_values, conjBy_values, he] using h
  have hηExtensionRaw :
      IsExtensionAlong (cyclicOverInclusion N q)
        (θ.comap (MulAut.conjNormal b))
        (η.1.comap eU) :=
    IsExtensionAlong.comap_equiv
      eU (MulAut.conjNormal b)
      (cyclicOverConjugationEquiv_inclusion_commutes N b q)
      η.2
  have hηExtension :
      IsExtensionAlong (cyclicOverInclusion N q)
        θ (η.1.comap eU) := by
    simpa only [hθComap] using hηExtensionRaw
  have hSource :=
    hq ⟨η.1.comap eU, hηExtension⟩ dSource
  have hd : eD dSource = dTarget := eD.apply_symm_apply dTarget
  rw [← hd]
  apply (comapEquiv eU).injective
  change
    (goodElementAction N (conjugateQuotientElement N b q)
      (eD dSource) • η.1).comap eU = η.1.comap eU
  rw [comap_goodElementAction_smul_conjugation]
  exact hSource

/-- Goodness is constant on quotient elements conjugate by an ambient
element when `θ` is invariant. -/
theorem isGoodQuotientElement_conj_iff
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    (q : A ⧸ N) (b : A) :
    IsGoodQuotientElement N θ
        (conjugateQuotientElement N b q) ↔
      IsGoodQuotientElement N θ q := by
  constructor
  · intro h
    have h' := h.conj N θ hinvariant b⁻¹
    simpa [conjugateQuotientElement, mul_assoc] using h'
  · exact fun h => h.conj N θ hinvariant b

/-- Goodness is constant on conjugacy classes of `A / N` when `θ` is
invariant. -/
theorem isGoodQuotientElement_iff_of_isConj
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    {q r : A ⧸ N} (hqr : IsConj q r) :
    IsGoodQuotientElement N θ q ↔
      IsGoodQuotientElement N θ r := by
  obtain ⟨g, rfl⟩ := isConj_iff.mp hqr
  obtain ⟨b, rfl⟩ := QuotientGroup.mk'_surjective N g
  exact (isGoodQuotientElement_conj_iff N θ hinvariant q b).symm

/-- Ambient conjugation preserves goodness when `θ` is invariant. -/
theorem isGoodElement_conj_iff
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    (a b : A) :
    IsGoodElement N θ (b * a * b⁻¹) ↔
      IsGoodElement N θ a := by
  simpa only [IsGoodElement, map_mul, map_inv] using
    isGoodQuotientElement_conj_iff
      N θ hinvariant (QuotientGroup.mk' N a) b

/-- A quotient conjugacy class is good when one (and, for invariant
`θ`, equivalently every) representative is good.  The existential
definition avoids choosing a representative. -/
def IsGoodQuotientConjugacyClass
    (θ : IrreducibleCharacter N)
    (c : ConjClasses (A ⧸ N)) : Prop :=
  ∃ q : A ⧸ N,
    ConjClasses.mk q = c ∧ IsGoodQuotientElement N θ q

/-- The subtype of good conjugacy classes in `A / N`. -/
def GoodQuotientConjugacyClasses
    (θ : IrreducibleCharacter N) :=
  {c : ConjClasses (A ⧸ N) //
    IsGoodQuotientConjugacyClass N θ c}

@[simp]
theorem isGoodQuotientConjugacyClass_mk_iff
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    (q : A ⧸ N) :
    IsGoodQuotientConjugacyClass N θ (ConjClasses.mk q) ↔
      IsGoodQuotientElement N θ q := by
  constructor
  · rintro ⟨r, hr, hgood⟩
    exact (isGoodQuotientElement_iff_of_isConj N θ hinvariant
      (ConjClasses.mk_eq_mk_iff_isConj.mp hr)).mp hgood
  · exact fun hgood => ⟨q, rfl, hgood⟩

instance [Finite A] (θ : IrreducibleCharacter N) :
    Finite (GoodQuotientConjugacyClasses N θ) :=
  Subtype.finite

end IrreducibleCharacter
end McKayConjecture
