/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.GallagherCosetNorm
import McKayConjecture.Character.GoodElementExtensionRatio

/-!
# Coset norms for cyclic-over-normal-subgroup extensions

The quotient of `cyclicOverQuotientElement N q` by its internal copy of
`N` is generated by the canonical lift of `q`.  This file packages that
fact as an `IsCyclic` instance and specializes Gallagher's cyclic coset
norm to the ambient copy of `N`.
-/

noncomputable section

open scoped BigOperators

namespace McKayConjecture
namespace IrreducibleCharacter

variable {A : Type} [Group A]
variable (N : Subgroup A) [N.Normal]

noncomputable local instance (priority := 2000)
    goodElementCosetNormFintype
    (G : Type) [Group G] [Finite G] : Fintype G :=
  Fintype.ofFinite G

local instance goodElementCosetNormDecidableProp
    (p : Prop) : Decidable p :=
  Classical.propDecidable p

/-- The canonical quotient class generates
`N⟨q⟩ / N`, packaged as a cyclicity instance. -/
instance cyclicOverInternalQuotientIsCyclic
    (q : A ⧸ N) :
    IsCyclic
      (cyclicOverQuotientElement N q ⧸
        cyclicOverNormalSubgroup N q) :=
  { exists_zpow_surjective := by
      refine
        ⟨cyclicOverInternalQuotientGenerator N q, ?_⟩
      intro y
      obtain ⟨z, hz⟩ :=
        Subgroup.mem_zpowers_iff.mp
          (mem_zpowers_cyclicOverInternalQuotientGenerator
            N q y)
      exact ⟨z, hz⟩ }

/-- Gallagher's cyclic coset norm for an extension to `N⟨q⟩`,
reindexed from the internal copy of `N` back to the original subgroup. -/
theorem cyclicOverExtension_coset_bilinearNorm
    [Finite A]
    (θ : IrreducibleCharacter N)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q) :
    (∑ n : N,
      η.1.values
          (cyclicOverQuotientGenerator N q *
            cyclicOverInclusion N q n) *
        η.1.values
          ((cyclicOverQuotientGenerator N q *
            cyclicOverInclusion N q n)⁻¹)) =
      (Nat.card N : ℂ) := by
  have hnorm :=
    cyclicQuotientExtension_coset_bilinearNorm
      (cyclicOverNormalSubgroup N q)
      (cyclicOverInternalCharacter N θ q)
      η.1
      ((isExtensionAlong_cyclicOverInclusion_iff
        N θ q η.1).mp η.2)
      (cyclicOverQuotientGenerator N q)
  have hcard :
      Nat.card (cyclicOverNormalSubgroup N q) =
        Nat.card N :=
    Nat.card_congr (cyclicOverNormalEquiv N q).symm
  rw [hcard] at hnorm
  rw [← hnorm]
  apply Fintype.sum_equiv
    (cyclicOverNormalEquiv N q).toEquiv
  intro n
  rfl

end IrreducibleCharacter
end McKayConjecture
