import McKayConjecture.Character.ExtensionConstituent
import McKayConjecture.Character.GoodElementTorsor

/-!
# Good elements and two-generator extensions

This file proves the quotient-native form of Navarro's two-generator
extension criterion (`Character Theory and the McKay Conjecture`, 2018,
Lemma 5.13).

For `N ◁ A`, a quotient element `q : A ⧸ N`, and a lift `d : A` whose
image centralizes `q`, let
`twoGeneratorOverQuotientElement N q d` be the subgroup generated by `d`
and the inverse image `cyclicOverQuotientElement N q` of `⟨q⟩`.  The main
theorem says that `q` is good for an `A`-invariant character `θ` precisely
when `θ` extends to every such two-generator subgroup.

The intermediate-restriction helper in the first section is stated in
universe zero.  This matches the current finite-dimensional
representation and Glauberman APIs used by this project.
-/

noncomputable section

open CategoryTheory

namespace McKayConjecture
namespace IrreducibleCharacter

variable {G K H : Type}
variable [Group G] [Group K] [Group H] [Finite H]

/-- An extension restricts irreducibly through every intermediate group.

This is presently universe-zero because the character-norm simplicity
criterion used in the proof is available there; this is sufficient for
the project's finite-group character theory.
-/
theorem IsExtensionAlong.exists_intermediate
    {f : H →* K} {g : K →* G}
    {χ : IrreducibleCharacter H}
    {ψ : IrreducibleCharacter G}
    (hψ : IsExtensionAlong (g.comp f) χ ψ) :
    ∃ η : IrreducibleCharacter K,
      IsExtensionAlong f χ η ∧
        IsExtensionAlong g η ψ := by
  classical
  let V : FDRep ℂ K :=
    FDRep.res g ψ.realization
  letI : Fintype H := Fintype.ofFinite H
  letI : Simple (FDRep.res f V) := by
    rw [FDRep.simple_iff_char_is_norm_one]
    have hsimple : Simple χ.realization :=
      inferInstance
    have hnorm :=
      (FDRep.simple_iff_char_is_norm_one
        χ.realization).mp hsimple
    have hchar :
        (FDRep.res f V).character = χ.values := by
      funext h
      change
        ψ.realization.character (g (f h)) =
          χ.values h
      rw [ψ.realization_character]
      exact hψ h
    rw [hchar, ← χ.realization_character]
    exact hnorm
  letI :
      Representation.IsIrreducible V.ρ :=
    RepresentationTheory.Representation.isIrreducible_of_isIrreducible_comp
      V.ρ
      (CliffordRestriction.isIrreducible_of_simple
        (FDRep.res f V))
  letI : Simple V :=
    RepresentationTheory.simple_fdRep_of_isIrreducible V.ρ
  refine ⟨ofSimple V, ?_, ?_⟩
  · intro h
    rw [ofSimple_values_apply]
    change
      ψ.realization.character (g (f h)) =
        χ.values h
    rw [ψ.realization_character]
    exact hψ h
  · intro k
    rw [ofSimple_values_apply]
    change
      ψ.values (g k) =
        ψ.realization.character (g k)
    exact (congrFun ψ.realization_character (g k)).symm

end IrreducibleCharacter
end McKayConjecture

namespace McKayConjecture
namespace IrreducibleCharacter

variable {A : Type} [Group A]
variable (N : Subgroup A) [N.Normal]

/-- The subgroup generated by the inverse image of `⟨q⟩` and a chosen
lift of a quotient element centralizing `q`. -/
abbrev twoGeneratorOverQuotientElement
    (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    Subgroup A :=
  Subgroup.zpowers (d : A) ⊔
    cyclicOverQuotientElement N q

/-- The chosen quotient-centralizer lift normalizes the cyclic-over
subgroup. -/
theorem zpowers_goodElementCentralizer_le_normalizer_cyclicOver
    (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    Subgroup.zpowers (d : A) ≤
      Subgroup.normalizer
        (cyclicOverQuotientElement N q : Set A) := by
  rw [Subgroup.zpowers_le]
  exact
    goodElementCentralizer_le_normalizer_cyclicOver
      N q d.2

/-- The cyclic-over subgroup lies in the associated two-generator
subgroup. -/
theorem cyclicOver_le_twoGeneratorOverQuotientElement
    (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    cyclicOverQuotientElement N q ≤
      twoGeneratorOverQuotientElement N q d :=
  le_sup_right

/-- The normal subgroup `N` lies in every associated two-generator
subgroup. -/
theorem normal_le_twoGeneratorOverQuotientElement
    (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    N ≤ twoGeneratorOverQuotientElement N q d :=
  (normal_le_cyclicOverQuotientElement N q).trans le_sup_right

/-- Modulo the cyclic-over subgroup, the associated two-generator
subgroup is cyclic, generated by the class of `d`. -/
theorem twoGeneratorOverQuotientElement_quotient_isCyclic
    (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    letI :
        ((cyclicOverQuotientElement N q).subgroupOf
          (twoGeneratorOverQuotientElement N q d)).Normal :=
      Subgroup.normal_subgroupOf_sup_of_le_normalizer
        (zpowers_goodElementCentralizer_le_normalizer_cyclicOver
          N q d)
    IsCyclic
      ((twoGeneratorOverQuotientElement N q d) ⧸
        (cyclicOverQuotientElement N q).subgroupOf
          (twoGeneratorOverQuotientElement N q d)) := by
  let U := cyclicOverQuotientElement N q
  let L := twoGeneratorOverQuotientElement N q d
  have hnormalize :
      Subgroup.zpowers (d : A) ≤
        Subgroup.normalizer (U : Set A) :=
    zpowers_goodElementCentralizer_le_normalizer_cyclicOver
      N q d
  letI : (U.subgroupOf L).Normal :=
    Subgroup.normal_subgroupOf_sup_of_le_normalizer
      hnormalize
  rw [isCyclic_iff_exists_zpowers_eq_top]
  let dL : L :=
    ⟨d,
      (show
        Subgroup.zpowers (d : A) ≤
          Subgroup.zpowers (d : A) ⊔ U from
        le_sup_left)
        (Subgroup.mem_zpowers (d : A))⟩
  refine ⟨QuotientGroup.mk' (U.subgroupOf L) dL, ?_⟩
  rw [Subgroup.eq_top_iff']
  intro x
  induction x using QuotientGroup.induction_on with
  | H x =>
      have hx :
          (x : A) ∈
            (Subgroup.zpowers (d : A) ⊔ U :
              Subgroup A) :=
        x.2
      rw [← SetLike.mem_coe,
        Subgroup.coe_mul_of_left_le_normalizer_right
          (Subgroup.zpowers (d : A)) U hnormalize] at hx
      obtain ⟨y, hy, z, hz, hyz⟩ := hx
      obtain ⟨i, hi⟩ := Subgroup.mem_zpowers_iff.mp hy
      apply Subgroup.mem_zpowers_iff.mpr
      refine ⟨i, ?_⟩
      rw [← map_zpow]
      apply QuotientGroup.eq_iff_div_mem.mpr
      change
        ((dL : L) ^ i) /
            x ∈ U.subgroupOf L
      change
        ((d : A) ^ i) / (x : A) ∈ U
      rw [hi, ← hyz]
      simp only [div_eq_mul_inv, mul_inv_rev]
      simpa only [mul_assoc] using
        (Subgroup.mem_normalizer_iff.mp
          (hnormalize hy) z⁻¹).mp (U.inv_mem hz)

variable [Finite A]

/-- Fixedness under one quotient-centralizer element is independent of
the chosen cyclic-over extension. -/
theorem goodElementAction_fixed_iff_of_extensions
    (θ : IrreducibleCharacter N)
    (q : A ⧸ N)
    (η φ : CyclicOverExtensions N θ q)
    (d : goodElementCentralizer N q) :
    goodElementAction N q d • η.1 = η.1 ↔
      goodElementAction N q d • φ.1 = φ.1 := by
  have hηInternal :
      IsExtensionAlong
        (cyclicOverNormalSubgroup N q).subtype
        (cyclicOverInternalCharacter N θ q) η.1 :=
    (isExtensionAlong_cyclicOverInclusion_iff N θ q η.1).mp
      η.2
  have hφInternal :
      IsExtensionAlong
        (cyclicOverNormalSubgroup N q).subtype
        (cyclicOverInternalCharacter N θ q) φ.1 :=
    (isExtensionAlong_cyclicOverInclusion_iff N θ q φ.1).mp
      φ.2
  constructor
  · intro hη
    obtain ⟨lam, hlam, hφ⟩ :=
      hηInternal.exists_eq_twist hφInternal
    rw [hφ,
      goodElementAction_smul_twist N q d lam hlam η.1,
      hη]
  · intro hφ
    obtain ⟨lam, hlam, hη⟩ :=
      hφInternal.exists_eq_twist hηInternal
    rw [hη,
      goodElementAction_smul_twist N q d lam hlam φ.1,
      hφ]

/-- A cyclic-over extension fixed by `d` extends across the subgroup
generated by that cyclic-over group and `d`.  This is the forward local
extension step in Navarro's Lemma 5.13. -/
theorem exists_twoGenerator_extension_of_goodElementAction_fixed
    (θ : IrreducibleCharacter N)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q)
    (d : goodElementCentralizer N q)
    (hfixed :
      goodElementAction N q d • η.1 = η.1) :
    ∃ ψ :
        IrreducibleCharacter
          (twoGeneratorOverQuotientElement N q d),
      IsExtensionAlong
        (Subgroup.inclusion
          (normal_le_twoGeneratorOverQuotientElement N q d))
        θ ψ := by
  classical
  let U := cyclicOverQuotientElement N q
  let L := twoGeneratorOverQuotientElement N q d
  have hnormalize :
      Subgroup.zpowers (d : A) ≤
        Subgroup.normalizer (U : Set A) :=
    zpowers_goodElementCentralizer_le_normalizer_cyclicOver
      N q d
  letI : (U.subgroupOf L).Normal :=
    Subgroup.normal_subgroupOf_sup_of_le_normalizer
      hnormalize
  let f : U →* L :=
    Subgroup.inclusion le_sup_right
  have hf : Function.Injective f := by
    intro x y hxy
    exact Subtype.ext
      (congrArg (fun z : L => (z : A)) hxy)
  have hfRange :
      f.range = U.subgroupOf L :=
    Subgroup.inclusion_range le_sup_right
  have hfRangeNormal : f.range.Normal := by
    rw [hfRange]
    infer_instance
  letI : IsCyclic (L ⧸ U.subgroupOf L) :=
    twoGeneratorOverQuotientElement_quotient_isCyclic
      N q d
  have hcyclic : IsCyclic (L ⧸ f.range) := by
    let e :
        L ⧸ f.range ≃*
          L ⧸ U.subgroupOf L :=
      QuotientGroup.quotientMulEquivOfEq hfRange
    exact isCyclic_of_surjective e.symm e.symm.surjective
  have hLnormalize :
      L ≤ Subgroup.normalizer (U : Set A) :=
    sup_le hnormalize Subgroup.le_normalizer
  let action : L →* MulAut U :=
    U.normalizerMonoidHom.comp
      (Subgroup.inclusion hLnormalize)
  have hinvariant :
      ∀ (l : L) (u : U),
        η.1.values (action l u) =
          η.1.values u := by
    intro l u
    have hl :
        (l : A) ∈
          (Subgroup.zpowers (d : A) ⊔ U :
            Subgroup A) :=
      l.2
    rw [← SetLike.mem_coe,
      Subgroup.coe_mul_of_left_le_normalizer_right
        (Subgroup.zpowers (d : A)) U hnormalize] at hl
    obtain ⟨y, hy, z, hz, hyz⟩ := hl
    obtain ⟨i, hi⟩ := Subgroup.mem_zpowers_iff.mp hy
    let a : MulAut U :=
      goodElementAction N q d
    have ha :
        a ∈
          MulAction.stabilizer (MulAut U) η.1 :=
      MulAction.mem_stabilizer_iff.mpr hfixed
    have hai :
        a ^ i ∈
          MulAction.stabilizer (MulAut U) η.1 :=
      (MulAction.stabilizer (MulAut U) η.1).zpow_mem ha i
    have haiFixed :
        a ^ i • η.1 = η.1 :=
      MulAction.mem_stabilizer_iff.mp hai
    have haiValues (v : U) :
        η.1.values ((a ^ i) v) =
          η.1.values v := by
      have hv :=
        congrArg
          (fun χ : IrreducibleCharacter U =>
            χ.values ((a ^ i) v))
          haiFixed
      simpa only [smul_values,
        MulEquiv.symm_apply_apply] using hv.symm
    let zU : U := ⟨z, hz⟩
    have haction :
        action l u =
          (a ^ i) (zU * u * zU⁻¹) := by
      apply Subtype.ext
      change
        (l : A) * (u : A) * (l : A)⁻¹ =
          (((a ^ i) (zU * u * zU⁻¹) : U) : A)
      have haiApply :
          (((a ^ i) (zU * u * zU⁻¹) : U) : A) =
            (d : A) ^ i *
                ((zU * u * zU⁻¹ : U) : A) *
              ((d : A) ^ i)⁻¹ := by
        change
          ((((goodElementAction N q d) ^ i)
              (zU * u * zU⁻¹) : U) : A) =
            _
        rw [← map_zpow]
        exact
          goodElementAction_apply_coe
            N q (d ^ i) (zU * u * zU⁻¹)
      rw [haiApply, hi, ← hyz]
      simp only [Subgroup.coe_mul, Subgroup.coe_inv]
      dsimp [zU]
      group
    rw [haction, haiValues]
    exact ClassFunction.conj_apply η.1.toClassFunction u zU
  obtain ⟨ψ, hψ⟩ :=
    exists_extensionAlong_of_injective_cyclic_range
      f hf hfRangeNormal hcyclic action
      (fun l u => by
        apply Subtype.ext
        rfl)
      η.1 hinvariant
  refine ⟨ψ, ?_⟩
  intro n
  exact (hψ (cyclicOverInclusion N q n)).trans (η.2 n)

/-- An extension across the two-generator subgroup restricts to a
cyclic-over extension fixed by the chosen quotient-centralizer element.
This is the reverse local extension step in Navarro's Lemma 5.13. -/
theorem exists_goodElementAction_fixed_of_twoGenerator_extension
    (θ : IrreducibleCharacter N)
    (q : A ⧸ N)
    (d : goodElementCentralizer N q)
    (ψ :
      IrreducibleCharacter
        (twoGeneratorOverQuotientElement N q d))
    (hψ :
      IsExtensionAlong
        (Subgroup.inclusion
          (normal_le_twoGeneratorOverQuotientElement N q d))
        θ ψ) :
    ∃ η : CyclicOverExtensions N θ q,
      goodElementAction N q d • η.1 = η.1 := by
  let U := cyclicOverQuotientElement N q
  let L := twoGeneratorOverQuotientElement N q d
  let f : N →* U :=
    cyclicOverInclusion N q
  let g : U →* L :=
    Subgroup.inclusion le_sup_right
  have hψ' :
      IsExtensionAlong (g.comp f) θ ψ := by
    intro n
    exact hψ n
  obtain ⟨η, hη, hηψ⟩ :=
    IsExtensionAlong.exists_intermediate hψ'
  let η' : CyclicOverExtensions N θ q :=
    ⟨η, hη⟩
  refine ⟨η', ?_⟩
  apply IrreducibleCharacter.ext
  funext u
  rw [smul_values]
  let dL : L :=
    ⟨d,
      (show
        Subgroup.zpowers (d : A) ≤
          Subgroup.zpowers (d : A) ⊔ U from
        le_sup_left)
        (Subgroup.mem_zpowers (d : A))⟩
  calc
    η.values
        ((goodElementAction N q d).symm u) =
        ψ.values
          (g ((goodElementAction N q d).symm u)) :=
      (hηψ ((goodElementAction N q d).symm u)).symm
    _ =
        ψ.values
          (dL⁻¹ * g u * (dL⁻¹)⁻¹) := by
      apply congrArg ψ.values
      apply Subtype.ext
      simpa only [g, dL, L, U, Subgroup.coe_mul, Subgroup.coe_inv,
        Subgroup.coe_inclusion, inv_inv] using
        (goodElementAction_symm_apply_coe N q d u)
    _ = ψ.values (g u) :=
      ClassFunction.conj_apply ψ.toClassFunction (g u) dL⁻¹
    _ = η.values u := hηψ u

/-- Navarro's two-generator extension criterion
(`Character Theory and the McKay Conjecture`, 2018, Lemma 5.13), in the
quotient-centralizer formulation used by the good-element API.

For an `A`-invariant irreducible character `θ` of `N`, the quotient
element `q` is good exactly when `θ` extends to the subgroup generated by
`N`, `q`, and every lift of an element centralizing `q` modulo `N`.
-/
theorem isGoodQuotientElement_iff_forall_exists_twoGenerator_extension
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ a : A, a • θ = θ)
    (q : A ⧸ N) :
    IsGoodQuotientElement N θ q ↔
      ∀ d : goodElementCentralizer N q,
        ∃ ψ :
            IrreducibleCharacter
              (twoGeneratorOverQuotientElement N q d),
          IsExtensionAlong
            (Subgroup.inclusion
              (normal_le_twoGeneratorOverQuotientElement
                N q d))
            θ ψ := by
  constructor
  · intro hgood
    obtain ⟨η⟩ :=
      nonempty_cyclicOverExtensions N θ hinvariant q
    intro d
    exact
      exists_twoGenerator_extension_of_goodElementAction_fixed
        N θ q η d (hgood η d)
  · intro hext η d
    obtain ⟨ψ, hψ⟩ := hext d
    obtain ⟨φ, hφ⟩ :=
      exists_goodElementAction_fixed_of_twoGenerator_extension
        N θ q d ψ hψ
    exact
      (goodElementAction_fixed_iff_of_extensions
        N θ q φ η d).mp hφ

end IrreducibleCharacter
end McKayConjecture
