/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.GoodElementCommutatorFiber
import McKayConjecture.Character.GoodElementRatioSum

/-!
# Local commutator sums over good-element centralizers

Fix an extension `η` of an irreducible character `θ` from `N` to the
cyclic-over-`N` subgroup attached to `q : A ⧸ N`.  Averaging the matrices
of the conjugates of the canonical lift of `q` over its quotient
preimage centralizer gives an endomorphism commuting with that cyclic subgroup.
Schur's lemma and two trace computations then identify the corresponding
local commutator sum with a sum of values of the conjugates of `η`.

Rewriting those conjugate values by the extension-ratio character yields
a ratio-weighted identity.  The finite character sum from
`GoodElementRatioSum` finally turns it into a formula split according to
whether `q` is good.
-/

noncomputable section

open scoped BigOperators

universe u

namespace McKayConjecture
namespace IrreducibleCharacter

variable {A : Type u} [Group A]
variable (N : Subgroup A) [N.Normal]

/-- The cyclic-over-`N` subgroup generated by a quotient element is
contained in the preimage of that element's centralizer. -/
theorem cyclicOverQuotientElement_le_goodElementCentralizer
    (q : A ⧸ N) :
    cyclicOverQuotientElement N q ≤
      goodElementCentralizer N q := by
  intro u hu
  change
    QuotientGroup.mk' N (u : A) ∈
      Subgroup.centralizer ({q} : Set (A ⧸ N))
  rw [Subgroup.mem_centralizer_singleton_iff]
  obtain ⟨z, hz⟩ :=
    Subgroup.mem_zpowers_iff.mp hu
  rw [← hz]
  exact (Commute.zpow_self q z).eq

/-- Two lifts in the cyclic-over-`N` subgroup have the same internal
quotient class when they both map to `q` in the ambient quotient. -/
theorem cyclicOverInternalQuotient_eq_generator_of_ambientQuotient_eq
    (q : A ⧸ N)
    (x : cyclicOverQuotientElement N q)
    (hx :
      QuotientGroup.mk' N (x : A) = q) :
    QuotientGroup.mk' (cyclicOverNormalSubgroup N q) x =
      cyclicOverInternalQuotientGenerator N q := by
  rw [cyclicOverInternalQuotientGenerator]
  apply
    (QuotientGroup.eq_iff_div_mem
      (N := cyclicOverNormalSubgroup N q)).mpr
  change
    (((x /
      cyclicOverQuotientGenerator N q :
        cyclicOverQuotientElement N q)) :
      A) ∈ N
  refine (QuotientGroup.eq_one_iff (N := N) _).mp ?_
  change
    QuotientGroup.mk' N
        ((x : A) /
          (cyclicOverQuotientGenerator N q : A)) =
      1
  rw [map_div, hx,
    cyclicOverQuotientGenerator_ambientQuotient]
  exact div_self' q

/-- The commutator of any lift of `q` with an element in the preimage
centralizer lies in `N`. -/
theorem cyclicOverElement_commutator_mem_of_ambientQuotient_eq
    (q : A ⧸ N)
    (x : cyclicOverQuotientElement N q)
    (hx :
      QuotientGroup.mk' N (x : A) = q)
    (d : goodElementCentralizer N q) :
    ((x : A)⁻¹ * (d : A)⁻¹ *
        (x : A) * (d : A)) ∈ N := by
  apply
    (gallagherCommutator_mem_iff_mem_goodElementCentralizer
      N (x : A) (d : A)).mpr
  have hd := d.property
  change
    QuotientGroup.mk' N (d : A) ∈
      Subgroup.centralizer ({q} : Set (A ⧸ N))
    at hd
  change
    QuotientGroup.mk' N (d : A) ∈
      Subgroup.centralizer
        ({QuotientGroup.mk' N (x : A)} :
          Set (A ⧸ N))
  simpa only [hx] using hd

/-- Multiplying the canonical lift by an element of `N` does not change
its ambient quotient class. -/
theorem cyclicOverQuotientGenerator_mul_normal_ambientQuotient
    (q : A ⧸ N)
    (h : N) :
    QuotientGroup.mk' N
        (((cyclicOverQuotientGenerator N q) *
          cyclicOverInclusion N q h :
            cyclicOverQuotientElement N q) : A) =
      q := by
  rw [Subgroup.coe_mul, map_mul,
    cyclicOverQuotientGenerator_ambientQuotient]
  have hh :
      QuotientGroup.mk' N (h : A) = 1 :=
    (QuotientGroup.eq_one_iff (h : A)).mpr h.2
  change
    q * QuotientGroup.mk' N (h : A) = q
  rw [hh, mul_one]

/-- The commutator of a representative obtained by multiplying the
canonical lift by an element of `N` with an element of the preimage
centralizer lies in `N`. -/
theorem cyclicOverQuotientGenerator_mul_normal_commutator_mem
    (q : A ⧸ N)
    (h : N)
    (d : goodElementCentralizer N q) :
    let x : cyclicOverQuotientElement N q :=
      cyclicOverQuotientGenerator N q *
        cyclicOverInclusion N q h
    ((x : A)⁻¹ * (d : A)⁻¹ *
        (x : A) * (d : A)) ∈ N := by
  exact cyclicOverElement_commutator_mem_of_ambientQuotient_eq
    N q
      (cyclicOverQuotientGenerator N q *
        cyclicOverInclusion N q h)
      (cyclicOverQuotientGenerator_mul_normal_ambientQuotient
        N q h)
      d

/-- The commutator of the canonical lift of `q` with an element of its
preimage centralizer lies in `N`. -/
theorem cyclicOverQuotientGenerator_commutator_mem
    (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    ((cyclicOverQuotientGenerator N q : A)⁻¹ *
        (d : A)⁻¹ *
        (cyclicOverQuotientGenerator N q : A) *
        (d : A)) ∈ N :=
  cyclicOverElement_commutator_mem_of_ambientQuotient_eq
    N q (cyclicOverQuotientGenerator N q)
      (cyclicOverQuotientGenerator_ambientQuotient N q) d

section Finite

variable [Finite A]

-- These are the exact local instances used by `GoodElementRatioSum`.
-- Sharing them keeps all finite sums definitionally aligned.
attribute [local instance] goodElementRatioSumFintype
attribute [local instance] goodElementRatioSumDecidableProp

/-- At any lift of `q`, conjugating an extension multiplies its value by
the same ratio used at the canonical lift. -/
theorem goodElementAction_value_of_ambientQuotient_eq
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ b : A, b • θ = θ)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q)
    (d : goodElementCentralizer N q)
    (x : cyclicOverQuotientElement N q)
    (hx :
      QuotientGroup.mk' N (x : A) = q) :
    (goodElementAction N q d • η.1).values x =
      (goodElementExtensionRatio
          N θ hinvariant q η d : ℂ) *
        η.1.values x := by
  have h := congrArg
    (fun χ : IrreducibleCharacter
        (cyclicOverQuotientElement N q) =>
      χ.values x)
    (goodElementExtensionRatioCharacter_spec
      N θ hinvariant q η d)
  simpa only [twist_values, inflateLinearCharacter_apply,
    goodElementExtensionRatio_apply,
    goodElementExtensionRatioValue,
    cyclicOverInternalQuotient_eq_generator_of_ambientQuotient_eq
      N q x hx] using h

/-- Schur's lemma turns the local commutator sum over the preimage
centralizer into the corresponding sum of values of conjugates of an
extension to the cyclic-over-`N` subgroup, for any lift of `q`. -/
theorem degree_mul_localCommutatorSum_eq_actionCharacterSum_of_ambientQuotient_eq
    (θ : IrreducibleCharacter N)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q)
    (x : cyclicOverQuotientElement N q)
    (hx :
      QuotientGroup.mk' N (x : A) = q) :
    (θ.degree : ℂ) *
        ∑ d : goodElementCentralizer N q,
          θ.values
            ⟨(x : A)⁻¹ *
                (d : A)⁻¹ *
                (x : A) *
                (d : A),
              cyclicOverElement_commutator_mem_of_ambientQuotient_eq
                N q x hx d⟩ =
      η.1.values x⁻¹ *
        ∑ d : goodElementCentralizer N q,
          (goodElementAction N q d • η.1).values
            x := by
  classical
  let U := cyclicOverQuotientElement N q
  let D := goodElementCentralizer N q
  let ρ : Representation ℂ U η.1.realization :=
    η.1.realization.ρ
  letI : Representation.IsIrreducible ρ :=
    CliffordRestriction.isIrreducible_of_simple
      η.1.realization
  let T : Module.End ℂ η.1.realization :=
    ∑ d : D, ρ ((goodElementAction N q d).symm x)
  have hUleD :
      U ≤ D :=
    cyclicOverQuotientElement_le_goodElementCentralizer
      N q
  have hTcomm (a : U) :
      ρ a * T = T * ρ a := by
    let aD : D := ⟨a, hUleD a.2⟩
    change
      ρ a *
          (∑ d : D,
            ρ ((goodElementAction N q d).symm x)) =
        (∑ d : D,
            ρ ((goodElementAction N q d).symm x)) *
          ρ a
    rw [Finset.mul_sum, Finset.sum_mul]
    apply Fintype.sum_equiv (Equiv.mulRight aD⁻¹)
    intro d
    simp only [Equiv.coe_mulRight]
    rw [← map_mul, ← map_mul]
    congr 1
    apply Subtype.ext
    simp only [goodElementAction_symm_apply_coe,
      Subgroup.coe_mul, Subgroup.coe_inv]
    change
      (a : A) * ((d : A)⁻¹ * (x : A) * (d : A)) =
        ((d : A) * (a : A)⁻¹)⁻¹ * (x : A) *
            ((d : A) * (a : A)⁻¹) *
          (a : A)
    group
  obtain ⟨c, hc⟩ :=
    McKayConjecture.RepresentationTheory.exists_smul_id_of_forall_mul_comm
      ρ T hTcomm
  have htraceρ (u : U) :
      LinearMap.trace ℂ η.1.realization (ρ u) =
        η.1.values u := by
    change η.1.realization.character u = η.1.values u
    exact congrFun η.1.realization_character u
  have htraceT :
      LinearMap.trace ℂ η.1.realization T =
        ∑ d : D,
          (goodElementAction N q d • η.1).values x := by
    calc
      LinearMap.trace ℂ η.1.realization T =
          ∑ d : D,
            LinearMap.trace ℂ η.1.realization
              (ρ ((goodElementAction N q d).symm x)) := by
        simp only [T, map_sum]
      _ =
          ∑ d : D,
            (goodElementAction N q d • η.1).values x := by
        apply Finset.sum_congr rfl
        intro d _
        rw [htraceρ]
        rfl
  have hcDegree :
      c * (θ.degree : ℂ) =
        ∑ d : D,
          (goodElementAction N q d • η.1).values x := by
    rw [← η.2.degree_eq]
    calc
      c * (η.1.degree : ℂ) =
          LinearMap.trace ℂ η.1.realization
            (c • (LinearMap.id :
              Module.End ℂ η.1.realization)) := by
        simp [η.1.realization_finrank]
      _ = LinearMap.trace ℂ η.1.realization T := by
        rw [← hc]
      _ = _ := htraceT
  have htraceProduct :
      LinearMap.trace ℂ η.1.realization (ρ x⁻¹ * T) =
        ∑ d : D,
          θ.values
            ⟨(x : A)⁻¹ * (d : A)⁻¹ *
                (x : A) * (d : A),
              cyclicOverElement_commutator_mem_of_ambientQuotient_eq
                N q x hx d⟩ := by
    calc
      LinearMap.trace ℂ η.1.realization (ρ x⁻¹ * T) =
          ∑ d : D,
            LinearMap.trace ℂ η.1.realization
              (ρ x⁻¹ *
                ρ ((goodElementAction N q d).symm x)) := by
        simp only [T, Finset.mul_sum, map_sum]
      _ =
          ∑ d : D,
            θ.values
              ⟨(x : A)⁻¹ * (d : A)⁻¹ *
                  (x : A) * (d : A),
                cyclicOverElement_commutator_mem_of_ambientQuotient_eq
                  N q x hx d⟩ := by
        apply Finset.sum_congr rfl
        intro d _
        rw [← map_mul, htraceρ]
        let n : N :=
          ⟨(x : A)⁻¹ * (d : A)⁻¹ *
              (x : A) * (d : A),
            cyclicOverElement_commutator_mem_of_ambientQuotient_eq
              N q x hx d⟩
        calc
          η.1.values
              (x⁻¹ * (goodElementAction N q d).symm x) =
              η.1.values (cyclicOverInclusion N q n) := by
            congr 1
            apply Subtype.ext
            change
              (x : A)⁻¹ *
                  (((goodElementAction N q d).symm x : U) : A) =
                (n : A)
            rw [goodElementAction_symm_apply_coe]
            dsimp [n]
            group
          _ = θ.values n := η.2 n
  have htraceProductScalar :
      LinearMap.trace ℂ η.1.realization (ρ x⁻¹ * T) =
        c * η.1.values x⁻¹ := by
    rw [hc]
    change
      LinearMap.trace ℂ η.1.realization
          (ρ x⁻¹ *
            (c • (LinearMap.id :
              Module.End ℂ η.1.realization))) =
        c * η.1.values x⁻¹
    have hmul :
        ρ x⁻¹ *
            (LinearMap.id :
              Module.End ℂ η.1.realization) =
          ρ x⁻¹ := by
      ext v
      rfl
    rw [mul_smul_comm, hmul, map_smul, htraceρ]
    rfl
  change
    (θ.degree : ℂ) *
        ∑ d : D,
          θ.values
            ⟨(x : A)⁻¹ * (d : A)⁻¹ *
                (x : A) * (d : A),
              cyclicOverElement_commutator_mem_of_ambientQuotient_eq
                N q x hx d⟩ =
      η.1.values x⁻¹ *
        ∑ d : D,
          (goodElementAction N q d • η.1).values x
  rw [← htraceProduct, htraceProductScalar]
  calc
    (θ.degree : ℂ) * (c * η.1.values x⁻¹) =
        (c * (θ.degree : ℂ)) * η.1.values x⁻¹ := by
      ring
    _ =
        (∑ d : D,
          (goodElementAction N q d • η.1).values x) *
            η.1.values x⁻¹ := by
      rw [hcDegree]
    _ =
        η.1.values x⁻¹ *
          ∑ d : D,
            (goodElementAction N q d • η.1).values x := by
      ring

/-- The Schur-trace local commutator identity at the canonical lift of
`q`. -/
theorem degree_mul_localCommutatorSum_eq_actionCharacterSum
    (θ : IrreducibleCharacter N)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q) :
    (θ.degree : ℂ) *
        ∑ d : goodElementCentralizer N q,
          θ.values
            ⟨(cyclicOverQuotientGenerator N q : A)⁻¹ *
                (d : A)⁻¹ *
                (cyclicOverQuotientGenerator N q : A) *
                (d : A),
              cyclicOverQuotientGenerator_commutator_mem
                N q d⟩ =
      η.1.values (cyclicOverQuotientGenerator N q)⁻¹ *
        ∑ d : goodElementCentralizer N q,
          (goodElementAction N q d • η.1).values
            (cyclicOverQuotientGenerator N q) := by
  simpa only using
    degree_mul_localCommutatorSum_eq_actionCharacterSum_of_ambientQuotient_eq
      N θ q η (cyclicOverQuotientGenerator N q)
        (cyclicOverQuotientGenerator_ambientQuotient N q)

/-- The local commutator identity at any lift of `q`, after expressing
every conjugate value through the extension-ratio character. -/
theorem degree_mul_localCommutatorSum_eq_ratioSum_of_ambientQuotient_eq
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ a : A, a • θ = θ)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q)
    (x : cyclicOverQuotientElement N q)
    (hx :
      QuotientGroup.mk' N (x : A) = q) :
    (θ.degree : ℂ) *
        ∑ d : goodElementCentralizer N q,
          θ.values
            ⟨(x : A)⁻¹ *
                (d : A)⁻¹ *
                (x : A) *
                (d : A),
              cyclicOverElement_commutator_mem_of_ambientQuotient_eq
                N q x hx d⟩ =
      η.1.values x⁻¹ *
          η.1.values x *
        ∑ d : goodElementCentralizer N q,
          (goodElementExtensionRatio
            N θ hinvariant q η d : ℂ) := by
  rw [
    degree_mul_localCommutatorSum_eq_actionCharacterSum_of_ambientQuotient_eq
      N θ q η x hx]
  calc
    η.1.values x⁻¹ *
          ∑ d : goodElementCentralizer N q,
            (goodElementAction N q d • η.1).values
              x =
        η.1.values x⁻¹ *
          ∑ d : goodElementCentralizer N q,
            (goodElementExtensionRatio
                N θ hinvariant q η d : ℂ) *
              η.1.values x := by
      congr 1
      apply Finset.sum_congr rfl
      intro d _
      exact goodElementAction_value_of_ambientQuotient_eq
        N θ hinvariant q η d x hx
    _ =
        η.1.values x⁻¹ *
          (η.1.values x *
            ∑ d : goodElementCentralizer N q,
              (goodElementExtensionRatio
                N θ hinvariant q η d : ℂ)) := by
      congr 1
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro d _
      ring
    _ =
        η.1.values x⁻¹ *
            η.1.values x *
          ∑ d : goodElementCentralizer N q,
            (goodElementExtensionRatio
              N θ hinvariant q η d : ℂ) := by
      ring

/-- The ratio form of the local commutator identity at the canonical lift
of `q`. -/
theorem degree_mul_localCommutatorSum_eq_ratioSum
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ a : A, a • θ = θ)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q) :
    (θ.degree : ℂ) *
        ∑ d : goodElementCentralizer N q,
          θ.values
            ⟨(cyclicOverQuotientGenerator N q : A)⁻¹ *
                (d : A)⁻¹ *
                (cyclicOverQuotientGenerator N q : A) *
                (d : A),
              cyclicOverQuotientGenerator_commutator_mem
                N q d⟩ =
      η.1.values (cyclicOverQuotientGenerator N q)⁻¹ *
          η.1.values (cyclicOverQuotientGenerator N q) *
        ∑ d : goodElementCentralizer N q,
          (goodElementExtensionRatio
            N θ hinvariant q η d : ℂ) := by
  simpa only using
    degree_mul_localCommutatorSum_eq_ratioSum_of_ambientQuotient_eq
      N θ hinvariant q η (cyclicOverQuotientGenerator N q)
        (cyclicOverQuotientGenerator_ambientQuotient N q)

/-- At any lift of `q`, the local commutator sum is supported exactly on
good quotient elements, with its good-case value obtained from the order
of the preimage centralizer. -/
theorem degree_mul_localCommutatorSum_eq_if_isGood_of_ambientQuotient_eq
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ a : A, a • θ = θ)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q)
    (x : cyclicOverQuotientElement N q)
    (hx :
      QuotientGroup.mk' N (x : A) = q) :
    (θ.degree : ℂ) *
        ∑ d : goodElementCentralizer N q,
          θ.values
            ⟨(x : A)⁻¹ *
                (d : A)⁻¹ *
                (x : A) *
                (d : A),
              cyclicOverElement_commutator_mem_of_ambientQuotient_eq
                N q x hx d⟩ =
      if IsGoodQuotientElement N θ q then
        η.1.values x⁻¹ *
            η.1.values x *
          (Nat.card (goodElementCentralizer N q) : ℂ)
      else 0 := by
  rw [
    degree_mul_localCommutatorSum_eq_ratioSum_of_ambientQuotient_eq
      N θ hinvariant q η x hx]
  have hsum :=
    sum_goodElementExtensionRatio N θ hinvariant q η
  rw [hsum]
  by_cases hq : IsGoodQuotientElement N θ q <;>
    simp only [hq, if_true, if_false, mul_zero]

/-- The good/zero form of the local commutator identity at the canonical
lift of `q`. -/
theorem degree_mul_localCommutatorSum_eq_if_isGood
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ a : A, a • θ = θ)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q) :
    (θ.degree : ℂ) *
        ∑ d : goodElementCentralizer N q,
          θ.values
            ⟨(cyclicOverQuotientGenerator N q : A)⁻¹ *
                (d : A)⁻¹ *
                (cyclicOverQuotientGenerator N q : A) *
                (d : A),
              cyclicOverQuotientGenerator_commutator_mem
                N q d⟩ =
      if IsGoodQuotientElement N θ q then
        η.1.values (cyclicOverQuotientGenerator N q)⁻¹ *
            η.1.values (cyclicOverQuotientGenerator N q) *
          (Nat.card (goodElementCentralizer N q) : ℂ)
      else 0 := by
  simpa only using
    degree_mul_localCommutatorSum_eq_if_isGood_of_ambientQuotient_eq
      N θ hinvariant q η (cyclicOverQuotientGenerator N q)
        (cyclicOverQuotientGenerator_ambientQuotient N q)

/-- The good/zero local commutator identity for every representative
obtained by multiplying the canonical lift of `q` by an element of `N`. -/
theorem degree_mul_localCommutatorSum_generator_mul_normal_eq_if_isGood
    (θ : IrreducibleCharacter N)
    (hinvariant : ∀ a : A, a • θ = θ)
    (q : A ⧸ N)
    (η : CyclicOverExtensions N θ q)
    (h : N) :
    let x : cyclicOverQuotientElement N q :=
      cyclicOverQuotientGenerator N q *
        cyclicOverInclusion N q h
    (θ.degree : ℂ) *
        ∑ d : goodElementCentralizer N q,
          θ.values
            ⟨(x : A)⁻¹ * (d : A)⁻¹ *
                (x : A) * (d : A),
              cyclicOverQuotientGenerator_mul_normal_commutator_mem
                N q h d⟩ =
      if IsGoodQuotientElement N θ q then
        η.1.values x⁻¹ * η.1.values x *
          (Nat.card (goodElementCentralizer N q) : ℂ)
      else 0 := by
  simpa only using
    degree_mul_localCommutatorSum_eq_if_isGood_of_ambientQuotient_eq
      N θ hinvariant q η
        (cyclicOverQuotientGenerator N q *
          cyclicOverInclusion N q h)
        (cyclicOverQuotientGenerator_mul_normal_ambientQuotient
          N q h)

end Finite

end IrreducibleCharacter
end McKayConjecture
