/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.GoodElementClassTransport
import McKayConjecture.Character.GoodElementTwoGeneratorExtension
import McKayConjecture.Character.OkuyamaWajimaExtensionReduction
import McKayConjecture.GroupTheory.CommutatorEquiv

/-!
# Good-element consequences of the Okuyama--Wajima extension comparison

This file packages the application of the ordinary Okuyama--Wajima
extension theorem to Gallagher good elements.  Its main hypothesis is
semantic: extension existence is compared uniformly for every abelian
intermediate subgroup between `C_K(Q)` and `U`.  This is precisely the
form consumed by Navarro's two-generator criterion.

Factor matching remains one sufficient way to construct the semantic
input, but it is not built into the good-element or counting statements.
-/

noncomputable section

open scoped IsMulCommutative

namespace McKayConjecture
namespace IrreducibleCharacter

variable {A : Type} [Group A] [Finite A]

/-- The subgroup generated by a quotient element and a lift of an element
centralizing it has abelian quotient over the normal subgroup. -/
theorem commutator_twoGeneratorOverQuotientElement_le
    (N : Subgroup A) [N.Normal]
    (q : A ⧸ N)
    (d : goodElementCentralizer N q) :
    _root_.commutator
        (twoGeneratorOverQuotientElement N q d) ≤
      N.subgroupOf
        (twoGeneratorOverQuotientElement N q d) := by
  let L := twoGeneratorOverQuotientElement N q d
  let dq : A ⧸ N := QuotientGroup.mk' N (d : A)
  let R : Subgroup (A ⧸ N) :=
    Subgroup.closure ({dq, q} : Set (A ⧸ N))
  have hdq : dq * q = q * dq := by
    exact Subgroup.mem_centralizer_singleton_iff.mp d.2
  have hRcomm :
      ∀ x ∈ ({dq, q} : Set (A ⧸ N)),
        ∀ y ∈ ({dq, q} : Set (A ⧸ N)),
          x * y = y * x := by
    intro x hx y hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
    rcases hx with rfl | rfl <;>
      rcases hy with rfl | rfl
    · rfl
    · exact hdq
    · exact hdq.symm
    · rfl
  letI : IsMulCommutative R :=
    Subgroup.isMulCommutative_closure hRcomm
  letI : CommGroup R := inferInstance
  have hmap :
      L.map (QuotientGroup.mk' N) ≤ R := by
    rw [show L =
      Subgroup.zpowers (d : A) ⊔
        cyclicOverQuotientElement N q by rfl,
      Subgroup.map_sup,
      (QuotientGroup.mk' N).map_zpowers]
    apply sup_le
    · rw [Subgroup.zpowers_le]
      exact Subgroup.subset_closure (by simp [dq])
    · rintro _ ⟨x, hx, rfl⟩
      have hRq : Subgroup.zpowers q ≤ R := by
        rw [Subgroup.zpowers_le]
        exact Subgroup.subset_closure (by simp)
      exact hRq hx
  let f : L →* R :=
    ((QuotientGroup.mk' N).domRestrict L).codRestrict
      R (fun x => hmap (Subgroup.mem_map_of_mem _ x.2))
  have hker : f.ker = N.subgroupOf L := by
    ext x
    simp only [MonoidHom.mem_ker, Subgroup.mem_subgroupOf]
    change
      (⟨QuotientGroup.mk' N (x : A),
          hmap (Subgroup.mem_map_of_mem _ x.2)⟩ : R) =
          1 ↔
        (x : A) ∈ N
    rw [Subtype.ext_iff]
    exact QuotientGroup.eq_one_iff (x : A)
  rw [← hker]
  exact Abelianization.commutator_subset_ker f

/-- Extension existence is unchanged when a subgroup is replaced by its
image under an injective ambient homomorphism.  This is the concrete
subgroup-coordinate adapter used below. -/
theorem exists_extensionAlong_map_subtype_iff
    (C U : Subgroup A)
    (hCU : C ≤ U)
    (L : Subgroup U)
    (hCL : C.subgroupOf U ≤ L)
    (hCV : C ≤ L.map U.subtype)
    (χ : IrreducibleCharacter C) :
    (∃ ψ : IrreducibleCharacter (L.map U.subtype),
        IsExtensionAlong
          (Subgroup.inclusion hCV)
          χ ψ) ↔
      ∃ η : IrreducibleCharacter L,
        IsExtensionAlong
          (Subgroup.inclusion hCL)
          (χ.comap (Subgroup.subgroupOfEquivOfLe hCU))
          η := by
  let V := L.map U.subtype
  let eG : L ≃* V :=
    L.equivMapOfInjective U.subtype U.subtype_injective
  let eC : C.subgroupOf U ≃* C :=
    Subgroup.subgroupOfEquivOfLe hCU
  have hcomm :
      eG.toMonoidHom.comp (Subgroup.inclusion hCL) =
        (Subgroup.inclusion hCV).comp eC.toMonoidHom := by
    rfl
  constructor
  · rintro ⟨ψ, hψ⟩
    exact
      ⟨ψ.comap eG,
        IsExtensionAlong.comap_equiv eG eC hcomm hψ⟩
  · rintro ⟨η, hη⟩
    have hcomm' :
        eG.symm.toMonoidHom.comp (Subgroup.inclusion hCV) =
          (Subgroup.inclusion hCL).comp eC.symm.toMonoidHom := by
      apply MonoidHom.ext
      intro c
      apply eG.injective
      change
        eG (eG.symm (Subgroup.inclusion hCV c)) =
          eG
            (Subgroup.inclusion hCL
              (eC.symm c))
      rw [eG.apply_symm_apply]
      apply Subtype.ext
      rfl
    refine ⟨η.comap eG.symm, ?_⟩
    have h :=
      IsExtensionAlong.comap_equiv
        eG.symm eC.symm hcomm' hη
    simpa [eC] using h

/-- Extension existence is insensitive to replacing an ambient subgroup by
an equal subgroup; the two inclusion proofs are propositionally irrelevant. -/
theorem exists_extensionAlong_inclusion_congr
    (C V W : Subgroup A)
    (hCV : C ≤ V)
    (hCW : C ≤ W)
    (hVW : V = W)
    (χ : IrreducibleCharacter C) :
    (∃ ψ : IrreducibleCharacter V,
        IsExtensionAlong (Subgroup.inclusion hCV) χ ψ) ↔
      ∃ φ : IrreducibleCharacter W,
        IsExtensionAlong (Subgroup.inclusion hCW) χ φ := by
  subst W
  rfl

/-- The commutator containment for a subgroup of `U` transports to its
ambient image in `A`. -/
theorem commutator_map_subtype_le
    (C U : Subgroup A)
    (L : Subgroup U)
    (hcomm :
      _root_.commutator L ≤
        (C.subgroupOf U).subgroupOf L) :
    _root_.commutator (L.map U.subtype) ≤
      C.subgroupOf (L.map U.subtype) := by
  let V := L.map U.subtype
  let e : L ≃* V :=
    L.equivMapOfInjective U.subtype U.subtype_injective
  rw [← e.map_commutator_eq]
  rintro x ⟨y, hy, rfl⟩
  change ((y : L) : U) ∈ C.subgroupOf U
  exact hcomm hy

/-- Replacing a lift by another element in the same normal coset does not
change the two-generator subgroup. -/
theorem twoGeneratorOverQuotientElement_eq_of_mk_eq
    (N : Subgroup A) [N.Normal]
    (q : A ⧸ N)
    (d₁ d₂ : goodElementCentralizer N q)
    (hquot :
      QuotientGroup.mk' N (d₁ : A) =
        QuotientGroup.mk' N (d₂ : A)) :
    twoGeneratorOverQuotientElement N q d₁ =
      twoGeneratorOverQuotientElement N q d₂ := by
  apply le_antisymm
  · apply sup_le
    · rw [Subgroup.zpowers_le]
      have hdiv : (d₁ : A) / (d₂ : A) ∈ N :=
        (QuotientGroup.eq_iff_div_mem (N := N)).mp hquot
      have hn :
          (d₁ : A) / (d₂ : A) ∈
            twoGeneratorOverQuotientElement N q d₂ :=
        (normal_le_twoGeneratorOverQuotientElement N q d₂) hdiv
      have hd :
          (d₂ : A) ∈
            twoGeneratorOverQuotientElement N q d₂ :=
        (show
            Subgroup.zpowers (d₂ : A) ≤
              twoGeneratorOverQuotientElement N q d₂ from
          le_sup_left)
          (Subgroup.mem_zpowers (d₂ : A))
      simpa only [div_mul_cancel] using
        (twoGeneratorOverQuotientElement N q d₂).mul_mem hn hd
    · exact le_sup_right
  · apply sup_le
    · rw [Subgroup.zpowers_le]
      have hdiv : (d₂ : A) / (d₁ : A) ∈ N :=
        (QuotientGroup.eq_iff_div_mem (N := N)).mp hquot.symm
      have hn :
          (d₂ : A) / (d₁ : A) ∈
            twoGeneratorOverQuotientElement N q d₁ :=
        (normal_le_twoGeneratorOverQuotientElement N q d₁) hdiv
      have hd :
          (d₁ : A) ∈
            twoGeneratorOverQuotientElement N q d₁ :=
        (show
            Subgroup.zpowers (d₁ : A) ≤
              twoGeneratorOverQuotientElement N q d₁ from
          le_sup_left)
          (Subgroup.mem_zpowers (d₁ : A))
      simpa only [div_mul_cancel] using
        (twoGeneratorOverQuotientElement N q d₁).mul_mem hn hd
    · exact le_sup_right

section QuotientProduct

variable {B : Type} [Group B]

/-- Under a quotient equivalence induced by a normal-product embedding,
the cyclic-over subgroup is the normal kernel joined with the image of the
cyclic-over subgroup on the smaller side. -/
theorem cyclicOverQuotientElement_eq_sup_map_of_quotientEquiv
    (N : Subgroup A) [N.Normal]
    (M : Subgroup B) [M.Normal]
    (j : B →* A)
    (e : B ⧸ M ≃* A ⧸ N)
    (he :
      ∀ b : B,
        e (QuotientGroup.mk' M b) =
          QuotientGroup.mk' N (j b))
    (hproduct :
      ∀ a : A,
        ∃ n : N, ∃ b : B,
          (n : A) * j b = a)
    (q : B ⧸ M) :
    cyclicOverQuotientElement N (e q) =
      N ⊔
        (cyclicOverQuotientElement M q).map j := by
  apply le_antisymm
  · intro a ha
    obtain ⟨n, b, hnb⟩ := hproduct a
    have hbe :
        e (QuotientGroup.mk' M b) =
          QuotientGroup.mk' N a := by
      calc
        e (QuotientGroup.mk' M b) =
            QuotientGroup.mk' N (j b) := he b
        _ =
            QuotientGroup.mk' N (n : A) *
              QuotientGroup.mk' N (j b) := by
                have hnq :
                    QuotientGroup.mk' N (n : A) = 1 :=
                  (QuotientGroup.eq_one_iff (n : A)).mpr n.2
                calc
                  QuotientGroup.mk' N (j b) =
                      1 * QuotientGroup.mk' N (j b) :=
                    (one_mul _).symm
                  _ =
                      QuotientGroup.mk' N (n : A) *
                        QuotientGroup.mk' N (j b) := by
                    rw [hnq]
        _ = QuotientGroup.mk' N a := by
              rw [← map_mul, hnb]
    have hbq :
        QuotientGroup.mk' M b ∈
          Subgroup.zpowers q := by
      have ha' :
          e (QuotientGroup.mk' M b) ∈
            Subgroup.zpowers (e q) := by
        rw [hbe]
        exact ha
      have hmapzp :
          (Subgroup.zpowers q).map e.toMonoidHom =
            Subgroup.zpowers (e q) := by
        simpa using e.toMonoidHom.map_zpowers q
      rw [← hmapzp] at ha'
      obtain ⟨r, hr, her⟩ := ha'
      have hrb : r = QuotientGroup.mk' M b :=
        e.injective her
      rwa [← hrb]
    have hb :
        j b ∈
          (cyclicOverQuotientElement M q).map j :=
      ⟨b, hbq, rfl⟩
    rw [← hnb]
    exact Subgroup.mul_mem_sup n.2 hb
  · apply sup_le
    · exact normal_le_cyclicOverQuotientElement N (e q)
    · rintro _ ⟨b, hb, rfl⟩
      change
        QuotientGroup.mk' N (j b) ∈
          Subgroup.zpowers (e q)
      rw [← he]
      have hbq :
          QuotientGroup.mk' M b ∈
            Subgroup.zpowers q :=
        hb
      have hbmap :=
        Subgroup.mem_map_of_mem e.toMonoidHom hbq
      have hmapzp :
          (Subgroup.zpowers q).map e.toMonoidHom =
            Subgroup.zpowers (e q) := by
        simpa using e.toMonoidHom.map_zpowers q
      rwa [hmapzp] at hbmap

/-- The corresponding two-generator subgroup is the normal kernel joined
with the image of the two-generator subgroup on the smaller side. -/
theorem twoGeneratorOverQuotientElement_eq_sup_map_of_quotientEquiv
    (N : Subgroup A) [N.Normal]
    (M : Subgroup B) [M.Normal]
    (j : B →* A)
    (e : B ⧸ M ≃* A ⧸ N)
    (he :
      ∀ b : B,
        e (QuotientGroup.mk' M b) =
          QuotientGroup.mk' N (j b))
    (hproduct :
      ∀ a : A,
        ∃ n : N, ∃ b : B,
          (n : A) * j b = a)
    (q : B ⧸ M)
    (d : goodElementCentralizer M q)
    (jd : goodElementCentralizer N (e q))
    (hjd : (jd : A) = j (d : B)) :
    twoGeneratorOverQuotientElement N (e q) jd =
      N ⊔
        (twoGeneratorOverQuotientElement M q d).map j := by
  rw [show
      twoGeneratorOverQuotientElement N (e q) jd =
        Subgroup.zpowers (jd : A) ⊔
          cyclicOverQuotientElement N (e q) by rfl,
    cyclicOverQuotientElement_eq_sup_map_of_quotientEquiv
      N M j e he hproduct q,
    show
      twoGeneratorOverQuotientElement M q d =
        Subgroup.zpowers (d : B) ⊔
          cyclicOverQuotientElement M q by rfl,
    Subgroup.map_sup, j.map_zpowers, hjd]
  ac_rfl

end QuotientProduct

end IrreducibleCharacter
end McKayConjecture

namespace McKayConjecture

open GroupTheory
open IrreducibleCharacter
open CliffordCorrespondence

variable {A : Type} [Group A] [Finite A]
variable {p : ℕ} [Fact p.Prime]
variable (K Q U : Subgroup A) [K.Normal]

/-- Character-triple invariance in the smul form expected by the
good-element API. -/
theorem CharacterTriple.smul_character_eq
    {G : Type} [Group G] [Finite G]
    (T : CharacterTriple G) (g : G) :
    g • T.character = T.character := by
  apply IrreducibleCharacter.ext
  funext x
  rw [IrreducibleCharacter.conjBy_values]
  change
    T.character.values
        (conjugateNormalElement
          T.normalSubgroup T.isNormal g⁻¹ x) =
      T.character.values x
  exact T.isInvariant g⁻¹ x

/-- The semantic uniform form of the ordinary Okuyama--Wajima input.

For each intermediate subgroup `C_K(Q) ≤ V ≤ U` with abelian quotient
`V / C_K(Q)`, it asks only for the extension-existence conclusion.  No
choice of projective representations or factor sets is exposed to the
good-element API. -/
def UniformOkuyamaWajimaExtensionComparison
    (d : GlaubermanCorrespondence K Q p)
    (theta : PInvariantPPrimeIrreducibleCharacter K Q p) : Prop :=
  ∀ (V : Subgroup A)
      (hCV : coprimeFixedPoints K Q ≤ V),
    V ≤ U →
      _root_.commutator V ≤
          (coprimeFixedPoints K Q).subgroupOf V →
        okuyamaWajimaExtensionConclusion
          K Q V hCV d theta

/-- The former, stronger uniform factor-matching input.

It asks for the named factor-matching theorem at every intermediate
subgroup `C_K(Q) ≤ V ≤ U`.  The abelian-quotient premise remains inside
`InvariantOkuyamaWajimaAbelianQuotientFactorMatching`, so callers only
need to establish it for the two-generator subgroup currently under
consideration. -/
def UniformInvariantOkuyamaWajimaAbelianQuotientFactorMatching
    (hU : U ≤ Subgroup.normalizer (Q : Set A))
    (hCU : coprimeFixedPoints K Q ≤ U)
    (d : GlaubermanCorrespondence K Q p)
    (theta : PInvariantPPrimeIrreducibleCharacter K Q p)
    (hinvariant : ∀ a : A, a • theta.1.1 = theta.1.1) : Prop :=
  ∀ (V : Subgroup A)
      (hCV : coprimeFixedPoints K Q ≤ V)
      (hVU : V ≤ U),
    InvariantOkuyamaWajimaAbelianQuotientFactorMatching
      K Q V (hVU.trans hU) hCV d theta hinvariant

/-- Uniform factor matching supplies the weaker semantic extension
comparison consumed below.  This is the only adapter through which
projective factor-set data enters the good-element chain. -/
theorem uniformOkuyamaWajimaExtensionComparison_of_factorMatching
    (hQ : IsPGroup p Q)
    (hK : IsPPrimeGroup p K)
    (hKQ : (K ⊔ Q).Normal)
    (hU : U ≤ Subgroup.normalizer (Q : Set A))
    (hCU : coprimeFixedPoints K Q ≤ U)
    (d : GlaubermanCorrespondence K Q p)
    (theta : PInvariantPPrimeIrreducibleCharacter K Q p)
    (hinvariant : ∀ a : A, a • theta.1.1 = theta.1.1)
    (how :
      UniformInvariantOkuyamaWajimaAbelianQuotientFactorMatching
        K Q U hU hCU d theta hinvariant) :
    UniformOkuyamaWajimaExtensionComparison
      K Q U d theta := by
  intro V hCV hVU hcomm
  exact
    okuyamaWajimaExtensionConclusion_of_abelianQuotientFactorMatching
      K Q V hQ hK hKQ (hVU.trans hU) hCV hcomm
      d theta hinvariant (how V hCV hVU)

/-- The uniform OW input compares extension existence on an arbitrary
intermediate subgroup of `U` with extension existence on its normal
product with `K`. -/
theorem okuyamaWajimaIntermediateExtension_iff
    (hCU : coprimeFixedPoints K Q ≤ U)
    (d : GlaubermanCorrespondence K Q p)
    (theta : PInvariantPPrimeIrreducibleCharacter K Q p)
    (how :
      UniformOkuyamaWajimaExtensionComparison
        K Q U d theta)
    (L : Subgroup U)
    (hCL :
      (coprimeFixedPoints K Q).subgroupOf U ≤ L)
    (hcomm :
      _root_.commutator L ≤
        ((coprimeFixedPoints K Q).subgroupOf U).subgroupOf L) :
    (∃ ψ :
        IrreducibleCharacter
          (L.map U.subtype ⊔ K : Subgroup A),
        IrreducibleCharacter.IsExtensionAlong
          (Subgroup.inclusion le_sup_right)
          theta.1.1 ψ) ↔
      ∃ φ : IrreducibleCharacter L,
        IrreducibleCharacter.IsExtensionAlong
          (Subgroup.inclusion hCL)
          ((d.characterEquiv theta).1.comap
            (Subgroup.subgroupOfEquivOfLe hCU))
          φ := by
  let C := coprimeFixedPoints K Q
  let V : Subgroup A := L.map U.subtype
  have hCV : C ≤ V := by
    intro c hc
    let u : U := ⟨c, hCU hc⟩
    have huC : u ∈ C.subgroupOf U := hc
    exact ⟨u, hCL huC, rfl⟩
  have hVU : V ≤ U := by
    rintro _ ⟨u, _hu, rfl⟩
    exact u.2
  have hcommV :
      _root_.commutator V ≤ C.subgroupOf V :=
    IrreducibleCharacter.commutator_map_subtype_le
      C U L hcomm
  have hOW :
      okuyamaWajimaExtensionConclusion
        K Q V hCV d theta :=
    how V hCV hVU hcommV
  have htarget :=
    IrreducibleCharacter.exists_extensionAlong_map_subtype_iff
      C U hCU L hCL hCV (d.characterEquiv theta).1
  exact hOW.trans htarget

/-- For a target two-generator subgroup, the uniform OW input identifies
extension existence with extension existence on the corresponding
two-generator subgroup of the normal product. -/
theorem okuyamaWajimaTwoGeneratorExtension_iff
    (hQ : IsPGroup p Q)
    (hK : IsPPrimeGroup p K)
    (hU : U ≤ Subgroup.normalizer (Q : Set A))
    (hCU : coprimeFixedPoints K Q ≤ U)
    (d : GlaubermanCorrespondence K Q p)
    (theta : PInvariantPPrimeIrreducibleCharacter K Q p)
    (hinvariant : ∀ a : A, a • theta.1.1 = theta.1.1)
    (how :
      UniformOkuyamaWajimaExtensionComparison
        K Q U d theta) :
    letI :
        ((coprimeFixedPoints K Q).subgroupOf U).Normal :=
      Subgroup.normal_subgroupOf_of_le_normalizer
        (hU.trans
          (normalizer_le_normalizer_inf_centralizer K Q))
    ∀ (q :
          U ⧸ (coprimeFixedPoints K Q).subgroupOf U)
      (dt :
        IrreducibleCharacter.goodElementCentralizer
          ((coprimeFixedPoints K Q).subgroupOf U) q)
      (ds :
        IrreducibleCharacter.goodElementCentralizer
          (K.subgroupOf (U ⊔ K : Subgroup A))
          (okuyamaWajimaQuotientEquiv
            K Q hQ hK U hU hCU q)),
      (ds : (U ⊔ K : Subgroup A)) =
          Subgroup.inclusion le_sup_left (dt : U) →
      ((∃ ψ :
          IrreducibleCharacter
            (IrreducibleCharacter.twoGeneratorOverQuotientElement
              (K.subgroupOf (U ⊔ K : Subgroup A))
              (okuyamaWajimaQuotientEquiv
                K Q hQ hK U hU hCU q) ds),
          IrreducibleCharacter.IsExtensionAlong
            (Subgroup.inclusion
              (IrreducibleCharacter.normal_le_twoGeneratorOverQuotientElement
                (K.subgroupOf (U ⊔ K : Subgroup A))
                (okuyamaWajimaQuotientEquiv
                  K Q hQ hK U hU hCU q) ds))
            (theta.1.1.comap
              (Subgroup.subgroupOfEquivOfLe le_sup_right))
            ψ) ↔
        ∃ φ :
          IrreducibleCharacter
            (IrreducibleCharacter.twoGeneratorOverQuotientElement
              ((coprimeFixedPoints K Q).subgroupOf U) q dt),
          IrreducibleCharacter.IsExtensionAlong
            (Subgroup.inclusion
              (IrreducibleCharacter.normal_le_twoGeneratorOverQuotientElement
                ((coprimeFixedPoints K Q).subgroupOf U) q dt))
            ((d.characterEquiv theta).1.comap
              (Subgroup.subgroupOfEquivOfLe hCU))
            φ) := by
  letI :
      ((coprimeFixedPoints K Q).subgroupOf U).Normal :=
    Subgroup.normal_subgroupOf_of_le_normalizer
      (hU.trans
        (normalizer_le_normalizer_inf_centralizer K Q))
  intro q dt ds hds
  let C := coprimeFixedPoints K Q
  let B := (U ⊔ K : Subgroup A)
  let N := K.subgroupOf B
  let M := C.subgroupOf U
  let j : U →* B := Subgroup.inclusion le_sup_left
  let e : U ⧸ M ≃* B ⧸ N :=
    okuyamaWajimaQuotientEquiv
      K Q hQ hK U hU hCU
  let Lt :=
    IrreducibleCharacter.twoGeneratorOverQuotientElement M q dt
  let Ls :=
    IrreducibleCharacter.twoGeneratorOverQuotientElement N (e q) ds
  have he (u : U) :
      e (QuotientGroup.mk' M u) =
        QuotientGroup.mk' N (j u) := by
    exact
      okuyamaWajimaQuotientEquiv_mk
        K Q hQ hK U hU hCU u
  have hproduct :
      ∀ b : B,
        ∃ n : N, ∃ u : U,
          (n : B) * j u = b := by
    intro b
    exact
      (invariantOkuyamaWajimaFactorMatchedGroupData
        K Q U hQ hK hU hCU d theta hinvariant).ambient_eq_product b
  have hLs :
      Ls = N ⊔ Lt.map j :=
    IrreducibleCharacter.twoGeneratorOverQuotientElement_eq_sup_map_of_quotientEquiv
      N M j e he hproduct q dt ds hds
  have hcomp :
      B.subtype.comp j = U.subtype := by
    rfl
  have hLsMap :
      Ls.map B.subtype =
        Lt.map U.subtype ⊔ K := by
    calc
      Ls.map B.subtype =
          (N ⊔ Lt.map j).map B.subtype := by
            rw [hLs]
      _ =
          N.map B.subtype ⊔
            (Lt.map j).map B.subtype := by
              rw [Subgroup.map_sup]
      _ =
          K ⊔ Lt.map U.subtype := by
            rw [Subgroup.subgroupOf_map_subtype,
              inf_eq_left.mpr le_sup_right,
              Subgroup.map_map, hcomp]
      _ = Lt.map U.subtype ⊔ K :=
        sup_comm _ _
  have hNLs : N ≤ Ls :=
    IrreducibleCharacter.normal_le_twoGeneratorOverQuotientElement
      N (e q) ds
  have hKLsMap : K ≤ Ls.map B.subtype := by
    intro k hk
    let b : B :=
      ⟨k,
        (show K ≤ U ⊔ K from le_sup_right) hk⟩
    have hbN : b ∈ N := hk
    exact ⟨b, hNLs hbN, rfl⟩
  have hsourceMap :=
    IrreducibleCharacter.exists_extensionAlong_map_subtype_iff
      K B le_sup_right Ls hNLs hKLsMap theta.1.1
  have hcoord :
      (∃ ψ :
          IrreducibleCharacter (Ls.map B.subtype),
          IrreducibleCharacter.IsExtensionAlong
            (Subgroup.inclusion hKLsMap)
            theta.1.1 ψ) ↔
      (∃ ψ :
          IrreducibleCharacter
            (Lt.map U.subtype ⊔ K : Subgroup A),
          IrreducibleCharacter.IsExtensionAlong
            (Subgroup.inclusion le_sup_right)
            theta.1.1 ψ) :=
    IrreducibleCharacter.exists_extensionAlong_inclusion_congr
      K (Ls.map B.subtype)
      (Lt.map U.subtype ⊔ K)
      hKLsMap le_sup_right hLsMap theta.1.1
  have hLtcomm :
      _root_.commutator Lt ≤ M.subgroupOf Lt :=
    IrreducibleCharacter.commutator_twoGeneratorOverQuotientElement_le
      M q dt
  have hlocal :=
    okuyamaWajimaIntermediateExtension_iff
      K Q U hCU d theta how
      Lt
      (IrreducibleCharacter.normal_le_twoGeneratorOverQuotientElement
        M q dt)
      hLtcomm
  exact hsourceMap.symm.trans (hcoord.trans hlocal)

/-- The uniform semantic Okuyama--Wajima comparison preserves Gallagher
good elements pointwise under the canonical quotient equivalence. -/
theorem okuyamaWajima_isGoodQuotientElement_iff
    (hQ : IsPGroup p Q)
    (hK : IsPPrimeGroup p K)
    (hU : U ≤ Subgroup.normalizer (Q : Set A))
    (hCU : coprimeFixedPoints K Q ≤ U)
    (d : GlaubermanCorrespondence K Q p)
    (theta : PInvariantPPrimeIrreducibleCharacter K Q p)
    (hinvariant : ∀ a : A, a • theta.1.1 = theta.1.1)
    (how :
      UniformOkuyamaWajimaExtensionComparison
        K Q U d theta) :
    letI :
        ((coprimeFixedPoints K Q).subgroupOf U).Normal :=
      Subgroup.normal_subgroupOf_of_le_normalizer
        (hU.trans
          (normalizer_le_normalizer_inf_centralizer K Q))
    ∀ q : U ⧸ (coprimeFixedPoints K Q).subgroupOf U,
      IrreducibleCharacter.IsGoodQuotientElement
          ((coprimeFixedPoints K Q).subgroupOf U)
          ((d.characterEquiv theta).1.comap
            (Subgroup.subgroupOfEquivOfLe hCU))
          q ↔
        IrreducibleCharacter.IsGoodQuotientElement
          (K.subgroupOf (U ⊔ K : Subgroup A))
          (theta.1.1.comap
            (Subgroup.subgroupOfEquivOfLe le_sup_right))
          (okuyamaWajimaQuotientEquiv
            K Q hQ hK U hU hCU q) := by
  letI :
      ((coprimeFixedPoints K Q).subgroupOf U).Normal :=
    Subgroup.normal_subgroupOf_of_le_normalizer
      (hU.trans
        (normalizer_le_normalizer_inf_centralizer K Q))
  intro q
  let C := coprimeFixedPoints K Q
  let B := (U ⊔ K : Subgroup A)
  let N := K.subgroupOf B
  let M := C.subgroupOf U
  let j : U →* B := Subgroup.inclusion le_sup_left
  let e : U ⧸ M ≃* B ⧸ N :=
    okuyamaWajimaQuotientEquiv
      K Q hQ hK U hU hCU
  let thetaT : IrreducibleCharacter M :=
    (d.characterEquiv theta).1.comap
      (Subgroup.subgroupOfEquivOfLe hCU)
  let thetaS : IrreducibleCharacter N :=
    theta.1.1.comap
      (Subgroup.subgroupOfEquivOfLe le_sup_right)
  let TT :=
    invariantOkuyamaWajimaTargetTriple
      K Q U hU hCU d theta hinvariant
  let TS :=
    invariantOkuyamaWajimaSourceTriple
      K Q U theta hinvariant
  have hTinvariant : ∀ u : U, u • thetaT = thetaT := by
    intro u
    exact TT.smul_character_eq u
  have hSinvariant : ∀ b : B, b • thetaS = thetaS := by
    intro b
    exact TS.smul_character_eq b
  have he (u : U) :
      e (QuotientGroup.mk' M u) =
        QuotientGroup.mk' N (j u) := by
    exact
      okuyamaWajimaQuotientEquiv_mk
        K Q hQ hK U hU hCU u
  rw [
    IrreducibleCharacter.isGoodQuotientElement_iff_forall_exists_twoGenerator_extension
      M thetaT hTinvariant q,
    IrreducibleCharacter.isGoodQuotientElement_iff_forall_exists_twoGenerator_extension
      N thetaS hSinvariant (e q)]
  constructor
  · intro htarget ds
    obtain ⟨u, hu⟩ :=
      QuotientGroup.mk'_surjective M
        (e.symm (QuotientGroup.mk' N (ds : B)))
    have hquot :
        QuotientGroup.mk' N (j u) =
          QuotientGroup.mk' N (ds : B) := by
      rw [← he u, hu, e.apply_symm_apply]
    have huCentral :
        u ∈
          IrreducibleCharacter.goodElementCentralizer M q := by
      rw [IrreducibleCharacter.goodElementCentralizer,
        Subgroup.mem_comap,
        Subgroup.mem_centralizer_singleton_iff]
      apply e.injective
      rw [map_mul, map_mul, he u, hquot]
      exact
        Subgroup.mem_centralizer_singleton_iff.mp ds.2
    let dt :
        IrreducibleCharacter.goodElementCentralizer M q :=
      ⟨u, huCentral⟩
    have hjuCentral :
        j u ∈
          IrreducibleCharacter.goodElementCentralizer N (e q) := by
      rw [IrreducibleCharacter.goodElementCentralizer,
        Subgroup.mem_comap,
        Subgroup.mem_centralizer_singleton_iff]
      rw [← he]
      have h :=
        Subgroup.mem_centralizer_singleton_iff.mp huCentral
      simpa only [map_mul] using congrArg e h
    let ds' :
        IrreducibleCharacter.goodElementCentralizer N (e q) :=
      ⟨j u, hjuCentral⟩
    have hlocal :=
      okuyamaWajimaTwoGeneratorExtension_iff
        K Q U hQ hK hU hCU d theta hinvariant how
        q dt ds' rfl
    have hext' := hlocal.mpr (htarget dt)
    have hsub :
        IrreducibleCharacter.twoGeneratorOverQuotientElement
            N (e q) ds' =
          IrreducibleCharacter.twoGeneratorOverQuotientElement
            N (e q) ds :=
      IrreducibleCharacter.twoGeneratorOverQuotientElement_eq_of_mk_eq
        N (e q) ds' ds hquot
    exact
      (IrreducibleCharacter.exists_extensionAlong_inclusion_congr
        N
        (IrreducibleCharacter.twoGeneratorOverQuotientElement
          N (e q) ds')
        (IrreducibleCharacter.twoGeneratorOverQuotientElement
          N (e q) ds)
        (IrreducibleCharacter.normal_le_twoGeneratorOverQuotientElement
          N (e q) ds')
        (IrreducibleCharacter.normal_le_twoGeneratorOverQuotientElement
          N (e q) ds)
        hsub thetaS).mp hext'
  · intro hsource dt
    have hjuCentral :
        j (dt : U) ∈
          IrreducibleCharacter.goodElementCentralizer N (e q) := by
      rw [IrreducibleCharacter.goodElementCentralizer,
        Subgroup.mem_comap,
        Subgroup.mem_centralizer_singleton_iff]
      rw [← he]
      have h :=
        Subgroup.mem_centralizer_singleton_iff.mp dt.2
      simpa only [map_mul] using congrArg e h
    let ds :
        IrreducibleCharacter.goodElementCentralizer N (e q) :=
      ⟨j (dt : U), hjuCentral⟩
    exact
      (okuyamaWajimaTwoGeneratorExtension_iff
        K Q U hQ hK hU hCU d theta hinvariant how
        q dt ds rfl).mp
        (hsource ds)

/-- Conditional ordinary Okuyama--Wajima count: once the uniform
semantic extension comparison is supplied, Gallagher's good-class formula
gives equal cardinalities of the two ordinary lying-over fibres. -/
theorem okuyamaWajima_natCard_irreducibleCharactersOverAlong_eq
    (hQ : IsPGroup p Q)
    (hK : IsPPrimeGroup p K)
    (hU : U ≤ Subgroup.normalizer (Q : Set A))
    (hCU : coprimeFixedPoints K Q ≤ U)
    (d : GlaubermanCorrespondence K Q p)
    (theta : PInvariantPPrimeIrreducibleCharacter K Q p)
    (hinvariant : ∀ a : A, a • theta.1.1 = theta.1.1)
    (how :
      UniformOkuyamaWajimaExtensionComparison
        K Q U d theta) :
    letI :
        ((coprimeFixedPoints K Q).subgroupOf U).Normal :=
      Subgroup.normal_subgroupOf_of_le_normalizer
        (hU.trans
          (normalizer_le_normalizer_inf_centralizer K Q))
    Nat.card
        (CliffordCorrespondence.IrreducibleCharactersOverAlong
          ((coprimeFixedPoints K Q).subgroupOf U).subtype
          ((d.characterEquiv theta).1.comap
            (Subgroup.subgroupOfEquivOfLe hCU))) =
      Nat.card
        (CliffordCorrespondence.IrreducibleCharactersOverAlong
          (K.subgroupOf (U ⊔ K : Subgroup A)).subtype
          (theta.1.1.comap
            (Subgroup.subgroupOfEquivOfLe le_sup_right))) := by
  letI :
      ((coprimeFixedPoints K Q).subgroupOf U).Normal :=
    Subgroup.normal_subgroupOf_of_le_normalizer
      (hU.trans
        (normalizer_le_normalizer_inf_centralizer K Q))
  let C := coprimeFixedPoints K Q
  let B := (U ⊔ K : Subgroup A)
  let N := K.subgroupOf B
  let M := C.subgroupOf U
  let thetaT : IrreducibleCharacter M :=
    (d.characterEquiv theta).1.comap
      (Subgroup.subgroupOfEquivOfLe hCU)
  let thetaS : IrreducibleCharacter N :=
    theta.1.1.comap
      (Subgroup.subgroupOfEquivOfLe le_sup_right)
  let TT :=
    invariantOkuyamaWajimaTargetTriple
      K Q U hU hCU d theta hinvariant
  let TS :=
    invariantOkuyamaWajimaSourceTriple
      K Q U theta hinvariant
  have hTinvariant : ∀ u : U, u • thetaT = thetaT := by
    intro u
    exact TT.smul_character_eq u
  have hSinvariant : ∀ b : B, b • thetaS = thetaS := by
    intro b
    exact TS.smul_character_eq b
  let e : U ⧸ M ≃* B ⧸ N :=
    okuyamaWajimaQuotientEquiv
      K Q hQ hK U hU hCU
  have hgood :
      ∀ q : U ⧸ M,
        IrreducibleCharacter.IsGoodQuotientElement
              M thetaT q ↔
          IrreducibleCharacter.IsGoodQuotientElement
              N thetaS (e q) :=
    okuyamaWajima_isGoodQuotientElement_iff
      K Q U hQ hK hU hCU d theta hinvariant how
  let eClasses :=
    IrreducibleCharacter.goodQuotientConjugacyClassesEquivOfMulEquiv
      M N thetaT thetaS e hgood
  exact
    natCard_irreducibleCharactersOverAlong_eq_of_goodQuotientConjugacyClassesEquiv
      M N thetaT thetaS hTinvariant hSinvariant eClasses

end McKayConjecture
