/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.OkuyamaWajimaFullFixedCoordinates
import McKayConjecture.GroupTheory.PGroupMaximalCyclicQuotient
import Mathlib.GroupTheory.Frattini

/-!
# Burnside-basis input for the full-fixed Okuyama--Wajima branch

This file proves the coprime Burnside-basis input isolated by
`OkuyamaWajimaFullFixedCoordinates`.

The proof uses a finite counting form of the Burnside basis argument.
The automorphisms of a finite `p`-group which induce the identity on its
abelianization act freely on the set of pointwise lifts of the identity
map of the abelianization.  Every such lift generates the group, since
the commutator subgroup lies in the Frattini subgroup.  The lift set has
`p`-power cardinality, so its freely acting automorphism group is a
`p`-group.  A homomorphism from a finite `p'`-group to that kernel is
therefore trivial.
-/

noncomputable section

universe u v

namespace McKayConjecture
namespace GroupTheory

/-- The commutator subgroup of a finite `p`-group is contained in its
Frattini subgroup. -/
theorem commutator_le_frattini_of_isPGroup
    {p : ℕ} [Fact p.Prime]
    (P : Type u) [Group P] [Finite P]
    (hP : IsPGroup p P) :
    _root_.commutator P ≤ frattini P := by
  rw [frattini, Order.radical]
  refine le_iInf fun H ↦ le_iInf fun hH ↦ ?_
  letI : Group.IsNilpotent P := hP.isNilpotent
  letI : H.Normal :=
    Subgroup.NormalizerCondition.normal_of_coatom
      H Group.normalizerCondition_of_isNilpotent hH
  letI : Nontrivial (P ⧸ H) :=
    QuotientGroup.nontrivial_iff.mpr hH.ne_top
  letI : IsSimpleGroup (P ⧸ H) :=
    isSimpleGroup_quotient_of_isCoatom H hH
  have hquotientP :
      IsPGroup p (P ⧸ H) :=
    hP.of_surjective
      (QuotientGroup.mk' H)
      (QuotientGroup.mk'_surjective H)
  letI : Group.IsNilpotent (P ⧸ H) :=
    hquotientP.isNilpotent
  letI : IsCyclic (P ⧸ H) := inferInstance
  have hcommutator :
      _root_.commutator P ≤
        (QuotientGroup.mk' H).ker :=
    Abelianization.commutator_subset_ker
      (QuotientGroup.mk' H)
  simpa only [QuotientGroup.ker_mk'] using hcommutator

/-- Pointwise lifts to `P` of the identity function on `P / P'`. -/
abbrev AbelianizationIdentityLift
    (P : Type u) [Group P] :=
  (x : P) →
    (Abelianization.of : P →* Abelianization P) ⁻¹'
      {Abelianization.of x}

/-- Pointwise identity lifts are canonically functions into the
commutator kernel. -/
def abelianizationIdentityLiftEquiv
    (P : Type u) [Group P] :
    AbelianizationIdentityLift P ≃
      (P → (Abelianization.of : P →* Abelianization P).ker) :=
  Equiv.piCongrRight fun x ↦
    (Abelianization.of : P →* Abelianization P).fiberEquivKer x

/-- The subgroup generated by the values of a pointwise identity lift. -/
abbrev AbelianizationIdentityLift.generated
    {P : Type u} [Group P]
    (f : AbelianizationIdentityLift P) :
    Subgroup P :=
  Subgroup.closure (Set.range fun x ↦ (f x : P))

/-- A pointwise identity lift generates a finite `p`-group. -/
theorem AbelianizationIdentityLift.generated_eq_top
    {p : ℕ} [Fact p.Prime]
    {P : Type u} [Group P] [Finite P]
    (hP : IsPGroup p P)
    (f : AbelianizationIdentityLift P) :
    f.generated = ⊤ := by
  have hcommutator :
      _root_.commutator P ≤ frattini P :=
    commutator_le_frattini_of_isPGroup P hP
  apply frattini_nongenerating
  apply top_unique
  intro x _hx
  have hfiber :
      Abelianization.of (f x : P) =
        Abelianization.of x :=
    (f x).2
  have hk :
      x⁻¹ * (f x : P) ∈
        _root_.commutator P := by
    rw [← Abelianization.ker_of]
    exact MonoidHom.mem_ker.mpr <| by
      rw [map_mul, map_inv, hfiber, inv_mul_cancel]
  have hfx :
      (f x : P) ∈ f.generated :=
    Subgroup.subset_closure ⟨x, rfl⟩
  have hkFrattini :
      x⁻¹ * (f x : P) ∈ frattini P :=
    hcommutator hk
  have hproduct :
      (f x : P) * (x⁻¹ * (f x : P))⁻¹ ∈
        f.generated ⊔ frattini P :=
    (f.generated ⊔ frattini P).mul_mem
      ((show f.generated ≤
          f.generated ⊔ frattini P from le_sup_left) hfx)
      ((show frattini P ≤
          f.generated ⊔ frattini P from le_sup_right)
        (inv_mem hkFrattini))
  simpa only [mul_inv_rev, inv_inv, mul_assoc,
    mul_inv_cancel_left] using hproduct

/-- Automorphisms inducing the identity on the abelianization. -/
abbrev IAAutomorphism
    (P : Type u) [Group P] :
    Subgroup (MulAut P) :=
  (abelianizationActionHom (MulAut P) P).ker

/-- The IA automorphism group acts on pointwise identity lifts by
postcomposition. -/
@[instance_reducible]
def iaAutomorphismAbelianizationIdentityLiftAction
    (P : Type u) [Group P] :
    MulAction (IAAutomorphism P)
      (AbelianizationIdentityLift P) where
  smul a f x :=
    ⟨a.1 (f x : P), by
      change
        Abelianization.of (a.1 (f x : P)) =
          Abelianization.of x
      have ha :
          abelianizationActionHom (MulAut P) P a.1 = 1 :=
        MonoidHom.mem_ker.mp a.2
      change
        (abelianizationActionHom (MulAut P) P a.1)
            (Abelianization.of (f x : P)) =
          Abelianization.of x
      rw [ha, MulAut.one_apply]
      exact (f x).2⟩
  one_smul f := by
    funext x
    apply Subtype.ext
    rfl
  mul_smul a b f := by
    funext x
    apply Subtype.ext
    rfl

/-- The IA action on pointwise identity lifts is free. -/
theorem iaAutomorphismAbelianizationIdentityLift_isCancelSMul
    {p : ℕ} [Fact p.Prime]
    (P : Type u) [Group P] [Finite P]
    (hP : IsPGroup p P) :
    letI : MulAction (IAAutomorphism P)
        (AbelianizationIdentityLift P) :=
      iaAutomorphismAbelianizationIdentityLiftAction P
    IsCancelSMul (IAAutomorphism P)
      (AbelianizationIdentityLift P) := by
  letI : MulAction (IAAutomorphism P)
      (AbelianizationIdentityLift P) :=
    iaAutomorphismAbelianizationIdentityLiftAction P
  rw [isCancelSMul_iff_eq_one_of_smul_eq]
  intro a f haf
  have hgenerated :
      f.generated = ⊤ :=
    f.generated_eq_top hP
  have heq :
      a.1.toMonoidHom = MonoidHom.id P := by
    apply MonoidHom.eq_of_eqOn_dense hgenerated
    rintro _ ⟨x, rfl⟩
    exact congrArg Subtype.val (congrFun haf x)
  apply Subtype.ext
  apply MulEquiv.ext
  intro x
  exact DFunLike.congr_fun heq x

/-- A finite group acting freely on a finite type has order dividing the
cardinality of that type. -/
theorem natCard_dvd_natCard_of_isCancelSMul
    (G : Type u) (X : Type v)
    [Group G] [MulAction G X]
    [Finite G] [Finite X]
    [IsCancelSMul G X] :
    Nat.card G ∣ Nat.card X := by
  let Ω := Quotient (MulAction.orbitRel G X)
  have hcard :
      Nat.card X =
        Nat.card Ω * Nat.card G := by
    rw [Nat.card_congr
      (MulAction.selfEquivOrbitsQuotientProd
        (G := G) (X := X)
        IsCancelSMul.stabilizer_eq_bot)]
    exact Nat.card_prod Ω G
  exact ⟨Nat.card Ω, by rw [mul_comm, hcard]⟩

/-- **Burnside basis theorem, IA-kernel form.**

For a finite `p`-group, the automorphisms which induce the identity on
the abelianization form a `p`-group.  Using the abelianization rather
than the smaller Frattini quotient only strengthens the hypothesis. -/
theorem iaAutomorphism_isPGroup
    {p : ℕ} [Fact p.Prime]
    (P : Type u) [Group P] [Finite P]
    (hP : IsPGroup p P) :
    IsPGroup p (IAAutomorphism P) := by
  letI : MulAction (IAAutomorphism P)
      (AbelianizationIdentityLift P) :=
    iaAutomorphismAbelianizationIdentityLiftAction P
  letI : IsCancelSMul (IAAutomorphism P)
      (AbelianizationIdentityLift P) :=
    iaAutomorphismAbelianizationIdentityLift_isCancelSMul
      P hP
  have hdvd :
      Nat.card (IAAutomorphism P) ∣
        Nat.card (AbelianizationIdentityLift P) :=
    natCard_dvd_natCard_of_isCancelSMul
      (IAAutomorphism P)
      (AbelianizationIdentityLift P)
  obtain ⟨n, hn⟩ :=
    (hP.to_subgroup
      (Abelianization.of : P →*
        Abelianization P).ker).exists_card_eq
  have hlifts :
      Nat.card (AbelianizationIdentityLift P) =
        p ^ (n * Nat.card P) := by
    calc
      Nat.card (AbelianizationIdentityLift P) =
          Nat.card
            (P →
              (Abelianization.of : P →*
                Abelianization P).ker) :=
        Nat.card_congr
          (abelianizationIdentityLiftEquiv P)
      _ =
          Nat.card
              (Abelianization.of : P →*
                Abelianization P).ker ^
            Nat.card P :=
        Nat.card_fun
      _ = (p ^ n) ^ Nat.card P := by rw [hn]
      _ = p ^ (n * Nat.card P) :=
        (pow_mul p n (Nat.card P)).symm
  apply IsPGroup.of_card_dvd_pow
  rwa [← hlifts]

/-- **Coprime Burnside basis theorem, action form.**

A finite `p'`-group acting on a finite `p`-group acts trivially as soon
as its induced action on the abelianization is trivial. -/
theorem actionHom_eq_one_of_abelianizationActionHom_eq_one
    {p : ℕ} [Fact p.Prime]
    (M : Type u) (P : Type v)
    [Group M] [Group P]
    [Finite M] [Finite P]
    [MulDistribMulAction M P]
    (hP : IsPGroup p P)
    (hM : IsPPrimeGroup p M)
    (hAbelianization :
      abelianizationActionHom M P = 1) :
    MulDistribMulAction.toMulAut M P = 1 := by
  let f : M →* IAAutomorphism P :=
    (MulDistribMulAction.toMulAut M P).codRestrict
      (IAAutomorphism P) fun m ↦ by
        change
          abelianizationActionHom (MulAut P) P
              (MulDistribMulAction.toMulAut M P m) =
            1
        exact DFunLike.congr_fun hAbelianization m
  have hf :
      f = 1 :=
    by
      apply MonoidHom.ext
      intro m
      change f m = 1
      obtain ⟨k, hk⟩ :=
        iaAutomorphism_isPGroup P hP (f m)
      have hpow :
          orderOf (f m) ∣ p ^ k :=
        orderOf_dvd_of_pow_eq_one hk
      have hcard :
          orderOf (f m) ∣ Nat.card M :=
        (orderOf_map_dvd f m).trans
          (orderOf_dvd_natCard m)
      apply orderOf_eq_one_iff.mp
      exact
        Nat.eq_one_of_dvd_coprimes
          (hM.pow_left k) hpow hcard
  apply MonoidHom.ext
  intro m
  exact congrArg Subtype.val (DFunLike.congr_fun hf m)

/-- Pointwise form of the coprime Burnside basis theorem. -/
theorem smul_eq_of_abelianizationActionHom_eq_one
    {p : ℕ} [Fact p.Prime]
    (M : Type u) (P : Type v)
    [Group M] [Group P]
    [Finite M] [Finite P]
    [MulDistribMulAction M P]
    (hP : IsPGroup p P)
    (hM : IsPPrimeGroup p M)
    (hAbelianization :
      abelianizationActionHom M P = 1)
    (m : M) (x : P) :
    m • x = x := by
  have haction :=
    actionHom_eq_one_of_abelianizationActionHom_eq_one
      M P hP hM hAbelianization
  have hm :=
    DFunLike.congr_fun haction m
  exact congrArg (fun e : MulAut P ↦ e x) hm

end GroupTheory

namespace GroupTheory.OkuyamaWajimaCyclicQuotientSubgroup

variable {M : Type u} {P : Type v}
variable [Group M] [Group P]
variable [MulDistribMulAction M P]
variable {L : Subgroup M}

/-- If the selected subgroup fixes the whole abelianization, then its
induced action homomorphism on the abelianization is trivial. -/
theorem abelianizationActionHom_eq_one_of_fixedPoints_eq_top
    (d : OkuyamaWajimaCyclicQuotientSubgroup M P L)
    (hfull : d.fixedPoints = ⊤) :
    abelianizationActionHom d.U.toSubgroup P = 1 := by
  apply MonoidHom.ext
  intro u
  apply MulEquiv.ext
  intro a
  have ha : a ∈ d.fixedPoints := by
    rw [hfull]
    exact Subgroup.mem_top a
  exact ha u

end GroupTheory.OkuyamaWajimaCyclicQuotientSubgroup

namespace OkuyamaWajimaFullFixedCoordinates

variable {A : Type} [Group A]
variable (M P : Subgroup A)
variable
  (hMNormalizer :
    M ≤ Subgroup.normalizer (P : Set A))
variable {L : Subgroup M}
variable
  (d :
    @GroupTheory.OkuyamaWajimaCyclicQuotientSubgroup
      M P inferInstance inferInstance
      (normalizerConjugationAction M P hMNormalizer) L)

/-- The coprime Burnside basis theorem supplies the centralization input
for the full-fixed coordinate branch automatically. -/
theorem fullFixedCoprimeCentralizationInput_automatic
    [Finite A]
    {p : ℕ} [Fact p.Prime]
    (hP : IsPGroup p P)
    (hMPrime : GroupTheory.IsPPrimeGroup p M)
    (hfull :
      letI : MulDistribMulAction M P :=
        normalizerConjugationAction M P hMNormalizer
      d.fixedPoints = ⊤) :
    FullFixedCoprimeCentralizationInput
      M P hMNormalizer d hP hMPrime hfull := by
  letI : MulDistribMulAction M P :=
    normalizerConjugationAction M P hMNormalizer
  have hAbelianization :
      GroupTheory.abelianizationActionHom
          d.U.toSubgroup P =
        1 :=
    d.abelianizationActionHom_eq_one_of_fixedPoints_eq_top
      hfull
  intro u x
  exact
    GroupTheory.smul_eq_of_abelianizationActionHom_eq_one
      d.U.toSubgroup P hP
        (hMPrime.to_subgroup d.U.toSubgroup)
        hAbelianization u x

end OkuyamaWajimaFullFixedCoordinates
end McKayConjecture
