/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.Character.ElementaryRestriction
import McKayConjecture.Character.PRegularDecomposition
import Mathlib.GroupTheory.Sylow

/-!
# The elementary subgroup attached to a central `p`-regular element

Let `a` be a central `p`-regular element of a finite group `C`, and let
`P` be a Sylow `p`-subgroup of `C`.  The subgroups `⟨a⟩` and `P` commute
and have coprime orders.  Their product is therefore the `p`-elementary
subgroup

`⟨a⟩ P = ⟨a⟩ × P`.

This file packages that product as a `PElementaryDecomposition`.  It also
exposes the copy of `a` in the cyclic coordinate and the inclusion of `P`,
which are the inputs needed in Bernstein's proof of Brauer induction.
-/

noncomputable section

open scoped Pointwise

namespace McKayConjecture

variable {p : ℕ}
variable {C : Type} [Group C] [Finite C] [Fact p.Prime]

/-- The subgroup generated by a central `p`-regular element and a selected
Sylow `p`-subgroup. -/
def centralPRegularElementarySubgroup
    (a : C) (P : Sylow p C) : Subgroup C :=
  Subgroup.zpowers a ⊔ (P : Subgroup C)

/-- The canonical `p`-elementary direct-product decomposition of
`⟨a⟩ P`, for central `p`-regular `a` and Sylow `P`. -/
def centralPRegularElementaryDecomposition
    (a : C)
    (haCentral : a ∈ Subgroup.center C)
    (haRegular : IsPRegular p a)
    (P : Sylow p C) :
    PElementaryDecomposition p
      (centralPRegularElementarySubgroup a P) := by
  let D : Subgroup C := Subgroup.zpowers a
  let S : Subgroup C :=
    centralPRegularElementarySubgroup a P
  let DS : Subgroup S := D.subgroupOf S
  let PS : Subgroup S := (P : Subgroup C).subgroupOf S
  have hDleS : D ≤ S := by
    exact le_sup_left
  have hPleS : (P : Subgroup C) ≤ S := by
    exact le_sup_right
  have hDleCenter : D ≤ Subgroup.center C := by
    exact Subgroup.zpowers_le.mpr haCentral
  have hDnormal : D.Normal := by
    exact
      ⟨fun x hx g => by
        simpa [Subgroup.mem_center_iff.mp
          (hDleCenter hx) g] using hx⟩
  have hDnormalizesP :
      D ≤ Subgroup.normalizer (P : Set C) :=
    hDleCenter.trans
      (Subgroup.center_le_normalizer
        (P : Set C))
  have hDSnormal : DS.Normal := by
    exact hDnormal.subgroupOf S
  have hPSnormal : PS.Normal := by
    change
      ((P : Subgroup C).subgroupOf
        (D ⊔ (P : Subgroup C))).Normal
    exact
      Subgroup.normal_subgroupOf_sup_of_le_normalizer
        hDnormalizesP
  let eD : DS ≃* D :=
    Subgroup.subgroupOfEquivOfLe hDleS
  let eP : PS ≃* (P : Subgroup C) :=
    Subgroup.subgroupOfEquivOfLe hPleS
  have hDcard :
      Nat.card DS = Nat.card D :=
    Nat.card_congr eD.toEquiv
  have hPcard :
      Nat.card PS = Nat.card P :=
    Nat.card_congr eP.toEquiv
  have hDcoprimeP :
      Nat.Coprime (Nat.card D) (Nat.card P) := by
    obtain ⟨k, hk⟩ :=
      IsPGroup.iff_card.mp P.isPGroup'
    change
      Nat.Coprime
        (Nat.card (Subgroup.zpowers a))
        (Nat.card P)
    rw [Nat.card_zpowers]
    rw [hk]
    exact haRegular.symm.pow_right k
  have hDScoprimePS :
      Nat.Coprime (Nat.card DS) (Nat.card PS) := by
    rw [hDcard, hPcard]
    exact hDcoprimeP
  have hdisjoint : Disjoint DS PS :=
    Subgroup.disjoint_of_coprime_natCard
      hDScoprimePS
  have hsup : DS ⊔ PS = ⊤ := by
    exact
      codisjoint_iff.mp
        (Subgroup.codisjoint_subgroupOf_sup
          D (P : Subgroup C))
  have hproduct :
      (DS : Set S) * (PS : Set S) =
        Set.univ := by
    calc
      (DS : Set S) * (PS : Set S) =
          (↑(DS ⊔ PS) : Set S) :=
        (Subgroup.normal_mul DS PS).symm
      _ = (↑(⊤ : Subgroup S) : Set S) := by
        rw [hsup]
      _ = Set.univ := Subgroup.coe_top
  have hcomplement : DS.IsComplement' PS :=
    Subgroup.isComplement'_of_disjoint_and_mul_eq_univ
      hdisjoint hproduct
  exact
    { cyclicPart := DS
      pPart := PS
      cyclic := eD.isCyclic.mpr inferInstance
      cyclicPart_coprime := by
        rw [hDcard]
        change p.Coprime (Nat.card (Subgroup.zpowers a))
        rw [Nat.card_zpowers]
        exact haRegular
      isPGroup :=
        P.isPGroup'.of_equiv eP.symm
      cyclicPart_normal := hDSnormal
      pPart_normal := hPSnormal
      complementary := hcomplement }

omit [Finite C] [Fact p.Prime] in
/-- The chosen Sylow subgroup lies in the elementary subgroup. -/
theorem sylow_le_centralPRegularElementarySubgroup
    (a : C) (P : Sylow p C) :
    (P : Subgroup C) ≤
      centralPRegularElementarySubgroup a P :=
  le_sup_right

/-- The chosen central element, regarded as an element of its elementary
subgroup. -/
def centralPRegularElementInElementarySubgroup
    (a : C) (P : Sylow p C) :
    centralPRegularElementarySubgroup a P :=
  ⟨a,
    (show
      Subgroup.zpowers a ≤
        centralPRegularElementarySubgroup a P
      from le_sup_left)
      (Subgroup.mem_zpowers a)⟩

/-- The chosen central element in the cyclic coordinate of the canonical
elementary decomposition. -/
def centralPRegularCyclicCoordinate
    (a : C)
    (haCentral : a ∈ Subgroup.center C)
    (haRegular : IsPRegular p a)
    (P : Sylow p C) :
    (centralPRegularElementaryDecomposition
      a haCentral haRegular P).cyclicPart :=
  ⟨centralPRegularElementInElementarySubgroup a P,
    Subgroup.mem_zpowers a⟩

omit [Finite C] [Fact p.Prime] in
@[simp]
theorem centralPRegularElementInElementarySubgroup_coe
    (a : C) (P : Sylow p C) :
    (centralPRegularElementInElementarySubgroup a P : C) =
      a :=
  rfl

@[simp]
theorem centralPRegularCyclicCoordinate_coe
    (a : C)
    (haCentral : a ∈ Subgroup.center C)
    (haRegular : IsPRegular p a)
    (P : Sylow p C) :
    (((centralPRegularCyclicCoordinate
        a haCentral haRegular P :
      centralPRegularElementarySubgroup a P) : C)) =
      a :=
  rfl

end McKayConjecture
