/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.LinearCombination
import McKayConjecture.InductiveMcKay.AlternatingSixFiveAmbientMatrixDataDegreeOneThree

/-!
# The square of the first generator in ambient row `2`

This file is generated by `scripts/a6_character_matrices_to_lean.py`.
Each multiplication is split by matrix row or entry and checked with an
explicit quotient by `Φ₁₂₀`, keeping every command below the default
heartbeat limit.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace McKayConjecture
namespace InductiveMcKay

local notation "ζ" => alternatingSixComplexCyclotomicRoot

/-- Exact target matrix for the `matrixA_sq` multiplication step. -/
private def alternatingSixFiveAmbient_row02_matrixA_sqTarget :
    Matrix (Fin 3) (Fin 3) ℂ :=
  (ζ ^ 80) •
    (1 : Matrix (Fin 3) (Fin 3) ℂ)

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row02_matrixA_sq_row00
    (j : Fin 3) :
    (alternatingSixFiveAmbient_row02_matrixA * alternatingSixFiveAmbient_row02_matrixA)
          (0 : Fin 3) j =
      alternatingSixFiveAmbient_row02_matrixA_sqTarget (0 : Fin 3) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (((7 / 4) : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 + ((1 / 2) : ℂ) * ζ ^ 8 + ((3 / 4) : ℂ) * ζ ^ 12 - ((3 / 4) : ℂ) * ζ ^ 16 - ((5 / 4) : ℂ) * ζ ^ 20 + ((5 / 4) : ℂ) * ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(((7 / 4) : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 + ((1 / 2) : ℂ) * ζ ^ 8 + ((3 / 4) : ℂ) * ζ ^ 12 - ((3 / 4) : ℂ) * ζ ^ 16 - ((5 / 4) : ℂ) * ζ ^ 20 + ((5 / 4) : ℂ) * ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (((5 / 2) : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 - ((1 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16 - ζ ^ 20 + ζ ^ 24) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(((5 / 2) : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 - ((1 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16 - ζ ^ 20 + ζ ^ 24)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-((3 / 4) : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 + ((1 / 2) : ℂ) * ζ ^ 8 - ((3 / 4) : ℂ) * ζ ^ 12 + ((3 / 4) : ℂ) * ζ ^ 16 + ((1 / 4) : ℂ) * ζ ^ 20 - ((1 / 4) : ℂ) * ζ ^ 24) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-((3 / 4) : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 + ((1 / 2) : ℂ) * ζ ^ 8 - ((3 / 4) : ℂ) * ζ ^ 12 + ((3 / 4) : ℂ) * ζ ^ 16 + ((1 / 4) : ℂ) * ζ ^ 20 - ((1 / 4) : ℂ) * ζ ^ 24)) *
          alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row02_matrixA_sq_row01
    (j : Fin 3) :
    (alternatingSixFiveAmbient_row02_matrixA * alternatingSixFiveAmbient_row02_matrixA)
          (1 : Fin 3) j =
      alternatingSixFiveAmbient_row02_matrixA_sqTarget (1 : Fin 3) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-(2 : ℂ) + ζ ^ 4 - ζ ^ 12 + ζ ^ 16) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-(2 : ℂ) + ζ ^ 4 - ζ ^ 12 + ζ ^ 16)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-((1 / 4) : ℂ) + ζ ^ 8 - ((5 / 4) : ℂ) * ζ ^ 12 + ((3 / 4) : ℂ) * ζ ^ 16 - ((3 / 4) : ℂ) * ζ ^ 20 + ((3 / 4) : ℂ) * ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-((1 / 4) : ℂ) + ζ ^ 8 - ((5 / 4) : ℂ) * ζ ^ 12 + ((3 / 4) : ℂ) * ζ ^ 16 - ((3 / 4) : ℂ) * ζ ^ 20 + ((3 / 4) : ℂ) * ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (((3 / 2) : ℂ) - ζ ^ 8 + ((1 / 2) : ℂ) * ζ ^ 12 - ((1 / 2) : ℂ) * ζ ^ 16 - ((1 / 2) : ℂ) * ζ ^ 20 + ((1 / 2) : ℂ) * ζ ^ 24) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(((3 / 2) : ℂ) - ζ ^ 8 + ((1 / 2) : ℂ) * ζ ^ 12 - ((1 / 2) : ℂ) * ζ ^ 16 - ((1 / 2) : ℂ) * ζ ^ 20 + ((1 / 2) : ℂ) * ζ ^ 24)) *
          alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row02_matrixA_sq_row02
    (j : Fin 3) :
    (alternatingSixFiveAmbient_row02_matrixA * alternatingSixFiveAmbient_row02_matrixA)
          (2 : Fin 3) j =
      alternatingSixFiveAmbient_row02_matrixA_sqTarget (2 : Fin 3) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) + ((1 / 2) : ℂ) * ζ ^ 4 - ((3 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16 - ((1 / 2) : ℂ) * ζ ^ 20 + ((1 / 2) : ℂ) * ζ ^ 24) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) + ((1 / 2) : ℂ) * ζ ^ 4 - ((3 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16 - ((1 / 2) : ℂ) * ζ ^ 20 + ((1 / 2) : ℂ) * ζ ^ 24)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (((1 / 2) : ℂ) + ((1 / 2) : ℂ) * ζ ^ 4 - ((1 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(((1 / 2) : ℂ) + ((1 / 2) : ℂ) * ζ ^ 4 - ((1 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA, alternatingSixFiveAmbient_row02_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 + ((3 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16 - ((1 / 2) : ℂ) * ζ ^ 20 + ((1 / 2) : ℂ) * ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) - ((1 / 2) : ℂ) * ζ ^ 4 + ((3 / 2) : ℂ) * ζ ^ 8 - ((1 / 2) : ℂ) * ζ ^ 16 - ((1 / 2) : ℂ) * ζ ^ 20 + ((1 / 2) : ℂ) * ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
          alternatingSixComplexCyclotomicRoot_relation

private theorem alternatingSixFiveAmbient_row02_matrixA_sq_mul :
    alternatingSixFiveAmbient_row02_matrixA * alternatingSixFiveAmbient_row02_matrixA =
      alternatingSixFiveAmbient_row02_matrixA_sqTarget := by
  ext i j
  fin_cases i
  · exact alternatingSixFiveAmbient_row02_matrixA_sq_row00 j
  · exact alternatingSixFiveAmbient_row02_matrixA_sq_row01 j
  · exact alternatingSixFiveAmbient_row02_matrixA_sq_row02 j

/-- The corrected first generator has the required central
square in ambient row `2`. -/
theorem alternatingSixFiveAmbient_row02_matrixA_sq :
    alternatingSixFiveAmbient_row02_matrixA ^ 2 =
      (ζ ^ 80) • (1 : Matrix (Fin 3) (Fin 3) ℂ) := by
  simpa [pow_two, alternatingSixFiveAmbient_row02_matrixA_sqTarget] using
    alternatingSixFiveAmbient_row02_matrixA_sq_mul


end InductiveMcKay
end McKayConjecture
