/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.InductiveMcKay.AlternatingSixFiveAmbientMatrixDataDegreeFiveTenFifteen

/-!
# Reduced matrix data for the two long row-25 class words

This file is generated by `scripts/a6_row25_representative_traces.py`.
Lean separately checks every multiplication producing these matrices.
-/

noncomputable section

namespace McKayConjecture
namespace InductiveMcKay

local notation "ζ" => alternatingSixComplexCyclotomicRoot

/-- Reduced row-25 matrix for `ab`. -/
def alternatingSixAmbientRow25LongMatrixAB :
    Matrix (Fin 10) (Fin 10) ℂ :=
  ![
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (-1, 5),
            ((-1 / 3), 15),
            (1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((2 / 3), 5),
            ((1 / 3), 15),
            ((-2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 15),
            ((-1 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((1 / 6), 5),
            ((-1 / 2), 15),
            ((-1 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((-1 / 6), 5),
            ((1 / 2), 15),
            ((1 / 6), 25),
            ((-1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-5 / 6), 0),
            ((1 / 6), 5),
            ((1 / 2), 15),
            ((-1 / 6), 25),
            ((-5 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((-1 / 2), 5),
            ((-1 / 6), 15),
            ((1 / 2), 25),
            ((-1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-2 / 3), 15),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 0)]],
      ![alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue [(1, 0), (1, 5), (1, 15), (-1, 25)],
        alternatingSixCyclotomicValue [(1, 0), (1, 15)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            (1, 5),
            (1, 15),
            (-1, 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-2 / 3), 5),
            ((2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (-1, 0),
            ((-1 / 3), 5),
            ((-1 / 3), 15),
            ((1 / 3), 25),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (-1, 0),
            ((1 / 3), 5),
            ((-2 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (1, 5),
            ((2 / 3), 15),
            (-1, 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            (1, 5),
            ((1 / 3), 15),
            (-1, 25),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 0),
            ((-2 / 3), 15),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((5 / 3), 15),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-1 / 3), 5),
            (-1, 15),
            ((1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-1 / 3), 5),
            (-1, 15),
            ((1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25)]],
      ![alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-1 / 3), 5),
            ((1 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 5),
            ((-2 / 3), 15),
            ((-1 / 3), 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 5),
            ((-1 / 3), 15),
            ((-2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            (-1, 5),
            ((-2 / 3), 15),
            (1, 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (-1, 5),
            ((-1 / 3), 15),
            (1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (-1, 5),
            ((-1 / 3), 15),
            (1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-2 / 3), 15),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((4 / 3), 5),
            (-1, 15),
            ((-4 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 30)]],
      ![alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((-1 / 3), 5),
            ((-2 / 3), 15),
            ((1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-1 / 3), 5),
            (1, 15),
            ((1 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((1 / 3), 15),
            ((-1 / 3), 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 5),
            ((2 / 3), 15),
            ((4 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 5),
            ((1 / 3), 15),
            ((-4 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((2 / 3), 15),
            ((-1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-2 / 3), 5),
            ((2 / 3), 15),
            ((2 / 3), 25)
          ],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25), (1, 30)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 30)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 30)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []]
    ]

/-- Reduced row-25 matrix for `ab²`. -/
def alternatingSixAmbientRow25LongMatrixABB :
    Matrix (Fin 10) (Fin 10) ℂ :=
  ![
      ![alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-1 / 3), 5),
            ((1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((4 / 3), 15),
            ((-1 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((1 / 2), 5),
            ((-1 / 6), 15),
            ((-1 / 2), 25),
            ((-7 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((1 / 2), 5),
            ((1 / 6), 15),
            ((-1 / 2), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((2 / 3), 15),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((1 / 2), 5),
            ((-1 / 6), 15),
            ((-1 / 2), 25),
            ((-7 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((-1 / 6), 5),
            ((-1 / 2), 15),
            ((1 / 6), 25),
            ((-1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-2 / 3), 5),
            (1, 15),
            ((2 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 15)]],
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (-1, 5),
            ((-1 / 3), 15),
            (1, 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((2 / 3), 5),
            ((-2 / 3), 15),
            ((-2 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 15),
            ((-1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-5 / 6), 0),
            ((-5 / 6), 5),
            ((-1 / 2), 15),
            ((5 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((-1 / 6), 5),
            ((1 / 2), 15),
            ((1 / 6), 25),
            ((-1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((1 / 3), 5),
            (-1, 15),
            ((-1 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((-5 / 6), 5),
            ((1 / 2), 15),
            ((5 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((1 / 2), 5),
            ((-1 / 6), 15),
            ((-1 / 2), 25),
            ((-1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            (1, 5),
            ((-2 / 3), 15),
            (-1, 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 15)]],
      ![alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((-1 / 3), 5),
            ((-2 / 3), 15),
            ((1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-1 / 3), 5),
            (1, 15),
            ((1 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((1 / 3), 15),
            ((-1 / 3), 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 5),
            ((2 / 3), 15),
            ((4 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 5),
            ((1 / 3), 15),
            ((-4 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((2 / 3), 15),
            ((-1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-2 / 3), 5),
            ((2 / 3), 15),
            ((2 / 3), 25)
          ],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25)]],
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((1 / 3), 5),
            (1, 15),
            ((-1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (-1, 0),
            ((-4 / 3), 5),
            ((-4 / 3), 15),
            ((4 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (-1, 0),
            ((-2 / 3), 5),
            ((-2 / 3), 15),
            ((2 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((2 / 3), 15),
            ((5 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-2 / 3), 15),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-5 / 3), 15),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((2 / 3), 15),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-1 / 3), 5),
            ((1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 0),
            ((-1 / 3), 5),
            (-1, 15),
            ((1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 0)]],
      ![alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(1, 0)],
        alternatingSixCyclotomicValue [(-1, 5), (1, 15), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 5), (1, 15), (1, 25)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((2 / 3), 5),
            ((1 / 3), 15),
            ((-2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-4 / 3), 5),
            (1, 15),
            ((4 / 3), 25),
            ((5 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((-5 / 3), 5),
            ((5 / 3), 25),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((1 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((2 / 3), 5),
            ((-1 / 3), 15),
            ((-2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 5),
            ((2 / 3), 15),
            ((4 / 3), 25),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((4 / 3), 5),
            ((1 / 3), 15),
            ((-4 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-2 / 3), 5),
            ((-1 / 3), 15),
            ((2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 0),
            ((-5 / 3), 5),
            ((-1 / 3), 15),
            ((5 / 3), 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue [(1, 30)]],
      ![alternatingSixCyclotomicValue [(-1, 30)],
        alternatingSixCyclotomicValue [(-1, 5), (1, 15), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [(1, 30)],
        alternatingSixCyclotomicValue [(1, 0), (1, 5), (-1, 25)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 5), (1, 15), (-1, 25)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((1 / 3), 15),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 0),
            ((-2 / 3), 5),
            ((-1 / 3), 15),
            ((2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((-1 / 3), 5),
            ((-2 / 3), 15),
            ((1 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-2 / 3), 5),
            (1, 15),
            ((2 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-1 / 3), 5),
            (1, 15),
            ((1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-1 / 3), 5),
            (1, 15),
            ((1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-2 / 3), 5),
            ((2 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((-1 / 3), 15),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            (-1, 5),
            ((-4 / 3), 15),
            (1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 0)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue []]
    ]

/-- Reduced row-25 matrix for `ab³`. -/
def alternatingSixAmbientRow25LongMatrixABBB :
    Matrix (Fin 10) (Fin 10) ℂ :=
  ![
      ![alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-2 / 3), 5),
            ((-1 / 3), 15),
            ((2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            ((4 / 3), 5),
            (1, 15),
            ((-4 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((2 / 3), 5),
            (1, 15),
            ((-2 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 6), 5),
            ((-5 / 6), 15),
            ((-1 / 6), 25),
            ((-7 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 6), 5),
            ((-1 / 6), 15),
            ((1 / 6), 25),
            ((-5 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((4 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 6), 5),
            ((-5 / 6), 15),
            ((-1 / 6), 25),
            ((-7 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((1 / 6), 5),
            ((-1 / 6), 15),
            ((-1 / 6), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            ((-1 / 3), 5),
            ((4 / 3), 15),
            ((1 / 3), 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue [(1, 0)]],
      ![alternatingSixCyclotomicValue [(-1, 5), (1, 25)],
        alternatingSixCyclotomicValue [(1, 5), (-1, 15), (-1, 25), (-1, 30)],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25), (-1, 30)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            (1, 5),
            (-1, 15),
            (-1, 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 5),
            ((1 / 3), 15),
            ((2 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (1, 5),
            ((2 / 3), 15),
            (-1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            (1, 5),
            ((1 / 3), 15),
            (-1, 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((4 / 3), 15),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (1, 5),
            ((-1 / 3), 15),
            (-1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-1 / 3), 5),
            ((1 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-4 / 3), 0),
            ((-4 / 3), 5),
            ((4 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 15)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 30)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            (-1, 0),
            ((-1 / 3), 5),
            ((-1 / 3), 15),
            ((1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            (1, 5),
            ((2 / 3), 15),
            (-1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((1 / 3), 15),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((1 / 6), 5),
            ((-7 / 6), 15),
            ((-1 / 6), 25),
            ((-3 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((-1 / 6), 5),
            ((1 / 6), 15),
            ((1 / 6), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((1 / 3), 5),
            ((2 / 3), 15),
            ((-1 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((1 / 6), 5),
            ((-7 / 6), 15),
            ((-1 / 6), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 6), 5),
            ((-1 / 6), 15),
            ((1 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((1 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 0)]],
      ![alternatingSixCyclotomicValue [(-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 15), (-1, 30)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 15), (-1, 30)],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [(1, 15)],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25)],
        alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue
          [
            (-1, 0),
            (1, 5),
            (-1, 15),
            (-1, 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((2 / 3), 5),
            ((-2 / 3), 15),
            ((-2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-1 / 3), 5),
            (1, 15),
            ((1 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-2 / 3), 5),
            (1, 15),
            ((2 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 5),
            ((1 / 3), 15),
            ((-1 / 3), 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 5),
            ((-1 / 3), 15),
            ((-2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((-2 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 15),
            ((-1 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-2 / 3), 5),
            ((5 / 3), 15),
            ((2 / 3), 25)
          ],
        alternatingSixCyclotomicValue [(1, 15)]],
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (1, 5),
            ((-1 / 3), 15),
            (-1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-4 / 3), 5),
            ((4 / 3), 15),
            ((4 / 3), 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-2 / 3), 5),
            ((2 / 3), 15),
            ((2 / 3), 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((5 / 3), 0),
            ((2 / 3), 5),
            ((-2 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            ((-2 / 3), 5),
            ((2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            ((-5 / 3), 5),
            ((5 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((2 / 3), 5),
            ((-2 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 15),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            (-1, 5),
            ((1 / 3), 15),
            (1, 25),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 30)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []]
    ]

/-- Reduced product `(ab)(ab²)`. -/
def alternatingSixAmbientRow25LongPrefix77 :
    Matrix (Fin 10) (Fin 10) ℂ :=
  ![
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-1 / 3), 5),
            ((1 / 3), 15),
            ((1 / 3), 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((2 / 3), 5),
            (-1, 15),
            ((-2 / 3), 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-3 / 2), 0),
            ((-7 / 6), 5),
            ((-1 / 6), 15),
            ((7 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 6), 5),
            ((1 / 6), 15),
            ((-1 / 6), 25),
            ((-1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 5),
            ((-1 / 3), 15),
            ((-2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-7 / 6), 5),
            ((-1 / 6), 15),
            ((7 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((-1 / 6), 5),
            ((1 / 6), 15),
            ((1 / 6), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 15),
            ((-1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue [(-1, 30)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25), (-1, 30)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 15), (-1, 30)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 15), (-1, 30)],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [(1, 15)],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25)],
        alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue
          [
            (-1, 0),
            (1, 5),
            (-1, 15),
            (-1, 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            (-1, 0),
            ((-1 / 3), 5),
            ((-1 / 3), 15),
            ((1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            (1, 5),
            ((2 / 3), 15),
            (-1, 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            (1, 5),
            ((1 / 3), 15),
            (-1, 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((1 / 6), 5),
            ((-7 / 6), 15),
            ((-1 / 6), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((-1 / 6), 5),
            ((-5 / 6), 15),
            ((1 / 6), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 15),
            ((-1 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((1 / 6), 5),
            ((-7 / 6), 15),
            ((-1 / 6), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 6), 5),
            ((-1 / 6), 15),
            ((1 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((4 / 3), 5),
            ((1 / 3), 15),
            ((-4 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            (1, 5),
            ((-4 / 3), 15),
            (-1, 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            (1, 5),
            ((-2 / 3), 15),
            (-1, 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-7 / 6), 0),
            ((-5 / 6), 5),
            ((-1 / 6), 15),
            ((5 / 6), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-5 / 6), 0),
            ((-1 / 6), 5),
            ((1 / 6), 15),
            ((1 / 6), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((4 / 3), 5),
            ((-1 / 3), 15),
            ((-4 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-7 / 6), 0),
            ((-5 / 6), 5),
            ((-1 / 6), 15),
            ((5 / 6), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 6), 5),
            ((-1 / 6), 15),
            ((1 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((4 / 3), 5),
            ((1 / 3), 15),
            ((-4 / 3), 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 30)]],
      ![alternatingSixCyclotomicValue [(1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((1 / 3), 5),
            (-1, 15),
            ((-1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((2 / 3), 5),
            ((2 / 3), 15),
            ((-2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((1 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((1 / 2), 5),
            ((-5 / 6), 15),
            ((-1 / 2), 25),
            ((-5 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((-1 / 2), 5),
            ((-1 / 6), 15),
            ((1 / 2), 25),
            ((-1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            (1, 5),
            ((1 / 3), 15),
            (-1, 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 6), 0),
            ((-1 / 2), 5),
            ((-5 / 6), 15),
            ((1 / 2), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 6), 0),
            ((1 / 6), 5),
            ((1 / 2), 15),
            ((-1 / 6), 25),
            ((1 / 6), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((2 / 3), 5),
            (1, 15),
            ((-2 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25)]],
      ![alternatingSixCyclotomicValue
          [
            ((1 / 3), 5),
            ((-2 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((5 / 3), 0),
            (1, 5),
            ((4 / 3), 15),
            (-1, 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            ((5 / 3), 15),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 15),
            ((-1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((-1 / 3), 5),
            ((-2 / 3), 15),
            ((1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((4 / 3), 0),
            ((2 / 3), 5),
            ((4 / 3), 15),
            ((-2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((-4 / 3), 15),
            ((-1 / 3), 25),
            (-1, 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((-1 / 3), 5),
            ((5 / 3), 15),
            ((1 / 3), 25),
            ((4 / 3), 30)
          ],
        alternatingSixCyclotomicValue [(1, 0)]],
      ![alternatingSixCyclotomicValue [(-1, 30)],
        alternatingSixCyclotomicValue [(-1, 5), (1, 15), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [(1, 30)],
        alternatingSixCyclotomicValue [(1, 0), (1, 5), (-1, 25)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 5), (1, 15), (-1, 25)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue []]
    ]

/-- Reduced product `(ab)(ab³)`. -/
def alternatingSixAmbientRow25LongPrefix79 :
    Matrix (Fin 10) (Fin 10) ℂ :=
  ![
      ![alternatingSixCyclotomicValue [(1, 15)],
        alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 5), (-1, 15), (1, 25)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 15), (-1, 30)],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [(1, 5), (-1, 15), (-1, 25), (-1, 30)],
        alternatingSixCyclotomicValue [(1, 0), (1, 5), (-1, 25), (-1, 30)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(1, 5), (-1, 15), (-1, 25)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(1, 0), (1, 5), (-1, 25), (-1, 30)],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 0)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(1, 0)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 5), (-1, 15), (1, 25)],
        alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [(1, 15), (1, 30)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 5), (1, 15), (1, 25)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 15)],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(1, 5), (-1, 25)],
        alternatingSixCyclotomicValue [(1, 15)],
        alternatingSixCyclotomicValue [(1, 0)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((-1 / 2), 5),
            ((1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(1, 15), (-1, 30)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(1, 15)],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 30)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(-1, 15)],
        alternatingSixCyclotomicValue [(1, 0), (1, 5), (1, 15), (-1, 25)],
        alternatingSixCyclotomicValue [(1, 0), (1, 15)],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25)],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((-1 / 2), 5),
            ((-1 / 2), 15),
            ((1 / 2), 25),
            ((-1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 2), 0),
            ((1 / 2), 5),
            ((-1 / 2), 15),
            ((-1 / 2), 25),
            ((1 / 2), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            (1, 5),
            (1, 15),
            (-1, 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue [(1, 0), (1, 15)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [(-1, 0), (-1, 5), (1, 25), (1, 30)],
        alternatingSixCyclotomicValue [(1, 30)],
        alternatingSixCyclotomicValue [(1, 5), (-1, 25)],
        alternatingSixCyclotomicValue [(1, 30)],
        alternatingSixCyclotomicValue [(1, 15)],
        alternatingSixCyclotomicValue [(-1, 5), (1, 25)],
        alternatingSixCyclotomicValue
          [
            (-1, 0),
            (-1, 5),
            (-1, 15),
            (1, 25),
            (1, 30)
          ],
        alternatingSixCyclotomicValue []],
      ![alternatingSixCyclotomicValue
          [
            ((-2 / 3), 0),
            ((2 / 3), 5),
            ((-2 / 3), 15),
            ((-2 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 0),
            ((-1 / 3), 5),
            (1, 15),
            ((1 / 3), 25),
            ((2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 0),
            ((-2 / 3), 5),
            (1, 15),
            ((2 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((1 / 3), 5),
            ((1 / 3), 15),
            ((-1 / 3), 25),
            ((-4 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((2 / 3), 5),
            ((-1 / 3), 15),
            ((-2 / 3), 25),
            ((-2 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 5),
            ((2 / 3), 15),
            ((1 / 3), 25),
            ((1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            (1, 0),
            ((1 / 3), 5),
            ((-2 / 3), 15),
            ((-1 / 3), 25),
            ((-1 / 3), 30)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((1 / 3), 5),
            ((-1 / 3), 15),
            ((-1 / 3), 25)
          ],
        alternatingSixCyclotomicValue
          [
            ((-1 / 3), 0),
            ((-2 / 3), 5),
            ((5 / 3), 15),
            ((2 / 3), 25)
          ],
        alternatingSixCyclotomicValue [(1, 15)]]
    ]

end InductiveMcKay
end McKayConjecture
