/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.LinearCombination
import McKayConjecture.InductiveMcKay.AlternatingSixFiveAmbientMatrixDataDegreeFourSix

/-!
# The fourth power of the second generator in ambient row `6`

This file is generated by `scripts/a6_character_matrices_to_lean.py`.
Each multiplication is split by matrix row or entry and checked with an
explicit quotient by `Φ₁₂₀`, keeping every command below the default
heartbeat limit.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace McKayConjecture
namespace InductiveMcKay

local notation "ζ" => alternatingSixComplexCyclotomicRoot

/-- Exact target matrix for the `matrixB_sq` multiplication step. -/
private def alternatingSixFiveAmbient_row06_matrixB_sqValue :
    Matrix (Fin 4) (Fin 4) ℂ :=
  ![
      ![alternatingSixCyclotomicValue [(-1, 0), (1, 20)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 0), (-1, 20)],
        alternatingSixCyclotomicValue [(-1, 0)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 20)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 0)]],
      ![alternatingSixCyclotomicValue [(-1, 0)],
        alternatingSixCyclotomicValue [(1, 0), (-1, 20)],
        alternatingSixCyclotomicValue [(1, 0), (-1, 20)],
        alternatingSixCyclotomicValue [(-2, 0), (1, 20)]],
      ![alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(-1, 20)],
        alternatingSixCyclotomicValue [],
        alternatingSixCyclotomicValue [(1, 20)]]
    ]

/-- Exact target matrix for the `matrixB_fourth` multiplication step. -/
private def alternatingSixFiveAmbient_row06_matrixB_fourthTarget :
    Matrix (Fin 4) (Fin 4) ℂ :=
  (ζ ^ 60) •
    (1 : Matrix (Fin 4) (Fin 4) ℂ)

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_sq_row00
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB * alternatingSixFiveAmbient_row06_matrixB)
          (0 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_sqValue (0 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_sq_row01
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB * alternatingSixFiveAmbient_row06_matrixB)
          (1 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_sqValue (1 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-(1 : ℂ) + ζ ^ 4 - ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-(1 : ℂ) + ζ ^ 4 - ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_sq_row02
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB * alternatingSixFiveAmbient_row06_matrixB)
          (2 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_sqValue (2 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-(1 : ℂ) + ζ ^ 4 - ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-(1 : ℂ) + ζ ^ 4 - ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((2 : ℂ) - (2 : ℂ) * ζ ^ 4 + (2 : ℂ) * ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((2 : ℂ) - (2 : ℂ) * ζ ^ 4 + (2 : ℂ) * ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_sq_row03
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB * alternatingSixFiveAmbient_row06_matrixB)
          (3 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_sqValue (3 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring

private theorem alternatingSixFiveAmbient_row06_matrixB_sq_mul :
    alternatingSixFiveAmbient_row06_matrixB * alternatingSixFiveAmbient_row06_matrixB =
      alternatingSixFiveAmbient_row06_matrixB_sqValue := by
  ext i j
  fin_cases i
  · exact alternatingSixFiveAmbient_row06_matrixB_sq_row00 j
  · exact alternatingSixFiveAmbient_row06_matrixB_sq_row01 j
  · exact alternatingSixFiveAmbient_row06_matrixB_sq_row02 j
  · exact alternatingSixFiveAmbient_row06_matrixB_sq_row03 j

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_fourth_row00
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB_sqValue * alternatingSixFiveAmbient_row06_matrixB_sqValue)
          (0 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_fourthTarget (0 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-ζ ^ 20 + ζ ^ 24 - ζ ^ 28) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-ζ ^ 20 + ζ ^ 24 - ζ ^ 28)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-(1 : ℂ) + ζ ^ 4 - ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-(1 : ℂ) + ζ ^ 4 - ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_fourth_row01
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB_sqValue * alternatingSixFiveAmbient_row06_matrixB_sqValue)
          (1 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_fourthTarget (1 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-ζ ^ 20 + ζ ^ 24 - ζ ^ 28) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-ζ ^ 20 + ζ ^ 24 - ζ ^ 28)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_fourth_row02
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB_sqValue * alternatingSixFiveAmbient_row06_matrixB_sqValue)
          (2 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_fourthTarget (2 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-ζ ^ 20 + ζ ^ 24 - ζ ^ 28) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-ζ ^ 20 + ζ ^ 24 - ζ ^ 28)) *
          alternatingSixComplexCyclotomicRoot_relation
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row06_matrixB_fourth_row03
    (j : Fin 4) :
    (alternatingSixFiveAmbient_row06_matrixB_sqValue * alternatingSixFiveAmbient_row06_matrixB_sqValue)
          (3 : Fin 4) j =
      alternatingSixFiveAmbient_row06_matrixB_fourthTarget (3 : Fin 4) j := by
  rw [Matrix.mul_apply]
  fin_cases j
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
    ring
  · simp [alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_sqValue, alternatingSixFiveAmbient_row06_matrixB_fourthTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
    first
    | linear_combination
        (-ζ ^ 20 + ζ ^ 24 - ζ ^ 28) *
          alternatingSixComplexCyclotomicRoot_relation
    | linear_combination
        (-(-ζ ^ 20 + ζ ^ 24 - ζ ^ 28)) *
          alternatingSixComplexCyclotomicRoot_relation

private theorem alternatingSixFiveAmbient_row06_matrixB_fourth_mul :
    alternatingSixFiveAmbient_row06_matrixB_sqValue * alternatingSixFiveAmbient_row06_matrixB_sqValue =
      alternatingSixFiveAmbient_row06_matrixB_fourthTarget := by
  ext i j
  fin_cases i
  · exact alternatingSixFiveAmbient_row06_matrixB_fourth_row00 j
  · exact alternatingSixFiveAmbient_row06_matrixB_fourth_row01 j
  · exact alternatingSixFiveAmbient_row06_matrixB_fourth_row02 j
  · exact alternatingSixFiveAmbient_row06_matrixB_fourth_row03 j

/-- The corrected second generator has the required central fourth
power in ambient row `6`. -/
theorem alternatingSixFiveAmbient_row06_matrixB_fourth :
    alternatingSixFiveAmbient_row06_matrixB ^ 4 =
      (ζ ^ 60) • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
  have hB2 :
      alternatingSixFiveAmbient_row06_matrixB ^ 2 = alternatingSixFiveAmbient_row06_matrixB_sqValue := by
    simpa [pow_two] using alternatingSixFiveAmbient_row06_matrixB_sq_mul
  calc
    alternatingSixFiveAmbient_row06_matrixB ^ 4 = (alternatingSixFiveAmbient_row06_matrixB ^ 2) ^ 2 := by
      simpa using
        (pow_mul alternatingSixFiveAmbient_row06_matrixB 2 2)
    _ = alternatingSixFiveAmbient_row06_matrixB_sqValue ^ 2 := by rw [hB2]
    _ = alternatingSixFiveAmbient_row06_matrixB_sqValue * alternatingSixFiveAmbient_row06_matrixB_sqValue := by rw [pow_two]
    _ = alternatingSixFiveAmbient_row06_matrixB_fourthTarget :=
      alternatingSixFiveAmbient_row06_matrixB_fourth_mul
    _ = (ζ ^ 60) • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
      rfl


end InductiveMcKay
end McKayConjecture
