/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.LinearCombination
import McKayConjecture.InductiveMcKay.AlternatingSixFiveAmbientMatrixDataDegreeFiveTenFifteen

/-!
# The square of the first generator in ambient row `23`

This file is generated by `scripts/a6_character_matrices_to_lean.py`.
Each multiplication is split by matrix row or entry and checked with an
explicit quotient by `Φ₁₂₀`, keeping every command below the default
heartbeat limit.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace McKayConjecture
namespace InductiveMcKay

local notation "ζ" => alternatingSixComplexCyclotomicRoot

/-- Exact target matrix for the `matrixA_sq` multiplication step. -/
private def alternatingSixFiveAmbient_row23_matrixA_sqTarget :
    Matrix (Fin 10) (Fin 10) ℂ :=
  (ζ ^ 0) •
    (1 : Matrix (Fin 10) (Fin 10) ℂ)

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry00_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (0 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (0 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry01_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (1 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (1 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry02_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (2 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (2 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry03_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (3 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (3 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry04_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (4 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (4 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry05_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (5 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (5 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry06_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (6 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (6 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry07_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (7 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (7 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry08_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (8 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (8 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_00 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (0 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (0 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_01 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (1 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (1 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_02 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (2 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (2 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_03 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (3 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (3 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_04 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (4 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (4 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_05 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (5 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (5 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_06 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (6 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (6 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_07 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (7 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (7 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_08 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (8 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (8 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row23_matrixA_sq_entry09_09 :
    (alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA)
          (9 : Fin 10) (9 : Fin 10) =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget (9 : Fin 10) (9 : Fin 10) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA, alternatingSixFiveAmbient_row23_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

private theorem alternatingSixFiveAmbient_row23_matrixA_sq_mul :
    alternatingSixFiveAmbient_row23_matrixA * alternatingSixFiveAmbient_row23_matrixA =
      alternatingSixFiveAmbient_row23_matrixA_sqTarget := by
  ext i j
  fin_cases i <;> fin_cases j
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry00_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry01_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry02_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry03_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry04_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry05_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry06_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry07_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry08_09
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_00
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_01
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_02
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_03
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_04
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_05
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_06
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_07
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_08
  · exact alternatingSixFiveAmbient_row23_matrixA_sq_entry09_09

/-- The corrected first generator has the required central
square in ambient row `23`. -/
theorem alternatingSixFiveAmbient_row23_matrixA_sq :
    alternatingSixFiveAmbient_row23_matrixA ^ 2 =
      (ζ ^ 0) • (1 : Matrix (Fin 10) (Fin 10) ℂ) := by
  simpa [pow_two, alternatingSixFiveAmbient_row23_matrixA_sqTarget] using
    alternatingSixFiveAmbient_row23_matrixA_sq_mul


end InductiveMcKay
end McKayConjecture
