/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.LinearCombination
import McKayConjecture.InductiveMcKay.AlternatingSixFiveAmbientMatrixDataDegreeEightNine

/-!
# The square of the first generator in ambient row `21`

This file is generated by `scripts/a6_character_matrices_to_lean.py`.
Each multiplication is split by matrix row or entry and checked with an
explicit quotient by `Φ₁₂₀`, keeping every command below the default
heartbeat limit.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace McKayConjecture
namespace InductiveMcKay

local notation "ζ" => alternatingSixComplexCyclotomicRoot

/-- Exact target matrix for the `matrixA_sq` multiplication step. -/
private def alternatingSixFiveAmbient_row21_matrixA_sqTarget :
    Matrix (Fin 9) (Fin 9) ℂ :=
  (ζ ^ 80) •
    (1 : Matrix (Fin 9) (Fin 9) ℂ)

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((16 / 9) : ℂ) - ((16 / 9) : ℂ) * ζ ^ 4 + ((16 / 9) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((16 / 9) : ℂ) - ((16 / 9) : ℂ) * ζ ^ 4 + ((16 / 9) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((4 / 3) : ℂ) - ((4 / 3) : ℂ) * ζ ^ 4 + ((4 / 3) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((4 / 3) : ℂ) - ((4 / 3) : ℂ) * ζ ^ 4 + ((4 / 3) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((1 / 3) : ℂ) + ((1 / 3) : ℂ) * ζ ^ 4 - ((1 / 3) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((1 / 3) : ℂ) + ((1 / 3) : ℂ) * ζ ^ 4 - ((1 / 3) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((38 / 9) : ℂ) - ((38 / 9) : ℂ) * ζ ^ 4 + ((38 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((38 / 9) : ℂ) - ((38 / 9) : ℂ) * ζ ^ 4 + ((38 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((20 / 9) : ℂ) - ((20 / 9) : ℂ) * ζ ^ 4 + ((20 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((20 / 9) : ℂ) - ((20 / 9) : ℂ) * ζ ^ 4 + ((20 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry00_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (0 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (0 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((16 / 9) : ℂ) + ((16 / 9) : ℂ) * ζ ^ 4 - ((16 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((16 / 9) : ℂ) + ((16 / 9) : ℂ) * ζ ^ 4 - ((16 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((2 / 9) : ℂ) - ((2 / 9) : ℂ) * ζ ^ 4 + ((2 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((2 / 9) : ℂ) - ((2 / 9) : ℂ) * ζ ^ 4 + ((2 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((16 / 9) : ℂ) - ((16 / 9) : ℂ) * ζ ^ 4 + ((16 / 9) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((16 / 9) : ℂ) - ((16 / 9) : ℂ) * ζ ^ 4 + ((16 / 9) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((4 / 9) : ℂ) + ((4 / 9) : ℂ) * ζ ^ 4 - ((4 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((4 / 9) : ℂ) + ((4 / 9) : ℂ) * ζ ^ 4 - ((4 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((2 / 9) : ℂ) - ((2 / 9) : ℂ) * ζ ^ 4 + ((2 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((2 / 9) : ℂ) - ((2 / 9) : ℂ) * ζ ^ 4 + ((2 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((5 / 9) : ℂ) - ((5 / 9) : ℂ) * ζ ^ 4 + ((5 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((5 / 9) : ℂ) - ((5 / 9) : ℂ) * ζ ^ 4 + ((5 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      ((1 : ℂ) - ζ ^ 4 + ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry01_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (1 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (1 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((14 / 9) : ℂ) + ((14 / 9) : ℂ) * ζ ^ 4 - ((14 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((14 / 9) : ℂ) + ((14 / 9) : ℂ) * ζ ^ 4 - ((14 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      ((1 : ℂ) - ζ ^ 4 + ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry02_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (2 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (2 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((4 / 9) : ℂ) + ((4 / 9) : ℂ) * ζ ^ 4 - ((4 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((4 / 9) : ℂ) + ((4 / 9) : ℂ) * ζ ^ 4 - ((4 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-(1 : ℂ) + ζ ^ 4 - ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-(1 : ℂ) + ζ ^ 4 - ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((7 / 6) : ℂ) + ((7 / 6) : ℂ) * ζ ^ 4 - ((7 / 6) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((7 / 6) : ℂ) + ((7 / 6) : ℂ) * ζ ^ 4 - ((7 / 6) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((2 / 3) : ℂ) - ((2 / 3) : ℂ) * ζ ^ 4 + ((2 / 3) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((2 / 3) : ℂ) - ((2 / 3) : ℂ) * ζ ^ 4 + ((2 / 3) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((1 / 9) : ℂ) + ((1 / 9) : ℂ) * ζ ^ 4 - ((1 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((1 / 9) : ℂ) + ((1 / 9) : ℂ) * ζ ^ 4 - ((1 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((43 / 18) : ℂ) + ((43 / 18) : ℂ) * ζ ^ 4 - ((43 / 18) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((43 / 18) : ℂ) + ((43 / 18) : ℂ) * ζ ^ 4 - ((43 / 18) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((14 / 9) : ℂ) + ((14 / 9) : ℂ) * ζ ^ 4 - ((14 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((14 / 9) : ℂ) + ((14 / 9) : ℂ) * ζ ^ 4 - ((14 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry03_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (3 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (3 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((13 / 9) : ℂ) - ((13 / 9) : ℂ) * ζ ^ 4 + ((13 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((13 / 9) : ℂ) - ((13 / 9) : ℂ) * ζ ^ 4 + ((13 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((10 / 9) : ℂ) + ((10 / 9) : ℂ) * ζ ^ 4 - ((10 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((10 / 9) : ℂ) + ((10 / 9) : ℂ) * ζ ^ 4 - ((10 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((13 / 9) : ℂ) + ((13 / 9) : ℂ) * ζ ^ 4 - ((13 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((13 / 9) : ℂ) + ((13 / 9) : ℂ) * ζ ^ 4 - ((13 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((4 / 9) : ℂ) - ((4 / 9) : ℂ) * ζ ^ 4 + ((4 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((4 / 3) : ℂ) - ((4 / 3) : ℂ) * ζ ^ 4 + ((4 / 3) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((4 / 3) : ℂ) - ((4 / 3) : ℂ) * ζ ^ 4 + ((4 / 3) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((11 / 9) : ℂ) + ((11 / 9) : ℂ) * ζ ^ 4 - ((11 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((11 / 9) : ℂ) + ((11 / 9) : ℂ) * ζ ^ 4 - ((11 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((7 / 9) : ℂ) - ((7 / 9) : ℂ) * ζ ^ 4 + ((7 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((7 / 9) : ℂ) - ((7 / 9) : ℂ) * ζ ^ 4 + ((7 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry04_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (4 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (4 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((10 / 3) : ℂ) - ((10 / 3) : ℂ) * ζ ^ 4 + ((10 / 3) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((10 / 3) : ℂ) - ((10 / 3) : ℂ) * ζ ^ 4 + ((10 / 3) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry05_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (5 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (5 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry06_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (6 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (6 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      ((1 : ℂ) - ζ ^ 4 + ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-((1 : ℂ) - ζ ^ 4 + ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry07_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (7 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (7 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_00 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (0 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (0 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ] <;>
  ring

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_01 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (1 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (1 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((5 / 9) : ℂ) - ((5 / 9) : ℂ) * ζ ^ 4 + ((5 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((5 / 9) : ℂ) - ((5 / 9) : ℂ) * ζ ^ 4 + ((5 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_02 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (2 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (2 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((2 / 9) : ℂ) - ((2 / 9) : ℂ) * ζ ^ 4 + ((2 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((2 / 9) : ℂ) - ((2 / 9) : ℂ) * ζ ^ 4 + ((2 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_03 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (3 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (3 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((2 / 9) : ℂ) + ((2 / 9) : ℂ) * ζ ^ 4 - ((2 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((2 / 9) : ℂ) + ((2 / 9) : ℂ) * ζ ^ 4 - ((2 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_04 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (4 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (4 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_05 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (5 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (5 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (-((8 / 9) : ℂ) + ((8 / 9) : ℂ) * ζ ^ 4 - ((8 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(-((8 / 9) : ℂ) + ((8 / 9) : ℂ) * ζ ^ 4 - ((8 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_06 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (6 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (6 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((1 / 9) : ℂ) - ((1 / 9) : ℂ) * ζ ^ 4 + ((1 / 9) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((1 / 9) : ℂ) - ((1 / 9) : ℂ) * ζ ^ 4 + ((1 / 9) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_07 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (7 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (7 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8)) *
        alternatingSixComplexCyclotomicRoot_relation

set_option linter.flexible false in
private theorem alternatingSixFiveAmbient_row21_matrixA_sq_entry08_08 :
    (alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA)
          (8 : Fin 9) (8 : Fin 9) =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget (8 : Fin 9) (8 : Fin 9) := by
  rw [Matrix.mul_apply]
  simp [alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA, alternatingSixFiveAmbient_row21_matrixA_sqTarget, alternatingSixCyclotomicValue, Fin.sum_univ_succ]
  first
  | linear_combination
      (((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48) *
        alternatingSixComplexCyclotomicRoot_relation
  | linear_combination
      (-(((1 / 3) : ℂ) - ((1 / 3) : ℂ) * ζ ^ 4 + ((1 / 3) : ℂ) * ζ ^ 8 - ζ ^ 20 + ζ ^ 24 - ζ ^ 28 - ζ ^ 40 + ζ ^ 44 - ζ ^ 48)) *
        alternatingSixComplexCyclotomicRoot_relation

private theorem alternatingSixFiveAmbient_row21_matrixA_sq_mul :
    alternatingSixFiveAmbient_row21_matrixA * alternatingSixFiveAmbient_row21_matrixA =
      alternatingSixFiveAmbient_row21_matrixA_sqTarget := by
  ext i j
  fin_cases i <;> fin_cases j
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry00_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry01_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry02_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry03_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry04_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry05_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry06_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry07_08
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_00
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_01
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_02
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_03
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_04
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_05
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_06
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_07
  · exact alternatingSixFiveAmbient_row21_matrixA_sq_entry08_08

/-- The corrected first generator has the required central
square in ambient row `21`. -/
theorem alternatingSixFiveAmbient_row21_matrixA_sq :
    alternatingSixFiveAmbient_row21_matrixA ^ 2 =
      (ζ ^ 80) • (1 : Matrix (Fin 9) (Fin 9) ℂ) := by
  simpa [pow_two, alternatingSixFiveAmbient_row21_matrixA_sqTarget] using
    alternatingSixFiveAmbient_row21_matrixA_sq_mul


end InductiveMcKay
end McKayConjecture
