/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.CharacterTriple.CentralProjectiveScalarMismatchConjugation
import McKayConjecture.InductiveMcKay.CentralTripleProjectiveScalarCorrectionExtension

/-!
# Scalar correction from conjugation invariance

Literal factor agreement makes the scalar mismatch invariant under the whole
right ambient group.  Hence it automatically kills the relative commutator
of the comparison centralizer with that ambient group.  Normalized agreement
on the matched normal-central subgroup kills that subgroup as well.

The sharp ambient-extension condition therefore follows as soon as the
intersection with `U.normalSubgroup ⊔ commutator B` is generated by these two
automatically killed pieces.  This file records that precise residual
group-theoretic condition and the resulting scalar-correction constructor.
-/

noncomputable section

open scoped commutatorElement

namespace McKayConjecture
namespace InductiveMcKay

open CharacterTriple

variable {A B : Type}
variable [Group A] [Finite A] [Group B] [Finite B]
variable {T : CharacterTriple A} {U : CharacterTriple B}
variable {e : B →* A}

/-- The relative commutator `[K,B]`, regarded as a subgroup of the
projective comparison centralizer `K`. -/
abbrev projectiveComparisonAmbientCommutatorSubgroup
    (T : CharacterTriple A) (e : B →* A) :
    Subgroup (projectiveComparisonCentralizer T e) :=
  (⁅projectiveComparisonCentralizer T e, (⊤ : Subgroup B)⁆).subgroupOf
    (projectiveComparisonCentralizer T e)

/-- The exact group-theoretic generation condition left after conjugation
invariance and normalized normal-central values have been used.

It says
`K ∩ (U [B,B]) ≤ (K ∩ U) [K,B]`.  The reverse containment is automatic,
so this is equivalently equality of the two subgroups. -/
def ScalarCorrectionKernelGenerationCondition
    (T : CharacterTriple A) (U : CharacterTriple B)
    (e : B →* A) : Prop :=
  ((U.normalSubgroup ⊔ _root_.commutator B).comap
      (projectiveComparisonCentralizer T e).subtype) ≤
    projectiveComparisonNormalCentralSubgroup T U e ⊔
      projectiveComparisonAmbientCommutatorSubgroup T e

/-- The normal-central and relative-commutator pieces always lie in the
sharp scalar-correction kernel subgroup. -/
theorem normalCentral_sup_ambientCommutator_le_correctionKernel :
    projectiveComparisonNormalCentralSubgroup T U e ⊔
        projectiveComparisonAmbientCommutatorSubgroup T e ≤
      (U.normalSubgroup ⊔ _root_.commutator B).comap
        (projectiveComparisonCentralizer T e).subtype := by
  apply sup_le
  · intro k hk
    exact Subgroup.mem_sup_left hk
  · intro k hk
    apply Subgroup.mem_sup_right
    rw [_root_.commutator_def]
    exact
      Subgroup.commutator_mono
        (show projectiveComparisonCentralizer T e ≤
          (⊤ : Subgroup B) from le_top)
        le_rfl hk

/-- The residual generation condition is equivalently equality of the sharp
kernel subgroup with the subgroup generated by the two canonical pieces. -/
theorem scalarCorrectionKernelGenerationCondition_iff :
    ScalarCorrectionKernelGenerationCondition T U e ↔
      (U.normalSubgroup ⊔ _root_.commutator B).comap
          (projectiveComparisonCentralizer T e).subtype =
        projectiveComparisonNormalCentralSubgroup T U e ⊔
          projectiveComparisonAmbientCommutatorSubgroup T e := by
  constructor
  · intro h
    exact
      le_antisymm h
        normalCentral_sup_ambientCommutator_le_correctionKernel
  · intro h
    exact h.le

end InductiveMcKay

namespace CharacterTriple
namespace AssociatedProjectiveRepresentation

open InductiveMcKay

variable {A B : Type}
variable [Group A] [Finite A] [Group B] [Finite B]
variable {T : CharacterTriple A} {U : CharacterTriple B}
variable {e : B →* A}

variable {V W : Type}
variable [AddCommGroup V] [Module ℂ V]
  [Module.Finite ℂ V] [Nontrivial V]
variable [AddCommGroup W] [Module ℂ W]
  [Module.Finite ℂ W] [Nontrivial W]
variable {P : ProjectiveRepresentation ℂ A V}
variable {Q : ProjectiveRepresentation ℂ B W}

/-- Conjugation invariance makes the mismatch trivial on the relative
commutator subgroup `[K,B]`. -/
theorem projectiveComparisonAmbientCommutatorSubgroup_le_scalarMismatchKernel
    (R : AssociatedProjectiveRepresentation T V P)
    (S : AssociatedProjectiveRepresentation U W Q)
    (g : CentralRestrictionGroupData T U e)
    (factorAgreement :
      ∀ b c : B,
        P.factor (e b) (e c) =
          Q.factor b c) :
    projectiveComparisonAmbientCommutatorSubgroup T e ≤
      (R.comparisonCentralScalarMismatch
        S
        g.projectiveComparisonCentralizer_le_rightCentralizer
        factorAgreement).ker := by
  let K := projectiveComparisonCentralizer T e
  let mismatch :=
    R.comparisonCentralScalarMismatch
      S
      g.projectiveComparisonCentralizer_le_rightCentralizer
      factorAgreement
  have hmap :
      ⁅K, (⊤ : Subgroup B)⁆ ≤
        mismatch.ker.map K.subtype :=
    R.projectiveComparisonCentralizer_commutator_le_scalarMismatchKernel
      S
      g.projectiveComparisonCentralizer_le_rightCentralizer
      factorAgreement
  intro k hk
  have hkMap :
      (k : B) ∈ mismatch.ker.map K.subtype :=
    hmap hk
  obtain ⟨k', hk'Ker, hk'Eq⟩ := hkMap
  have hk' : k' = k :=
    Subtype.ext hk'Eq
  rw [hk'] at hk'Ker
  exact hk'Ker

/-- Normalized values and conjugation invariance kill the two canonical
pieces of the scalar-correction kernel. -/
theorem normalCentral_sup_ambientCommutator_le_scalarMismatchKernel
    (R : AssociatedProjectiveRepresentation T V P)
    (S : AssociatedProjectiveRepresentation U W Q)
    (g : CentralRestrictionGroupData T U e)
    (factorAgreement :
      ∀ b c : B,
        P.factor (e b) (e c) =
          Q.factor b c)
    (hvalues : g.NormalizedNormalCentralValuesAgree) :
    projectiveComparisonNormalCentralSubgroup T U e ⊔
        projectiveComparisonAmbientCommutatorSubgroup T e ≤
      (R.comparisonCentralScalarMismatch
        S
        g.projectiveComparisonCentralizer_le_rightCentralizer
        factorAgreement).ker := by
  apply sup_le
  · intro k hk
    apply MonoidHom.mem_ker.mpr
    exact
      R.comparisonCentralScalarMismatch_apply_eq_one_of_normalizedNormalCentralValuesAgree
        S g factorAgreement hvalues ⟨k, hk⟩
  · exact
      R.projectiveComparisonAmbientCommutatorSubgroup_le_scalarMismatchKernel
        S g factorAgreement

/-- The residual generation condition, normalized values, and conjugation
invariance imply the sharp kernel condition for scalar correction. -/
theorem comparisonCentralScalarCorrectionKernelCondition_of_generation
    (R : AssociatedProjectiveRepresentation T V P)
    (S : AssociatedProjectiveRepresentation U W Q)
    (g : CentralRestrictionGroupData T U e)
    (factorAgreement :
      ∀ b c : B,
        P.factor (e b) (e c) =
          Q.factor b c)
    (hvalues : g.NormalizedNormalCentralValuesAgree)
    (hgeneration :
      ScalarCorrectionKernelGenerationCondition T U e) :
    R.ComparisonCentralScalarCorrectionKernelCondition
      S g factorAgreement := by
  exact
    hgeneration.trans
      (R.normalCentral_sup_ambientCommutator_le_scalarMismatchKernel
        S g factorAgreement hvalues)

/-- Under the exact residual generation condition, the mismatch extends to
an ambient linear character which is trivial on the right normal subgroup.
This is the scalar correction needed to normalize the right projective
lift. -/
theorem exists_comparisonCentralScalarCorrection_of_generation
    (R : AssociatedProjectiveRepresentation T V P)
    (S : AssociatedProjectiveRepresentation U W Q)
    (g : CentralRestrictionGroupData T U e)
    (factorAgreement :
      ∀ b c : B,
        P.factor (e b) (e c) =
          Q.factor b c)
    (hvalues : g.NormalizedNormalCentralValuesAgree)
    (hgeneration :
      ScalarCorrectionKernelGenerationCondition T U e) :
    ∃ χ : B →* ℂˣ,
      (∀ x : U.normalSubgroup, χ (x : B) = 1) ∧
      ∀ b : projectiveComparisonCentralizer T e,
        χ b =
          R.comparisonCentralScalarMismatch
            S
            g.projectiveComparisonCentralizer_le_rightCentralizer
            factorAgreement b := by
  apply
    R.exists_comparisonCentralScalarCorrection_of_kernelCondition
      S g factorAgreement
  exact
    R.comparisonCentralScalarCorrectionKernelCondition_of_generation
      S g factorAgreement hvalues hgeneration

end AssociatedProjectiveRepresentation
end CharacterTriple

end McKayConjecture
