/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.InductiveMcKay.CentralTripleActivityTransport

/-!
# Clifford assembly from central witnesses on matched characters

Let `N ◁ G`, let `H ≤ G`, and let `M ◁ H`, with `N ⊔ H = ⊤`.
Suppose an `H`-equivariant equivalence matches the prime-to-`p`
irreducible characters of `N` and `M`, and suppose every exactly matched
pair of canonical inertia triples carries a complete central-isomorphism
witness.

`activeOrbitEquivOfCompleteCentralIsomorphismWitness` supplies the active
orbit equivalence.  Its target orbit is represented by the image of the
source orbit's chosen representative, but the target Clifford block is
defined using the quotient's independently chosen `out` representative.
The two representatives have equal quotient classes.  This file uses
`pPrimeOrbitBlockEquivOfQuotientMkEq` to perform precisely that final
repackaging, so no additional central witness at the target `out`
representative is needed.
-/

noncomputable section

namespace McKayConjecture
namespace InductiveMcKay

open CharacterTriple
open CliffordCorrespondence
open CliffordEquivalence
open CliffordPartition

variable {G : Type} [Group G] [Finite G]
variable (N H : Subgroup G) [N.Normal]
variable (M : Subgroup H) [M.Normal]

noncomputable local instance matchedCentralTripleAssemblyFintypeG :
    Fintype G :=
  Fintype.ofFinite G

noncomputable local instance matchedCentralTripleAssemblyFintypeH :
    Fintype H :=
  Fintype.ofFinite H

/-- The exact input for matched central-triple Clifford assembly.

The central witness is requested at the actual matched character `e θ`;
there is deliberately no second hypothesis requesting a witness at an
arbitrary quotient-chosen representative of its orbit. -/
structure MatchedCentralTripleCliffordAssemblyData (p : ℕ) where
  /-- The ambient group is generated by the normal subgroup and `H`. -/
  sup_eq_top : N ⊔ H = ⊤
  /-- Equivalence of prime-to-`p` normal-subgroup characters. -/
  characterEquiv :
    PPrimeIrreducibleCharacter N p ≃
      PPrimeIrreducibleCharacter M p
  /-- Equivariance for the restricted `H`-action. -/
  characterEquiv_smul :
    ∀ (h : H) (θ : PPrimeIrreducibleCharacter N p),
      characterEquiv (h • θ) = h • characterEquiv θ
  /-- Complete central witnesses on the exactly matched inertia triples. -/
  centralWitness :
    ∀ θ : PPrimeIrreducibleCharacter N p,
      CompleteCentralIsomorphismWitness
        (ofInertia N θ.1)
        (ofInertia M (characterEquiv θ).1)

namespace MatchedCentralTripleCliffordAssemblyData

variable {N H M}
variable {p : ℕ} [Fact p.Prime]

/-- The active-orbit equivalence forced by the matched complete central
witnesses. -/
def activeOrbitEquiv
    (d : MatchedCentralTripleCliffordAssemblyData N H M p) :
    ActiveOrbit N p ≃ ActiveOrbit M p :=
  activeOrbitEquivOfCompleteCentralIsomorphismWitness
    N H M d.sup_eq_top d.characterEquiv
      d.characterEquiv_smul d.centralWitness

/-- The target active orbit is represented by the image of the source
orbit's chosen prime-to-`p` representative. -/
@[simp]
theorem activeOrbitEquiv_apply_coe
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (q : ActiveOrbit N p) :
    (d.activeOrbitEquiv q).1 =
      (Quotient.mk''
        (d.characterEquiv (q.pPrimeOut N)).1 :
          OrbitSpace M) :=
  activeOrbitEquivOfCompleteCentralIsomorphismWitness_apply_coe
    N H M d.sup_eq_top d.characterEquiv
      d.characterEquiv_smul d.centralWitness q

/-- The matched target character and the target orbit's independently
chosen `out` representative determine the same orbit class. -/
theorem targetRepresentativeOrbitEq
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (q : ActiveOrbit N p) :
    (Quotient.mk''
        (d.characterEquiv (q.pPrimeOut N)).1 :
          OrbitSpace M) =
      Quotient.mk'' (d.activeOrbitEquiv q).1.out := by
  calc
    (Quotient.mk''
        (d.characterEquiv (q.pPrimeOut N)).1 :
          OrbitSpace M) =
        (d.activeOrbitEquiv q).1 :=
      (d.activeOrbitEquiv_apply_coe q).symm
    _ = Quotient.mk'' (d.activeOrbitEquiv q).1.out :=
      (Quotient.out_eq' (d.activeOrbitEquiv q).1).symm

/-- The matched target character is active.  This is just the activity of
the target orbit, transported along its explicit quotient equality. -/
theorem targetCharacter_isActive
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (q : ActiveOrbit N p) :
    @IsActivePPrimeCharacter H _ M _ p
      (d.characterEquiv (q.pPrimeOut N)) := by
  unfold IsActivePPrimeCharacter
  rw [← d.activeOrbitEquiv_apply_coe q]
  exact (d.activeOrbitEquiv q).2

/-- The inertia index of the exactly matched target representative is
prime to `p`. -/
theorem targetCharacter_inertia_index_isPPrime
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (q : ActiveOrbit N p) :
    ¬p ∣
      (IrreducibleCharacter.inertia M
        (d.characterEquiv (q.pPrimeOut N)).1).index :=
  ((isActivePPrimeCharacter_iff_inertia
    M (Fact.out : p.Prime)
      (d.characterEquiv (q.pPrimeOut N))).mp
        (d.targetCharacter_isActive q)).1

/-- The exact active Clifford-block equivalence for a matched orbit.

After the central inertia correspondence and Clifford induction at the
matched target character, the final equivalence only repackages the block
along `targetRepresentativeOrbitEq`. -/
def blockEquiv
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (q : ActiveOrbit N p) :
    PPrimeOrbitBlock N p q.1 ≃
      PPrimeOrbitBlock M p (d.activeOrbitEquiv q).1 := by
  let θ := q.pPrimeOut N
  let φ := d.characterEquiv θ
  let C := d.centralWitness θ
  letI := C.leftAddCommGroup
  letI := C.leftModule
  letI := C.leftModuleFinite
  letI := C.leftNontrivial
  letI := C.rightAddCommGroup
  letI := C.rightModule
  letI := C.rightModuleFinite
  letI := C.rightNontrivial
  exact
    (activeOrbitCliffordEquiv
      N (Fact.out : p.Prime) q).symm |>.trans
      ((C.witness.pPrimeInertiaEquiv
        N θ.1 M φ.1 (Fact.out : p.Prime)
          θ.2 φ.2).trans
        ((cliffordPPrimeCorrespondence
          M φ.1 (Fact.out : p.Prime)
            (d.targetCharacter_inertia_index_isPPrime q)).trans
          (pPrimeOrbitBlockEquivOfQuotientMkEq
            M (d.targetRepresentativeOrbitEq q) p)))

/-- Package the exact matched block equivalences as active orbitwise
correspondence data. -/
def toActivePPrimeOrbitwiseCorrespondence
    (d : MatchedCentralTripleCliffordAssemblyData N H M p) :
    ActivePPrimeOrbitwiseCorrespondence N M p where
  activeOrbitEquiv := d.activeOrbitEquiv
  blockEquiv := d.blockEquiv

@[simp]
theorem toActivePPrimeOrbitwiseCorrespondence_activeOrbitEquiv
    (d : MatchedCentralTripleCliffordAssemblyData N H M p) :
    d.toActivePPrimeOrbitwiseCorrespondence.activeOrbitEquiv =
      d.activeOrbitEquiv :=
  rfl

@[simp]
theorem toActivePPrimeOrbitwiseCorrespondence_blockEquiv
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (q : ActiveOrbit N p) :
    d.toActivePPrimeOrbitwiseCorrespondence.blockEquiv q =
      d.blockEquiv q :=
  rfl

/-- Assemble all matched central-triple block equivalences into a global
prime-to-`p` character equivalence. -/
def assembledPPrimeEquiv
    (d : MatchedCentralTripleCliffordAssemblyData N H M p) :
    PPrimeIrreducibleCharacter G p ≃
      PPrimeIrreducibleCharacter H p :=
  d.toActivePPrimeOrbitwiseCorrespondence.assemble

/-- The assembled equivalence has exactly the induced active-orbit law. -/
@[simp]
theorem activeOrbitIndex_assembledPPrimeEquiv
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (χ : PPrimeIrreducibleCharacter G p) :
    activeOrbitIndex M (d.assembledPPrimeEquiv χ) =
      d.activeOrbitEquiv (activeOrbitIndex N χ) :=
  d.toActivePPrimeOrbitwiseCorrespondence
    |>.activeOrbitIndex_assemble χ

/-- Expanded form of the active-orbit law: the target orbit is the orbit
of the image of the chosen source representative. -/
@[simp]
theorem activeOrbitIndex_assembledPPrimeEquiv_coe
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (χ : PPrimeIrreducibleCharacter G p) :
    (activeOrbitIndex M (d.assembledPPrimeEquiv χ)).1 =
      (Quotient.mk''
        (d.characterEquiv
          ((activeOrbitIndex N χ).pPrimeOut N)).1 :
          OrbitSpace M) := by
  rw [d.activeOrbitIndex_assembledPPrimeEquiv χ]
  exact d.activeOrbitEquiv_apply_coe (activeOrbitIndex N χ)

/-- The inverse assembled equivalence obeys the inverse active-orbit law. -/
@[simp]
theorem activeOrbitIndex_assembledPPrimeEquiv_symm
    (d : MatchedCentralTripleCliffordAssemblyData N H M p)
    (ψ : PPrimeIrreducibleCharacter H p) :
    activeOrbitIndex N (d.assembledPPrimeEquiv.symm ψ) =
      d.activeOrbitEquiv.symm (activeOrbitIndex M ψ) :=
  d.toActivePPrimeOrbitwiseCorrespondence
    |>.activeOrbitIndex_assemble_symm ψ

end MatchedCentralTripleCliffordAssemblyData

end InductiveMcKay
end McKayConjecture
