/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.NormalCentralSylowDecomposition
import McKayConjecture.InductiveMcKay.NormalSubgroupCentralIntersectionReduction
import McKayConjecture.InductiveMcKay.CentralIntersectionKernelAssembly

/-!
# The canonical `p′` kernel in the `CP` central-intersection reduction

Inside `CP`, the intersection `C ∩ P` is a central Sylow subgroup of the
internal copy of `C`.  Burnside transfer therefore splits that copy as its
canonical `p′`-core times `C ∩ P`.  Since the latter factor already lies in
`P`, the whole group is generated by the ambient image of the `p′`-core and
`P`.

This is the group-theoretic starting point of the ordinary-character
Okuyama--Wajima route.  On the local side the Sylow normalizer is the direct
product of the fixed points of the `p′` kernel and the Sylow subgroup.
-/

noncomputable section

namespace McKayConjecture
namespace InductiveMcKay
namespace NormalSubgroupCentralIntersectionReduction
namespace ComplementReduction

open GroupTheory

variable {X : Type} [Group X] [Finite X]
variable {q : ℕ} [Fact q.Prime]
variable (S : Sylow q X) (C : Subgroup X) [C.Normal]

/-- The canonical normal `q′`-kernel inside `CP`. -/
abbrev productPPrimeKernel
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    Subgroup (product S C) :=
  ambientNormalIntersectionComplement
    (productSylow S C)
    (internalKernel S C)
    (internalKernel_inf_productSylow_le_center
      S C hcentral)

/-- The canonical `q′`-kernel is normal in `CP`. -/
instance productPPrimeKernel_normal
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    (productPPrimeKernel S C hcentral).Normal :=
  inferInstance

/-- The canonical kernel has order prime to `q`. -/
theorem productPPrimeKernel_isPPrimeGroup
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    IsPPrimeGroup q
      (productPPrimeKernel S C hcentral) :=
  ambientNormalIntersectionComplement_isPPrimeGroup
    (productSylow S C)
    (internalKernel S C)
    (internalKernel_inf_productSylow_le_center
      S C hcentral)

/-- The `q′`-kernel and the restricted Sylow subgroup generate `CP`. -/
theorem productPPrimeKernel_sup_productSylow_eq_top
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    productPPrimeKernel S C hcentral ⊔
        (productSylow S C :
          Subgroup (product S C)) =
      ⊤ :=
  ambientNormalIntersectionComplement_sup_sylow_eq_top
    (productSylow S C)
    (internalKernel S C)
    (internalKernel_inf_productSylow_le_center
      S C hcentral)
    (internalKernel_sup_productSylow S C)

/-- The source is a split extension with disjoint `q′` and Sylow
factors. -/
theorem productPPrimeKernel_inf_productSylow_eq_bot
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    productPPrimeKernel S C hcentral ⊓
        (productSylow S C :
          Subgroup (product S C)) =
      ⊥ :=
  ambientNormalIntersectionComplement_inf_sylow_eq_bot
    (productSylow S C)
    (internalKernel S C)
    (internalKernel_inf_productSylow_le_center
      S C hcentral)

/-- The coprime kernel itself satisfies the central-intersection setup,
with trivial intersection with the Sylow subgroup. -/
theorem productPPrimeKernelCentralIntersectionSetup
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    CentralIntersectionKernelAssembly.CentralIntersectionSetup
      (p := q)
      (productPPrimeKernel S C hcentral)
      (productSylow S C :
        Subgroup (product S C)) :=
  CentralIntersectionKernelAssembly.CentralIntersectionSetup.ofGenerate
    (productPPrimeKernel S C hcentral)
    (productSylow S C :
      Subgroup (product S C))
    (productSylow S C).isPGroup'
    (productPPrimeKernel_sup_productSylow_eq_top
      S C hcentral)
    (by
      rw [productPPrimeKernel_inf_productSylow_eq_bot
        S C hcentral]
      exact bot_le)

/-- The local group has the elementary form
`N_{CP}(P) = C_R(P)P`, where `R` is the canonical `q′`-kernel. -/
theorem normalizer_productSylow_eq_fixedPoints_sup
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    Subgroup.normalizer
        (productSylow S C :
          Set (product S C)) =
      (productPPrimeKernel S C hcentral ⊓
          Subgroup.centralizer
            (productSylow S C :
              Set (product S C))) ⊔
        (productSylow S C :
          Subgroup (product S C)) :=
  normalizer_eq_complement_inf_centralizer_sup
    (productSylow S C)
    (internalKernel S C)
    (internalKernel_inf_productSylow_le_center
      S C hcentral)
    (internalKernel_sup_productSylow S C)

/-- For the coprime kernel, the internal kernel used by Clifford theory is
literally its fixed-point subgroup.  This is the subgroup on which the
Glauberman correspondent lives. -/
theorem internalKernelNormalizer_productPPrimeKernel_eq_fixedPoints
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    CentralIntersectionKernelAssembly.internalKernelNormalizer
        (productPPrimeKernel S C hcentral)
        (productSylow S C :
          Subgroup (product S C)) =
      internalPPrimeKernelFixedPoints
        (productSylow S C)
        (productPPrimeKernel S C hcentral) := by
  apply le_antisymm
  · intro x hx
    exact
      ⟨hx,
        inf_normalizer_le_centralizer_of_normal_isPPrime
          (p := q)
          (productSylow S C :
            Subgroup (product S C))
          (productPPrimeKernel S C hcentral)
          (productSylow S C).isPGroup'
          (productPPrimeKernel_isPPrimeGroup
            S C hcentral)
          ⟨hx, x.property⟩⟩
  · intro x hx
    exact hx.1

/-- The canonical relabelling between the local Clifford kernel and the
fixed-point group occurring in the Glauberman correspondence. -/
def localKernelFixedPointsEquiv
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    CentralIntersectionKernelAssembly.internalKernelNormalizer
          (productPPrimeKernel S C hcentral)
          (productSylow S C :
            Subgroup (product S C)) ≃*
      internalPPrimeKernelFixedPoints
        (productSylow S C)
        (productPPrimeKernel S C hcentral) :=
  MulEquiv.subgroupCongr
    (internalKernelNormalizer_productPPrimeKernel_eq_fixedPoints
      S C hcentral)

/-- The ambient fixed-point subgroup `C_R(P) ≤ CP`. -/
abbrev productPPrimeKernelFixedPoints
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    Subgroup (product S C) :=
  productPPrimeKernel S C hcentral ⊓
    Subgroup.centralizer
      (productSylow S C :
        Set (product S C))

/-- The same relabelling with codomain the ambient fixed-point subgroup
`C_R(P) ≤ CP`, rather than its internal copy in the normalizer. -/
def localKernelAmbientFixedPointsEquiv
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    CentralIntersectionKernelAssembly.internalKernelNormalizer
          (productPPrimeKernel S C hcentral)
          (productSylow S C :
            Subgroup (product S C)) ≃*
      productPPrimeKernelFixedPoints
        S C hcentral :=
  (localKernelFixedPointsEquiv S C hcentral).trans
    (Subgroup.subgroupOfEquivOfLe
      (show
        productPPrimeKernel S C hcentral ⊓
            Subgroup.centralizer
              (productSylow S C :
                Set (product S C)) ≤
          Subgroup.normalizer
            (productSylow S C :
              Set (product S C)) from
        inf_le_right.trans
          (Subgroup.centralizer_le_normalizer
            (productSylow S C :
              Set (product S C)))))

/-- Direct-product coordinates on the local Sylow normalizer. -/
def normalizerProductEquiv
    (hcentral :
      C ⊓ (S : Subgroup X) ≤ Subgroup.center X) :
    internalPPrimeKernelFixedPoints
          (productSylow S C)
          (productPPrimeKernel S C hcentral) ×
        internalNormalizerSylow (productSylow S C) ≃*
      Subgroup.normalizer
        (productSylow S C :
          Set (product S C)) :=
  pPrimeKernelFixedPointsProductEquiv
    (productSylow S C)
    (productPPrimeKernel S C hcentral)
    (productPPrimeKernel_isPPrimeGroup
      S C hcentral)
    (productPPrimeKernel_sup_productSylow_eq_top
      S C hcentral)

end ComplementReduction
end NormalSubgroupCentralIntersectionReduction
end InductiveMcKay
end McKayConjecture
