name = "mckay-conjecture"
version = "0.1.0"
defaultTargets = ["McKayConjecture"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "3b6f23172a994dc739dfcc974199fe05c44f691d"

[[lean_lib]]
name = "McKayConjecture"
