name = "mckay-conjecture"
version = "0.1.0"
defaultTargets = ["McKayConjecture"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "12ab8e82f8447fa639dabe9ffeda74436b72be31"

[[lean_lib]]
name = "McKayConjecture"
