/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import SplittingSpheres.Foundations.RelativeDiffeomorph

/-!
# Functoriality of relative mapping-class quotients

This file contains only the algebra needed to descend a homomorphism of relative
diffeomorphism groups through the two mapping-class quotients.  Geometric constructions such as
capping or lifting remain external: they need only prove the displayed relator and selected-class
hypotheses for their underlying group homomorphisms.
-/

@[expose] public section

open Set
open scoped ContDiff Manifold

noncomputable section

namespace SplittingSpheres

universe uM uN uHM uHN

variable {EM EN : Type*}
  [NormedAddCommGroup EM] [NormedSpace ℝ EM]
  [NormedAddCommGroup EN] [NormedSpace ℝ EN]
variable {HM : Type uHM} [TopologicalSpace HM]
  {HN : Type uHN} [TopologicalSpace HN]
variable {IM : ModelWithCorners ℝ EM HM} {IN : ModelWithCorners ℝ EN HN}
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace HM M]
  {N : Type uN} [TopologicalSpace N] [ChartedSpace HN N]
variable {s : Set M} {t : Set N}

/-- The exact algebraic condition for a homomorphism of relative diffeomorphism groups to
descend to relative mapping classes: every generating diffeotopy relator lands in the target
normal subgroup. -/
def PreservesRelativeDiffeotopyRelators
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t) : Prop :=
  MapsTo Φ (relativeDiffeotopyRelators (IM := IM) s)
    (relativeDiffeotopyNormal (IM := IN) t)

/-- Relator preservation extends from the generating set to its normal closure. -/
theorem relativeDiffeotopyNormal_le_comap
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ) :
    relativeDiffeotopyNormal (IM := IM) s ≤
      (relativeDiffeotopyNormal (IM := IN) t).comap Φ := by
  apply Subgroup.normalClosure_le_normal
  intro r hr
  exact hΦ hr

/-- The homomorphism induced on relative mapping-class groups. -/
def relativeMappingClassMap
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ) :
    RelativeMappingClass (IM := IM) s →* RelativeMappingClass (IM := IN) t :=
  QuotientGroup.map (relativeDiffeotopyNormal (IM := IM) s)
    (relativeDiffeotopyNormal (IM := IN) t) Φ
    (relativeDiffeotopyNormal_le_comap Φ hΦ)

/-- The induced mapping-class homomorphism sends a canonical class to the class of its image. -/
@[simp]
theorem relativeMappingClassMap_mk
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (f : TauCeti.RelativeDiff (I := IM) M ∞ s) :
    relativeMappingClassMap Φ hΦ (relativeMappingClassMk (IM := IM) s f) =
      relativeMappingClassMk (IM := IN) t (Φ f) :=
  QuotientGroup.map_mk' _ _ _ _ f

/-- The induced homomorphism sends the identity mapping class to the identity. -/
@[simp]
theorem relativeMappingClassMap_one
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ) :
    relativeMappingClassMap Φ hΦ 1 = 1 :=
  map_one _

/-- The exact second-quotient descent condition: every selected source representative has image
class in the normal closure generated by the selected target representatives. -/
def SendsSelectedClassesIntoNormal
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t)) : Prop :=
  ∀ ⦃f : TauCeti.RelativeDiff (I := IM) M ∞ s⦄, f ∈ T →
    relativeMappingClassMap Φ hΦ (relativeMappingClassMk (IM := IM) s f) ∈
      Subgroup.normalClosure (relativeMappingClassMk (IM := IN) t '' U)

/-- The selected-class descent hypothesis extends to the normal closure defining the source
quotient. -/
theorem relativeMappingClassSelectedNormal_le_comap
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U) :
    Subgroup.normalClosure (relativeMappingClassMk (IM := IM) s '' T) ≤
      (Subgroup.normalClosure (relativeMappingClassMk (IM := IN) t '' U)).comap
        (relativeMappingClassMap Φ hΦ) := by
  apply Subgroup.normalClosure_le_normal
  rintro q ⟨f, hf, rfl⟩
  exact hTU hf

/-- A clean representative-level sufficient condition for second-quotient descent: if `Φ`
sends `T` into `U`, then it sends the corresponding source classes into the target normal
closure. -/
theorem sendsSelectedClassesIntoNormal_of_mapsTo
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : MapsTo Φ T U) : SendsSelectedClassesIntoNormal Φ hΦ T U := by
  intro f hf
  rw [relativeMappingClassMap_mk]
  exact Subgroup.subset_normalClosure ⟨Φ f, hTU hf, rfl⟩

/-- The homomorphism induced on the mapping-class quotients by selected representatives. -/
def relativeMappingClassModMap
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U) :
    RelativeMappingClassMod (IM := IM) s T →*
      RelativeMappingClassMod (IM := IN) t U :=
  QuotientGroup.map
    (Subgroup.normalClosure (relativeMappingClassMk (IM := IM) s '' T))
    (Subgroup.normalClosure (relativeMappingClassMk (IM := IN) t '' U))
    (relativeMappingClassMap Φ hΦ)
    (relativeMappingClassSelectedNormal_le_comap Φ hΦ T U hTU)

/-- Convenience constructor using the sufficient representative-level condition `Φ(T) ⊆ U`. -/
def relativeMappingClassModMapOfMapsTo
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : MapsTo Φ T U) :
    RelativeMappingClassMod (IM := IM) s T →*
      RelativeMappingClassMod (IM := IN) t U :=
  relativeMappingClassModMap Φ hΦ T U
    (sendsSelectedClassesIntoNormal_of_mapsTo Φ hΦ T U hTU)

/-- Formula for the induced map on a class in the first quotient. -/
@[simp]
theorem relativeMappingClassModMap_mk
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U)
    (q : RelativeMappingClass (IM := IM) s) :
    relativeMappingClassModMap Φ hΦ T U hTU
        (QuotientGroup.mk'
          (Subgroup.normalClosure (relativeMappingClassMk (IM := IM) s '' T)) q) =
      QuotientGroup.mk'
        (Subgroup.normalClosure (relativeMappingClassMk (IM := IN) t '' U))
        (relativeMappingClassMap Φ hΦ q) :=
  QuotientGroup.map_mk' _ _ _ _ q

/-- Application formula on a canonical relative-diffeomorphism representative. -/
@[simp]
theorem relativeMappingClassModMap_apply
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U)
    (f : TauCeti.RelativeDiff (I := IM) M ∞ s) :
    relativeMappingClassModMap Φ hΦ T U hTU
        (relativeMappingClassModMk (IM := IM) s T f) =
      relativeMappingClassModMk (IM := IN) t U (Φ f) := by
  rfl

/-- The induced second-quotient homomorphism preserves the identity. -/
@[simp]
theorem relativeMappingClassModMap_one
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U) :
    relativeMappingClassModMap Φ hΦ T U hTU 1 = 1 :=
  map_one _

/-- A canonical representative maps trivially whenever its target mapping class belongs to the
target selected-class normal closure. -/
theorem relativeMappingClassModMap_apply_eq_one_of_mem
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U)
    (f : TauCeti.RelativeDiff (I := IM) M ∞ s)
    (hf : relativeMappingClassMk (IM := IN) t (Φ f) ∈
      Subgroup.normalClosure (relativeMappingClassMk (IM := IN) t '' U)) :
    relativeMappingClassModMap Φ hΦ T U hTU
        (relativeMappingClassModMk (IM := IM) s T f) = 1 := by
  rw [relativeMappingClassModMap_apply]
  exact (QuotientGroup.eq_one_iff _).mpr hf

/-- In particular, a representative whose image lies in `U` maps trivially. -/
theorem relativeMappingClassModMap_apply_eq_one_of_mem_target
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U)
    (f : TauCeti.RelativeDiff (I := IM) M ∞ s) (hf : Φ f ∈ U) :
    relativeMappingClassModMap Φ hΦ T U hTU
        (relativeMappingClassModMk (IM := IM) s T f) = 1 := by
  apply relativeMappingClassModMap_apply_eq_one_of_mem Φ hΦ T U hTU f
  exact Subgroup.subset_normalClosure ⟨Φ f, hf, rfl⟩

/-- Every selected source representative is already trivial in the source quotient, hence its
image under the induced homomorphism is trivial. -/
theorem relativeMappingClassModMap_selected_eq_one
    (Φ : TauCeti.RelativeDiff (I := IM) M ∞ s →*
      TauCeti.RelativeDiff (I := IN) N ∞ t)
    (hΦ : PreservesRelativeDiffeotopyRelators Φ)
    (T : Set (TauCeti.RelativeDiff (I := IM) M ∞ s))
    (U : Set (TauCeti.RelativeDiff (I := IN) N ∞ t))
    (hTU : SendsSelectedClassesIntoNormal Φ hΦ T U)
    (f : TauCeti.RelativeDiff (I := IM) M ∞ s) (hf : f ∈ T) :
    relativeMappingClassModMap Φ hΦ T U hTU
        (relativeMappingClassModMk (IM := IM) s T f) = 1 := by
  rw [relativeMappingClassModMk_eq_one hf, map_one]

end SplittingSpheres
