/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import SplittingSpheres.Foundations.SmoothCoverLiftGroup

/-!
# Mapping-class descent for certified liftable diffeotopies

Not every isotopy of base diffeomorphisms is asserted to lift.  The source relation in this file
is deliberately narrower: a witness includes joint smoothness, fixedness of the projected chosen
point, the fundamental-group lifting criterion on the whole product, and forward and inverse
recovered-subgroup preservation at every time.

Canonical lifting sends every such certified relation to a genuine relative diffeotopy upstairs.
Consequently it descends through the normal closure generated by exactly these relations.
-/

@[expose] public section

open Function Set
open scoped ContDiff Manifold Topology

noncomputable section

namespace SplittingSpheres

universe uE uX uHE uHX

variable {EE EX : Type*}
  [NormedAddCommGroup EE] [NormedSpace ℝ EE]
  [NormedAddCommGroup EX] [NormedSpace ℝ EX]
variable {HE : Type uHE} [TopologicalSpace HE]
  {HX : Type uHX} [TopologicalSpace HX]
variable {IE : ModelWithCorners ℝ EE HE} {IX : ModelWithCorners ℝ EX HX}
variable {E : Type uE} [TopologicalSpace E] [ChartedSpace HE E]
  {X : Type uX} [TopologicalSpace X] [ChartedSpace HX X]
variable {p : E → X}

namespace SmoothCover

/-- A certified liftable diffeotopy between elements of the two-sided-liftable subgroup.

The product lifting criterion and the two all-time preservation hypotheses are data.  Thus this
structure cannot be constructed from an arbitrary ordinary diffeotopy. -/
structure TwoSidedLiftableDiffeotopy (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E)
    (f g : hp.twoSidedLiftableSubgroup e₀) where
  /-- The base diffeomorphism at each time. -/
  family : unitInterval → (X ≃ₘ^∞⟮IX, IX⟯ X)
  /-- Smoothness jointly in time and the base variable. -/
  contMDiff_eval :
    ContMDiff ((𝓡∂ 1).prod IX) IX ∞ (diffeomorphismFamilyEval family)
  /-- Every slice fixes the projected selected point. -/
  fixed : ∀ t, family t (p e₀) = p e₀
  /-- The lifting criterion on the entire product, not merely on individual slices. -/
  liftingCriterion :
    hp.FamilyLiftingCriterion (diffeomorphismFamilyEval family) contMDiff_eval e₀
      (fixed 0).symm
  /-- Forward preservation at every time. -/
  preserves : hp.DiffeomorphismFamilyPreservesRecoveredSubgroup family e₀ fixed
  /-- Inverse preservation at every time. -/
  preservesInv : hp.DiffeomorphismFamilyInversePreservesRecoveredSubgroup family e₀ fixed
  /-- Exact initial endpoint. -/
  zero : family 0 = f.1
  /-- Exact final endpoint. -/
  one : family 1 = g.1

namespace TwoSidedLiftableDiffeotopy

variable (hp : SmoothCover IE IX ∞ p)
  [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E)
  {f g : hp.twoSidedLiftableSubgroup e₀}

/-- The initial canonical relative slice agrees with the lift homomorphism applied to the initial
base endpoint. -/
theorem initialRelativeSlice_eq (K : hp.TwoSidedLiftableDiffeotopy e₀ f g) :
    hp.basedFamilyLiftRelativeSlice K.family K.contMDiff_eval e₀ K.fixed
        K.liftingCriterion K.preserves K.preservesInv {e₀}
        (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
          K.liftingCriterion) 0 =
      hp.liftableDiffeomorphLiftHom e₀ f := by
  apply Subtype.ext
  apply Diffeomorph.ext
  intro z
  have hEq :
      (fun w ↦ hp.basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
        e₀ K.fixed K.liftingCriterion ((0 : unitInterval), w)) =
      hp.liftableDiffeomorphLift e₀ f := by
    apply hp.eq_of_contMDiff_lifts (e₀ := e₀)
    · exact hp.basedFamilyLift_slice_contMDiff
        (diffeomorphismFamilyEval K.family) K.contMDiff_eval e₀ K.fixed
        K.liftingCriterion 0
    · exact (hp.liftableDiffeomorphLift e₀ f).contMDiff
    · funext w
      calc
        p (hp.basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
            e₀ K.fixed K.liftingCriterion ((0 : unitInterval), w)) =
            K.family 0 (p w) :=
          hp.proj_basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
            e₀ K.fixed K.liftingCriterion 0 w
        _ = f.1 (p w) := congrArg (fun d : X ≃ₘ^∞⟮IX, IX⟯ X ↦ d (p w)) K.zero
        _ = p (hp.liftableDiffeomorphLift e₀ f w) :=
          (hp.proj_liftableDiffeomorphLift e₀ f w).symm
    · exact (hp.basedFamilyLift_basepoint (diffeomorphismFamilyEval K.family)
        K.contMDiff_eval e₀ K.fixed K.liftingCriterion 0).trans
        (hp.liftableDiffeomorphLift_basepoint e₀ f).symm
  rw [hp.basedFamilyLiftRelativeSlice_apply]
  exact congrFun hEq z

/-- The final canonical relative slice agrees with the lift homomorphism applied to the final
base endpoint. -/
theorem finalRelativeSlice_eq (K : hp.TwoSidedLiftableDiffeotopy e₀ f g) :
    hp.basedFamilyLiftRelativeSlice K.family K.contMDiff_eval e₀ K.fixed
        K.liftingCriterion K.preserves K.preservesInv {e₀}
        (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
          K.liftingCriterion) 1 =
      hp.liftableDiffeomorphLiftHom e₀ g := by
  apply Subtype.ext
  apply Diffeomorph.ext
  intro z
  have hEq :
      (fun w ↦ hp.basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
        e₀ K.fixed K.liftingCriterion ((1 : unitInterval), w)) =
      hp.liftableDiffeomorphLift e₀ g := by
    apply hp.eq_of_contMDiff_lifts (e₀ := e₀)
    · exact hp.basedFamilyLift_slice_contMDiff
        (diffeomorphismFamilyEval K.family) K.contMDiff_eval e₀ K.fixed
        K.liftingCriterion 1
    · exact (hp.liftableDiffeomorphLift e₀ g).contMDiff
    · funext w
      calc
        p (hp.basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
            e₀ K.fixed K.liftingCriterion ((1 : unitInterval), w)) =
            K.family 1 (p w) :=
          hp.proj_basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
            e₀ K.fixed K.liftingCriterion 1 w
        _ = g.1 (p w) := congrArg (fun d : X ≃ₘ^∞⟮IX, IX⟯ X ↦ d (p w)) K.one
        _ = p (hp.liftableDiffeomorphLift e₀ g w) :=
          (hp.proj_liftableDiffeomorphLift e₀ g w).symm
    · exact (hp.basedFamilyLift_basepoint (diffeomorphismFamilyEval K.family)
        K.contMDiff_eval e₀ K.fixed K.liftingCriterion 1).trans
        (hp.liftableDiffeomorphLift_basepoint e₀ g).symm
  rw [hp.basedFamilyLiftRelativeSlice_apply]
  exact congrFun hEq z

/-- A certified liftable diffeotopy lifts to a genuine relative diffeotopy upstairs between the
values of the canonical lift homomorphism at its endpoints. -/
noncomputable def lift (K : hp.TwoSidedLiftableDiffeotopy e₀ f g) :
    RelativeDiffeotopy ({e₀} : Set E)
      (hp.liftableDiffeomorphLiftHom e₀ f)
      (hp.liftableDiffeomorphLiftHom e₀ g) where
  toFun := hp.basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
    e₀ K.fixed K.liftingCriterion
  contMDiff_toFun := hp.basedFamilyLift_contMDiff
    (diffeomorphismFamilyEval K.family) K.contMDiff_eval e₀ K.fixed K.liftingCriterion
  slice t :=
    ⟨hp.basedFamilyLiftRelativeSlice K.family K.contMDiff_eval e₀ K.fixed
      K.liftingCriterion K.preserves K.preservesInv {e₀}
      (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
        K.liftingCriterion) t,
      fun z ↦ (hp.basedFamilyLiftRelativeSlice_apply K.family K.contMDiff_eval e₀ K.fixed
        K.liftingCriterion K.preserves K.preservesInv {e₀}
        (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
          K.liftingCriterion) t z).symm⟩
  zero z := by
    calc
      hp.basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
          e₀ K.fixed K.liftingCriterion ((0 : unitInterval), z) =
          (hp.basedFamilyLiftRelativeSlice K.family K.contMDiff_eval e₀ K.fixed
            K.liftingCriterion K.preserves K.preservesInv {e₀}
            (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
              K.liftingCriterion) 0).1 z :=
        (hp.basedFamilyLiftRelativeSlice_apply K.family K.contMDiff_eval e₀ K.fixed
          K.liftingCriterion K.preserves K.preservesInv {e₀}
          (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
            K.liftingCriterion) 0 z).symm
      _ = (hp.liftableDiffeomorphLiftHom e₀ f).1 z := by
        rw [K.initialRelativeSlice_eq hp e₀]
  one z := by
    calc
      hp.basedFamilyLift (diffeomorphismFamilyEval K.family) K.contMDiff_eval
          e₀ K.fixed K.liftingCriterion ((1 : unitInterval), z) =
          (hp.basedFamilyLiftRelativeSlice K.family K.contMDiff_eval e₀ K.fixed
            K.liftingCriterion K.preserves K.preservesInv {e₀}
            (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
              K.liftingCriterion) 1).1 z :=
        (hp.basedFamilyLiftRelativeSlice_apply K.family K.contMDiff_eval e₀ K.fixed
          K.liftingCriterion K.preserves K.preservesInv {e₀}
          (hp.basedFamilyLift_fixes_singleton K.family K.contMDiff_eval e₀ K.fixed
            K.liftingCriterion) 1 z).symm
      _ = (hp.liftableDiffeomorphLiftHom e₀ g).1 z := by
        rw [K.finalRelativeSlice_eq hp e₀]

end TwoSidedLiftableDiffeotopy

/-- Endpoint differences of certified two-sided-liftable diffeotopies.  This is intentionally a
properly constrained relation, not the set of all ordinary diffeotopy relators. -/
def twoSidedLiftableDiffeotopyRelators (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    Set (hp.twoSidedLiftableSubgroup e₀) :=
  {r | ∃ f g, Nonempty (hp.TwoSidedLiftableDiffeotopy e₀ f g) ∧ r = f / g}

/-- The normal subgroup generated by certified liftable-diffeotopy endpoint differences. -/
def twoSidedLiftableDiffeotopyNormal (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    Subgroup (hp.twoSidedLiftableSubgroup e₀) :=
  Subgroup.normalClosure (hp.twoSidedLiftableDiffeotopyRelators e₀)

instance twoSidedLiftableDiffeotopyNormal_normal (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    (hp.twoSidedLiftableDiffeotopyNormal e₀).Normal :=
  Subgroup.normalClosure_normal

/-- The source mapping-class group formed using only certified liftable diffeotopies. -/
abbrev TwoSidedLiftableMappingClass (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :=
  hp.twoSidedLiftableSubgroup e₀ ⧸ hp.twoSidedLiftableDiffeotopyNormal e₀

/-- The canonical class of a two-sided-liftable base diffeomorphism. -/
def twoSidedLiftableMappingClassMk (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    hp.twoSidedLiftableSubgroup e₀ →* hp.TwoSidedLiftableMappingClass e₀ :=
  QuotientGroup.mk' (hp.twoSidedLiftableDiffeotopyNormal e₀)

/-- Every certified liftable relator maps to an actual relative-diffeotopy relator upstairs. -/
theorem liftableDiffeomorphLiftHom_maps_relators (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    MapsTo (hp.liftableDiffeomorphLiftHom e₀)
      (hp.twoSidedLiftableDiffeotopyRelators e₀)
      (relativeDiffeotopyRelators (IM := IE) ({e₀} : Set E)) := by
  rintro r ⟨f, g, ⟨K⟩, rfl⟩
  refine ⟨hp.liftableDiffeomorphLiftHom e₀ f,
    hp.liftableDiffeomorphLiftHom e₀ g, ⟨K.lift hp e₀⟩, ?_⟩
  exact map_div (hp.liftableDiffeomorphLiftHom e₀) f g

/-- Hence every certified generating relator maps into the upstairs diffeotopy normal subgroup. -/
theorem liftableDiffeomorphLiftHom_maps_relators_normal (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    MapsTo (hp.liftableDiffeomorphLiftHom e₀)
      (hp.twoSidedLiftableDiffeotopyRelators e₀)
      (relativeDiffeotopyNormal (IM := IE) ({e₀} : Set E)) :=
  fun _ hhr ↦ Subgroup.subset_normalClosure
    (hp.liftableDiffeomorphLiftHom_maps_relators e₀ hhr)

/-- Relator preservation extends honestly to the normal closure defining the source quotient. -/
theorem twoSidedLiftableDiffeotopyNormal_le_comap (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    hp.twoSidedLiftableDiffeotopyNormal e₀ ≤
      (relativeDiffeotopyNormal (IM := IE) ({e₀} : Set E)).comap
        (hp.liftableDiffeomorphLiftHom e₀) := by
  apply Subgroup.normalClosure_le_normal
  intro r hr
  exact hp.liftableDiffeomorphLiftHom_maps_relators_normal e₀ hr

/-- Canonical lifting descended to the quotient by certified liftable diffeotopies. -/
noncomputable def twoSidedLiftableMappingClassLift (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    hp.TwoSidedLiftableMappingClass e₀ →*
      RelativeMappingClass (IM := IE) ({e₀} : Set E) :=
  QuotientGroup.map (hp.twoSidedLiftableDiffeotopyNormal e₀)
    (relativeDiffeotopyNormal (IM := IE) ({e₀} : Set E))
    (hp.liftableDiffeomorphLiftHom e₀)
    (hp.twoSidedLiftableDiffeotopyNormal_le_comap e₀)

/-- Representative formula for the quotient-level lift homomorphism. -/
@[simp]
theorem twoSidedLiftableMappingClassLift_mk (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E)
    (f : hp.twoSidedLiftableSubgroup e₀) :
    hp.twoSidedLiftableMappingClassLift e₀ (hp.twoSidedLiftableMappingClassMk e₀ f) =
      relativeMappingClassMk (IM := IE) ({e₀} : Set E)
        (hp.liftableDiffeomorphLiftHom e₀ f) :=
  QuotientGroup.map_mk' _ _ _ _ f

/-- The quotient-level lift preserves the identity class. -/
@[simp]
theorem twoSidedLiftableMappingClassLift_one (hp : SmoothCover IE IX ∞ p)
    [PathConnectedSpace E] [LocallyPathConnectedSpace E] (e₀ : E) :
    hp.twoSidedLiftableMappingClassLift e₀ 1 = 1 :=
  map_one _

end SmoothCover

end SplittingSpheres
