/-
  IrreducibleStep.lean — Vanishing for irreducible spaces of positive dimension

  Hartshorne III.2.7, Steps 3–5: For an irreducible Noetherian space X of
  dimension d ≥ 1, reduce H^n(X, F) = 0 for n > d to lower-dimensional spaces.

  Decomposed into sub-lemmas:
  1. constantSheaf_flasque_of_irreducible: Z is flasque on irreducible X
  2. constantSheaf_cohomology_vanishing: H^{n+1}(X, Z) = 0 (from 1 + FlasqueVanishing)
  3. cohomology_direct_limit_noetherian: Prop 2.9 (sorry — deferred)
  4. grothendieck_vanishing_irreducible_pos: main step (uses 2, 3, and IH)

  SORRY — requires Proposition 2.9 (direct limits) and extension-by-zero.
-/
import Aristotle.GrothendieckVanishing.main.Setup

universe u

open CategoryTheory TopologicalSpace

/-- On an irreducible space, the constant sheaf Z has epi restriction maps (is flasque).

    On an irreducible space, any two nonempty opens intersect. The constant sheaf
    (sheafification of the constant presheaf with value Z) assigns Z to every
    nonempty connected open, with identity restriction maps. Since every nonempty
    open in an irreducible space is connected, all restriction maps are identity = epi.

    SORRY — requires working with the sheafification construction. -/
theorem constantSheaf_flasque_of_irreducible
    (X : TopCat.{u}) [IrreducibleSpace X]
    {U V : Opens X} (i : U ⟶ V) :
    Epi (((constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
      (AddCommGrpCat.of (ULift ℤ))).val.map i.op) := by
  admit

/-- The constant sheaf Z on an irreducible Noetherian space has vanishing
    higher cohomology. Follows from `constantSheaf_flasque_of_irreducible`
    and `FlasqueVanishing`. -/
theorem constantSheaf_cohomology_vanishing
    (X : TopCat.{u}) [NoetherianSpace X] [IrreducibleSpace X] (n : ℕ) :
    Subsingleton (Sheaf.H ((constantSheaf (Opens.grothendieckTopology X)
      AddCommGrpCat.{u}).obj (AddCommGrpCat.of (ULift ℤ))) (n + 1)) :=
  FlasqueVanishing X _ (fun i => constantSheaf_flasque_of_irreducible X i) n

/-- Proposition 2.9 (Hartshorne): On a Noetherian topological space, sheaf
    cohomology commutes with filtered direct limits.

    More precisely: if (F_α) is a direct system of sheaves, then
    H^i(X, lim→ F_α) ≅ lim→ H^i(X, F_α).

    SORRY — major theorem, deferred. -/
theorem cohomology_direct_limit_noetherian : True := trivial
-- Placeholder: the actual statement requires formalizing direct systems of sheaves,
-- which is substantial. For now, we record this as a known dependency.

/-- For an irreducible Noetherian space X of positive dimension, vanishing
    of H^n for n > dim X follows from vanishing on all lower-dimensional spaces.

    Uses Prop 2.9, the Z_U → Z → Z_Y sequence, FlasqueVanishing, and
    the fact that the constant sheaf on an irreducible space is flasque.

    Hartshorne Steps 3–5. -/
theorem grothendieck_vanishing_irreducible_pos
    (X : TopCat.{u}) [TopologicalSpace.NoetherianSpace X] [IrreducibleSpace X]
    (n : ℕ) (hn : n > topologicalKrullDim X)
    (hpos : topologicalKrullDim X > 0)
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (ih : ∀ (Y : TopCat.{u}) [TopologicalSpace.NoetherianSpace Y]
      (G : TopCat.Sheaf AddCommGrpCat.{u} Y),
      topologicalKrullDim Y < topologicalKrullDim X →
      n > topologicalKrullDim Y →
      Subsingleton (Sheaf.H G n)) :
    Subsingleton (Sheaf.H F n) := by
  -- Proof sketch (Hartshorne Steps 3-5):
  -- Step 3: By Prop 2.9 (cohomology_direct_limit_noetherian), reduce to
  --   finitely generated subsheaves F_α.
  -- Step 4: By induction on #generators, reduce to F generated by single
  --   section s ∈ F(U). Then F is a quotient of Z_U with kernel R supported
  --   on a closed set of dim < dim X. By LES + ih, reduce to Z_U.
  -- Step 5: For Z_U, use SES 0 → Z_U → Z → Z_Y → 0 where Y = X \ U.
  --   Z is flasque (constantSheaf_flasque_of_irreducible) so H^n(Z) = 0
  --   by constantSheaf_cohomology_vanishing. Z_Y supported on Y with
  --   dim Y < dim X, so H^n(Z_Y) = 0 by ih. By LES, H^n(Z_U) = 0.
  admit
