/-
  IrreducibleStep.lean — Vanishing for irreducible spaces of positive dimension

  Hartshorne III.2.7, Steps 3–5: For an irreducible Noetherian space X of
  dimension d ≥ 1, reduce H^n(X, F) = 0 for n > d to lower-dimensional spaces.

  The proof (to be filled in) uses:
  - Proposition 2.9: cohomology commutes with direct limits on Noetherian spaces
  - Reduction to sheaves generated by a single section (quotients of Z_U)
  - The short exact sequence 0 → Z_U → Z → Z_Y → 0 where Z is the
    constant sheaf (flasque on irreducible X) and Y = X \ U
  - FlasqueVanishing for the constant sheaf Z
  - Induction hypothesis for lower-dimensional closed subsets

  SORRY — requires Proposition 2.9 (direct limits) and extension-by-zero.
-/
import Aristotle.GrothendieckVanishing.main.Setup

universe u

open CategoryTheory TopologicalSpace

/-- For an irreducible Noetherian space X of positive dimension, vanishing
    of H^n for n > dim X follows from vanishing on all lower-dimensional spaces.

    Uses Prop 2.9, the Z_U → Z → Z_Y sequence, FlasqueVanishing, and
    the fact that the constant sheaf on an irreducible space is flasque.

    Hartshorne Steps 3–5. -/
theorem grothendieck_vanishing_irreducible_pos
    (X : TopCat.{u}) [TopologicalSpace.NoetherianSpace X] [IrreducibleSpace X]
    (n : ℕ) (hn : n > topologicalKrullDim X)
    (hpos : topologicalKrullDim X > 0)
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (ih : ∀ (Y : TopCat.{u}) [TopologicalSpace.NoetherianSpace Y]
      (G : TopCat.Sheaf AddCommGrpCat.{u} Y),
      topologicalKrullDim Y < topologicalKrullDim X →
      n > topologicalKrullDim Y →
      Subsingleton (Sheaf.H G n)) :
    Subsingleton (Sheaf.H F n) := by
  admit
