import Aristotle.GrothendieckVanishing.main.SetupCore
import Aristotle.GrothendieckVanishing.main.ReducibleVanishing

universe u

open CategoryTheory TopologicalSpace Abelian Limits Opposite

/-! ## Main vanishing theorems -/

/-- **Reducible vanishing** (Hartshorne III.2.7, reducible case).
    This is proved in `ReducibleVanishing.lean`; `Setup.lean` re-exports the
    finished theorem so downstream files do not depend on the auxiliary primed
    name. -/
theorem ReducibleVanishing
    (X : TopCat.{u}) [NoetherianSpace X]
    (n : ℕ) (hn : n > topologicalKrullDim X)
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (hNotIrred : ¬ IrreducibleSpace X) [Nonempty X]
    (ih_irred : ∀ (Y : TopCat.{u}) [NoetherianSpace Y]
      [IrreducibleSpace Y] (G : TopCat.Sheaf AddCommGrpCat.{u} Y),
      topologicalKrullDim Y ≤ topologicalKrullDim X →
      n > topologicalKrullDim Y → Subsingleton (Sheaf.H G n)) :
    Subsingleton (Sheaf.H F n) :=
  ReducibleVanishing' X n hn F hNotIrred ih_irred

set_option synthInstance.maxHeartbeats 80000 in
/-- **Irreducible positive-dimension vanishing** (Hartshorne III.2.7, irreducible case).
    For an irreducible Noetherian space `X` of dim `d ≥ 1`, cohomology vanishing above
    the dimension follows from vanishing on all spaces of strictly smaller dimension.

    **Important:** the naive closed-support argument for the kernel of
    `F → i_*(i^*F)` is *not* valid on an irreducible space: from
    `K_x = 0` on a proper closed subset `Z`, one only gets
    `supp(K) ⊆ X \ Z`, and `X \ Z` may be dense of the same dimension as `X`.

    The correct proof is Hartshorne's Steps 3-5:
    1. write `F` as a filtered colimit of finitely generated subsheaves and use
       cohomology/direct-limit compatibility on noetherian spaces;
    2. reduce by induction on the number of generators to the case where `F` is
       generated by one section `s ∈ F(U)`;
    3. realize that singly generated sheaf as a quotient of `Z_U`
       (formalized here by `zeroOutsideInt U`);
    4. reduce vanishing for subsheaves of `Z_U` to vanishing for `Z_V` on a
       smaller nonempty open `V ⊆ U`;
    5. prove vanishing of `Z_U` from `0 → Z_U → Z → Z_Y → 0`, using that the
       constant sheaf `Z` is flasque on irreducible spaces and that
       `Y = X \ U` has strictly smaller dimension.

    The present code below only sets up the initial proper closed subset and the
    pushforward vanishing term. The kernel term remains the genuine Hartshorne
    Steps 3-5 gap. -/
theorem IrreduciblePosVanishing
    (X : TopCat.{u}) [NoetherianSpace X] [IrreducibleSpace X]
    (n : ℕ) (hn : n > topologicalKrullDim X) (hpos : topologicalKrullDim X > 0)
    (F : TopCat.Sheaf AddCommGrpCat.{u} X)
    (ih : ∀ (Y : TopCat.{u}) [NoetherianSpace Y]
      (G : TopCat.Sheaf AddCommGrpCat.{u} Y),
      topologicalKrullDim Y < topologicalKrullDim X →
      n > topologicalKrullDim Y →
      Subsingleton (Sheaf.H G n)) :
    Subsingleton (Sheaf.H F n) := by
  -- We can correctly set up the proper closed subset `Z ⊊ X` and kill the
  -- pushforward term `i_*(i^*F)` using the induction hypothesis on `Z`.
  -- What does *not* follow is that the kernel of `F → i_*(i^*F)` is supported
  -- on a smaller closed subset; that would be false in general on irreducible
  -- spaces because `X \ Z` can be dense. The actual remaining proof must switch
  -- here to Hartshorne Steps 3-5 via singly generated subsheaves and `Z_U`.
  -- Step 1: Extract a proper closed subset Z ⊊ X (from dim ≥ 1)
  simp only [topologicalKrullDim, gt_iff_lt] at hpos
  rw [Order.krullDim_pos_iff] at hpos
  obtain ⟨a, b, hab⟩ := hpos
  -- a is an IrreducibleCloseds with a.carrier ⊊ X (since a < b ≤ univ)
  set Z := a.carrier with hZ_def
  have hZ_closed : IsClosed Z := a.isClosed'
  have hZ_ne_univ : Z ≠ Set.univ := fun h => lt_irrefl a (lt_of_lt_of_le hab
    (show b.carrier ⊆ a.carrier from by rw [show a.carrier = Set.univ from h]; exact Set.subset_univ _))
  -- dim Z < dim X (Z is a proper closed subset of irreducible X)
  have hZ_dim : topologicalKrullDim (TopCat.of Z) < topologicalKrullDim X := by
    exact topologicalKrullDim_lt_of_isIrreducible_of_isClosed hZ_closed hZ_ne_univ
      (lt_of_le_of_lt (topologicalKrullDim_subspace_le X Z)
        (lt_of_lt_of_le (show topologicalKrullDim X < ⊤ from by
          exact lt_of_lt_of_le hn le_top) le_top))
  -- n > dim Z (since n > dim X > dim Z)
  have hn_Z : ↑n > topologicalKrullDim (TopCat.of Z) := lt_trans hZ_dim hn
  -- Step 2: ClosedImmersionSES: 0 → K → F → i_*(i^*F) → 0
  obtain ⟨S, hSE, hS₂, hS₃⟩ := ClosedImmersionSES Z hZ_closed F
  -- Step 3: Pushforward vanishes
  have hPush : Subsingleton (Sheaf.H S.X₃ n) := by
    rw [hS₃]
    exact PushforwardHVanishing Z hZ_closed _ n (@ih (TopCat.of Z) _ _ hZ_dim hn_Z)
  -- The pushforward term is the only part of the closed-immersion reduction that
  -- is currently justified. Finishing the kernel term requires the separate
  -- Hartshorne Steps 3-5 argument, not the invalid support-shrinking shortcut.
  have hKer : Subsingleton (Sheaf.H S.X₁ n) := by
    sorry -- needs Hartshorne III.2.7 Steps 3-5 via zeroOutsideInt/direct limits
  -- Step 6: SES gives H(F) = 0 (subsingleton_ext_of_ses_middle inline)
  rw [← hS₂]
  let Z' := (constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
    (AddCommGrpCat.of (ULift ℤ))
  constructor; intro a b
  have ha : a.comp (Ext.mk₀ S.g) (add_zero n) = 0 :=
    @Subsingleton.elim _ ((add_zero n) ▸ hPush) _ _
  have hb : b.comp (Ext.mk₀ S.g) (add_zero n) = 0 :=
    @Subsingleton.elim _ ((add_zero n) ▸ hPush) _ _
  obtain ⟨c, hc⟩ := Ext.covariant_sequence_exact₂ Z' hSE a ha
  obtain ⟨d, hd⟩ := Ext.covariant_sequence_exact₂ Z' hSE b hb
  rw [← hc, ← hd, @Subsingleton.elim _ hKer c d]
  -- The remaining missing ingredient is the Hartshorne Steps 3-5 kernel analysis.
