import Mathlib

/-!
# `ULift ℤ` additive API

This module packages the generic additive algebra around `ULift ℤ` used by the
Grothendieck vanishing development without tying it to extension-by-zero.

## Main declarations

* `AddCommGrpCat.uliftZMultiplesHom_add`
* `AddCommGrpCat.uliftZMultiplesAddEquiv`
* `AddCommGrpCat.uliftZMultiplesAddEquiv_symm_apply`
* `ulift_int_subgroup_cyclic`
-/

universe u

open CategoryTheory

noncomputable section

namespace AddCommGrpCat

theorem uliftZMultiplesHom_add (G : Type u) [AddCommGroup G] (x y : G) :
    (uliftZMultiplesHom G) (x + y) = ((uliftZMultiplesHom G) x) + ((uliftZMultiplesHom G) y) := by
  ext
  simp_all only [uliftZMultiplesHom_apply_apply, smul_add, AddMonoidHom.add_apply]

/-- The additive equivalence `(ULift ℤ ⟶ G) ≃+ G`. -/
def uliftZMultiplesAddEquiv (G : AddCommGrpCat.{u}) :
    (AddCommGrpCat.of (ULift ℤ) ⟶ G) ≃+ G :=
  AddEquiv.trans
    (@AddCommGrpCat.homAddEquiv (AddCommGrpCat.of (ULift ℤ)) G)
    (AddEquiv.mk' (uliftZMultiplesHom G) (uliftZMultiplesHom_add G)).symm

@[simp] theorem uliftZMultiplesAddEquiv_symm_apply
    (G : AddCommGrpCat.{u}) (x : G) (n : ULift ℤ) :
    AddCommGrpCat.Hom.hom ((AddCommGrpCat.uliftZMultiplesAddEquiv G).symm x) n =
      (n.down : ℤ) • x := rfl

end AddCommGrpCat

/-- Every nonzero subgroup of `ULift ℤ` is generated by its smallest positive element.
    Derived from `Int.subgroup_cyclic` (Mathlib). -/
theorem _root_.ulift_int_subgroup_cyclic
    (H : AddSubgroup (ULift.{u} ℤ)) (hH : H ≠ ⊥) :
    ∃ d : ULift.{u} ℤ, d ∈ H ∧ d.down > 0 ∧
      ∀ h ∈ H, ∃ k : ℤ, h = ⟨k * d.down⟩ := by
  obtain ⟨a, ha⟩ := Int.subgroup_cyclic (H.map AddEquiv.ulift.toAddMonoidHom)
  have ha_ne : a ≠ 0 := by
    intro heq
    apply hH
    rw [eq_bot_iff]
    intro x hx
    rw [AddSubgroup.mem_bot]
    have hx' := AddSubgroup.mem_map_of_mem AddEquiv.ulift.toAddMonoidHom hx
    rw [ha, heq, AddSubgroup.closure_singleton_zero, AddSubgroup.mem_bot] at hx'
    exact AddEquiv.ulift.injective (hx'.trans (map_zero _).symm)
  have ha_mem : (⟨a⟩ : ULift.{u} ℤ) ∈ H := by
    have : a ∈ H.map AddEquiv.ulift.toAddMonoidHom :=
      ha ▸ AddSubgroup.subset_closure rfl
    obtain ⟨y, hy, hey⟩ := AddSubgroup.mem_map.mp this
    rwa [show y = ⟨a⟩ from by ext; exact hey] at hy
  refine ⟨⟨|a|⟩, ?_, abs_pos.mpr ha_ne, fun h hh => ?_⟩
  · by_cases hle : 0 ≤ a
    · rwa [abs_of_nonneg hle]
    · push_neg at hle
      rw [abs_of_neg hle]
      exact H.neg_mem ha_mem
  · have hx' := AddSubgroup.mem_map_of_mem AddEquiv.ulift.toAddMonoidHom hh
    rw [ha, AddSubgroup.mem_closure_singleton] at hx'
    obtain ⟨n, hn⟩ := hx'
    rw [zsmul_eq_mul] at hn
    by_cases hle : 0 ≤ a
    · exact ⟨n, ULift.ext _ _ (by rw [abs_of_nonneg hle]; exact hn.symm)⟩
    · push_neg at hle
      exact ⟨-n, ULift.ext _ _ (by rw [abs_of_neg hle, neg_mul_neg]; exact hn.symm)⟩
