import Aristotle.GrothendieckVanishing.main.GeneratedSubsheaf
import Aristotle.GrothendieckVanishing.main.ZeroOutside

/-!
  ZeroOutsideFinset.lean — `zeroOutsideInt`-driven finitely generated subsheaf machinery

  Contains:
  - `familyGeneratorMap`, `familyGeneratedSheaf`, `familyGeneratedSheafι`
  - `finsetGeneratorMap`, `finsetGeneratedSheaf`
-/

universe u

open CategoryTheory TopologicalSpace Limits Opposite

noncomputable section

namespace TopCat

namespace Sheaf

/-- For a family of local sections, the universal map from the coproduct of the corresponding
`zeroOutsideInt (U i)` into `F`. This packages the "generated by a family of sections"
construction used in Hartshorne Step 3. -/
abbrev familyGeneratorMap {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) {F : Sheaf AddCommGrpCat.{u} X}
    (s : ∀ i, F.presheaf.obj (op (U i)))
    [HasCoproduct fun i => zeroOutsideInt (U i)] :
    (∐ fun i => zeroOutsideInt (U i)) ⟶ F :=
  familyMap (fun i => zeroOutsideInt (U i)) (fun i => zeroOutsideInt.sHom (s i))

/-- The subsheaf of `F` generated by a family of local sections. -/
abbrev familyGeneratedSheaf {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) {F : Sheaf AddCommGrpCat.{u} X}
    (s : ∀ i, F.presheaf.obj (op (U i)))
    [HasCoproduct fun i => zeroOutsideInt (U i)] :
    Sheaf AddCommGrpCat.{u} X :=
  Limits.image (familyGeneratorMap U s)

/-- The canonical inclusion of the subsheaf generated by a family of sections into `F`. -/
abbrev familyGeneratedSheafι {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) {F : Sheaf AddCommGrpCat.{u} X}
    (s : ∀ i, F.presheaf.obj (op (U i)))
    [HasCoproduct fun i => zeroOutsideInt (U i)] :
    familyGeneratedSheaf U s ⟶ F :=
  Limits.image.ι (familyGeneratorMap U s)

theorem familyGeneratedSheaf_ι_eq {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) {F : Sheaf AddCommGrpCat.{u} X}
    (s : ∀ i, F.presheaf.obj (op (U i)))
    [HasCoproduct fun i => zeroOutsideInt (U i)] :
    familyGeneratedSheafι U s = Limits.image.ι (familyGeneratorMap U s) := rfl

end Sheaf

namespace Presheaf

/-- The canonical map attached to a finite set of local sections. -/
abbrev finsetGeneratorMap {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1] :
    (∐ fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1) ⟶
      (⟨F, hF⟩ : TopCat.Sheaf AddCommGrpCat.{u} X) :=
  TopCat.Sheaf.familyMap
    (fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1)
    (fun σ => Sheaf.Hom.mk (TopCat.Sheaf.zeroOutsideInt.sHomVal hF σ.1.2))

/-- The subsheaf of `F` generated by a finite set of local sections. -/
abbrev finsetGeneratedSheaf {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1] :
    TopCat.Sheaf AddCommGrpCat.{u} X :=
  TopCat.Sheaf.familyImage (F := (⟨F, hF⟩ : TopCat.Sheaf AddCommGrpCat.{u} X))
    (fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1)
    (fun σ => Sheaf.Hom.mk (TopCat.Sheaf.zeroOutsideInt.sHomVal hF σ.1.2))

/-- Coproduct inclusion induced by `S ⊆ S'` on the finite generator coproducts. -/
noncomputable def finsetCoproductInclGen {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X}
    {S S' : Finset (SectionIndex F)}
    (h : S ⊆ S') :
    (∐ fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1) ⟶
      (∐ fun σ : {σ // σ ∈ S'} => TopCat.Sheaf.zeroOutsideInt σ.1.1) :=
  Sigma.desc fun σ =>
    Sigma.ι (fun τ : {τ // τ ∈ S'} => TopCat.Sheaf.zeroOutsideInt τ.1.1) ⟨σ.1, h σ.2⟩

/-- Inclusion of finitely generated subsheaves induced by `S ⊆ S'`. -/
noncomputable def finsetImageInclGen {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    {S S' : Finset (SectionIndex F)}
    (h : S ⊆ S') :
    finsetGeneratedSheaf hF S ⟶ finsetGeneratedSheaf hF S' :=
  Limits.image.lift
    { I := finsetGeneratedSheaf hF S'
      m := Limits.image.ι (finsetGeneratorMap hF S')
      e := finsetCoproductInclGen h ≫ factorThruImage (finsetGeneratorMap hF S')
      fac := by
        rw [Category.assoc, Limits.image.fac]
        ext ⟨σ, hσ⟩
        simp [finsetCoproductInclGen, finsetGeneratorMap, TopCat.Sheaf.familyMap] }

theorem finsetImageInclGen_comp_ι {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    {S S' : Finset (SectionIndex F)}
    (h : S ⊆ S') :
    finsetImageInclGen hF h ≫ Limits.image.ι (finsetGeneratorMap hF S') =
      Limits.image.ι (finsetGeneratorMap hF S) := by
  simpa [finsetImageInclGen] using
    (Limits.image.lift_fac (f := finsetGeneratorMap hF S)
      { I := finsetGeneratedSheaf hF S'
        m := Limits.image.ι (finsetGeneratorMap hF S')
        e := finsetCoproductInclGen h ≫ factorThruImage (finsetGeneratorMap hF S')
        fac := by
          rw [Category.assoc, Limits.image.fac]
          ext ⟨σ, hσ⟩
          simp [finsetCoproductInclGen, finsetGeneratorMap, TopCat.Sheaf.familyMap] })

instance finsetImageInclGen_mono {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    {S S' : Finset (SectionIndex F)}
    (h : S ⊆ S') :
    Mono (finsetImageInclGen hF h) :=
  mono_of_mono_fac (finsetImageInclGen_comp_ι hF h)

end Presheaf

namespace Sheaf

/-- The canonical map attached to a finite set of local sections. -/
abbrev finsetGeneratorMap {X : TopCat.{u}}
    {F : Sheaf AddCommGrpCat.{u} X}
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1] :
    (∐ fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1) ⟶ F :=
  TopCat.Presheaf.finsetGeneratorMap (F := F.presheaf) F.cond S

/-- The subsheaf of `F` generated by a finite set of local sections. -/
abbrev finsetGeneratedSheaf {X : TopCat.{u}}
    {F : Sheaf AddCommGrpCat.{u} X}
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1] :
    Sheaf AddCommGrpCat.{u} X :=
  TopCat.Presheaf.finsetGeneratedSheaf (F := F.presheaf) F.cond S

end Sheaf

end TopCat
