/-
  ZeroOutsideFinset.lean — Finset-generated subsheaf machinery

  Split from ZeroOutside.lean. Contains:
  - adjoinGeneratorOpens/adjoinGeneratorSections: adjoin one extra section to a family
  - oldGeneratedToAdjoinGenerated: structural map for Finset.induction
  - adjoinGeneratorShortComplex: the SES for induction step
  - SectionIndex, finsetGeneratorMap, finsetGeneratedSheaf
  - allSectionMap: canonical epi from coproduct of all zeroOutsideInt
-/
import Aristotle.GrothendieckVanishing.main.ZeroOutside

universe u

open CategoryTheory TopologicalSpace Limits Opposite

noncomputable section

namespace TopCat

namespace Sheaf

open Presheaf

/-- Adjoin one extra open set to a family of opens. -/
abbrev adjoinGeneratorOpens {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) (U₀ : Opens X) :
    ι ⊕ Unit → Opens X
  | Sum.inl i => U i
  | Sum.inr _ => U₀

/-- Adjoin one extra local section to a family of local sections. -/
abbrev adjoinGeneratorSections {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    {U₀ : Opens X} (s₀ : F.presheaf.obj (op U₀)) :
    ∀ j : ι ⊕ Unit, F.presheaf.obj (op (adjoinGeneratorOpens U U₀ j))
  | Sum.inl i => s i
  | Sum.inr _ => s₀

/-- The canonical inclusion of the old coproduct into the coproduct after adjoining one
more generator. -/
abbrev oldToAdjoinCoproduct {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) (U₀ : Opens X)
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    (∐ fun i => zeroOutsideInt (U i)) ⟶
      (∐ fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)) :=
  Sigma.desc (fun i =>
    Sigma.ι (fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)) (Sum.inl i))

@[reassoc]
theorem oldToAdjoinCoproduct_comp_familyGeneratorMap {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    oldToAdjoinCoproduct U U₀ ≫
        familyGeneratorMap (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀) =
      familyGeneratorMap U s := by
  ext i
  simp [oldToAdjoinCoproduct, familyGeneratorMap, adjoinGeneratorOpens, adjoinGeneratorSections]

/-- The canonical morphism from the subsheaf generated by a family to the subsheaf generated
after adjoining one extra section. This is the structural map used in induction on the number
of generators. -/
abbrev oldGeneratedToAdjoinGenerated {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    familyGeneratedSheaf U s ⟶
      familyGeneratedSheaf (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀) :=
  Limits.image.lift
    { I := familyGeneratedSheaf (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀)
      m := Limits.image.ι _
      e := oldToAdjoinCoproduct U U₀ ≫ factorThruImage
        (familyGeneratorMap (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀))
      fac := by
        rw [Category.assoc, Limits.image.fac, oldToAdjoinCoproduct_comp_familyGeneratorMap] }

@[reassoc]
theorem oldGeneratedToAdjoinGenerated_comp {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    oldGeneratedToAdjoinGenerated U s U₀ s₀ ≫
        Limits.image.ι (familyGeneratorMap (adjoinGeneratorOpens U U₀)
          (adjoinGeneratorSections U s s₀)) =
      Limits.image.ι (familyGeneratorMap U s) :=
  Limits.image.lift_fac _

instance oldGeneratedToAdjoinGenerated_mono {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    Mono (oldGeneratedToAdjoinGenerated U s U₀ s₀) :=
  mono_of_mono_fac (oldGeneratedToAdjoinGenerated_comp U s U₀ s₀)

lemma old_familyGeneratedSheafι_comp_oldGeneratedToAdjoinGenerated {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)]
    (i : ι) :
    familyGeneratedSheafι U s i ≫ oldGeneratedToAdjoinGenerated U s U₀ s₀ =
      familyGeneratedSheafι (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀)
        (Sum.inl i) := by
  apply (cancel_mono (image.ι (familyGeneratorMap (adjoinGeneratorOpens U U₀)
    (adjoinGeneratorSections U s s₀)))).1
  rw [Category.assoc, oldGeneratedToAdjoinGenerated_comp,
    familyGeneratedSheafι_comp_image_ι, familyGeneratedSheafι_comp_image_ι]

/-- The projection from the enlarged coproduct onto the newly adjoined generator, killing the
old summands. -/
abbrev adjoinGeneratorProjection {X : TopCat.{u}} {ι : Type*}
    (U : ι → Opens X) (U₀ : Opens X)
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    (∐ fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)) ⟶ zeroOutsideInt U₀ :=
  Sigma.desc fun
    | Sum.inl _ => 0
    | Sum.inr _ => 𝟙 _

/-- After adjoining one generator, the quotient by the old generated subsheaf is generated by the
new section alone. -/
abbrev adjoinedGeneratorToCokernel {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    zeroOutsideInt U₀ ⟶ cokernel (oldGeneratedToAdjoinGenerated U s U₀ s₀) :=
  familyGeneratedSheafι (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀) (Sum.inr ()) ≫
    cokernel.π (oldGeneratedToAdjoinGenerated U s U₀ s₀)

@[reassoc]
theorem adjoinGeneratorProjection_comp_adjoinedGeneratorToCokernel {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    adjoinGeneratorProjection U U₀ ≫ adjoinedGeneratorToCokernel U s U₀ s₀ =
      factorThruImage (familyGeneratorMap (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀)) ≫
        cokernel.π (oldGeneratedToAdjoinGenerated U s U₀ s₀) := by
  ext j
  cases j with
  | inl i =>
      simp [adjoinGeneratorProjection]
      calc
        0 = Sigma.ι (fun i => zeroOutsideInt (U i)) i ≫ factorThruImage (familyGeneratorMap U s) ≫
            0 := by simp
        _ = familyGeneratedSheafι U s i ≫ oldGeneratedToAdjoinGenerated U s U₀ s₀ ≫
            cokernel.π (oldGeneratedToAdjoinGenerated U s U₀ s₀) := by
              simp [familyGeneratedSheafι, Category.assoc]
        _ = familyGeneratedSheafι (adjoinGeneratorOpens U U₀) (adjoinGeneratorSections U s s₀)
            (Sum.inl i) ≫ cokernel.π (oldGeneratedToAdjoinGenerated U s U₀ s₀) := by
              rw [← Category.assoc, old_familyGeneratedSheafι_comp_oldGeneratedToAdjoinGenerated]
        _ = Sigma.ι (fun j => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)) (Sum.inl i) ≫
            factorThruImage (familyGeneratorMap (adjoinGeneratorOpens U U₀)
              (adjoinGeneratorSections U s s₀)) ≫
            cokernel.π (oldGeneratedToAdjoinGenerated U s U₀ s₀) := by
              simp [familyGeneratedSheafι]
  | inr u =>
      cases u
      simp [adjoinGeneratorProjection, adjoinedGeneratorToCokernel, familyGeneratedSheafι,
        Category.assoc]

instance adjoinedGeneratorToCokernel_epi {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    Epi (adjoinedGeneratorToCokernel U s U₀ s₀) :=
  epi_of_epi_fac (adjoinGeneratorProjection_comp_adjoinedGeneratorToCokernel U s U₀ s₀)

/-- The short complex attached to adjoining one generator. -/
abbrev adjoinGeneratorShortComplex {X : TopCat.{u}} {ι : Type*}
    {F : Sheaf AddCommGrpCat.{u} X}
    (U : ι → Opens X) (s : ∀ i, F.presheaf.obj (op (U i)))
    (U₀ : Opens X) (s₀ : F.presheaf.obj (op U₀))
    [HasCoproduct fun i => zeroOutsideInt (U i)]
    [HasCoproduct fun j : ι ⊕ Unit => zeroOutsideInt (adjoinGeneratorOpens U U₀ j)] :
    ShortComplex (Sheaf AddCommGrpCat.{u} X) :=
  ShortComplex.mk (oldGeneratedToAdjoinGenerated U s U₀ s₀)
    (cokernel.π (oldGeneratedToAdjoinGenerated U s U₀ s₀))
    (cokernel.condition _)

/-- Indexing type for all local sections of a sheaf. -/
abbrev SectionIndex {X : TopCat.{u}}
    (F : Sheaf AddCommGrpCat.{u} X) :=
  Σ U : Opens X, F.presheaf.obj (op U)

/-- The canonical map attached to a finite set of local sections. -/
abbrev finsetGeneratorMap {X : TopCat.{u}}
    {F : Sheaf AddCommGrpCat.{u} X}
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1] :
    (∐ fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1) ⟶ F :=
  familyGeneratorMap (fun σ : {σ // σ ∈ S} => σ.1.1) (fun σ => σ.1.2)

/-- The subsheaf of `F` generated by a finite set of local sections. -/
abbrev finsetGeneratedSheaf {X : TopCat.{u}}
    {F : Sheaf AddCommGrpCat.{u} X}
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1] :
    Sheaf AddCommGrpCat.{u} X :=
  Limits.image (finsetGeneratorMap S)

instance finsetGeneratorMap_epi_to_image {X : TopCat.{u}}
    {F : Sheaf AddCommGrpCat.{u} X}
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1] :
    Epi (factorThruImage (finsetGeneratorMap S)) :=
  inferInstance

/-- The canonical map from the coproduct of all `zeroOutsideInt U` indexed by local sections
of `F` onto `F`. This is the formal Step 3A starting point for building finitely generated
subsheaves via images of smaller subcoproducts. -/
abbrev allSectionMap {X : TopCat.{u}}
    (F : Sheaf AddCommGrpCat.{u} X)
    [HasCoproduct (fun σ : SectionIndex F => zeroOutsideInt σ.1)] :
    (∐ fun σ : SectionIndex F => zeroOutsideInt σ.1) ⟶ F :=
  Sigma.desc (fun σ => zeroOutsideInt.sHom σ.2)

instance allSectionMap_epi {X : TopCat.{u}}
    (F : Sheaf AddCommGrpCat.{u} X)
    [HasCoproduct (fun σ : SectionIndex F => zeroOutsideInt σ.1)] :
    Epi (allSectionMap F) := by
  letI : Balanced (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}) :=
    balanced_of_strongEpiCategory
  rw [← Sheaf.isLocallySurjective_iff_epi' AddCommGrpCat]
  change TopCat.Presheaf.IsLocallySurjective (allSectionMap F).val
  rw [TopCat.Presheaf.isLocallySurjective_iff]
  intro U t x hx
  refine ⟨U, 𝟙 U, ?_, hx⟩
  refine ⟨(Sigma.ι (fun σ : SectionIndex F => zeroOutsideInt σ.1) ⟨U, t⟩).val.app
      (op U) (zeroOutsideInt.generator U), ?_⟩
  change (((Sigma.ι (fun σ : SectionIndex F => zeroOutsideInt σ.1) ⟨U, t⟩) ≫
      allSectionMap F).val.app (op U) (zeroOutsideInt.generator U)) =
    TopCat.Presheaf.restrict t (𝟙 U)
  rw [Sigma.ι_desc, zeroOutsideInt.sHom_app_generator]
  change t = TopCat.Presheaf.restrict t (𝟙 U)
  symm
  change F.presheaf.map (𝟙 (Opposite.op U)) t = t
  simp

end Sheaf

end TopCat
