import Aristotle.GrothendieckVanishing.main.ZeroOutside

/-!
  ZeroOutsideFinset.lean — Finset-generated subsheaf machinery

  Contains:
  - SectionIndex, finsetGeneratorMap, finsetGeneratedSheaf
  - allSectionMap: canonical epi from coproduct of all zeroOutsideInt
-/

universe u

open CategoryTheory TopologicalSpace Limits Opposite

noncomputable section

namespace TopCat

namespace Presheaf

/-- Indexing type for all local sections of a presheaf. -/
abbrev SectionIndex {C : Type*} [Category C] {FC : C → C → Type*} {CC : C → Type*}
    [∀ X Y, FunLike (FC X Y) (CC X) (CC Y)] [ConcreteCategory C FC] {X : TopCat.{u}}
    (F : TopCat.Presheaf C X) :=
  Σ U : Opens X, ToType (F.obj (op U))

/-- The canonical map attached to a finite set of local sections. -/
abbrev finsetGeneratorMap {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1] :
    (∐ fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1) ⟶
      (⟨F, hF⟩ : TopCat.Sheaf AddCommGrpCat.{u} X) :=
  TopCat.Sheaf.familyMap
    (fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1)
    (fun σ => Sheaf.Hom.mk (TopCat.Sheaf.zeroOutsideInt.sHomVal hF σ.1.2))

/-- The subsheaf of `F` generated by a finite set of local sections. -/
abbrev finsetGeneratedSheaf {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1] :
    TopCat.Sheaf AddCommGrpCat.{u} X :=
  TopCat.Sheaf.familyImage (F := (⟨F, hF⟩ : TopCat.Sheaf AddCommGrpCat.{u} X))
    (fun σ : {σ // σ ∈ S} => TopCat.Sheaf.zeroOutsideInt σ.1.1)
    (fun σ => Sheaf.Hom.mk (TopCat.Sheaf.zeroOutsideInt.sHomVal hF σ.1.2))

/-- The canonical map from the coproduct of all `zeroOutsideInt U` indexed by local sections
of `F` onto the sheaf associated to `F`. This is the formal Step 3A starting point for
building finitely generated subsheaves via images of smaller subcoproducts. -/
abbrev allSectionMap {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    [HasCoproduct (fun σ : SectionIndex F => TopCat.Sheaf.zeroOutsideInt σ.1)] :
    (∐ fun σ : SectionIndex F => TopCat.Sheaf.zeroOutsideInt σ.1) ⟶
      (⟨F, hF⟩ : TopCat.Sheaf AddCommGrpCat.{u} X) :=
  TopCat.Sheaf.familyMap
    (fun σ : SectionIndex F => TopCat.Sheaf.zeroOutsideInt σ.1)
    (fun σ => Sheaf.Hom.mk (TopCat.Sheaf.zeroOutsideInt.sHomVal hF σ.2))

instance allSectionMap_epi {X : TopCat.{u}}
    {F : TopCat.Presheaf AddCommGrpCat.{u} X} (hF : F.IsSheaf)
    [HasCoproduct (fun σ : SectionIndex F => TopCat.Sheaf.zeroOutsideInt σ.1)] :
    Epi (allSectionMap hF) := by
  letI : Balanced (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}) :=
    balanced_of_strongEpiCategory
  rw [← Sheaf.isLocallySurjective_iff_epi' AddCommGrpCat]
  change TopCat.Presheaf.IsLocallySurjective (allSectionMap hF).val
  rw [TopCat.Presheaf.isLocallySurjective_iff]
  intro U t x hx
  refine ⟨U, 𝟙 U, ?_, hx⟩
  refine ⟨(Sigma.ι (fun σ : SectionIndex F => TopCat.Sheaf.zeroOutsideInt σ.1) ⟨U, t⟩).val.app
      (op U) (TopCat.Sheaf.zeroOutsideInt.generator U), ?_⟩
  change (((Sigma.ι (fun σ : SectionIndex F => TopCat.Sheaf.zeroOutsideInt σ.1) ⟨U, t⟩) ≫
      allSectionMap hF).val.app (op U) (TopCat.Sheaf.zeroOutsideInt.generator U)) =
    TopCat.Presheaf.restrict t (𝟙 U)
  rw [Sigma.ι_desc]
  trans t
  · simpa using TopCat.Sheaf.zeroOutsideInt.sHomVal_app_generator (F := F) hF t
  · symm
    change F.map (𝟙 (Opposite.op U)) t = t
    simp

end Presheaf

namespace Sheaf

/-- Indexing type for all local sections of a sheaf. -/
abbrev SectionIndex {C : Type*} [Category C] {FC : C → C → Type*} {CC : C → Type*}
    [∀ X Y, FunLike (FC X Y) (CC X) (CC Y)] [ConcreteCategory C FC] {X : TopCat.{u}}
    (F : Sheaf C X) :=
  TopCat.Presheaf.SectionIndex F.presheaf

/-- The canonical map attached to a finite set of local sections. -/
abbrev finsetGeneratorMap {X : TopCat.{u}}
    {F : Sheaf AddCommGrpCat.{u} X}
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1] :
    (∐ fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1) ⟶ F :=
  TopCat.Presheaf.finsetGeneratorMap (F := F.presheaf) F.cond S

/-- The subsheaf of `F` generated by a finite set of local sections. -/
abbrev finsetGeneratedSheaf {X : TopCat.{u}}
    {F : Sheaf AddCommGrpCat.{u} X}
    (S : Finset (SectionIndex F))
    [HasCoproduct fun σ : {σ // σ ∈ S} => zeroOutsideInt σ.1.1] :
    Sheaf AddCommGrpCat.{u} X :=
  TopCat.Presheaf.finsetGeneratedSheaf (F := F.presheaf) F.cond S

/-- The canonical map from the coproduct of all `zeroOutsideInt U` indexed by local sections
of `F` onto `F`. This is the formal Step 3A starting point for building finitely generated
subsheaves via images of smaller subcoproducts. -/
abbrev allSectionMap {X : TopCat.{u}}
    (F : Sheaf AddCommGrpCat.{u} X)
    [HasCoproduct (fun σ : SectionIndex F => zeroOutsideInt σ.1)] :
    (∐ fun σ : SectionIndex F => zeroOutsideInt σ.1) ⟶ F :=
  TopCat.Presheaf.allSectionMap (F := F.presheaf) F.cond

instance allSectionMap_epi {X : TopCat.{u}}
    (F : Sheaf AddCommGrpCat.{u} X)
    [HasCoproduct (fun σ : SectionIndex F => zeroOutsideInt σ.1)] :
    Epi (allSectionMap F) := by
  change Epi (TopCat.Presheaf.allSectionMap (F := F.presheaf) F.cond)
  infer_instance

end Sheaf

end TopCat
