/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.AlternatingSixRewriteTransitions06

/-!
# Checked `A₆` transitions 180–209

This file is generated by `scripts/a6_rewrite_certificate.py`.  Lean independently checks
every proof path, so the generator is not part of the trusted base.
-/

namespace McKayConjecture
namespace GroupTheory

theorem alternatingSixRewriteTransitionRow180_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow180 180 = true := by
  decide

theorem alternatingSixRewriteTransitionRow181_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow181 181 = true := by
  decide

theorem alternatingSixRewriteTransitionRow182_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow182 182 = true := by
  decide

theorem alternatingSixRewriteTransitionRow183_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow183 183 = true := by
  decide

theorem alternatingSixRewriteTransitionRow184_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow184 184 = true := by
  decide

theorem alternatingSixRewriteTransitionRow185_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow185 185 = true := by
  decide

theorem alternatingSixRewriteTransitionRow186_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow186 186 = true := by
  decide

theorem alternatingSixRewriteTransitionRow187_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow187 187 = true := by
  decide

theorem alternatingSixRewriteTransitionRow188_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow188 188 = true := by
  decide

theorem alternatingSixRewriteTransitionRow189_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow189 189 = true := by
  decide

theorem alternatingSixRewriteTransitionRow190_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow190 190 = true := by
  decide

theorem alternatingSixRewriteTransitionRow191_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow191 191 = true := by
  decide

theorem alternatingSixRewriteTransitionRow192_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow192 192 = true := by
  decide

theorem alternatingSixRewriteTransitionRow193_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow193 193 = true := by
  decide

theorem alternatingSixRewriteTransitionRow194_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow194 194 = true := by
  decide

theorem alternatingSixRewriteTransitionRow195_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow195 195 = true := by
  decide

theorem alternatingSixRewriteTransitionRow196_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow196 196 = true := by
  decide

theorem alternatingSixRewriteTransitionRow197_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow197 197 = true := by
  decide

theorem alternatingSixRewriteTransitionRow198_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow198 198 = true := by
  decide

theorem alternatingSixRewriteTransitionRow199_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow199 199 = true := by
  decide

theorem alternatingSixRewriteTransitionRow200_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow200 200 = true := by
  decide

theorem alternatingSixRewriteTransitionRow201_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow201 201 = true := by
  decide

theorem alternatingSixRewriteTransitionRow202_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow202 202 = true := by
  decide

theorem alternatingSixRewriteTransitionRow203_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow203 203 = true := by
  decide

theorem alternatingSixRewriteTransitionRow204_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow204 204 = true := by
  decide

theorem alternatingSixRewriteTransitionRow205_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow205 205 = true := by
  decide

theorem alternatingSixRewriteTransitionRow206_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow206 206 = true := by
  decide

theorem alternatingSixRewriteTransitionRow207_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow207 207 = true := by
  decide

theorem alternatingSixRewriteTransitionRow208_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow208 208 = true := by
  decide

theorem alternatingSixRewriteTransitionRow209_valid :
    AlternatingSixRewriteTransition.Valid
      alternatingSixRewriteRules
      alternatingSixRewriteNormalWords
      alternatingSixRewriteTransitionRow209 209 = true := by
  decide


end GroupTheory
end McKayConjecture
