/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.AlternatingSixRewriteCertificateData

/-!
# Generated `A₆` transitions, rows 60–89

This file is generated by `scripts/a6_rewrite_certificate.py`.  Lean independently checks
every proof path, so the generator is not part of the trusted base.
-/

namespace McKayConjecture
namespace GroupTheory

set_option linter.style.longLine false

/-- Right-multiplication row 60. -/
def alternatingSixRewriteTransitionRow060 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨38, [⟨[(1, true), (0, true), (1, true), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨38, [⟨[(1, true), (0, true), (1, true), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨90, []⟩,
    ⟨91, []⟩
  ]

/-- Right-multiplication row 61. -/
def alternatingSixRewriteTransitionRow061 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨92, []⟩,
    ⟨92, [⟨[(1, true), (0, true), (1, true), (1, true), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨93, []⟩,
    ⟨39, [⟨[(1, true), (0, true), (1, true), (1, true), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 62. -/
def alternatingSixRewriteTransitionRow062 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨94, []⟩,
    ⟨94, [⟨[(1, true), (0, true), (1, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨39, [⟨[(1, true), (0, true), (1, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨93, [⟨[(1, true), (0, true), (1, true), (1, true), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 63. -/
def alternatingSixRewriteTransitionRow063 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨40, [⟨[(1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨40, [⟨[(1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨95, []⟩,
    ⟨96, []⟩
  ]

/-- Right-multiplication row 64. -/
def alternatingSixRewriteTransitionRow064 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨97, []⟩,
    ⟨97, [⟨[(1, true), (0, true), (1, false), (0, true), (1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨41, [⟨[(1, true), (0, true), (1, false), (0, true)], [], .rule, 13, true⟩]⟩,
    ⟨40, [⟨[(1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 65. -/
def alternatingSixRewriteTransitionRow065 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨41, [⟨[(1, true), (0, true), (1, false), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨41, [⟨[(1, true), (0, true), (1, false), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨98, []⟩,
    ⟨42, [⟨[(1, true)], [], .rule, 37, true⟩]⟩
  ]

/-- Right-multiplication row 66. -/
def alternatingSixRewriteTransitionRow066 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨99, []⟩,
    ⟨99, [⟨[(1, true), (1, true), (0, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨42, [⟨[(1, true), (1, true), (0, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨98, [⟨[(1, true), (1, true), (0, true), (1, true), (0, true)], [], .rule, 25, true⟩, ⟨[(1, true)], [(1, true)], .rule, 31, true⟩]⟩
  ]

/-- Right-multiplication row 67. -/
def alternatingSixRewriteTransitionRow067 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨43, [⟨[(1, true), (1, true), (0, true), (1, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨43, [⟨[(1, true), (1, true), (0, true), (1, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨100, []⟩,
    ⟨101, []⟩
  ]

/-- Right-multiplication row 68. -/
def alternatingSixRewriteTransitionRow068 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨102, []⟩,
    ⟨102, [⟨[(1, true), (1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨103, []⟩,
    ⟨44, [⟨[(1, true), (1, true), (0, true), (1, false), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 69. -/
def alternatingSixRewriteTransitionRow069 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨45, [⟨[], [], .rule, 54, true⟩]⟩,
    ⟨45, [⟨[(1, true), (1, true), (0, true), (1, false), (0, true), (1, false)], [], .rule, 12, true⟩, ⟨[], [], .rule, 54, true⟩]⟩,
    ⟨44, [⟨[(1, true), (1, true), (0, true), (1, false), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨103, [⟨[(1, true), (1, true), (0, true), (1, false), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 70. -/
def alternatingSixRewriteTransitionRow070 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨104, []⟩,
    ⟨104, [⟨[(1, false), (0, true), (1, true), (0, true), (1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨46, [⟨[(1, false), (0, true), (1, true), (0, true)], [], .rule, 13, true⟩]⟩,
    ⟨45, [⟨[(1, false), (0, true), (1, true), (0, true), (1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 71. -/
def alternatingSixRewriteTransitionRow071 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨46, [⟨[(1, false), (0, true), (1, true), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨46, [⟨[(1, false), (0, true), (1, true), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨105, []⟩,
    ⟨106, []⟩
  ]

/-- Right-multiplication row 72. -/
def alternatingSixRewriteTransitionRow072 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨107, []⟩,
    ⟨107, [⟨[(1, false), (0, true), (1, true), (1, true), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨108, []⟩,
    ⟨47, [⟨[(1, false), (0, true), (1, true), (1, true), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 73. -/
def alternatingSixRewriteTransitionRow073 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨109, []⟩,
    ⟨109, [⟨[(1, false), (0, true), (1, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨47, [⟨[(1, false), (0, true), (1, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨108, [⟨[(1, false), (0, true), (1, true), (1, true), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 74. -/
def alternatingSixRewriteTransitionRow074 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨48, [⟨[(1, false), (0, true), (1, false), (0, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨48, [⟨[(1, false), (0, true), (1, false), (0, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨110, []⟩,
    ⟨111, []⟩
  ]

/-- Right-multiplication row 75. -/
def alternatingSixRewriteTransitionRow075 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨49, [⟨[(0, true), (1, true), (0, true), (1, true), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨49, [⟨[(0, true), (1, true), (0, true), (1, true), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨112, []⟩,
    ⟨113, []⟩
  ]

/-- Right-multiplication row 76. -/
def alternatingSixRewriteTransitionRow076 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨114, []⟩,
    ⟨114, [⟨[(0, true), (1, true), (0, true), (1, true), (1, true), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨115, []⟩,
    ⟨50, [⟨[(0, true), (1, true), (0, true), (1, true), (1, true), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 77. -/
def alternatingSixRewriteTransitionRow077 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨116, []⟩,
    ⟨116, [⟨[(0, true), (1, true), (0, true), (1, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨50, [⟨[(0, true), (1, true), (0, true), (1, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨115, [⟨[(0, true), (1, true), (0, true), (1, true), (1, true), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 78. -/
def alternatingSixRewriteTransitionRow078 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨51, [⟨[(0, true), (1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨51, [⟨[(0, true), (1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨117, []⟩,
    ⟨118, []⟩
  ]

/-- Right-multiplication row 79. -/
def alternatingSixRewriteTransitionRow079 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨119, []⟩,
    ⟨119, [⟨[(0, true), (1, true), (0, true), (1, false), (0, true), (1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨52, [⟨[(0, true), (1, true), (0, true), (1, false), (0, true)], [], .rule, 13, true⟩]⟩,
    ⟨51, [⟨[(0, true), (1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 80. -/
def alternatingSixRewriteTransitionRow080 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨52, [⟨[(0, true), (1, true), (0, true), (1, false), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨52, [⟨[(0, true), (1, true), (0, true), (1, false), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨120, []⟩,
    ⟨53, [⟨[(0, true), (1, true)], [], .rule, 37, true⟩]⟩
  ]

/-- Right-multiplication row 81. -/
def alternatingSixRewriteTransitionRow081 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨121, []⟩,
    ⟨121, [⟨[(0, true), (1, true), (1, true), (0, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨53, [⟨[(0, true), (1, true), (1, true), (0, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨120, [⟨[(0, true), (1, true), (1, true), (0, true), (1, true), (0, true)], [], .rule, 25, true⟩, ⟨[(0, true), (1, true)], [(1, true)], .rule, 31, true⟩]⟩
  ]

/-- Right-multiplication row 82. -/
def alternatingSixRewriteTransitionRow082 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨54, [⟨[(0, true), (1, true), (1, true), (0, true), (1, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨54, [⟨[(0, true), (1, true), (1, true), (0, true), (1, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨101, [⟨[], [], .rule, 43, true⟩]⟩,
    ⟨100, [⟨[], [], .rule, 49, true⟩]⟩
  ]

/-- Right-multiplication row 83. -/
def alternatingSixRewriteTransitionRow083 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨122, []⟩,
    ⟨122, [⟨[(0, true), (1, true), (1, true), (0, true), (1, false), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨123, []⟩,
    ⟨55, [⟨[(0, true), (1, true), (1, true), (0, true), (1, false), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 84. -/
def alternatingSixRewriteTransitionRow084 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨56, [⟨[(0, true)], [], .rule, 54, true⟩]⟩,
    ⟨56, [⟨[(0, true), (1, true), (1, true), (0, true), (1, false), (0, true), (1, false)], [], .rule, 12, true⟩, ⟨[(0, true)], [], .rule, 54, true⟩]⟩,
    ⟨55, [⟨[(0, true), (1, true), (1, true), (0, true), (1, false), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨123, [⟨[(0, true), (1, true), (1, true), (0, true), (1, false), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 85. -/
def alternatingSixRewriteTransitionRow085 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨124, []⟩,
    ⟨124, [⟨[(0, true), (1, false), (0, true), (1, true), (0, true), (1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨57, [⟨[(0, true), (1, false), (0, true), (1, true), (0, true)], [], .rule, 13, true⟩]⟩,
    ⟨56, [⟨[(0, true), (1, false), (0, true), (1, true), (0, true), (1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 86. -/
def alternatingSixRewriteTransitionRow086 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨57, [⟨[(0, true), (1, false), (0, true), (1, true), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨57, [⟨[(0, true), (1, false), (0, true), (1, true), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨125, []⟩,
    ⟨126, []⟩
  ]

/-- Right-multiplication row 87. -/
def alternatingSixRewriteTransitionRow087 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨127, []⟩,
    ⟨127, [⟨[(0, true), (1, false), (0, true), (1, true), (1, true), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨128, []⟩,
    ⟨58, [⟨[(0, true), (1, false), (0, true), (1, true), (1, true), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 88. -/
def alternatingSixRewriteTransitionRow088 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨129, []⟩,
    ⟨129, [⟨[(0, true), (1, false), (0, true), (1, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨58, [⟨[(0, true), (1, false), (0, true), (1, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨128, [⟨[(0, true), (1, false), (0, true), (1, true), (1, true), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 89. -/
def alternatingSixRewriteTransitionRow089 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨59, [⟨[(0, true), (1, false), (0, true), (1, false), (0, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨59, [⟨[(0, true), (1, false), (0, true), (1, false), (0, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨130, []⟩,
    ⟨131, []⟩
  ]


end GroupTheory
end McKayConjecture
