/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.AlternatingSixRewriteCertificateData

/-!
# Checked `A₆` rewrite rules 40–59

This file is generated by `scripts/a6_rewrite_certificate.py`.  Lean independently checks
every proof path, so the generator is not part of the trusted base.
-/

namespace McKayConjecture
namespace GroupTheory

theorem alternatingSixRewriteRule040_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 40 = true := by
  decide

theorem alternatingSixRewriteRule041_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 41 = true := by
  decide

theorem alternatingSixRewriteRule042_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 42 = true := by
  decide

theorem alternatingSixRewriteRule043_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 43 = true := by
  decide

theorem alternatingSixRewriteRule044_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 44 = true := by
  decide

theorem alternatingSixRewriteRule045_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 45 = true := by
  decide

theorem alternatingSixRewriteRule046_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 46 = true := by
  decide

theorem alternatingSixRewriteRule047_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 47 = true := by
  decide

theorem alternatingSixRewriteRule048_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 48 = true := by
  decide

theorem alternatingSixRewriteRule049_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 49 = true := by
  decide

theorem alternatingSixRewriteRule050_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 50 = true := by
  decide

theorem alternatingSixRewriteRule051_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 51 = true := by
  decide

theorem alternatingSixRewriteRule052_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 52 = true := by
  decide

theorem alternatingSixRewriteRule053_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 53 = true := by
  decide

theorem alternatingSixRewriteRule054_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 54 = true := by
  decide

theorem alternatingSixRewriteRule055_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 55 = true := by
  decide

theorem alternatingSixRewriteRule056_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 56 = true := by
  decide

theorem alternatingSixRewriteRule057_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 57 = true := by
  decide

theorem alternatingSixRewriteRule058_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 58 = true := by
  decide

theorem alternatingSixRewriteRule059_valid :
    AlternatingSixRewriteRule.Valid alternatingSixRewriteRules 59 = true := by
  decide


end GroupTheory
end McKayConjecture
