/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.AlternatingSixRewriteCertificateData

/-!
# Generated `A₆` transitions, rows 0–29

This file is generated by `scripts/a6_rewrite_certificate.py`.  Lean independently checks
every proof path, so the generator is not part of the trusted base.
-/

namespace McKayConjecture
namespace GroupTheory

set_option linter.style.longLine false

/-- Right-multiplication row 0. -/
def alternatingSixRewriteTransitionRow000 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨1, []⟩,
    ⟨1, [⟨[], [], .rule, 12, true⟩]⟩,
    ⟨2, []⟩,
    ⟨3, []⟩
  ]

/-- Right-multiplication row 1. -/
def alternatingSixRewriteTransitionRow001 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨0, [⟨[], [], .rule, 4, true⟩]⟩,
    ⟨0, [⟨[], [], .rule, 0, true⟩]⟩,
    ⟨4, []⟩,
    ⟨5, []⟩
  ]

/-- Right-multiplication row 2. -/
def alternatingSixRewriteTransitionRow002 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨6, []⟩,
    ⟨6, [⟨[(1, true)], [], .rule, 12, true⟩]⟩,
    ⟨7, []⟩,
    ⟨0, [⟨[], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 3. -/
def alternatingSixRewriteTransitionRow003 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨8, []⟩,
    ⟨8, [⟨[(1, false)], [], .rule, 12, true⟩]⟩,
    ⟨0, [⟨[], [], .rule, 3, true⟩]⟩,
    ⟨7, [⟨[], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 4. -/
def alternatingSixRewriteTransitionRow004 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨9, []⟩,
    ⟨9, [⟨[(0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨10, []⟩,
    ⟨1, [⟨[(0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 5. -/
def alternatingSixRewriteTransitionRow005 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨11, []⟩,
    ⟨11, [⟨[(0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨1, [⟨[(0, true)], [], .rule, 3, true⟩]⟩,
    ⟨10, [⟨[(0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 6. -/
def alternatingSixRewriteTransitionRow006 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨2, [⟨[(1, true)], [], .rule, 4, true⟩]⟩,
    ⟨2, [⟨[(1, true)], [], .rule, 0, true⟩]⟩,
    ⟨12, []⟩,
    ⟨13, []⟩
  ]

/-- Right-multiplication row 7. -/
def alternatingSixRewriteTransitionRow007 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨14, []⟩,
    ⟨14, [⟨[(1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨3, [⟨[], [], .rule, 13, true⟩]⟩,
    ⟨2, [⟨[(1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 8. -/
def alternatingSixRewriteTransitionRow008 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨3, [⟨[(1, false)], [], .rule, 4, true⟩]⟩,
    ⟨3, [⟨[(1, false)], [], .rule, 0, true⟩]⟩,
    ⟨15, []⟩,
    ⟨16, []⟩
  ]

/-- Right-multiplication row 9. -/
def alternatingSixRewriteTransitionRow009 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨4, [⟨[(0, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨4, [⟨[(0, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨17, []⟩,
    ⟨18, []⟩
  ]

/-- Right-multiplication row 10. -/
def alternatingSixRewriteTransitionRow010 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨19, []⟩,
    ⟨19, [⟨[(0, true), (1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨5, [⟨[(0, true)], [], .rule, 13, true⟩]⟩,
    ⟨4, [⟨[(0, true), (1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 11. -/
def alternatingSixRewriteTransitionRow011 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨5, [⟨[(0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨5, [⟨[(0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨20, []⟩,
    ⟨21, []⟩
  ]

/-- Right-multiplication row 12. -/
def alternatingSixRewriteTransitionRow012 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨22, []⟩,
    ⟨22, [⟨[(1, true), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨23, []⟩,
    ⟨6, [⟨[(1, true), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 13. -/
def alternatingSixRewriteTransitionRow013 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨24, []⟩,
    ⟨24, [⟨[(1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨6, [⟨[(1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨23, [⟨[(1, true), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 14. -/
def alternatingSixRewriteTransitionRow014 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨7, [⟨[(1, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨7, [⟨[(1, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨25, []⟩,
    ⟨26, []⟩
  ]

/-- Right-multiplication row 15. -/
def alternatingSixRewriteTransitionRow015 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨27, []⟩,
    ⟨27, [⟨[(1, false), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨28, []⟩,
    ⟨8, [⟨[(1, false), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 16. -/
def alternatingSixRewriteTransitionRow016 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨29, []⟩,
    ⟨29, [⟨[(1, false), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨8, [⟨[(1, false), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨28, [⟨[(1, false), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 17. -/
def alternatingSixRewriteTransitionRow017 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨30, []⟩,
    ⟨30, [⟨[(0, true), (1, true), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨31, []⟩,
    ⟨9, [⟨[(0, true), (1, true), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 18. -/
def alternatingSixRewriteTransitionRow018 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨32, []⟩,
    ⟨32, [⟨[(0, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨9, [⟨[(0, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨31, [⟨[(0, true), (1, true), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 19. -/
def alternatingSixRewriteTransitionRow019 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨10, [⟨[(0, true), (1, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨10, [⟨[(0, true), (1, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨33, []⟩,
    ⟨34, []⟩
  ]

/-- Right-multiplication row 20. -/
def alternatingSixRewriteTransitionRow020 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨35, []⟩,
    ⟨35, [⟨[(0, true), (1, false), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨36, []⟩,
    ⟨11, [⟨[(0, true), (1, false), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 21. -/
def alternatingSixRewriteTransitionRow021 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨37, []⟩,
    ⟨37, [⟨[(0, true), (1, false), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨11, [⟨[(0, true), (1, false), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨36, [⟨[(0, true), (1, false), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 22. -/
def alternatingSixRewriteTransitionRow022 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨12, [⟨[(1, true), (0, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨12, [⟨[(1, true), (0, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨37, [⟨[], [], .rule, 31, true⟩]⟩,
    ⟨38, []⟩
  ]

/-- Right-multiplication row 23. -/
def alternatingSixRewriteTransitionRow023 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨39, []⟩,
    ⟨39, [⟨[(1, true), (0, true), (1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨13, [⟨[(1, true), (0, true)], [], .rule, 13, true⟩]⟩,
    ⟨12, [⟨[(1, true), (0, true), (1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 24. -/
def alternatingSixRewriteTransitionRow024 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨13, [⟨[(1, true), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨13, [⟨[(1, true), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨40, []⟩,
    ⟨41, []⟩
  ]

/-- Right-multiplication row 25. -/
def alternatingSixRewriteTransitionRow025 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨42, []⟩,
    ⟨42, [⟨[(1, true), (1, true), (0, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨43, []⟩,
    ⟨14, [⟨[(1, true), (1, true), (0, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 26. -/
def alternatingSixRewriteTransitionRow026 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨44, []⟩,
    ⟨44, [⟨[(1, true), (1, true), (0, true), (1, false)], [], .rule, 12, true⟩]⟩,
    ⟨14, [⟨[(1, true), (1, true), (0, true)], [], .rule, 3, true⟩]⟩,
    ⟨43, [⟨[(1, true), (1, true), (0, true)], [], .rule, 25, true⟩]⟩
  ]

/-- Right-multiplication row 27. -/
def alternatingSixRewriteTransitionRow027 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨15, [⟨[(1, false), (0, true), (1, true)], [], .rule, 4, true⟩]⟩,
    ⟨15, [⟨[(1, false), (0, true), (1, true)], [], .rule, 0, true⟩]⟩,
    ⟨45, []⟩,
    ⟨46, []⟩
  ]

/-- Right-multiplication row 28. -/
def alternatingSixRewriteTransitionRow028 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨47, []⟩,
    ⟨47, [⟨[(1, false), (0, true), (1, true), (1, true)], [], .rule, 12, true⟩]⟩,
    ⟨16, [⟨[(1, false), (0, true)], [], .rule, 13, true⟩]⟩,
    ⟨15, [⟨[(1, false), (0, true), (1, true)], [], .rule, 2, true⟩]⟩
  ]

/-- Right-multiplication row 29. -/
def alternatingSixRewriteTransitionRow029 :
    Fin 4 → AlternatingSixRewriteTransition :=
  ![
    ⟨16, [⟨[(1, false), (0, true), (1, false)], [], .rule, 4, true⟩]⟩,
    ⟨16, [⟨[(1, false), (0, true), (1, false)], [], .rule, 0, true⟩]⟩,
    ⟨48, []⟩,
    ⟨30, [⟨[], [], .rule, 51, true⟩]⟩
  ]


end GroupTheory
end McKayConjecture
