/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.AlternatingSixPresentation

/-!
# Generation of `A₆` by its standard presentation generators

The concrete permutations in `AlternatingSixPresentation` generate `A₆`.
The small certificate in this file gives, for each ordered pair of nonzero
points, a word for the corresponding three-cycle through `0`.  Elementary
identities then express every three-cycle in terms of those certified words.

This is intentionally separate from the eventual normal-form certificate for
the abstract presented group: it establishes surjectivity of the presentation
map without assuming an order bound for that group.
-/

noncomputable section

namespace McKayConjecture
namespace GroupTheory

open Equiv

/-- The subgroup of `S₆` generated by the two concrete standard generators. -/
def alternatingSixPermutationGeneratorSubgroup :
    Subgroup (Equiv.Perm (Fin 6)) :=
  Subgroup.closure
    {alternatingSixPresentationPermA, alternatingSixPresentationPermB}

/-- Decode one letter in a short generation certificate.

The letters `a`, `b`, and `B` denote `a`, `b`, and `b⁻¹`, respectively.
Any other character is harmlessly decoded as the identity. -/
def alternatingSixGenerationLetter
    (c : Char) :
    Equiv.Perm (Fin 6) :=
  if c = 'a' then alternatingSixPresentationPermA
  else if c = 'b' then alternatingSixPresentationPermB
  else if c = 'B' then alternatingSixPresentationPermB⁻¹
  else 1

/-- Evaluate a short certificate word in the concrete permutations. -/
def alternatingSixEvaluateGenerationWord
    (w : String) :
    Equiv.Perm (Fin 6) :=
  (w.toList.map alternatingSixGenerationLetter).prod

/-- Every decoded certificate word lies in the generated subgroup. -/
theorem alternatingSixEvaluateGenerationWord_mem
    (w : String) :
    alternatingSixEvaluateGenerationWord w ∈
      alternatingSixPermutationGeneratorSubgroup := by
  apply Subgroup.list_prod_mem
  intro g hg
  simp only [List.mem_map] at hg
  obtain ⟨c, _, rfl⟩ := hg
  by_cases ha : c = 'a'
  · simp only [alternatingSixGenerationLetter, ha, if_pos]
    exact Subgroup.subset_closure (by simp)
  by_cases hb : c = 'b'
  · simp only [alternatingSixGenerationLetter, hb, if_pos]
    exact Subgroup.subset_closure (by simp)
  by_cases hB : c = 'B'
  · simp only [alternatingSixGenerationLetter, hB, if_pos]
    exact
      (alternatingSixPermutationGeneratorSubgroup.inv_mem
        (Subgroup.subset_closure (by simp)))
  · simp only [alternatingSixGenerationLetter, ha, hb, hB, if_false]
    exact alternatingSixPermutationGeneratorSubgroup.one_mem

/-- A compact word table for all ordered three-cycles through `0`.

Rows and columns are indexed by `Fin 5`; the actual points are their successors
in `Fin 6`.  The diagonal entries evaluate to the identity. -/
def alternatingSixStarCycleWord :
    Fin 5 → Fin 5 → String
  | 0, 0 => ""
  | 0, 1 => "babbabaBaba"
  | 0, 2 => "BabaBabbaBa"
  | 0, 3 => "abbabaBabab"
  | 0, 4 => "bbabaBabba"
  | 1, 0 => "aBabaBabbaB"
  | 1, 1 => ""
  | 1, 2 => "ababbabaBaba"
  | 1, 3 => "ababbaBaB"
  | 1, 4 => "bbaBaba"
  | 2, 0 => "ababbabaBab"
  | 2, 1 => "aBabaBabbaBa"
  | 2, 2 => ""
  | 2, 3 => "aBababbaB"
  | 2, 4 => "baBaBabab"
  | 3, 0 => "baBaBabaBaB"
  | 3, 1 => "aBaBabaBa"
  | 3, 2 => "babbaBaba"
  | 3, 3 => ""
  | 3, 4 => "ababaBaBabaB"
  | 4, 0 => "abbabaBabb"
  | 4, 1 => "aBababb"
  | 4, 2 => "BabbaBabb"
  | 4, 3 => "babbaBabbaBa"
  | 4, 4 => ""

/-- The word table evaluates to the claimed product of two swaps. -/
theorem alternatingSixStarCycleWord_valid
    (i j : Fin 5) :
    alternatingSixEvaluateGenerationWord
        (alternatingSixStarCycleWord i j) =
      Equiv.swap (0 : Fin 6) i.succ *
        Equiv.swap (0 : Fin 6) j.succ := by
  fin_cases i <;> fin_cases j <;> decide

/-- Every ordered three-cycle through `0` belongs to the generated subgroup. -/
theorem alternatingSixStarCycle_mem
    (i j : Fin 5) :
    Equiv.swap (0 : Fin 6) i.succ *
        Equiv.swap (0 : Fin 6) j.succ ∈
      alternatingSixPermutationGeneratorSubgroup := by
  rw [← alternatingSixStarCycleWord_valid i j]
  exact alternatingSixEvaluateGenerationWord_mem _

/-- Every three-cycle of six points belongs to the subgroup generated by the
standard generators. -/
theorem alternatingSix_isThreeCycle_mem_generatorSubgroup
    (g : Equiv.Perm (Fin 6))
    (hg : g.IsThreeCycle) :
    g ∈ alternatingSixPermutationGeneratorSubgroup := by
  obtain ⟨a, ha⟩ := hg.isCycle.nonempty_support
  have hword :
      g =
        Equiv.swap a (g a) *
          Equiv.swap (g a) (g (g a)) :=
    hg.eq_swap_mul_swap_iff_mem_support.mpr ha
  have hnodup :
      [a, g a, g (g a)].Nodup :=
    hg.nodup_iff_mem_support.mpr ha
  have hab : a ≠ g a := by
    grind
  have hac : a ≠ g (g a) := by
    grind
  have hbc : g a ≠ g (g a) := by
    grind
  by_cases ha0 : a = 0
  · subst a
    have hb0 : g 0 ≠ 0 := by
      exact Ne.symm hab
    have hc0 : g (g 0) ≠ 0 := by
      exact Ne.symm hac
    let b : Fin 5 := (g 0).pred hb0
    let c : Fin 5 := (g (g 0)).pred hc0
    have hb : b.succ = g 0 := Fin.succ_pred _ hb0
    have hc : c.succ = g (g 0) := Fin.succ_pred _ hc0
    have hswap :
        Equiv.swap (g 0) (g (g 0)) =
          Equiv.swap (0 : Fin 6) (g 0) *
            Equiv.swap (0 : Fin 6) (g (g 0)) *
              Equiv.swap (0 : Fin 6) (g 0) := by
      rw [← Equiv.swap_comm (g (g 0)) 0]
      exact
        (Equiv.swap_mul_swap_mul_swap
          (x := g (g 0)) (y := 0) (z := g 0)
          hc0 hbc.symm).symm
    rw [hword, hswap, ← hc, ← hb]
    simpa [mul_assoc] using alternatingSixStarCycle_mem c b
  by_cases hb0 : g a = 0
  · have hc0 : g (g a) ≠ 0 := by
      exact fun h => hbc (hb0.trans h.symm)
    let i : Fin 5 := a.pred ha0
    let k : Fin 5 := (g (g a)).pred hc0
    have hi : i.succ = a := Fin.succ_pred _ ha0
    have hk : k.succ = g (g a) := Fin.succ_pred _ hc0
    rw [hword, hb0, Equiv.swap_comm a 0]
    simpa only [hi, hk, hb0] using
      alternatingSixStarCycle_mem i k
  by_cases hc0 : g (g a) = 0
  · let i : Fin 5 := a.pred ha0
    let j : Fin 5 := (g a).pred hb0
    have hi : i.succ = a := Fin.succ_pred _ ha0
    have hj : j.succ = g a := Fin.succ_pred _ hb0
    have hswap :
        Equiv.swap a (g a) =
          Equiv.swap (0 : Fin 6) a *
            Equiv.swap (0 : Fin 6) (g a) *
              Equiv.swap (0 : Fin 6) a := by
      rw [← Equiv.swap_comm (g a) 0]
      exact
        (Equiv.swap_mul_swap_mul_swap
          (x := g a) (y := 0) (z := a)
          hb0 hab.symm).symm
    rw [hword, hc0, Equiv.swap_comm (g a) 0, hswap]
    simpa [hi, hj, pow_two, mul_assoc] using
      alternatingSixPermutationGeneratorSubgroup.pow_mem
        (alternatingSixStarCycle_mem i j) 2
  · let i : Fin 5 := a.pred ha0
    let j : Fin 5 := (g a).pred hb0
    let k : Fin 5 := (g (g a)).pred hc0
    have hi : i.succ = a := Fin.succ_pred _ ha0
    have hj : j.succ = g a := Fin.succ_pred _ hb0
    have hk : k.succ = g (g a) := Fin.succ_pred _ hc0
    have hswapAB :
        Equiv.swap a (g a) =
          Equiv.swap (0 : Fin 6) a *
            Equiv.swap (0 : Fin 6) (g a) *
              Equiv.swap (0 : Fin 6) a := by
      rw [← Equiv.swap_comm (g a) 0]
      exact
        (Equiv.swap_mul_swap_mul_swap
          (x := g a) (y := 0) (z := a)
          hb0 hab.symm).symm
    have hswapBC :
        Equiv.swap (g a) (g (g a)) =
          Equiv.swap (0 : Fin 6) (g a) *
            Equiv.swap (0 : Fin 6) (g (g a)) *
              Equiv.swap (0 : Fin 6) (g a) := by
      rw [← Equiv.swap_comm (g (g a)) 0]
      exact
        (Equiv.swap_mul_swap_mul_swap
          (x := g (g a)) (y := 0) (z := g a)
          hc0 hbc.symm).symm
    rw [hword, hswapAB, hswapBC]
    simpa [hi, hj, hk, pow_two, mul_assoc] using
      alternatingSixPermutationGeneratorSubgroup.mul_mem
        (alternatingSixPermutationGeneratorSubgroup.pow_mem
          (alternatingSixStarCycle_mem i j) 2)
        (alternatingSixStarCycle_mem k j)

/-- The two standard concrete permutations generate the alternating subgroup
of `S₆`. -/
theorem alternatingSixPermutationGeneratorSubgroup_eq_alternatingGroup :
    alternatingSixPermutationGeneratorSubgroup =
      alternatingGroup (Fin 6) := by
  apply le_antisymm
  · rw [alternatingSixPermutationGeneratorSubgroup, Subgroup.closure_le]
    intro g hg
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    rcases hg with rfl | rfl
    · exact alternatingSixPresentationA.2
    · exact alternatingSixPresentationB.2
  · rw [← Equiv.Perm.closure_three_cycles_eq_alternating,
      Subgroup.closure_le]
    exact alternatingSix_isThreeCycle_mem_generatorSubgroup

/-- The two standard elements generate `A₆` as an abstract subgroup. -/
theorem alternatingSixGeneratorSubgroup_eq_top :
    Subgroup.closure
        ({alternatingSixPresentationA, alternatingSixPresentationB} :
          Set AlternatingSix) =
      ⊤ := by
  rw [← Subgroup.map_subtype_inj, MonoidHom.map_closure]
  have himage :
      (alternatingGroup (Fin 6)).subtype ''
          ({alternatingSixPresentationA, alternatingSixPresentationB} :
            Set AlternatingSix) =
        ({alternatingSixPresentationPermA,
          alternatingSixPresentationPermB} :
            Set (Equiv.Perm (Fin 6))) := by
    ext g
    simp [alternatingSixPresentationA, alternatingSixPresentationB, eq_comm]
  rw [himage]
  rw [← MonoidHom.range_eq_map, Subgroup.range_subtype]
  simpa [alternatingSixPermutationGeneratorSubgroup] using
    alternatingSixPermutationGeneratorSubgroup_eq_alternatingGroup

/-- The standard presentation map is onto `A₆`. -/
theorem alternatingSixPresentationToAlternatingSix_surjective :
    Function.Surjective
      alternatingSixPresentationToAlternatingSix := by
  rw [← MonoidHom.range_eq_top]
  apply top_unique
  rw [← alternatingSixGeneratorSubgroup_eq_top, Subgroup.closure_le]
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl
  · exact
      ⟨alternatingSixPresentedA,
        alternatingSixPresentationToAlternatingSix_a⟩
  · exact
      ⟨alternatingSixPresentedB,
        alternatingSixPresentationToAlternatingSix_b⟩

end GroupTheory
end McKayConjecture
