/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.AlternatingSixUniversalCoverTwoCentralizer

/-!
# The two-local normalizer as a central product in `6.A₆`

The exact two-local calculations identify the normalizer of the fixed
Sylow `2`-subgroup in the canonical universal cover.  It is generated by
that Sylow subgroup and the ambient order-six center.  Equivalently, every
automorphism of the Sylow subgroup induced by its ambient normalizer is
already inner.

These statements are useful when organizing the remaining character-table
calculation: the local group has no unidentified group-theoretic extension
left in it.
-/

noncomputable section

namespace McKayConjecture
namespace GroupTheory

local instance alternatingSixUniversalCoverTwoNormalizerProductFactPrime :
    Fact (Nat.Prime 2) :=
  ⟨Nat.prime_two⟩

/-- The ambient center has relative index eight in the fixed Sylow
`2`-subgroup.  The intersection is the intrinsic order-two center of the
generalized-quaternion Sylow subgroup. -/
theorem relIndex_center_alternatingSixUniversalCover_sylowTwo :
    (Subgroup.center AlternatingSixUniversalCover).relIndex
        (alternatingSixUniversalCoverSylow 2 :
          Subgroup AlternatingSixUniversalCover) =
      8 := by
  let Z :=
    Subgroup.center AlternatingSixUniversalCover
  let P :=
    (alternatingSixUniversalCoverSylow 2 :
      Subgroup AlternatingSixUniversalCover)
  have hcard :=
    (Z.subgroupOf P).card_mul_index
  change
    Nat.card (Z.subgroupOf P) *
        Z.relIndex P =
      Nat.card P
    at hcard
  have hintersection :
      Nat.card (Z.subgroupOf P) = 2 := by
    change
      Nat.card
          ((Subgroup.center AlternatingSixUniversalCover).subgroupOf
            (alternatingSixUniversalCoverSylow 2)) =
        2
    exact
      natCard_center_subgroupOf_alternatingSixUniversalCoverSylowTwo
  have hP : Nat.card P = 16 := by
    change
      Nat.card (alternatingSixUniversalCoverSylow 2) = 16
    exact
      natCard_alternatingSixUniversalCoverSylowTwo_exact
  change Z.relIndex P = 8
  rw [hintersection, hP] at hcard
  omega

/-- Adjoining the ambient center to the fixed Sylow `2`-subgroup gives a
subgroup of order forty-eight. -/
@[simp]
theorem natCard_alternatingSixUniversalCoverSylowTwo_sup_center :
    Nat.card
        (((alternatingSixUniversalCoverSylow 2 :
              Subgroup AlternatingSixUniversalCover) ⊔
            Subgroup.center AlternatingSixUniversalCover) :
          Subgroup AlternatingSixUniversalCover) =
      48 := by
  let Z :=
    Subgroup.center AlternatingSixUniversalCover
  let P :=
    (alternatingSixUniversalCoverSylow 2 :
      Subgroup AlternatingSixUniversalCover)
  have hcard :=
    (Z.subgroupOf (P ⊔ Z)).card_mul_index
  change
    Nat.card (Z.subgroupOf (P ⊔ Z)) *
        Z.relIndex (P ⊔ Z) =
      Nat.card (P ⊔ Z : Subgroup AlternatingSixUniversalCover)
    at hcard
  have hcenter :
      Nat.card (Z.subgroupOf (P ⊔ Z)) = 6 := by
    calc
      Nat.card (Z.subgroupOf (P ⊔ Z)) =
          Nat.card Z :=
        Nat.card_congr
          (Subgroup.subgroupOfEquivOfLe
            (show Z ≤ P ⊔ Z from le_sup_right)).toEquiv
      _ = 6 :=
        alternatingSixHopfKernelHasOrderSix.center
  have hrelative :
      Z.relIndex (P ⊔ Z) = 8 := by
    rw [Subgroup.relIndex_sup_right]
    exact
      relIndex_center_alternatingSixUniversalCover_sylowTwo
  rw [hcenter, hrelative] at hcard
  norm_num at hcard
  exact hcard.symm

/-- The normalizer of the fixed Sylow `2`-subgroup is exactly its join
with the ambient center. -/
theorem normalizer_alternatingSixUniversalCoverSylowTwo_eq_sup_center :
    Subgroup.normalizer
        (alternatingSixUniversalCoverSylow 2 :
          Set AlternatingSixUniversalCover) =
      (alternatingSixUniversalCoverSylow 2 :
          Subgroup AlternatingSixUniversalCover) ⊔
        Subgroup.center AlternatingSixUniversalCover := by
  symm
  apply
    Subgroup.eq_of_le_of_card_ge
      (sup_le
        (alternatingSixUniversalCoverSylow 2 :
          Subgroup AlternatingSixUniversalCover).le_normalizer
        (Subgroup.center_le_normalizer
          (alternatingSixUniversalCoverSylow 2 :
            Set AlternatingSixUniversalCover)))
  have hnormalizer :
      Nat.card
          (Subgroup.normalizer
            (alternatingSixUniversalCoverSylow 2 :
              Set AlternatingSixUniversalCover)) =
        48 :=
    natCard_normalizer_alternatingSixUniversalCoverSylowTwo
  have hcoe :
      ((alternatingSixUniversalCoverSylow 2 :
          Subgroup AlternatingSixUniversalCover) :
        Set AlternatingSixUniversalCover) =
      (alternatingSixUniversalCoverSylow 2 :
        Set AlternatingSixUniversalCover) :=
    rfl
  rw [hcoe]
  simpa only [
    natCard_alternatingSixUniversalCoverSylowTwo_sup_center]
    using hnormalizer.le

/-- The normalizer induces no outer automorphisms of the fixed Sylow
`2`-subgroup: its action range is precisely the inner-action range. -/
theorem alternatingSixUniversalCoverSylowTwoInnerAction_range_eq_normalizer_range :
    alternatingSixUniversalCoverSylowTwoInnerAction.range =
      (alternatingSixUniversalCoverSylow 2 :
        Subgroup AlternatingSixUniversalCover).normalizerMonoidHom.range := by
  apply
    Subgroup.eq_of_le_of_card_ge
      alternatingSixUniversalCoverSylowTwoInnerAction_range_le_normalizer_range
  rw [
    natCard_alternatingSixUniversalCoverSylowTwoInnerAction_range,
    natCard_alternatingSixUniversalCoverSylowTwo_normalizerMonoidHom_range]

end GroupTheory
end McKayConjecture
