/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.BinaryIcosahedralNormalFormDataTypes

/-!
# Binary-icosahedral transition certificate, rows 40–49

This file is generated by `tmp/generate_binary_icosahedral_normal_form.py`.
-/

namespace McKayConjecture
namespace GroupTheory

/-- Right-multiplication row 40. -/
def binaryIcosahedralNormalFormTransitionRow040 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨16, [
      ⟨"BB", "", 120⟩
    ]⟩,
    ⟨60, [
      ⟨"", "", 71⟩
    ]⟩,
    ⟨65, []⟩,
    ⟨37, [
      ⟨"B", "", 107⟩
    ]⟩
  ]

/-- Right-multiplication row 41. -/
def binaryIcosahedralNormalFormTransitionRow041 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨31, [
      ⟨"", "", 70⟩
    ]⟩,
    ⟨57, [
      ⟨"", "", 69⟩
    ]⟩,
    ⟨16, [
      ⟨"BB", "", 118⟩
    ]⟩,
    ⟨26, [
      ⟨"", "", 68⟩,
      ⟨"", "", 105⟩
    ]⟩
  ]

/-- Right-multiplication row 42. -/
def binaryIcosahedralNormalFormTransitionRow042 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨50, [
      ⟨"", "", 62⟩
    ]⟩,
    ⟨66, []⟩,
    ⟨27, [
      ⟨"", "", 61⟩
    ]⟩,
    ⟨18, [
      ⟨"aab", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 43. -/
def binaryIcosahedralNormalFormTransitionRow043 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨63, [
      ⟨"", "", 57⟩
    ]⟩,
    ⟨20, [
      ⟨"abb", "", 121⟩
    ]⟩,
    ⟨37, [
      ⟨"ab", "", 110⟩,
      ⟨"", "", 102⟩
    ]⟩,
    ⟨67, []⟩
  ]

/-- Right-multiplication row 44. -/
def binaryIcosahedralNormalFormTransitionRow044 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨20, [
      ⟨"abb", "", 120⟩
    ]⟩,
    ⟨36, [
      ⟨"ab", "", 109⟩,
      ⟨"", "B", 116⟩
    ]⟩,
    ⟨68, []⟩,
    ⟨48, [
      ⟨"a", "", 81⟩
    ]⟩
  ]

/-- Right-multiplication row 45. -/
def binaryIcosahedralNormalFormTransitionRow045 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨69, []⟩,
    ⟨46, [
      ⟨"a", "", 80⟩
    ]⟩,
    ⟨23, [
      ⟨"", "", 56⟩
    ]⟩,
    ⟨20, [
      ⟨"abb", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 46. -/
def binaryIcosahedralNormalFormTransitionRow046 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨45, [
      ⟨"a", "", 77⟩
    ]⟩,
    ⟨48, [
      ⟨"aB", "", 116⟩
    ]⟩,
    ⟨70, []⟩,
    ⟨21, [
      ⟨"aBa", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 47. -/
def binaryIcosahedralNormalFormTransitionRow047 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨66, [
      ⟨"a", "", 76⟩
    ]⟩,
    ⟨25, [
      ⟨"aB", "", 115⟩,
      ⟨"", "", 98⟩
    ]⟩,
    ⟨21, [
      ⟨"aBa", "", 118⟩
    ]⟩,
    ⟨71, []⟩
  ]

/-- Right-multiplication row 48. -/
def binaryIcosahedralNormalFormTransitionRow048 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨46, [
      ⟨"aB", "", 108⟩
    ]⟩,
    ⟨22, [
      ⟨"aBB", "", 121⟩
    ]⟩,
    ⟨44, [
      ⟨"a", "", 72⟩
    ]⟩,
    ⟨72, []⟩
  ]

/-- Right-multiplication row 49. -/
def binaryIcosahedralNormalFormTransitionRow049 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨22, [
      ⟨"aBB", "", 120⟩
    ]⟩,
    ⟨69, [
      ⟨"a", "", 71⟩
    ]⟩,
    ⟨73, []⟩,
    ⟨24, [
      ⟨"aB", "", 107⟩,
      ⟨"", "A", 115⟩
    ]⟩
  ]

end GroupTheory
end McKayConjecture
