/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.BinaryIcosahedralNormalFormDataTypes

/-!
# Binary-icosahedral transition certificate, rows 10–19

This file is generated by `tmp/generate_binary_icosahedral_normal_form.py`.
-/

namespace McKayConjecture
namespace GroupTheory

/-- Right-multiplication row 10. -/
def binaryIcosahedralNormalFormTransitionRow010 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨12, [
      ⟨"", "", 111⟩
    ]⟩,
    ⟨26, []⟩,
    ⟨2, [
      ⟨"A", "", 118⟩
    ]⟩,
    ⟨27, []⟩
  ]

/-- Right-multiplication row 11. -/
def binaryIcosahedralNormalFormTransitionRow011 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨28, []⟩,
    ⟨3, [
      ⟨"b", "", 121⟩
    ]⟩,
    ⟨5, [
      ⟨"", "", 110⟩
    ]⟩,
    ⟨29, []⟩
  ]

/-- Right-multiplication row 12. -/
def binaryIcosahedralNormalFormTransitionRow012 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨3, [
      ⟨"b", "", 120⟩
    ]⟩,
    ⟨10, [
      ⟨"", "", 109⟩
    ]⟩,
    ⟨30, []⟩,
    ⟨31, []⟩
  ]

/-- Right-multiplication row 13. -/
def binaryIcosahedralNormalFormTransitionRow013 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨32, []⟩,
    ⟨33, []⟩,
    ⟨34, []⟩,
    ⟨3, [
      ⟨"b", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 14. -/
def binaryIcosahedralNormalFormTransitionRow014 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨6, [
      ⟨"", "", 108⟩
    ]⟩,
    ⟨4, [
      ⟨"B", "", 121⟩
    ]⟩,
    ⟨35, []⟩,
    ⟨36, []⟩
  ]

/-- Right-multiplication row 15. -/
def binaryIcosahedralNormalFormTransitionRow015 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨4, [
      ⟨"B", "", 120⟩
    ]⟩,
    ⟨37, []⟩,
    ⟨38, []⟩,
    ⟨8, [
      ⟨"", "", 107⟩
    ]⟩
  ]

/-- Right-multiplication row 16. -/
def binaryIcosahedralNormalFormTransitionRow016 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨39, []⟩,
    ⟨40, []⟩,
    ⟨4, [
      ⟨"B", "", 118⟩
    ]⟩,
    ⟨41, []⟩
  ]

/-- Right-multiplication row 17. -/
def binaryIcosahedralNormalFormTransitionRow017 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨8, [
      ⟨"", "", 106⟩
    ]⟩,
    ⟨5, [
      ⟨"aa", "", 121⟩
    ]⟩,
    ⟨26, [
      ⟨"", "", 105⟩
    ]⟩,
    ⟨19, [
      ⟨"a", "", 117⟩
    ]⟩
  ]

/-- Right-multiplication row 18. -/
def binaryIcosahedralNormalFormTransitionRow018 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨23, [
      ⟨"", "", 104⟩
    ]⟩,
    ⟨21, [
      ⟨"a", "", 116⟩
    ]⟩,
    ⟨42, []⟩,
    ⟨5, [
      ⟨"aa", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 19. -/
def binaryIcosahedralNormalFormTransitionRow019 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨37, [
      ⟨"", "", 102⟩
    ]⟩,
    ⟨6, [
      ⟨"ab", "", 121⟩
    ]⟩,
    ⟨17, [
      ⟨"", "", 101⟩,
      ⟨"", "", 114⟩
    ]⟩,
    ⟨34, [
      ⟨"", "", 100⟩
    ]⟩
  ]

end GroupTheory
end McKayConjecture
