/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.BinaryIcosahedralNormalFormDataTypes

/-!
# Binary-icosahedral transition certificate, rows 110–119

This file is generated by `tmp/generate_binary_icosahedral_normal_form.py`.
-/

namespace McKayConjecture
namespace GroupTheory

/-- Right-multiplication row 110. -/
def binaryIcosahedralNormalFormTransitionRow110 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨113, [
      ⟨"aBa", "", 40⟩,
      ⟨"a", "bbA", 76⟩,
      ⟨"", "A", 12⟩
    ]⟩,
    ⟨99, [
      ⟨"aBaBB", "", 115⟩,
      ⟨"", "b", 29⟩
    ]⟩,
    ⟨95, [
      ⟨"aBaBBa", "", 118⟩
    ]⟩,
    ⟨119, []⟩
  ]

/-- Right-multiplication row 111. -/
def binaryIcosahedralNormalFormTransitionRow111 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨96, [
      ⟨"aBBaBB", "", 120⟩
    ]⟩,
    ⟨108, [
      ⟨"aBBa", "", 71⟩,
      ⟨"a", "ba", 41⟩,
      ⟨"abb", "", 92⟩
    ]⟩,
    ⟨119, [
      ⟨"a", "", 6⟩
    ]⟩,
    ⟨97, [
      ⟨"aBBaB", "", 107⟩,
      ⟨"aBB", "A", 115⟩
    ]⟩
  ]

/-- Right-multiplication row 112. -/
def binaryIcosahedralNormalFormTransitionRow112 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨102, [
      ⟨"AbA", "", 40⟩,
      ⟨"Ab", "bbA", 111⟩,
      ⟨"", "", 9⟩
    ]⟩,
    ⟨100, [
      ⟨"AbABB", "", 115⟩,
      ⟨"", "b", 26⟩,
      ⟨"", "", 12⟩
    ]⟩,
    ⟨98, [
      ⟨"AbABBa", "", 118⟩
    ]⟩,
    ⟨118, [
      ⟨"", "", 4⟩
    ]⟩
  ]

/-- Right-multiplication row 113. -/
def binaryIcosahedralNormalFormTransitionRow113 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨100, [
      ⟨"ABBaBB", "", 120⟩
    ]⟩,
    ⟨110, [
      ⟨"ABBa", "", 71⟩,
      ⟨"", "bba", 51⟩,
      ⟨"Abb", "", 92⟩,
      ⟨"", "BaB", 92⟩
    ]⟩,
    ⟨115, [
      ⟨"A", "", 6⟩,
      ⟨"", "BBaBB", 111⟩
    ]⟩,
    ⟨101, [
      ⟨"ABBaB", "", 107⟩,
      ⟨"ABB", "A", 115⟩
    ]⟩
  ]

/-- Right-multiplication row 114. -/
def binaryIcosahedralNormalFormTransitionRow114 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨119, [
      ⟨"bAbb", "", 92⟩,
      ⟨"b", "BaB", 92⟩,
      ⟨"", "aB", 24⟩,
      ⟨"Abb", "B", 92⟩,
      ⟨"", "BaBB", 92⟩
    ]⟩,
    ⟨116, [
      ⟨"b", "", 9⟩
    ]⟩,
    ⟨104, [
      ⟨"bAbb", "", 91⟩,
      ⟨"b", "aB", 91⟩
    ]⟩,
    ⟨102, [
      ⟨"bAbbAb", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 115. -/
def binaryIcosahedralNormalFormTransitionRow115 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨118, [
      ⟨"bA", "", 15⟩,
      ⟨"", "BBaB", 83⟩,
      ⟨"A", "B", 15⟩,
      ⟨"", "", 4⟩
    ]⟩,
    ⟨117, [
      ⟨"", "", 3⟩
    ]⟩,
    ⟨103, [
      ⟨"bABBaB", "", 118⟩
    ]⟩,
    ⟨113, [
      ⟨"bABB", "", 96⟩,
      ⟨"b", "Ab", 88⟩,
      ⟨"", "bAb", 86⟩,
      ⟨"ABB", "", 93⟩
    ]⟩
  ]

/-- Right-multiplication row 116. -/
def binaryIcosahedralNormalFormTransitionRow116 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨114, [
      ⟨"bbAbb", "", 112⟩,
      ⟨"bb", "B", 92⟩,
      ⟨"b", "", 24⟩
    ]⟩,
    ⟨118, [
      ⟨"bbAb", "", 83⟩,
      ⟨"b", "BBa", 83⟩,
      ⟨"bA", "", 15⟩,
      ⟨"", "BBaB", 83⟩,
      ⟨"A", "B", 15⟩,
      ⟨"", "", 4⟩
    ]⟩,
    ⟨108, [
      ⟨"", "", 2⟩
    ]⟩,
    ⟨105, [
      ⟨"bbAbbA", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 117. -/
def binaryIcosahedralNormalFormTransitionRow117 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨115, [
      ⟨"Ba", "", 15⟩,
      ⟨"B", "BBaB", 116⟩,
      ⟨"", "B", 15⟩
    ]⟩,
    ⟨119, [
      ⟨"", "", 0⟩
    ]⟩,
    ⟨106, [
      ⟨"BaBBaB", "", 118⟩
    ]⟩,
    ⟨107, [
      ⟨"BaBB", "", 96⟩,
      ⟨"B", "Ab", 96⟩,
      ⟨"BB", "", 93⟩
    ]⟩
  ]

/-- Right-multiplication row 118. -/
def binaryIcosahedralNormalFormTransitionRow118 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨116, [
      ⟨"abbAbb", "", 112⟩,
      ⟨"abb", "B", 92⟩,
      ⟨"ab", "", 24⟩,
      ⟨"", "bbAbb", 116⟩,
      ⟨"", "b", 17⟩
    ]⟩,
    ⟨115, [
      ⟨"abbAb", "", 83⟩,
      ⟨"ab", "BBa", 83⟩,
      ⟨"", "BBaBBa", 116⟩,
      ⟨"Ba", "", 15⟩,
      ⟨"B", "BBaB", 116⟩,
      ⟨"", "B", 15⟩
    ]⟩,
    ⟨112, [
      ⟨"a", "", 2⟩,
      ⟨"", "BaB", 62⟩
    ]⟩,
    ⟨109, [
      ⟨"abbAbbA", "", 119⟩
    ]⟩
  ]

/-- Right-multiplication row 119. -/
def binaryIcosahedralNormalFormTransitionRow119 :
    Fin 4 → BinaryIcosahedralNormalFormTransition :=
  ![
    ⟨117, [
      ⟨"aBa", "", 15⟩,
      ⟨"aB", "BBaB", 116⟩,
      ⟨"a", "B", 15⟩,
      ⟨"", "BBaBB", 116⟩
    ]⟩,
    ⟨114, [
      ⟨"a", "", 0⟩,
      ⟨"", "aBBaBB", 117⟩,
      ⟨"b", "BaBB", 117⟩,
      ⟨"b", "", 24⟩
    ]⟩,
    ⟨110, [
      ⟨"aBaBBaB", "", 118⟩
    ]⟩,
    ⟨111, [
      ⟨"aBaBB", "", 96⟩,
      ⟨"aB", "Ab", 96⟩,
      ⟨"aBB", "", 93⟩
    ]⟩
  ]

end GroupTheory
end McKayConjecture
