/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.GeneralizedFitting
import McKayConjecture.GroupTheory.SimpleQuasisimple
import McKayConjecture.GroupTheory.UniversalCentralExtension

/-!
# Derived subgroups of central extensions

If a central extension has perfect target, its derived subgroup is perfect
and still maps onto the target.  Consequently, a central extension of a
nonabelian simple group contains a canonical quasisimple subgroup, namely
its derived subgroup.
-/

noncomputable section

open Subgroup QuotientGroup

universe u v

namespace McKayConjecture.GroupTheory

namespace CentralExtension

variable {U : Type u} {S : Type v} [Group U] [Group S]

/-- Restrict a central extension to the derived subgroup of its source. -/
def commutatorProjection (E : CentralExtension U S) :
    _root_.commutator U →* S :=
  E.projection.domRestrict (_root_.commutator U)

@[simp]
theorem commutatorProjection_apply
    (E : CentralExtension U S)
    (x : _root_.commutator U) :
    E.commutatorProjection x = E.projection x :=
  rfl

/-- If the target is perfect, the derived subgroup still maps onto the
target. -/
theorem commutatorProjection_surjective
    (E : CentralExtension U S)
    (hperfect : Group.IsPerfect S) :
    Function.Surjective E.commutatorProjection := by
  letI : Group.IsPerfect S := hperfect
  rw [← MonoidHom.range_eq_top]
  change
    (E.projection.domRestrict
      (_root_.commutator U)).range = ⊤
  rw [MonoidHom.domRestrict_range,
    map_commutator_eq,
    E.projection.range_eq_top_of_surjective
      E.surjective]
  exact Subgroup.commutator_eq_self

/-- A central extension of a perfect group is generated by the source
derived subgroup and the source center. -/
theorem commutator_sup_center_eq_top
    (E : CentralExtension U S)
    (hperfect : Group.IsPerfect S) :
    _root_.commutator U ⊔ Subgroup.center U = ⊤ := by
  apply top_unique
  intro u _
  obtain ⟨k, hk⟩ :=
    E.commutatorProjection_surjective hperfect
      (E.projection u)
  have hzker :
      u * (k : U)⁻¹ ∈ E.projection.ker := by
    rw [MonoidHom.mem_ker]
    rw [map_mul, map_inv]
    change
      E.projection u *
          (E.commutatorProjection k)⁻¹ =
        1
    rw [hk, mul_inv_cancel]
  have hzcenter :
      u * (k : U)⁻¹ ∈ Subgroup.center U :=
    E.ker_le_center hzker
  have hfactor :
      u = (u * (k : U)⁻¹) * (k : U) := by
    simp
  rw [hfactor]
  exact (_root_.commutator U ⊔ Subgroup.center U).mul_mem
    (Subgroup.mem_sup_right hzcenter)
    (Subgroup.mem_sup_left k.property)

/-- The derived subgroup of a central extension with perfect target is
perfect. -/
theorem commutator_isPerfect
    (E : CentralExtension U S)
    (hperfect : Group.IsPerfect S) :
    Group.IsPerfect (_root_.commutator U) := by
  let K : Subgroup U := _root_.commutator U
  let L : Subgroup U := ⁅K, K⁆
  letI : K.Normal := inferInstance
  letI : L.Normal := inferInstance
  let q : U →* U ⧸ L := QuotientGroup.mk' L
  let A : Subgroup (U ⧸ L) := K.map q
  let B : Subgroup (U ⧸ L) :=
    (Subgroup.center U).map q
  have hAcommutator : ⁅A, A⁆ = ⊥ := by
    change ⁅K.map q, K.map q⁆ = ⊥
    rw [← Subgroup.map_commutator]
    change L.map q = ⊥
    exact
      (Subgroup.map_eq_bot_iff (H := L)).mpr
        (by
          rw [QuotientGroup.ker_mk'])
  have hAself :
      A ≤ Subgroup.centralizer (A : Set (U ⧸ L)) :=
    Subgroup.commutator_eq_bot_iff_le_centralizer.mp
      hAcommutator
  have hBcenter :
      B ≤ Subgroup.center (U ⧸ L) := by
    exact map_center_le_center_of_surjective
      (QuotientGroup.mk'_surjective L)
  have hAcentralB :
      A ≤ Subgroup.centralizer (B : Set (U ⧸ L)) := by
    rw [← Subgroup.commutator_eq_bot_iff_le_centralizer]
    apply le_bot_iff.mp
    exact
      (Subgroup.commutator_mono le_rfl hBcenter).trans
        (le_of_eq
          (Subgroup.commutator_center_right
            (H := A)))
  have hAcentralSup :
      A ≤
        Subgroup.centralizer
          ((A ⊔ B : Subgroup (U ⧸ L)) :
            Set (U ⧸ L)) := by
    rw [centralizer_sup]
    exact le_inf hAself hAcentralB
  have hBcentralSup :
      B ≤
        Subgroup.centralizer
          ((A ⊔ B : Subgroup (U ⧸ L)) :
            Set (U ⧸ L)) :=
    hBcenter.trans
      (Subgroup.center_le_centralizer
        ((A ⊔ B : Subgroup (U ⧸ L)) :
          Set (U ⧸ L)))
  have hSupcentral :
      A ⊔ B ≤
        Subgroup.centralizer
          ((A ⊔ B : Subgroup (U ⧸ L)) :
            Set (U ⧸ L)) :=
    sup_le hAcentralSup hBcentralSup
  have hSupTop : A ⊔ B = ⊤ := by
    have hmap :=
      congrArg (Subgroup.map q)
        (E.commutator_sup_center_eq_top hperfect)
    simpa only [Subgroup.map_sup,
      Subgroup.map_top_of_surjective q
        (QuotientGroup.mk'_surjective L)] using hmap
  have hquotientCommutative :
      IsMulCommutative (U ⧸ L) := by
    rw [← _root_.commutator_eq_bot_iff]
    change ⁅(⊤ : Subgroup (U ⧸ L)), ⊤⁆ = ⊥
    rw [← hSupTop]
    exact
      Subgroup.commutator_eq_bot_iff_le_centralizer.mpr
        hSupcentral
  have hKleL : K ≤ L := by
    letI : IsMulCommutative (U ⧸ L) :=
      hquotientCommutative
    exact
      Subgroup.Normal.quotient_commutative_iff_commutator_le.mp
        hquotientCommutative
  have hperfectK : ⁅K, K⁆ = K := by
    change L = K
    exact le_antisymm
      (Subgroup.commutator_le_left K K)
      hKleL
  exact Subgroup.isPerfect_iff.mpr hperfectK

/-- Restriction to the derived subgroup is again a central extension when
the target is perfect. -/
def commutatorCentralExtension
    (E : CentralExtension U S)
    (hperfect : Group.IsPerfect S) :
    CentralExtension (_root_.commutator U) S where
  projection := E.commutatorProjection
  surjective := E.commutatorProjection_surjective hperfect
  ker_le_center := by
    intro k hk
    have hkambient :
        (k : U) ∈ E.projection.ker := by
      exact hk
    have hkcenter :
        (k : U) ∈ Subgroup.center U :=
      E.ker_le_center hkambient
    rw [Subgroup.mem_center_iff]
    intro l
    apply Subtype.ext
    exact
      Subgroup.mem_center_iff.mp hkcenter
        (l : U)

/-- The derived subgroup of a central extension onto a nonabelian simple
group is quasisimple. -/
theorem commutator_isQuasisimple
    (E : CentralExtension U S)
    (hsimple : IsSimpleGroup S)
    (hnoncomm : ¬IsMulCommutative S) :
    IsQuasisimple (_root_.commutator U) := by
  let hperfect :
      Group.IsPerfect S :=
    isPerfect_of_isSimpleGroup hsimple hnoncomm
  exact
    (E.commutatorCentralExtension hperfect).source_isQuasisimple
      (E.commutator_isPerfect hperfect)
      hsimple hnoncomm

end CentralExtension

end McKayConjecture.GroupTheory
