/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.ComponentLocalSubgroup

/-!
# Conjugation-invariant component-local subgroups

Ambient conjugation canonically identifies the carrier of a component
`K` with the carrier of the conjugate component `g • K`.  This file
uses that identification to formulate exact conjugation-equivariance
for a family of coordinate subgroups `M K ≤ K`.

The main result says that an equivariant family generates a normal
ambient subgroup.  The coordinate and ambient map identities are also
recorded explicitly, so downstream arguments can use conjugation
without introducing dependent casts between component carriers.
-/

noncomputable section

universe u

namespace McKayConjecture
namespace GroupTheory

variable (G : Type u) [Group G]

/-- Conjugation by `g` as the canonical multiplicative equivalence
between the carrier of `K` and the carrier of `g • K`. -/
def componentConjugationEquiv
    (g : G) (K : ComponentIndex G) :
    K.1 ≃* (g • K).1 :=
  MulEquiv.subgroupMap (MulAut.conj g) K.1

@[simp]
theorem componentConjugationEquiv_apply_coe
    (g : G) (K : ComponentIndex G) (x : K.1) :
    ((componentConjugationEquiv G g K x :
        (g • K).1) : G) =
      g * (x : G) * g⁻¹ :=
  rfl

@[simp]
theorem componentConjugationEquiv_symm_apply_coe
    (g : G) (K : ComponentIndex G) (x : (g • K).1) :
    (((componentConjugationEquiv G g K).symm x :
        K.1) : G) =
      g⁻¹ * (x : G) * g := by
  rfl

/-- The canonical carrier equivalence commutes with the two inclusions
into the ambient group and ambient conjugation. -/
@[simp]
theorem component_subtype_comp_componentConjugationEquiv
    (g : G) (K : ComponentIndex G) :
    (g • K).1.subtype.comp
        (componentConjugationEquiv G g K).toMonoidHom =
      (MulAut.conj g).toMonoidHom.comp K.1.subtype := by
  ext x
  rfl

/-- Successive canonical carrier equivalences agree in the ambient
group with conjugation by the product.  Comparing ambient values avoids
any cast between `g • (h • K)` and `(g * h) • K`. -/
@[simp]
theorem componentConjugationEquiv_mul_apply_coe
    (g h : G) (K : ComponentIndex G) (x : K.1) :
    ((componentConjugationEquiv G g (h • K)
        (componentConjugationEquiv G h K x) :
          (g • (h • K)).1) : G) =
      ((componentConjugationEquiv G (g * h) K x :
          ((g * h) • K).1) : G) := by
  simp only [componentConjugationEquiv_apply_coe]
  simp [mul_assoc]

/-- Transport a subgroup of a component carrier along ambient
conjugation. -/
def componentConjugateSubgroup
    (g : G) (K : ComponentIndex G) (L : Subgroup K.1) :
    Subgroup (g • K).1 :=
  L.map (componentConjugationEquiv G g K).toMonoidHom

namespace ComponentLocalFamily

/-- Exact conjugation-equivariance of a family of subgroups of the
component carriers. -/
def IsConjugationEquivariant
    (M : ∀ K : ComponentIndex G, Subgroup K.1) : Prop :=
  ∀ (g : G) (K : ComponentIndex G),
    componentConjugateSubgroup G g K (M K) = M (g • K)

end ComponentLocalFamily

/-- Exact equivariance gives the corresponding identity after mapping
one coordinate subgroup into the ambient group. -/
theorem map_componentLocal_coordinate_conj
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hM : ComponentLocalFamily.IsConjugationEquivariant G M)
    (g : G) (K : ComponentIndex G) :
    ((M K).map K.1.subtype).map
        (MulAut.conj g).toMonoidHom =
      (M (g • K)).map (g • K).1.subtype := by
  calc
    ((M K).map K.1.subtype).map
          (MulAut.conj g).toMonoidHom =
        (M K).map
          ((MulAut.conj g).toMonoidHom.comp K.1.subtype) := by
      rw [Subgroup.map_map]
    _ = (M K).map
          ((g • K).1.subtype.comp
            (componentConjugationEquiv G g K).toMonoidHom) := by
      rw [component_subtype_comp_componentConjugationEquiv]
    _ = (componentConjugateSubgroup G g K (M K)).map
          (g • K).1.subtype := by
      rw [componentConjugateSubgroup, Subgroup.map_map]
    _ = (M (g • K)).map (g • K).1.subtype := by
      rw [hM g K]

/-- The subgroup generated by an equivariant family is fixed by every
ambient conjugation map. -/
theorem map_componentLocalSubgroup_conj
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hM : ComponentLocalFamily.IsConjugationEquivariant G M)
    (g : G) :
    (componentLocalSubgroup G M).map
        (MulAut.conj g).toMonoidHom =
      componentLocalSubgroup G M := by
  rw [componentLocalSubgroup, Subgroup.map_iSup]
  simp_rw [map_componentLocal_coordinate_conj G M hM g]
  apply le_antisymm
  · apply iSup_le
    intro K
    exact le_iSup
      (fun L : ComponentIndex G =>
        (M L).map L.1.subtype) (g • K)
  · apply iSup_le
    intro K
    have hle :=
      le_iSup
        (fun L : ComponentIndex G =>
          (M (g • L)).map (g • L).1.subtype)
        (g⁻¹ • K)
    have hindex : g • (g⁻¹ • K) = K :=
      smul_inv_smul g K
    rw [hindex] at hle
    exact hle

/-- The subgroup generated by an exactly conjugation-equivariant
component-local family is normal in the ambient group. -/
theorem componentLocalSubgroup_normal
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hM : ComponentLocalFamily.IsConjugationEquivariant G M) :
    (componentLocalSubgroup G M).Normal := by
  rw [Subgroup.normal_iff_map_conj_eq]
  exact map_componentLocalSubgroup_conj G M hM

end GroupTheory
end McKayConjecture
