/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.GroupTheory.IsSubnormal
import McKayConjecture.GroupTheory.Quasisimple

/-!
# Components and the layer of a group

A component is a quasisimple subnormal subgroup.  The layer `layer G`,
traditionally denoted `E(G)`, is generated by all components of `G`.

This file establishes the definition-independent structural facts needed by
the minimal-counterexample reduction: components and the layer are preserved
by group isomorphisms, the layer is characteristic (hence normal), and the
layer is perfect.  Commutation and central-product results for distinct
components belong in a separate file.
-/

noncomputable section

universe u v

namespace McKayConjecture.GroupTheory

variable {G : Type u} [Group G]
variable {H : Type v} [Group H]

/-- A component of `G` is a quasisimple subnormal subgroup. -/
def IsComponent (K : Subgroup G) : Prop :=
  K.IsSubnormal ∧ IsQuasisimple K

namespace IsComponent

/-- A component is subnormal in the ambient group. -/
theorem isSubnormal {K : Subgroup G} (hK : IsComponent K) :
    K.IsSubnormal :=
  hK.1

/-- A component is quasisimple. -/
theorem isQuasisimple {K : Subgroup G} (hK : IsComponent K) :
    IsQuasisimple K :=
  hK.2

/-- Components are nontrivial. -/
theorem ne_bot {K : Subgroup G} (hK : IsComponent K) :
    K ≠ ⊥ := by
  intro hbot
  haveI : Nontrivial K := hK.isQuasisimple.nontrivial
  have hsubsingleton : Subsingleton K := by
    rw [hbot]
    infer_instance
  exact not_subsingleton K hsubsingleton

/-- The image of a component under a group isomorphism is a component. -/
theorem map_mulEquiv (e : G ≃* H) {K : Subgroup G}
    (hK : IsComponent K) :
    IsComponent (K.map e.toMonoidHom) := by
  refine ⟨hK.isSubnormal.map e.surjective, ?_⟩
  exact IsQuasisimple.of_mulEquiv
    (K.equivMapOfInjective e.toMonoidHom e.injective)
    hK.isQuasisimple

/-- Pulling a component back along a group isomorphism gives a component. -/
theorem comap_mulEquiv (e : G ≃* H) {L : Subgroup H}
    (hL : IsComponent L) :
    IsComponent (L.comap e.toMonoidHom) := by
  have hmap : IsComponent (L.map e.symm.toMonoidHom) :=
    hL.map_mulEquiv e.symm
  have heq :
      L.map e.symm.toMonoidHom =
        L.comap e.toMonoidHom := by
    ext x
    constructor
    · rintro ⟨y, hy, hxy⟩
      subst x
      simpa using hy
    · intro hx
      exact ⟨e x, hx, by simp⟩
  rwa [← heq]

end IsComponent

/-- The set of all components of `G`. -/
def components (G : Type u) [Group G] : Set (Subgroup G) :=
  {K | IsComponent K}

/-- The layer of `G`, traditionally denoted `E(G)`, is generated by all
components. -/
def layer (G : Type u) [Group G] : Subgroup G :=
  sSup (components G)

/-- Every component lies in the layer. -/
theorem IsComponent.le_layer {K : Subgroup G} (hK : IsComponent K) :
    K ≤ layer G :=
  le_sSup hK

/-- The layer is the least subgroup containing every component. -/
theorem layer_le {L : Subgroup G}
    (hL : ∀ K : Subgroup G, IsComponent K → K ≤ L) :
    layer G ≤ L :=
  sSup_le hL

/-- A group isomorphism maps the layer into the target layer. -/
theorem map_layer_le (e : G ≃* H) :
    (layer G).map e.toMonoidHom ≤ layer H := by
  rw [Subgroup.map_le_iff_le_comap]
  apply layer_le
  intro K hK
  rw [← Subgroup.map_le_iff_le_comap]
  exact (hK.map_mulEquiv e).le_layer

/-- A group isomorphism maps the layer exactly onto the target layer. -/
theorem map_layer_mulEquiv (e : G ≃* H) :
    (layer G).map e.toMonoidHom = layer H := by
  apply le_antisymm
  · exact map_layer_le e
  · intro y hy
    have hreverse :
        (layer H).map e.symm.toMonoidHom ≤ layer G :=
      map_layer_le e.symm
    have hx : e.symm y ∈ layer G :=
      hreverse ⟨y, hy, rfl⟩
    exact ⟨e.symm y, hx, e.apply_symm_apply y⟩

/-- The layer is characteristic. -/
instance layer_characteristic :
    (layer G).Characteristic := by
  rw [Subgroup.characteristic_iff_map_le]
  intro e
  exact map_layer_le e

/-- The layer is normal. -/
instance layer_normal :
    (layer G).Normal :=
  inferInstance

/-- The ambient commutator of the layer with itself is the layer. -/
theorem layer_commutator_eq_self :
    ⁅layer G, layer G⁆ = layer G := by
  apply le_antisymm
  · exact Subgroup.commutator_le_self (layer G)
  · apply layer_le
    intro K hK
    have hperfect : Group.IsPerfect K :=
      hK.isQuasisimple.isPerfect
    rw [← @Subgroup.commutator_eq_self G _ K hperfect]
    exact Subgroup.commutator_mono hK.le_layer hK.le_layer

/-- The layer, as a group in its own right, is perfect. -/
instance layer_isPerfect :
    Group.IsPerfect (layer G) :=
  Subgroup.isPerfect_iff.mpr layer_commutator_eq_self

end McKayConjecture.GroupTheory
