/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.ComponentLocalSubgroup
import McKayConjecture.GroupTheory.LayerCenter

/-!
# Centers of components

The center of a component is central in the layer.  More precisely, the
canonical inclusion of a component `K` into `E(G)` sends `Z(K)` into
`Z(E(G))`.  Passing to ambient images then shows that the image of `Z(K)`
lies in the Fitting subgroup.  Under the reduction hypothesis
`F(G) = Z(G)`, it is therefore central in `G`.

The conclusion about the ambient center genuinely needs an additional
hypothesis: a component center need not be central in the whole group,
because ambient conjugation may permute or act nontrivially on components.
-/

noncomputable section

universe u

namespace McKayConjecture
namespace GroupTheory

variable (G : Type u) [Group G] [Finite G]

/-- The canonical inclusion of a component into the layer. -/
def componentToLayerHom (K : ComponentIndex G) :
    K.1 →* layer G :=
  K.1.subtype.codRestrict
    (layer G)
    (fun x => K.2.le_layer x.2)

omit [Finite G] in
@[simp, norm_cast]
theorem coe_componentToLayerHom
    (K : ComponentIndex G) (x : K.1) :
    ((componentToLayerHom G K x : layer G) : G) =
      (x : G) :=
  rfl

omit [Finite G] in
/-- The canonical inclusion of a component into the layer is injective. -/
theorem componentToLayerHom_injective
    (K : ComponentIndex G) :
    Function.Injective (componentToLayerHom G K) := by
  intro x y hxy
  exact Subtype.ext
    (congrArg (fun z : layer G => (z : G)) hxy)

/-- The canonical inclusion of a component into the layer sends the
component center into the center of the layer. -/
theorem map_center_componentToLayer_le_center
    (K : ComponentIndex G) :
    (Subgroup.center K.1).map
        (componentToLayerHom G K) ≤
      Subgroup.center (layer G) := by
  classical
  letI := Fintype.ofFinite (ComponentIndex G)
  rintro _ ⟨z, hz, rfl⟩
  let s : ∀ L : ComponentIndex G, L.1 :=
    Pi.mulSingle K z
  have hs :
      s ∈ Subgroup.center
        (∀ L : ComponentIndex G, L.1) := by
    rw [Subgroup.mem_center_iff]
    intro y
    funext L
    by_cases hLK : L = K
    · subst L
      simpa [s] using
        (Subgroup.mem_center_iff.mp hz (y K))
    · simp [s, hLK]
  have hs_eq :
      layerProductHom G s =
        componentToLayerHom G K z := by
    apply Subtype.ext
    change
      Subgroup.noncommPiCoprod
          (components_pairwise_commute_elements (G := G)) s =
        (z : G)
    dsimp [s]
    exact
      Subgroup.noncommPiCoprod_mulSingle K z
  have hmap :
      layerProductHom G s ∈
        Subgroup.center (layer G) :=
    map_center_le_center_of_surjective
      (layerProductHom_surjective G)
      ⟨s, hs, rfl⟩
  rw [hs_eq] at hmap
  exact hmap

/-- In ambient coordinates, the image of the center of every component
lies in the ambient image of the center of the layer. -/
theorem map_center_component_le_map_center_layer
    (K : ComponentIndex G) :
    (Subgroup.center K.1).map K.1.subtype ≤
      (Subgroup.center (layer G)).map
        (layer G).subtype := by
  rintro _ ⟨z, hz, rfl⟩
  refine
    ⟨componentToLayerHom G K z,
      map_center_componentToLayer_le_center G K
        ⟨z, hz, rfl⟩,
      rfl⟩

omit [Finite G] in
/-- If every chosen component-local subgroup contains its coordinate
center, then the ambient image of each coordinate center lies in the
subgroup generated by the component-local subgroups. -/
theorem map_center_component_le_componentLocalSubgroup
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hcenter : ∀ K, Subgroup.center K.1 ≤ M K)
    (K : ComponentIndex G) :
    (Subgroup.center K.1).map K.1.subtype ≤
      componentLocalSubgroup G M :=
  (Subgroup.map_mono (hcenter K)).trans
    (map_componentLocal_le G M K)

/-- Under the same coordinate-center hypothesis, every component center
also lies in the image of the product of the chosen local subgroups inside
the layer. -/
theorem map_center_component_le_ambientLayerLocalSubgroup
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hcenter : ∀ K, Subgroup.center K.1 ≤ M K)
    (K : ComponentIndex G) :
    (Subgroup.center K.1).map K.1.subtype ≤
      ambientLayerLocalSubgroup G M :=
  (map_center_component_le_componentLocalSubgroup
      G M hcenter K).trans
    (componentLocalSubgroup_le_ambientLayerLocalSubgroup G M)

/-- The ambient image of the center of a component lies in the Fitting
subgroup. -/
theorem map_center_component_le_fittingSubgroup
    (K : ComponentIndex G) :
    (Subgroup.center K.1).map K.1.subtype ≤
      fittingSubgroup G :=
  (map_center_component_le_map_center_layer G K).trans
    map_center_layer_le_fittingSubgroup

/-- A one-sided containment `F(G) ≤ Z(G)` is enough to make every
component center central in the ambient group. -/
theorem map_center_component_le_center_of_fittingSubgroup_le_center
    (hF : fittingSubgroup G ≤ Subgroup.center G)
    (K : ComponentIndex G) :
    (Subgroup.center K.1).map K.1.subtype ≤
      Subgroup.center G :=
  (map_center_component_le_fittingSubgroup G K).trans hF

/-- If `F(G) = Z(G)`, then the ambient image of the center of every
component is central in `G`. -/
theorem map_center_component_le_center_of_fittingSubgroup_eq_center
    (hF : fittingSubgroup G = Subgroup.center G)
    (K : ComponentIndex G) :
    (Subgroup.center K.1).map K.1.subtype ≤
      Subgroup.center G :=
  map_center_component_le_center_of_fittingSubgroup_le_center
    G hF.le K

end GroupTheory
end McKayConjecture
