/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.Nat.ModEq

/-!
# Powers of commuting elements of coprime order

Elementary Chinese-remainder lemmas for recovering each factor of a
product of commuting finite-order elements.
-/

namespace McKayConjecture

variable {G : Type} [Group G]

/-- If two commuting elements have coprime orders, the first factor
belongs to the cyclic subgroup generated by their product. -/
theorem left_mem_zpowers_mul_of_commute_of_coprime_orderOf
    {a b : G}
    (hab : Commute a b)
    (hcoprime : (orderOf a).Coprime (orderOf b)) :
    a ∈ Subgroup.zpowers (a * b) := by
  let t : ℕ :=
    Nat.chineseRemainder hcoprime 1 0
  have htA : t ≡ 1 [MOD orderOf a] :=
    (Nat.chineseRemainder hcoprime 1 0).prop.1
  have htB : t ≡ 0 [MOD orderOf b] :=
    (Nat.chineseRemainder hcoprime 1 0).prop.2
  have ha : a ^ t = a := by
    simpa only [pow_one] using
      (pow_eq_pow_iff_modEq.mpr htA)
  have hb : b ^ t = 1 :=
    pow_eq_one_iff_modEq.mpr htB
  have hpow : (a * b) ^ t = a := by
    rw [hab.mul_pow, ha, hb, mul_one]
  have hm :
      (a * b) ^ t ∈ Subgroup.zpowers (a * b) :=
    (Subgroup.zpowers (a * b)).pow_mem
      (Subgroup.mem_zpowers (a * b)) t
  exact
    Eq.mp
      (congrArg
        (fun z : G ↦ z ∈ Subgroup.zpowers (a * b))
        hpow)
      hm

/-- If two commuting elements have coprime orders, the second factor
belongs to the cyclic subgroup generated by their product. -/
theorem right_mem_zpowers_mul_of_commute_of_coprime_orderOf
    {a b : G}
    (hab : Commute a b)
    (hcoprime : (orderOf a).Coprime (orderOf b)) :
    b ∈ Subgroup.zpowers (a * b) := by
  rw [hab.eq]
  exact
    left_mem_zpowers_mul_of_commute_of_coprime_orderOf
      hab.symm hcoprime.symm

end McKayConjecture
