/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.GroupTheory.OrderOfElement

/-!
# Coprime commuting factors

Two commuting elements whose orders are coprime can each be recovered
as a power of their product.  In particular, every subgroup containing
the product contains both factors.
-/

namespace McKayConjecture
namespace GroupTheory

variable {G : Type*} [Group G]

/-- Commuting factors of coprime orders both belong to the cyclic
subgroup generated by their product. -/
theorem mem_zpowers_mul_of_commute_coprime_order
    {a b : G}
    (hab : Commute a b)
    (hcoprime : (orderOf a).Coprime (orderOf b)) :
    a ∈ Subgroup.zpowers (a * b) ∧
      b ∈ Subgroup.zpowers (a * b) := by
  constructor
  · obtain ⟨m, hm⟩ :=
      exists_pow_eq_self_of_coprime hcoprime.symm
    have hproduct :
        ((a * b) ^ orderOf b) ^ m = a := by
      rw [hab.mul_pow, pow_orderOf_eq_one, mul_one, hm]
    have hmem :
        ((a * b) ^ orderOf b) ^ m ∈
          Subgroup.zpowers (a * b) :=
      (Subgroup.zpowers (a * b)).pow_mem
        ((Subgroup.zpowers (a * b)).pow_mem
          (Subgroup.mem_zpowers (a * b))
          (orderOf b))
        m
    simpa only [hproduct] using hmem
  · obtain ⟨m, hm⟩ :=
      exists_pow_eq_self_of_coprime hcoprime
    have hproduct :
        ((a * b) ^ orderOf a) ^ m = b := by
      rw [hab.mul_pow, pow_orderOf_eq_one, one_mul, hm]
    have hmem :
        ((a * b) ^ orderOf a) ^ m ∈
          Subgroup.zpowers (a * b) :=
      (Subgroup.zpowers (a * b)).pow_mem
        ((Subgroup.zpowers (a * b)).pow_mem
          (Subgroup.mem_zpowers (a * b))
          (orderOf a))
        m
    simpa only [hproduct] using hmem

/-- A subgroup containing a product of commuting coprime-order
elements contains each factor. -/
theorem factors_mem_of_mul_mem_of_commute_coprime_order
    {a b : G}
    (H : Subgroup G)
    (hab : Commute a b)
    (hcoprime : (orderOf a).Coprime (orderOf b))
    (habH : a * b ∈ H) :
    a ∈ H ∧ b ∈ H := by
  have hz :
      Subgroup.zpowers (a * b) ≤ H :=
    Subgroup.zpowers_le.mpr habH
  exact
    ⟨hz
        (mem_zpowers_mul_of_commute_coprime_order
          hab hcoprime).1,
      hz
        (mem_zpowers_mul_of_commute_coprime_order
          hab hcoprime).2⟩

end GroupTheory
end McKayConjecture
