/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.ComponentCenter
import McKayConjecture.GroupTheory.ComponentStabilizer
import McKayConjecture.GroupTheory.LayerIntermediate

/-!
# Identifying the two component-local subgroup constructions

Multiplying chosen subgroups of the components and then viewing the
result in the ambient group gives exactly the subgroup generated by
their ambient images.  Consequently, the corresponding subgroups
inside the layer are equal as well.
-/

noncomputable section

universe u

namespace McKayConjecture
namespace GroupTheory

variable (G : Type u) [Group G] [Finite G]

/-- The ambient image of the product of the component-local subgroups
is contained in the subgroup generated by their individual ambient
images. -/
theorem ambientLayerLocalSubgroup_le_componentLocalSubgroup
    (M : ∀ K : ComponentIndex G, Subgroup K.1) :
    ambientLayerLocalSubgroup G M ≤
      componentLocalSubgroup G M := by
  classical
  letI := Fintype.ofFinite (ComponentIndex G)
  rintro g ⟨z, ⟨x, hx, rfl⟩, rfl⟩
  let f : (∀ K : ComponentIndex G, K.1) →* G :=
    (layer G).subtype.comp (layerProductHom G)
  change f x ∈ componentLocalSubgroup G M
  have hx' :
      x ∈ (componentLocalSubgroup G M).comap f := by
    apply Subgroup.pi_mem_of_mulSingle_mem x
    intro K
    change
      Subgroup.noncommPiCoprod
          (components_pairwise_commute_elements
            (G := G))
          (Pi.mulSingle K (x K)) ∈
        componentLocalSubgroup G M
    rw [Subgroup.noncommPiCoprod_mulSingle]
    exact
      map_componentLocal_le G M K
        ⟨x K, (mem_piLocalSubgroup M x).mp hx K, rfl⟩
  exact hx'

/-- The two ambient component-local subgroup constructions agree. -/
theorem ambientLayerLocalSubgroup_eq_componentLocalSubgroup
    (M : ∀ K : ComponentIndex G, Subgroup K.1) :
    ambientLayerLocalSubgroup G M =
      componentLocalSubgroup G M :=
  le_antisymm
    (ambientLayerLocalSubgroup_le_componentLocalSubgroup G M)
    (componentLocalSubgroup_le_ambientLayerLocalSubgroup G M)

/-- The subgroup obtained directly from the component product agrees
with the pullback to the layer of the ambient component-local
subgroup. -/
theorem layerLocalSubgroup_eq_componentLocalSubgroupInLayer
    (M : ∀ K : ComponentIndex G, Subgroup K.1) :
    layerLocalSubgroup G M =
      componentLocalSubgroupInLayer G M := by
  have h :=
    congrArg (Subgroup.comap (layer G).subtype)
      (ambientLayerLocalSubgroup_eq_componentLocalSubgroup G M)
  simpa only [ambientLayerLocalSubgroup,
    componentLocalSubgroupInLayer,
    Subgroup.comap_map_eq_self_of_injective
      (layer G).subtype_injective] using h

/-- Pulling the assembled layer-local subgroup back to one component
recovers exactly the chosen coordinate subgroup, provided the coordinate
subgroups contain their centers. -/
theorem comap_layerLocalSubgroup_componentToLayerHom
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hcenter : ∀ K, Subgroup.center K.1 ≤ M K)
    (K : ComponentIndex G) :
    (layerLocalSubgroup G M).comap
        (componentToLayerHom G K) =
      M K := by
  classical
  letI := Fintype.ofFinite (ComponentIndex G)
  ext x
  have hsingle :
      layerProductHom G (Pi.mulSingle K x) =
        componentToLayerHom G K x := by
    apply Subtype.ext
    change
      Subgroup.noncommPiCoprod
          (components_pairwise_commute_elements (G := G))
          (Pi.mulSingle K x) =
        (x : G)
    exact Subgroup.noncommPiCoprod_mulSingle K x
  constructor
  · intro hx
    change
      componentToLayerHom G K x ∈
        (piLocalSubgroup M).map (layerProductHom G)
      at hx
    obtain ⟨y, hy, hyx⟩ := hx
    let z :
        ∀ L : ComponentIndex G, L.1 :=
      y⁻¹ * Pi.mulSingle K x
    have hzKer :
        z ∈ (layerProductHom G).ker := by
      rw [MonoidHom.mem_ker]
      simp only [z, map_mul, map_inv, hsingle, hyx]
      simp
    have hzCenter :
        z ∈ Subgroup.center
          (∀ L : ComponentIndex G, L.1) :=
      layerProductHom_ker_le_center G hzKer
    have hzCoordinate :
        z K ∈ Subgroup.center K.1 :=
      (Subgroup.mem_pi Set.univ).mp
        (by simpa only [Subgroup.center_pi] using hzCenter)
        K (Set.mem_univ K)
    have hzLocal :
        (y K)⁻¹ * x ∈ M K := by
      simpa only [z, Pi.mul_apply, Pi.inv_apply,
        Pi.mulSingle_eq_same] using
          hcenter K hzCoordinate
    have hyCoordinate : y K ∈ M K :=
      (mem_piLocalSubgroup M y).mp hy K
    have hmul :=
      (M K).mul_mem hyCoordinate hzLocal
    simpa using hmul
  · intro hx
    change
      componentToLayerHom G K x ∈
        (piLocalSubgroup M).map (layerProductHom G)
    refine ⟨Pi.mulSingle K x, ?_, hsingle⟩
    apply (mem_piLocalSubgroup M _).2
    intro L
    by_cases hLK : L = K
    · subst L
      simpa using hx
    · simp [hLK]

/-- The intersection of the ambient component-local subgroup with one
component is exactly its chosen coordinate subgroup. -/
theorem comap_componentLocalSubgroup_component_subtype
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hcenter : ∀ K, Subgroup.center K.1 ≤ M K)
    (K : ComponentIndex G) :
    (componentLocalSubgroup G M).comap K.1.subtype =
      M K := by
  rw [← ambientLayerLocalSubgroup_eq_componentLocalSubgroup G M]
  ext x
  constructor
  · intro hx
    change
      (x : G) ∈
        (layerLocalSubgroup G M).map (layer G).subtype
      at hx
    obtain ⟨z, hz, hzx⟩ := hx
    have hzcomp :
        z = componentToLayerHom G K x := by
      apply Subtype.ext
      exact hzx
    have hxLayer :
        x ∈ (layerLocalSubgroup G M).comap
          (componentToLayerHom G K) := by
      change
        componentToLayerHom G K x ∈
          layerLocalSubgroup G M
      rw [← hzcomp]
      exact hz
    rw [comap_layerLocalSubgroup_componentToLayerHom
      G M hcenter K] at hxLayer
    exact hxLayer
  · intro hx
    have hxLayer :
        x ∈ (layerLocalSubgroup G M).comap
          (componentToLayerHom G K) := by
      rw [comap_layerLocalSubgroup_componentToLayerHom
        G M hcenter K]
      exact hx
    exact
      ⟨componentToLayerHom G K x, hxLayer, rfl⟩

/-- An ambient element normalizing both a component and the assembled
component-local subgroup preserves the chosen subgroup in that component. -/
theorem map_coordinateSubgroup_componentNormalizerAction
    (M : ∀ K : ComponentIndex G, Subgroup K.1)
    (hcenter : ∀ K, Subgroup.center K.1 ≤ M K)
    (K : ComponentIndex G)
    (n : Subgroup.normalizer (K.1 : Set G))
    (hn :
      (n : G) ∈
        Subgroup.normalizer
          (componentLocalSubgroup G M : Set G)) :
    (M K).map
        (componentNormalizerAction G K n).toMonoidHom =
      M K := by
  have hforward :
      ∀ (m : Subgroup.normalizer (K.1 : Set G)),
        (m : G) ∈
            Subgroup.normalizer
              (componentLocalSubgroup G M : Set G) →
          (M K).map
              (componentNormalizerAction G K m).toMonoidHom ≤
            M K := by
    intro m hm
    rintro y ⟨x, hx, rfl⟩
    have hxGlobal :
        (x : G) ∈ componentLocalSubgroup G M := by
      have hxComap :
          x ∈ (componentLocalSubgroup G M).comap K.1.subtype := by
        rw [comap_componentLocalSubgroup_component_subtype
          G M hcenter K]
        exact hx
      exact hxComap
    have hmap :
        (componentLocalSubgroup G M).map
            (MulAut.conj (m : G)).toMonoidHom =
          componentLocalSubgroup G M :=
      Subgroup.mem_normalizer_iff_map_conj_eq.mp hm
    have hyGlobal :
        ((componentNormalizerAction G K m x : K.1) : G) ∈
          componentLocalSubgroup G M := by
      rw [← hmap]
      exact ⟨(x : G), hxGlobal, rfl⟩
    have hyComap :
        componentNormalizerAction G K m x ∈
          (componentLocalSubgroup G M).comap K.1.subtype :=
      hyGlobal
    rw [comap_componentLocalSubgroup_component_subtype
      G M hcenter K] at hyComap
    exact hyComap
  apply le_antisymm
  · exact hforward n hn
  · intro y hy
    let m : Subgroup.normalizer (K.1 : Set G) := n⁻¹
    have hm :
        (m : G) ∈
          Subgroup.normalizer
            (componentLocalSubgroup G M : Set G) :=
      (Subgroup.normalizer
        (componentLocalSubgroup G M : Set G)).inv_mem hn
    let x : K.1 :=
      componentNormalizerAction G K m y
    have hx : x ∈ M K :=
      hforward m hm ⟨y, hy, rfl⟩
    refine ⟨x, hx, ?_⟩
    simp [x, m]

end GroupTheory
end McKayConjecture
