/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.NormalProductSylowQuotient
import McKayConjecture.GroupTheory.OkuyamaWajimaQuotient
import McKayConjecture.GroupTheory.QuotientComplement
import Mathlib.GroupTheory.SchurZassenhaus

/-!
# A complement in the Sylow normalizer for Okuyama--Wajima

Let `K ◁ Γ` be a normal `p′`-subgroup, let `S` be a Sylow `p`-subgroup,
and suppose that `K ⊔ S` is normal in `Γ`.  Put

* `H = N_Γ(S)`;
* `D = K ∩ C_Γ(S)`.

The intersection of the normal product with the Sylow normalizer is

`H ∩ (K ⊔ S) = D ⊔ S`.

Internally to `H`, this is a normal subgroup.  Modulo `D` it is the
normal quotient Sylow subgroup, so Schur--Zassenhaus supplies a complement.
Lifting that quotient complement back to `H` produces a subgroup `U`
with

`(D ⊔ S) ⊔ U = H` and `(D ⊔ S) ∩ U = D`.

This file contains only the group-theoretic setup; no character theory is
used.
-/

noncomputable section

universe u

namespace McKayConjecture
namespace GroupTheory

variable {Γ : Type u} [Group Γ] [Finite Γ]
variable {p : ℕ} [Fact p.Prime]

/-- The fixed-point subgroup `D = K ∩ C_Γ(S)`. -/
abbrev okuyamaWajimaFixedPoints
    (K S : Subgroup Γ) :
    Subgroup Γ :=
  K ⊓ Subgroup.centralizer (S : Set Γ)

/-- The copy of `D` inside the Sylow normalizer `H = N_Γ(S)`. -/
abbrev okuyamaWajimaInternalFixedPoints
    (K S : Subgroup Γ) :
    Subgroup (Subgroup.normalizer (S : Set Γ)) :=
  (okuyamaWajimaFixedPoints K S).subgroupOf
    (Subgroup.normalizer (S : Set Γ))

/-- The copy of `S` inside its normalizer. -/
abbrev okuyamaWajimaInternalSylow
    (S : Subgroup Γ) :
    Subgroup (Subgroup.normalizer (S : Set Γ)) :=
  S.subgroupOf (Subgroup.normalizer (S : Set Γ))

/-- An ambient Sylow subgroup, regarded as a Sylow subgroup of its
normalizer. -/
def okuyamaWajimaSylowInNormalizer
    (S : Sylow p Γ) :
    Sylow p (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ)) :=
  S.subtype Subgroup.le_normalizer

omit [Finite Γ] [Fact p.Prime] in
@[simp, norm_cast]
theorem coe_okuyamaWajimaSylowInNormalizer
    (S : Sylow p Γ) :
    (okuyamaWajimaSylowInNormalizer S :
        Subgroup
          (Subgroup.normalizer
            ((S : Subgroup Γ) : Set Γ))) =
      okuyamaWajimaInternalSylow (S : Subgroup Γ) :=
  rfl

/-- The normal product `K ⊔ S`, viewed inside the Sylow normalizer. -/
abbrev okuyamaWajimaInternalNormalProduct
    (K S : Subgroup Γ) :
    Subgroup (Subgroup.normalizer (S : Set Γ)) :=
  (K ⊔ S).subgroupOf
    (Subgroup.normalizer (S : Set Γ))

omit [Fact p.Prime] in
/-- The ambient form of the key normalizer intersection identity:
`N_Γ(S) ∩ (K ⊔ S) = (K ∩ C_Γ(S)) ⊔ S`. -/
theorem normalizer_inf_normalProduct_eq_fixedPoints_sup
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K) :
    Subgroup.normalizer (S : Set Γ) ⊓
        (K ⊔ (S : Subgroup Γ)) =
      okuyamaWajimaFixedPoints K (S : Subgroup Γ) ⊔
        (S : Subgroup Γ) := by
  apply le_antisymm
  · intro g hg
    obtain ⟨k, hkK, s, hsS, hks⟩ :=
      Subgroup.mem_sup_of_normal_left.mp hg.2
    have hsN :
        s ∈ Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ) :=
      Subgroup.le_normalizer hsS
    have hkN :
        k ∈ Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ) := by
      have hkEq : k = g * s⁻¹ := by
        rw [← hks]
        group
      rw [hkEq]
      exact mul_mem hg.1 (inv_mem hsN)
    have hkC :
        k ∈ Subgroup.centralizer
          ((S : Subgroup Γ) : Set Γ) :=
      inf_normalizer_le_centralizer_of_normal_isPPrime
        (p := p) (S : Subgroup Γ) K S.isPGroup' hK
        ⟨hkK, hkN⟩
    rw [← hks]
    exact
      (okuyamaWajimaFixedPoints K
            (S : Subgroup Γ) ⊔
          (S : Subgroup Γ)).mul_mem
        ((show
          okuyamaWajimaFixedPoints K (S : Subgroup Γ) ≤
            okuyamaWajimaFixedPoints K (S : Subgroup Γ) ⊔
              (S : Subgroup Γ) from
          le_sup_left) ⟨hkK, hkC⟩)
        ((show
          (S : Subgroup Γ) ≤
            okuyamaWajimaFixedPoints K (S : Subgroup Γ) ⊔
              (S : Subgroup Γ) from
          le_sup_right) hsS)
  · exact le_inf
      (sup_le
        (inf_le_right.trans
          (Subgroup.centralizer_le_normalizer
            ((S : Subgroup Γ) : Set Γ)))
        Subgroup.le_normalizer)
      (sup_le
        (inf_le_left.trans le_sup_left)
        le_sup_right)

omit [Fact p.Prime] in
/-- Internally to `N_Γ(S)`, the intersection identity says that the
normal product is generated by `D` and `S`. -/
theorem internalNormalProduct_eq_fixedPoints_sup_sylow
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K) :
    okuyamaWajimaInternalNormalProduct
        K (S : Subgroup Γ) =
      okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ) ⊔
        okuyamaWajimaInternalSylow
          (S : Subgroup Γ) := by
  rw [← Subgroup.subgroupOf_sup
    (show
      okuyamaWajimaFixedPoints K (S : Subgroup Γ) ≤
        Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ) from
      inf_le_right.trans
        (Subgroup.centralizer_le_normalizer
          ((S : Subgroup Γ) : Set Γ)))
    (show
      (S : Subgroup Γ) ≤
        Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ) from
      Subgroup.le_normalizer)]
  ext x
  change
    (x : Γ) ∈ K ⊔ (S : Subgroup Γ) ↔
      (x : Γ) ∈
        okuyamaWajimaFixedPoints K
            (S : Subgroup Γ) ⊔
          (S : Subgroup Γ)
  rw [← normalizer_inf_normalProduct_eq_fixedPoints_sup
    S K hK]
  constructor
  · intro hx
    exact ⟨x.property, hx⟩
  · exact fun hx => hx.2

omit [Finite Γ] in
/-- The fixed-point subgroup is normal inside the Sylow normalizer. -/
theorem internalFixedPoints_normal
    (K S : Subgroup Γ) [K.Normal] :
    (okuyamaWajimaInternalFixedPoints K S).Normal :=
  Subgroup.normal_subgroupOf_of_le_normalizer
    (normalizer_le_normalizer_inf_centralizer K S)

omit [Finite Γ] in
/-- If `K ⊔ S` is normal in `Γ`, its copy inside `N_Γ(S)` is normal. -/
theorem internalNormalProduct_normal
    (K S : Subgroup Γ)
    (hKS : (K ⊔ S).Normal) :
    (okuyamaWajimaInternalNormalProduct K S).Normal :=
  hKS.subgroupOf _

omit [Fact p.Prime] in
/-- Under the normal-product hypothesis, `D ⊔ S` is normal inside the
Sylow normalizer. -/
theorem internalFixedPoints_sup_sylow_normal
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ) ⊔
      okuyamaWajimaInternalSylow (S : Subgroup Γ)).Normal := by
  rw [← internalNormalProduct_eq_fixedPoints_sup_sylow S K hK]
  exact internalNormalProduct_normal K (S : Subgroup Γ) hKS

/-- Modulo `D`, the subgroup `D ⊔ S` is a normal Sylow subgroup of
`N_Γ(S) / D`. -/
theorem okuyamaWajimaQuotientSylow_normal
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    letI :
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ)).Normal :=
      internalFixedPoints_normal K (S : Subgroup Γ)
    (normalProductQuotientSylow
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ))
        (okuyamaWajimaSylowInNormalizer S) :
      Subgroup
        (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) ⧸
          okuyamaWajimaInternalFixedPoints
            K (S : Subgroup Γ))).Normal := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  apply normalProductQuotientSylow_normal
  rw [coe_okuyamaWajimaSylowInNormalizer]
  exact internalFixedPoints_sup_sylow_normal S K hK hKS

/-- Schur--Zassenhaus in `H / D`: the image of `D ⊔ S` has a quotient
complement.  This is the existence statement underlying the chosen
complement below. -/
theorem exists_okuyamaWajimaQuotientComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    letI :
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ)).Normal :=
      internalFixedPoints_normal K (S : Subgroup Γ)
    ∃ Ubar : Subgroup
        (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) ⧸
          okuyamaWajimaInternalFixedPoints
            K (S : Subgroup Γ)),
      (normalProductQuotientSylow
          (okuyamaWajimaInternalFixedPoints
            K (S : Subgroup Γ))
          (okuyamaWajimaSylowInNormalizer S) :
        Subgroup
          (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) ⧸
            okuyamaWajimaInternalFixedPoints
              K (S : Subgroup Γ))).IsComplement' Ubar := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  letI :
      (normalProductQuotientSylow
          (okuyamaWajimaInternalFixedPoints
            K (S : Subgroup Γ))
          (okuyamaWajimaSylowInNormalizer S) :
        Subgroup
          (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) ⧸
            okuyamaWajimaInternalFixedPoints
              K (S : Subgroup Γ))).Normal :=
    okuyamaWajimaQuotientSylow_normal S K hK hKS
  exact Subgroup.exists_right_complement'_of_coprime
    (normalProductQuotientSylow
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ))
      (okuyamaWajimaSylowInNormalizer S)).card_coprime_index

/-- A chosen Schur--Zassenhaus complement to the normal quotient Sylow
subgroup in `N_Γ(S) / D`. -/
def okuyamaWajimaQuotientComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    letI :
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ)).Normal :=
      internalFixedPoints_normal K (S : Subgroup Γ)
    Subgroup
      (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) ⧸
        okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ)) := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  exact Classical.choose
    (exists_okuyamaWajimaQuotientComplement S K hK hKS)

/-- The chosen quotient subgroup is complementary to the quotient Sylow. -/
theorem okuyamaWajimaQuotientComplement_isComplement'
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    letI :
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ)).Normal :=
      internalFixedPoints_normal K (S : Subgroup Γ)
    (normalProductQuotientSylow
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ))
        (okuyamaWajimaSylowInNormalizer S) :
      Subgroup
        (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) ⧸
          okuyamaWajimaInternalFixedPoints
            K (S : Subgroup Γ))).IsComplement'
      (okuyamaWajimaQuotientComplement S K hK hKS) := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  exact Classical.choose_spec
    (exists_okuyamaWajimaQuotientComplement S K hK hKS)

/-- The full preimage in `N_Γ(S)` of the chosen quotient complement. -/
def okuyamaWajimaComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    Subgroup
      (Subgroup.normalizer ((S : Subgroup Γ) : Set Γ)) := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  exact quotientComplementLift
    (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ))
    (okuyamaWajimaQuotientComplement S K hK hKS)

/-- Mapping the internal normal product to `H / D` gives the quotient
Sylow subgroup. -/
theorem map_internalNormalProduct_eq_quotientSylow
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K) :
    letI :
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ)).Normal :=
      internalFixedPoints_normal K (S : Subgroup Γ)
    (okuyamaWajimaInternalNormalProduct
        K (S : Subgroup Γ)).map
          (QuotientGroup.mk'
            (okuyamaWajimaInternalFixedPoints
              K (S : Subgroup Γ))) =
      (normalProductQuotientSylow
        (okuyamaWajimaInternalFixedPoints
          K (S : Subgroup Γ))
        (okuyamaWajimaSylowInNormalizer S) :
          Subgroup
            (Subgroup.normalizer
                ((S : Subgroup Γ) : Set Γ) ⧸
              okuyamaWajimaInternalFixedPoints
                K (S : Subgroup Γ))) := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  rw [internalNormalProduct_eq_fixedPoints_sup_sylow S K hK,
    ← coe_okuyamaWajimaSylowInNormalizer]
  exact map_normalProduct_eq_normalProductQuotientSylow
    (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ))
    (okuyamaWajimaSylowInNormalizer S)

/-- The fixed-point subgroup `D` is contained in the lifted complement. -/
theorem internalFixedPoints_le_okuyamaWajimaComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ) ≤
      okuyamaWajimaComplement S K hK hKS := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  change
    okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ) ≤
      quotientComplementLift
        (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ))
        (okuyamaWajimaQuotientComplement S K hK hKS)
  exact normal_le_quotientComplementLift _ _

omit [Finite Γ] in
/-- The internal fixed-point subgroup lies in the internal normal product. -/
theorem internalFixedPoints_le_internalNormalProduct
    (K S : Subgroup Γ) :
    okuyamaWajimaInternalFixedPoints K S ≤
      okuyamaWajimaInternalNormalProduct K S :=
  Subgroup.subgroupOf_mono
    (Subgroup.normalizer (S : Set Γ))
    (inf_le_left.trans le_sup_left)

/-- The internal normal product and the lifted complement generate the
whole Sylow normalizer. -/
theorem internalNormalProduct_sup_okuyamaWajimaComplement_eq_top
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    okuyamaWajimaInternalNormalProduct K (S : Subgroup Γ) ⊔
        okuyamaWajimaComplement S K hK hKS =
      ⊤ := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  change
    okuyamaWajimaInternalNormalProduct K (S : Subgroup Γ) ⊔
        quotientComplementLift
          (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ))
          (okuyamaWajimaQuotientComplement S K hK hKS) =
      ⊤
  apply quotientComplementLift_sup_eq_top
    (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ))
    (okuyamaWajimaInternalNormalProduct K (S : Subgroup Γ))
    (internalFixedPoints_le_internalNormalProduct
      K (S : Subgroup Γ))
    (okuyamaWajimaQuotientComplement S K hK hKS)
  rw [map_internalNormalProduct_eq_quotientSylow S K hK]
  exact okuyamaWajimaQuotientComplement_isComplement'
    S K hK hKS

/-- The internal normal product meets the lifted complement exactly in
the fixed-point subgroup. -/
theorem internalNormalProduct_inf_okuyamaWajimaComplement_eq_fixedPoints
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    okuyamaWajimaInternalNormalProduct K (S : Subgroup Γ) ⊓
        okuyamaWajimaComplement S K hK hKS =
      okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ) := by
  letI :
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).Normal :=
    internalFixedPoints_normal K (S : Subgroup Γ)
  change
    okuyamaWajimaInternalNormalProduct K (S : Subgroup Γ) ⊓
        quotientComplementLift
          (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ))
          (okuyamaWajimaQuotientComplement S K hK hKS) =
      okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ)
  apply quotientComplementLift_inf_eq_normal
    (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ))
    (okuyamaWajimaInternalNormalProduct K (S : Subgroup Γ))
    (internalFixedPoints_le_internalNormalProduct
      K (S : Subgroup Γ))
    (okuyamaWajimaQuotientComplement S K hK hKS)
  rw [map_internalNormalProduct_eq_quotientSylow S K hK]
  exact okuyamaWajimaQuotientComplement_isComplement'
    S K hK hKS

/-- Product form with the internal factors displayed explicitly:
`(D ⊔ S) ⊔ U = H`. -/
theorem internalFixedPoints_sup_sylow_sup_complement_eq_top
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ) ⊔
          okuyamaWajimaInternalSylow (S : Subgroup Γ)) ⊔
        okuyamaWajimaComplement S K hK hKS =
      ⊤ := by
  rw [← internalNormalProduct_eq_fixedPoints_sup_sylow S K hK]
  exact internalNormalProduct_sup_okuyamaWajimaComplement_eq_top
    S K hK hKS

/-- Intersection form with the internal factors displayed explicitly:
`(D ⊔ S) ∩ U = D`. -/
theorem internalFixedPoints_sup_sylow_inf_complement_eq_fixedPoints
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ) ⊔
          okuyamaWajimaInternalSylow (S : Subgroup Γ)) ⊓
        okuyamaWajimaComplement S K hK hKS =
      okuyamaWajimaInternalFixedPoints K (S : Subgroup Γ) := by
  rw [← internalNormalProduct_eq_fixedPoints_sup_sylow S K hK]
  exact internalNormalProduct_inf_okuyamaWajimaComplement_eq_fixedPoints
    S K hK hKS

/-- In the normal-product restriction setup, the intersection subgroup
inside `U` is literally the copy of `D` inside `U`. -/
theorem internalNormalProduct_subgroupOf_complement_eq_fixedPoints_subgroupOf
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (okuyamaWajimaInternalNormalProduct
        K (S : Subgroup Γ)).subgroupOf
          (okuyamaWajimaComplement S K hK hKS) =
      (okuyamaWajimaInternalFixedPoints
        K (S : Subgroup Γ)).subgroupOf
          (okuyamaWajimaComplement S K hK hKS) := by
  ext x
  change
    (x :
      Subgroup.normalizer ((S : Subgroup Γ) : Set Γ)) ∈
        okuyamaWajimaInternalNormalProduct
          K (S : Subgroup Γ) ↔
      (x :
        Subgroup.normalizer ((S : Subgroup Γ) : Set Γ)) ∈
          okuyamaWajimaInternalFixedPoints
            K (S : Subgroup Γ)
  rw [← internalNormalProduct_inf_okuyamaWajimaComplement_eq_fixedPoints
    S K hK hKS]
  exact ⟨fun hx => ⟨hx, x.property⟩, fun hx => hx.1⟩

/-- The lifted complement, mapped from `N_Γ(S)` back into `Γ`. -/
def okuyamaWajimaAmbientComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    Subgroup Γ :=
  (okuyamaWajimaComplement S K hK hKS).map
    (Subgroup.normalizer
      ((S : Subgroup Γ) : Set Γ)).subtype

/-- The canonical equivalence from the complement inside `N_Γ(S)` to its
ambient image in `Γ`. -/
def okuyamaWajimaComplementEquivAmbientComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    okuyamaWajimaComplement S K hK hKS ≃*
      okuyamaWajimaAmbientComplement S K hK hKS :=
  (okuyamaWajimaComplement S K hK hKS).equivMapOfInjective
    (Subgroup.normalizer
      ((S : Subgroup Γ) : Set Γ)).subtype
    (Subgroup.normalizer
      ((S : Subgroup Γ) : Set Γ)).subtype_injective

@[simp]
theorem coe_okuyamaWajimaComplementEquivAmbientComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal)
    (u : okuyamaWajimaComplement S K hK hKS) :
    ((okuyamaWajimaComplementEquivAmbientComplement
        S K hK hKS u :
      okuyamaWajimaAmbientComplement S K hK hKS) : Γ) =
      (u :
        Subgroup.normalizer ((S : Subgroup Γ) : Set Γ)) :=
  rfl

/-- The ambient complement lies in the Sylow normalizer. -/
theorem okuyamaWajimaAmbientComplement_le_normalizer
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    okuyamaWajimaAmbientComplement S K hK hKS ≤
      Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) :=
  (Subgroup.map_le_range
    (Subgroup.normalizer
      ((S : Subgroup Γ) : Set Γ)).subtype
    (okuyamaWajimaComplement S K hK hKS)).trans_eq
      (Subgroup.normalizer
        ((S : Subgroup Γ) : Set Γ)).range_subtype

omit [Finite Γ] in
/-- Mapping the internal fixed points back to `Γ` recovers `D`. -/
theorem map_internalFixedPoints_subtype
    (K S : Subgroup Γ) :
    (okuyamaWajimaInternalFixedPoints K S).map
        (Subgroup.normalizer (S : Set Γ)).subtype =
      okuyamaWajimaFixedPoints K S :=
  Subgroup.map_subgroupOf_eq_of_le
    (inf_le_right.trans
      (Subgroup.centralizer_le_normalizer (S : Set Γ)))

omit [Finite Γ] in
/-- Mapping the internal Sylow subgroup back to `Γ` recovers `S`. -/
theorem map_internalSylow_subtype
    (S : Subgroup Γ) :
    (okuyamaWajimaInternalSylow S).map
        (Subgroup.normalizer (S : Set Γ)).subtype =
      S :=
  Subgroup.map_subgroupOf_eq_of_le Subgroup.le_normalizer

/-- The ambient fixed-point subgroup lies in the ambient complement. -/
theorem fixedPoints_le_okuyamaWajimaAmbientComplement
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    okuyamaWajimaFixedPoints K (S : Subgroup Γ) ≤
      okuyamaWajimaAmbientComplement S K hK hKS := by
  rw [← map_internalFixedPoints_subtype
    K (S : Subgroup Γ)]
  exact Subgroup.map_mono
    (internalFixedPoints_le_okuyamaWajimaComplement
      S K hK hKS)

/-- Ambient product form:
`(D ⊔ S) ⊔ U = N_Γ(S)`. -/
theorem fixedPoints_sup_sylow_sup_ambientComplement_eq_normalizer
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (okuyamaWajimaFixedPoints K (S : Subgroup Γ) ⊔
          (S : Subgroup Γ)) ⊔
        okuyamaWajimaAmbientComplement S K hK hKS =
      Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) := by
  have hmap :=
    congrArg
      (Subgroup.map
        (Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ)).subtype)
      (internalFixedPoints_sup_sylow_sup_complement_eq_top
        S K hK hKS)
  have htop :
      (⊤ : Subgroup
          (Subgroup.normalizer
            ((S : Subgroup Γ) : Set Γ))).map
          (Subgroup.normalizer
            ((S : Subgroup Γ) : Set Γ)).subtype =
        Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) := by
    calc
      (⊤ : Subgroup
          (Subgroup.normalizer
            ((S : Subgroup Γ) : Set Γ))).map
            (Subgroup.normalizer
              ((S : Subgroup Γ) : Set Γ)).subtype =
          (Subgroup.normalizer
            ((S : Subgroup Γ) : Set Γ)).subtype.range :=
        (MonoidHom.range_eq_map _).symm
      _ = Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) :=
        (Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ)).range_subtype
  simpa only [Subgroup.map_sup,
    map_internalFixedPoints_subtype,
    map_internalSylow_subtype,
    okuyamaWajimaAmbientComplement,
    htop] using hmap

/-- Ambient intersection form:
`(D ⊔ S) ∩ U = D`. -/
theorem fixedPoints_sup_sylow_inf_ambientComplement_eq_fixedPoints
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (okuyamaWajimaFixedPoints K (S : Subgroup Γ) ⊔
          (S : Subgroup Γ)) ⊓
        okuyamaWajimaAmbientComplement S K hK hKS =
      okuyamaWajimaFixedPoints K (S : Subgroup Γ) := by
  have hmap :=
    congrArg
      (Subgroup.map
        (Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ)).subtype)
      (internalFixedPoints_sup_sylow_inf_complement_eq_fixedPoints
        S K hK hKS)
  rw [Subgroup.map_inf _ _
      (Subgroup.normalizer
        ((S : Subgroup Γ) : Set Γ)).subtype
      (Subgroup.normalizer
        ((S : Subgroup Γ) : Set Γ)).subtype_injective,
    Subgroup.map_sup,
    map_internalFixedPoints_subtype,
    map_internalSylow_subtype] at hmap
  simpa only [okuyamaWajimaAmbientComplement] using hmap

/-- The ambient complement has precisely the fixed points as its
intersection with the normal `p′`-kernel: `K ∩ U = D`. -/
theorem pPrimeKernel_inf_ambientComplement_eq_fixedPoints
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    K ⊓ okuyamaWajimaAmbientComplement S K hK hKS =
      okuyamaWajimaFixedPoints K (S : Subgroup Γ) :=
  pPrimeKernel_inf_eq_fixedPoints
    K (S : Subgroup Γ) S.isPGroup' hK
    (okuyamaWajimaAmbientComplement S K hK hKS)
    (okuyamaWajimaAmbientComplement_le_normalizer
      S K hK hKS)
    (fixedPoints_le_okuyamaWajimaAmbientComplement
      S K hK hKS)

/-- Inside the ambient complement, the copy of `K` is literally the copy
of `D`.  This is the subgroup identity expected by the OW quotient API. -/
theorem pPrimeKernel_subgroupOf_ambientComplement_eq_fixedPoints_subgroupOf
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    K.subgroupOf
        (okuyamaWajimaAmbientComplement S K hK hKS) =
      (okuyamaWajimaFixedPoints
        K (S : Subgroup Γ)).subgroupOf
          (okuyamaWajimaAmbientComplement S K hK hKS) :=
  pPrimeKernel_subgroupOf_eq_fixedPoints_subgroupOf
    K (S : Subgroup Γ) S.isPGroup' hK
    (okuyamaWajimaAmbientComplement S K hK hKS)
    (okuyamaWajimaAmbientComplement_le_normalizer
      S K hK hKS)
    (fixedPoints_le_okuyamaWajimaAmbientComplement
      S K hK hKS)

/-- The source-side normal-product identity used in the base-count
argument:

`(K ⊔ S) ⊔ (U ⊔ K) = Γ`.

Here `U` is the ambient image of the chosen complement. -/
theorem normalProduct_sup_ambientComplement_sup_kernel_eq_top
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (K ⊔ (S : Subgroup Γ)) ⊔
        (okuyamaWajimaAmbientComplement S K hK hKS ⊔ K) =
      ⊤ := by
  letI : (K ⊔ (S : Subgroup Γ)).Normal := hKS
  have hfrattini :
      Subgroup.normalizer ((S : Subgroup Γ) : Set Γ) ⊔
          (K ⊔ (S : Subgroup Γ)) =
        ⊤ :=
    Sylow.normalizer_sup_eq_top' S le_sup_right
  apply top_unique
  rw [← hfrattini]
  apply sup_le
  · rw [← fixedPoints_sup_sylow_sup_ambientComplement_eq_normalizer
      S K hK hKS]
    exact sup_le
      (sup_le
        ((inf_le_left.trans le_sup_left).trans le_sup_left)
        (le_sup_right.trans le_sup_left))
      (le_sup_left.trans le_sup_right)
  · exact le_sup_left

/-- The source-side intersection identity:

`(K ⊔ S) ∩ (U ⊔ K) = K`. -/
theorem normalProduct_inf_ambientComplement_sup_kernel_eq_kernel
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (K ⊔ (S : Subgroup Γ)) ⊓
        (okuyamaWajimaAmbientComplement S K hK hKS ⊔ K) =
      K := by
  apply le_antisymm
  · intro x hx
    obtain ⟨u, huU, k, hkK, huk⟩ :=
      Subgroup.mem_sup_of_normal_right.mp hx.2
    have hkM :
        k ∈ K ⊔ (S : Subgroup Γ) :=
      (show
        K ≤ K ⊔ (S : Subgroup Γ) from
        le_sup_left) hkK
    have huM :
        u ∈ K ⊔ (S : Subgroup Γ) := by
      have huEq : u = x * k⁻¹ := by
        rw [← huk]
        group
      rw [huEq]
      exact mul_mem hx.1 (inv_mem hkM)
    have huH :
        u ∈ Subgroup.normalizer
          ((S : Subgroup Γ) : Set Γ) :=
      okuyamaWajimaAmbientComplement_le_normalizer
        S K hK hKS huU
    have huDS :
        u ∈
          okuyamaWajimaFixedPoints K (S : Subgroup Γ) ⊔
            (S : Subgroup Γ) := by
      rw [← normalizer_inf_normalProduct_eq_fixedPoints_sup
        S K hK]
      exact ⟨huH, huM⟩
    have huD :
        u ∈ okuyamaWajimaFixedPoints K (S : Subgroup Γ) := by
      have hu :
          u ∈
            (okuyamaWajimaFixedPoints K (S : Subgroup Γ) ⊔
                (S : Subgroup Γ)) ⊓
              okuyamaWajimaAmbientComplement S K hK hKS :=
        ⟨huDS, huU⟩
      rw [fixedPoints_sup_sylow_inf_ambientComplement_eq_fixedPoints
        S K hK hKS] at hu
      exact hu
    rw [← huk]
    exact K.mul_mem huD.1 hkK
  · exact le_inf le_sup_left le_sup_right

/-- The internal intersection copy for source normal-product restriction is
literally the copy of `K` inside `U ⊔ K`. -/
theorem normalProduct_subgroupOf_ambientComplement_sup_kernel_eq
    (S : Sylow p Γ)
    (K : Subgroup Γ) [K.Normal]
    (hK : IsPPrimeGroup p K)
    (hKS : (K ⊔ (S : Subgroup Γ)).Normal) :
    (K ⊔ (S : Subgroup Γ)).subgroupOf
        (okuyamaWajimaAmbientComplement S K hK hKS ⊔ K) =
      K.subgroupOf
        (okuyamaWajimaAmbientComplement S K hK hKS ⊔ K) := by
  ext x
  change
    (x : Γ) ∈ K ⊔ (S : Subgroup Γ) ↔
      (x : Γ) ∈ K
  have hmem :
      ((x : Γ) ∈
          (K ⊔ (S : Subgroup Γ)) ⊓
            (okuyamaWajimaAmbientComplement S K hK hKS ⊔ K)) =
        ((x : Γ) ∈ K) :=
    congrArg
      (fun L : Subgroup Γ => (x : Γ) ∈ L)
      (normalProduct_inf_ambientComplement_sup_kernel_eq_kernel
        S K hK hKS)
  exact
    ⟨fun hx => Eq.mp hmem ⟨hx, x.property⟩,
      fun hx => (Eq.mpr hmem hx).1⟩

end GroupTheory
end McKayConjecture
