/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import McKayConjecture.GroupTheory.QuaternionGroupHom

/-!
# Injectivity criteria for dicyclic lifts

The constructor `QuaternionGroup.lift` produces a homomorphism from the
standard dicyclic relations.  This file supplies the complementary
injectivity criterion: the cyclic generator must have exact order `2n`,
and the second generator must lie outside its cyclic subgroup.
-/

namespace QuaternionGroup

variable {H : Type*} [Group H]

/-- `ZMod`-indexed powers are injective when their chosen generator has
the advertised exact order. -/
theorem zmodPower_injective_of_orderOf_eq
    {m : ℕ} (A : H) (hA : A ^ m = 1)
    (horder : orderOf A = m) :
    Function.Injective (zmodPower A hA) := by
  intro i j hij
  obtain ⟨a, rfl⟩ := ZMod.intCast_surjective i
  obtain ⟨b, rfl⟩ := ZMod.intCast_surjective j
  rw [zmodPower_intCast, zmodPower_intCast] at hij
  rw [ZMod.intCast_eq_intCast_iff]
  rw [← horder]
  exact zpow_eq_zpow_iff_modEq.mp hij

/-- Every `ZMod`-indexed power lies in the cyclic subgroup generated by
the chosen element. -/
theorem zmodPower_mem_zpowers
    {m : ℕ} (A : H) (hA : A ^ m = 1)
    (i : ZMod m) :
    zmodPower A hA i ∈ Subgroup.zpowers A := by
  obtain ⟨z, rfl⟩ := ZMod.intCast_surjective i
  rw [zmodPower_intCast]
  exact Subgroup.mem_zpowers_iff.mpr ⟨z, rfl⟩

/-- A dicyclic lift is injective if its cyclic generator has exact order
`2n` and the second generator is not a power of it. -/
theorem lift_injective_of_orderOf_eq
    {n : ℕ}
    (A X : H)
    (hA : A ^ (2 * n) = 1)
    (hXsq : X * X = zmodPower A hA n)
    (hconj :
      ∀ i : ZMod (2 * n),
        zmodPower A hA i * X =
          X * zmodPower A hA (-i))
    (horder : orderOf A = 2 * n)
    (hXnot : X ∉ Subgroup.zpowers A) :
    Function.Injective (lift A X hA hXsq hconj) := by
  intro g h hgh
  rcases g with i | i <;>
    rcases h with j | j
  · apply congrArg QuaternionGroup.a
    apply zmodPower_injective_of_orderOf_eq A hA horder
    exact hgh
  · exfalso
    apply hXnot
    have hsolve :
        X =
          zmodPower A hA i *
            (zmodPower A hA j)⁻¹ := by
      change
        zmodPower A hA i =
          X * zmodPower A hA j at hgh
      rw [hgh]
      group
    rw [hsolve]
    exact
      (Subgroup.zpowers A).mul_mem
        (zmodPower_mem_zpowers A hA i)
        ((Subgroup.zpowers A).inv_mem
          (zmodPower_mem_zpowers A hA j))
  · exfalso
    apply hXnot
    have hsolve :
        X =
          zmodPower A hA j *
            (zmodPower A hA i)⁻¹ := by
      change
        X * zmodPower A hA i =
          zmodPower A hA j at hgh
      rw [← hgh]
      group
    rw [hsolve]
    exact
      (Subgroup.zpowers A).mul_mem
        (zmodPower_mem_zpowers A hA j)
        ((Subgroup.zpowers A).inv_mem
          (zmodPower_mem_zpowers A hA i))
  · apply congrArg QuaternionGroup.xa
    apply zmodPower_injective_of_orderOf_eq A hA horder
    change
      X * zmodPower A hA i =
        X * zmodPower A hA j at hgh
    exact mul_left_cancel hgh

end QuaternionGroup
