/-
Copyright (c) 2026 Clawristotle contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Clawristotle contributors
-/
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
import Mathlib.Tactic
import Mathlib.GroupTheory.Sylow
import Mathlib.GroupTheory.IsPerfect

/-!
# The concrete group `SL(2, 𝔽₅)`

This file supplies the first computational data needed to use
`SL(2, ZMod 5)` as the binary cover of `A₅`.

It proves that the group has order `120` and is perfect, and gives literal
Sylow subgroups at `2`, `3`, and `5`.  The odd Sylow subgroups are generated
by explicit matrices.  The Sylow `2`-subgroup is the eight-element quaternion
subgroup

`{±1, ±i, ±j, ±ij}`.

All matrix identities are kernel-checked finite computations.
-/

noncomputable section

open Matrix
open scoped MatrixGroups

namespace McKayConjecture
namespace GroupTheory

local instance : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
local instance : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
local instance : Fact (Nat.Prime 5) := ⟨Nat.prime_five⟩

/-- The concrete binary-icosahedral candidate `SL(2, 𝔽₅)`. -/
abbrev SpecialLinearTwoFive :=
  SL(2, ZMod 5)

/-- `SL(2, 𝔽₅)` has order `120`. -/
theorem natCard_specialLinearTwoFive :
    Nat.card SpecialLinearTwoFive = 120 := by
  rw [Nat.card_eq_fintype_card]
  native_decide

/-- A diagonal parameter witnessing the perfectness criterion for
`SL(2, 𝔽₅)`. -/
theorem two_ne_zero_and_sq_ne_one_in_zmod_five :
    (2 : ZMod 5) ≠ 0 ∧ (2 : ZMod 5) ^ 2 ≠ 1 := by
  native_decide

/-- `SL(2, 𝔽₅)` is perfect. -/
instance specialLinearTwoFive_isPerfect :
    Group.IsPerfect SpecialLinearTwoFive where
  commutator_eq_top :=
    Matrix.SL2.commutator_eq_top
      two_ne_zero_and_sq_ne_one_in_zmod_five.1
      two_ne_zero_and_sq_ne_one_in_zmod_five.2

/-! ## Explicit odd Sylow subgroups -/

/-- The upper-unitriangular element `[[1,1],[0,1]]`, of order five. -/
def specialLinearTwoFive_orderFiveElement :
    SpecialLinearTwoFive :=
  ⟨!![(1 : ZMod 5), 1; 0, 1], by native_decide⟩

theorem orderOf_specialLinearTwoFive_orderFiveElement :
    orderOf specialLinearTwoFive_orderFiveElement = 5 :=
  orderOf_eq_prime (by native_decide) (by native_decide)

/-- The five elements of the explicit cyclic subgroup, in computational
form. -/
def specialLinearTwoFiveFiveSubgroupElements :
    Finset SpecialLinearTwoFive :=
  (Finset.range 5).image
    (specialLinearTwoFive_orderFiveElement ^ ·)

/-- The explicit cyclic Sylow `5`-subgroup generated by
`[[1,1],[0,1]]`. -/
def specialLinearTwoFiveSylowFive :
    Sylow 5 SpecialLinearTwoFive :=
  Sylow.ofCard
    (Subgroup.zpowers specialLinearTwoFive_orderFiveElement) (by
      rw [Nat.card_zpowers,
        orderOf_specialLinearTwoFive_orderFiveElement,
        natCard_specialLinearTwoFive]
      native_decide)

/-- The carrier of the chosen Sylow `5`-subgroup is the explicit five-row
finite table above. -/
theorem coe_specialLinearTwoFiveSylowFive :
    (specialLinearTwoFiveSylowFive :
      Set SpecialLinearTwoFive) =
      specialLinearTwoFiveFiveSubgroupElements := by
  ext x
  change
    x ∈ Subgroup.zpowers specialLinearTwoFive_orderFiveElement ↔
      x ∈ specialLinearTwoFiveFiveSubgroupElements
  rw [mem_zpowers_iff_mem_range_orderOf,
    orderOf_specialLinearTwoFive_orderFiveElement]
  rfl

/-- The element `[[0,-1],[1,-1]]`, of order three. -/
def specialLinearTwoFive_orderThreeElement :
    SpecialLinearTwoFive :=
  ⟨!![(0 : ZMod 5), -1; 1, -1], by native_decide⟩

theorem orderOf_specialLinearTwoFive_orderThreeElement :
    orderOf specialLinearTwoFive_orderThreeElement = 3 :=
  orderOf_eq_prime (by native_decide) (by native_decide)

/-- The three elements of the explicit cyclic subgroup, in computational
form. -/
def specialLinearTwoFiveThreeSubgroupElements :
    Finset SpecialLinearTwoFive :=
  (Finset.range 3).image
    (specialLinearTwoFive_orderThreeElement ^ ·)

/-- The explicit cyclic Sylow `3`-subgroup generated by
`[[0,-1],[1,-1]]`. -/
def specialLinearTwoFiveSylowThree :
    Sylow 3 SpecialLinearTwoFive :=
  Sylow.ofCard
    (Subgroup.zpowers specialLinearTwoFive_orderThreeElement) (by
      rw [Nat.card_zpowers,
        orderOf_specialLinearTwoFive_orderThreeElement,
        natCard_specialLinearTwoFive]
      native_decide)

/-- The carrier of the chosen Sylow `3`-subgroup is the explicit three-row
finite table above. -/
theorem coe_specialLinearTwoFiveSylowThree :
    (specialLinearTwoFiveSylowThree :
      Set SpecialLinearTwoFive) =
      specialLinearTwoFiveThreeSubgroupElements := by
  ext x
  change
    x ∈ Subgroup.zpowers specialLinearTwoFive_orderThreeElement ↔
      x ∈ specialLinearTwoFiveThreeSubgroupElements
  rw [mem_zpowers_iff_mem_range_orderOf,
    orderOf_specialLinearTwoFive_orderThreeElement]
  rfl

/-! ## An explicit quaternion Sylow `2`-subgroup -/

/-- The quaternion generator `i = [[0,1],[-1,0]]`. -/
def specialLinearTwoFiveQuaternionI :
    SpecialLinearTwoFive :=
  ⟨!![(0 : ZMod 5), 1; -1, 0], by native_decide⟩

/-- The quaternion generator `j = [[2,0],[0,-2]]`. -/
def specialLinearTwoFiveQuaternionJ :
    SpecialLinearTwoFive :=
  ⟨!![(2 : ZMod 5), 0; 0, -2], by native_decide⟩

/-- The third quaternion generator `k = i j`. -/
def specialLinearTwoFiveQuaternionK :
    SpecialLinearTwoFive :=
  specialLinearTwoFiveQuaternionI * specialLinearTwoFiveQuaternionJ

/-- The eight quaternion elements as an executable finite table. -/
def specialLinearTwoFiveQuaternionElements :
    Finset SpecialLinearTwoFive :=
  {1, -1,
    specialLinearTwoFiveQuaternionI,
    -specialLinearTwoFiveQuaternionI,
    specialLinearTwoFiveQuaternionJ,
    -specialLinearTwoFiveQuaternionJ,
    specialLinearTwoFiveQuaternionK,
    -specialLinearTwoFiveQuaternionK}

/-- The literal eight-element quaternion subgroup
`{±1, ±i, ±j, ±k}` of `SL(2, 𝔽₅)`. -/
def specialLinearTwoFiveQuaternionSubgroup :
    Subgroup SpecialLinearTwoFive where
  carrier :=
    {1, -1,
      specialLinearTwoFiveQuaternionI,
      -specialLinearTwoFiveQuaternionI,
      specialLinearTwoFiveQuaternionJ,
      -specialLinearTwoFiveQuaternionJ,
      specialLinearTwoFiveQuaternionK,
      -specialLinearTwoFiveQuaternionK}
  one_mem' := by simp
  mul_mem' := by
    intro x y hx hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy ⊢
    rcases hx with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
      rcases hy with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
      native_decide
  inv_mem' := by
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx ⊢
    rcases hx with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
      native_decide

/-- The quaternion subgroup has exactly eight elements. -/
theorem natCard_specialLinearTwoFiveQuaternionSubgroup :
    Nat.card specialLinearTwoFiveQuaternionSubgroup = 8 := by
  change
    ({1, -1,
      specialLinearTwoFiveQuaternionI,
      -specialLinearTwoFiveQuaternionI,
      specialLinearTwoFiveQuaternionJ,
      -specialLinearTwoFiveQuaternionJ,
      specialLinearTwoFiveQuaternionK,
      -specialLinearTwoFiveQuaternionK} :
      Set SpecialLinearTwoFive).ncard = 8
  rw [Set.ncard_insert_of_notMem (by native_decide)]
  rw [Set.ncard_insert_of_notMem (by native_decide)]
  rw [Set.ncard_insert_of_notMem (by native_decide)]
  rw [Set.ncard_insert_of_notMem (by native_decide)]
  rw [Set.ncard_insert_of_notMem (by native_decide)]
  rw [Set.ncard_insert_of_notMem (by native_decide)]
  rw [Set.ncard_insert_of_notMem (by native_decide)]
  simp

/-- The explicit quaternion subgroup is a Sylow `2`-subgroup. -/
def specialLinearTwoFiveSylowTwo :
    Sylow 2 SpecialLinearTwoFive :=
  Sylow.ofCard specialLinearTwoFiveQuaternionSubgroup (by
    rw [natCard_specialLinearTwoFiveQuaternionSubgroup,
      natCard_specialLinearTwoFive]
    native_decide)

theorem coe_specialLinearTwoFiveSylowTwo :
    (specialLinearTwoFiveSylowTwo :
      Set SpecialLinearTwoFive) =
      specialLinearTwoFiveQuaternionElements := by
  ext x
  change
    x ∈ specialLinearTwoFiveQuaternionSubgroup ↔
      x ∈ specialLinearTwoFiveQuaternionElements
  simp [
    specialLinearTwoFiveQuaternionSubgroup,
    specialLinearTwoFiveQuaternionElements]

/-! ## Executable exact normalizers -/

/-- For a finite set in a finite group, enumerate the elements which
normalize it.  This is the computational form of `Subgroup.normalizer`. -/
def finiteSetNormalizer
    {G : Type*} [Group G] [Fintype G] [DecidableEq G]
    (s : Finset G) : Finset G :=
  Finset.univ.filter fun g ↦
    ∀ h : G, h ∈ s ↔ g * h * g⁻¹ ∈ s

/-- When `s` is the carrier table of a subgroup `H`,
`finiteSetNormalizer s` enumerates the carrier of `N_G(H)`. -/
theorem coe_finiteSetNormalizer
    {G : Type*} [Group G] [Fintype G] [DecidableEq G]
    (H : Subgroup G) (s : Finset G)
    (hs : (H : Set G) = s) :
    (Subgroup.normalizer (H : Set G) : Set G) =
      finiteSetNormalizer s := by
  ext g
  simp only [finiteSetNormalizer, Finset.mem_coe,
    Finset.mem_filter, Finset.mem_univ, true_and]
  have hmem (x : G) : x ∈ s ↔ x ∈ H := by
    change x ∈ (s : Set G) ↔ x ∈ (H : Set G)
    rw [hs]
  simp only [hmem]
  change
    g ∈ Subgroup.normalizer (H : Set G) ↔
      ∀ h : G,
        h ∈ (H : Set G) ↔
          g * h * g⁻¹ ∈ (H : Set G)
  exact
    Subgroup.mem_set_normalizer_iff

/-- The exact normalizer of the chosen quaternion Sylow subgroup has
order `24`. -/
theorem card_specialLinearTwoFiveSylowTwoNormalizerElements :
    (finiteSetNormalizer
      specialLinearTwoFiveQuaternionElements).card = 24 := by
  native_decide

/-- The exact normalizer of the chosen cyclic Sylow `3`-subgroup has
order `12`. -/
theorem card_specialLinearTwoFiveSylowThreeNormalizerElements :
    (finiteSetNormalizer
      specialLinearTwoFiveThreeSubgroupElements).card = 12 := by
  native_decide

/-- The exact normalizer of the chosen cyclic Sylow `5`-subgroup has
order `20`. -/
theorem card_specialLinearTwoFiveSylowFiveNormalizerElements :
    (finiteSetNormalizer
      specialLinearTwoFiveFiveSubgroupElements).card = 20 := by
  native_decide

/-- The normalizer subtype used by the inductive McKay condition at `2`
has order `24`. -/
theorem natCard_specialLinearTwoFiveSylowTwoNormalizer :
    Nat.card
      (Subgroup.normalizer
        (specialLinearTwoFiveSylowTwo :
          Set SpecialLinearTwoFive)) = 24 := by
  change
    (Subgroup.normalizer
      ((specialLinearTwoFiveSylowTwo :
        Subgroup SpecialLinearTwoFive) :
          Set SpecialLinearTwoFive) :
      Set SpecialLinearTwoFive).ncard = 24
  rw [coe_finiteSetNormalizer
    (specialLinearTwoFiveSylowTwo : Subgroup SpecialLinearTwoFive)
    specialLinearTwoFiveQuaternionElements
    coe_specialLinearTwoFiveSylowTwo]
  simpa using
    card_specialLinearTwoFiveSylowTwoNormalizerElements

/-- The normalizer subtype used by the inductive McKay condition at `3`
has order `12`. -/
theorem natCard_specialLinearTwoFiveSylowThreeNormalizer :
    Nat.card
      (Subgroup.normalizer
        (specialLinearTwoFiveSylowThree :
          Set SpecialLinearTwoFive)) = 12 := by
  change
    (Subgroup.normalizer
      ((specialLinearTwoFiveSylowThree :
        Subgroup SpecialLinearTwoFive) :
          Set SpecialLinearTwoFive) :
      Set SpecialLinearTwoFive).ncard = 12
  rw [coe_finiteSetNormalizer
    (specialLinearTwoFiveSylowThree : Subgroup SpecialLinearTwoFive)
    specialLinearTwoFiveThreeSubgroupElements
    coe_specialLinearTwoFiveSylowThree]
  simpa using
    card_specialLinearTwoFiveSylowThreeNormalizerElements

/-- The normalizer subtype used by the inductive McKay condition at `5`
has order `20`. -/
theorem natCard_specialLinearTwoFiveSylowFiveNormalizer :
    Nat.card
      (Subgroup.normalizer
        (specialLinearTwoFiveSylowFive :
          Set SpecialLinearTwoFive)) = 20 := by
  change
    (Subgroup.normalizer
      ((specialLinearTwoFiveSylowFive :
        Subgroup SpecialLinearTwoFive) :
          Set SpecialLinearTwoFive) :
      Set SpecialLinearTwoFive).ncard = 20
  rw [coe_finiteSetNormalizer
    (specialLinearTwoFiveSylowFive : Subgroup SpecialLinearTwoFive)
    specialLinearTwoFiveFiveSubgroupElements
    coe_specialLinearTwoFiveSylowFive]
  simpa using
    card_specialLinearTwoFiveSylowFiveNormalizerElements

end GroupTheory
end McKayConjecture
