/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import SplittingSpheres.Handlebody.CoordinateExteriorRightTubePowerPullbackDiffeomorph
public import SplittingSpheres.Foundations.CollaredCutSideManifold
public import SplittingSpheres.Foundations.LocalDiffeomorphismRecognition
import all Mathlib.Geometry.Manifold.LocalDiffeomorph

/-!
# The standard-collar smooth structure on the closed right-tube exterior

This file equips the complement of the open radius-`1/8` right unlink tube with the direct
collared-cut atlas generated by the common-model ambient sphere and the literal standard radial
collar.  It also pulls this atlas back along the existing cyclic power-cover projection.

This smooth structure is intentionally distinct from the custom collar structure used by the
explicit affine diffeomorphism to `OneHandlePiece`: here the literal standard collar is retained
so that inclusions from the compact coordinate exterior agree at the radial face.  No comparison
between those two right-tube smooth structures is asserted in this module.
-/

@[expose] public section

open Function Metric Set Topology TopologicalSpace
open scoped ContDiff Manifold

noncomputable section

namespace SplittingSpheres

private abbrev rightTubeStandardInnerRadius : ℝ := 1 / 8

/-- The literal standard radial collar of the closed right-tube exterior. -/
def coordinateExteriorRightTubeStandardCollarAmbient
    (p : CoordinateExteriorRightTubeClosedCollarDomain) : Sphere 4 :=
  (standardUnlinkExteriorEighthCollarHomeomorph 1 p : Sphere 4)

/-- The standard radial collar has exactly the radius-`[1/8,1/4)` shell as its image. -/
theorem range_coordinateExteriorRightTubeStandardCollarAmbient :
    range coordinateExteriorRightTubeStandardCollarAmbient =
      standardUnlinkOpenTube 1 (1 / 4 : ℝ) ∩ coordinateExteriorRightTubeClosedCarrier := by
  rw [show range coordinateExteriorRightTubeStandardCollarAmbient =
      standardUnlinkExteriorCollarSet 1 (1 / 8 : ℝ) (1 / 4 : ℝ) by
    exact range_standardUnlinkExteriorEighthCollarHomeomorph 1]
  ext q
  rw [mem_standardUnlinkExteriorCollarSet_iff 1 (by norm_num) (by norm_num),
    coordinateExteriorRightTubeClosedCarrier_eq_compl_openTube]
  simp only [mem_inter_iff, mem_compl_iff, standardUnlinkOpenTube,
    mem_preimage, mem_ball, not_lt]
  change ((1 / 8 : ℝ) ≤
        ‖standardUnlinkNormalProjection q - standardUnlinkNormalCenter 1‖ ∧
      ‖standardUnlinkNormalProjection q - standardUnlinkNormalCenter 1‖ < 1 / 4) ↔
    (dist (standardUnlinkNormalProjection q) (standardUnlinkNormalCenter 1) < 1 / 4 ∧
      (1 / 8 : ℝ) ≤ ‖standardUnlinkNormalProjection q - standardUnlinkNormalCenter 1‖)
  rw [dist_eq_norm]
  constructor <;> rintro ⟨h₁, h₂⟩
  · exact ⟨h₂, h₁⟩
  · exact ⟨h₂, h₁⟩

/-- The standard collar lies in the complement of the open radius-`1/8` right tube. -/
theorem range_coordinateExteriorRightTubeStandardCollarAmbient_subset :
    range coordinateExteriorRightTubeStandardCollarAmbient ⊆
      coordinateExteriorRightTubeClosedCarrier := by
  rw [range_coordinateExteriorRightTubeStandardCollarAmbient]
  exact inter_subset_right

/-- Corestrict the standard ambient collar to the closed right-tube exterior. -/
def coordinateExteriorRightTubeStandardBoundaryCollar
    (p : CoordinateExteriorRightTubeClosedCollarDomain) :
    CoordinateExteriorRightTubeClosed :=
  collaredCutSideHalfCollarMap coordinateExteriorRightTubeClosedCarrier
    coordinateExteriorRightTubeStandardCollarAmbient
    range_coordinateExteriorRightTubeStandardCollarAmbient_subset p

/-- Coercing the corestricted standard collar recovers its literal ambient value. -/
@[simp] theorem coordinateExteriorRightTubeStandardBoundaryCollar_coe
    (p : CoordinateExteriorRightTubeClosedCollarDomain) :
    (coordinateExteriorRightTubeStandardBoundaryCollar p : Sphere 4) =
      coordinateExteriorRightTubeStandardCollarAmbient p := rfl

/-- The literal ambient standard collar is an embedding. -/
theorem isEmbedding_coordinateExteriorRightTubeStandardCollarAmbient :
    IsEmbedding coordinateExteriorRightTubeStandardCollarAmbient := by
  exact Topology.IsEmbedding.subtypeVal.comp
    (standardUnlinkExteriorEighthCollarHomeomorph 1).isEmbedding

/-- The corestricted standard collar is an open embedding into the closed exterior. -/
theorem isOpenEmbedding_coordinateExteriorRightTubeStandardBoundaryCollar :
    IsOpenEmbedding coordinateExteriorRightTubeStandardBoundaryCollar := by
  exact isOpenEmbedding_collaredCutSideHalfCollarMap
    coordinateExteriorRightTubeClosedCarrier
    coordinateExteriorRightTubeStandardCollarAmbient
    range_coordinateExteriorRightTubeStandardCollarAmbient_subset
    isEmbedding_coordinateExteriorRightTubeStandardCollarAmbient
    (standardUnlinkOpenTube 1 (1 / 4 : ℝ))
    (isOpen_standardUnlinkOpenTube 1 (1 / 4 : ℝ))
    range_coordinateExteriorRightTubeStandardCollarAmbient

/-- Removing the radial boundary from the closed right-tube exterior gives an open stratum. -/
theorem isOpen_coordinateExteriorRightTubeClosed_offBoundary :
    IsOpen (collaredCutSideOffBoundary coordinateExteriorRightTubeClosedCarrier
      coordinateExteriorRightTubeBoundary) := by
  rw [coordinateExteriorRightTubeClosed_offBoundary]
  exact (isClosed_standardUnlinkClosedTube 1 (1 / 8 : ℝ)).isOpen_compl

/-- Every closed right-tube exterior point is in its open stratum or standard collar image. -/
theorem coordinateExteriorRightTubeClosed_offBoundary_or_standardCollar
    (q : CoordinateExteriorRightTubeClosed) :
    q.1 ∈ collaredCutSideOffBoundary coordinateExteriorRightTubeClosedCarrier
        coordinateExteriorRightTubeBoundary ∨
      q.1 ∈ range coordinateExteriorRightTubeStandardCollarAmbient := by
  by_cases heq : ‖standardUnlinkNormalProjection q.1 - standardUnlinkNormalCenter 1‖ =
      rightTubeStandardInnerRadius
  · right
    rw [range_coordinateExteriorRightTubeStandardCollarAmbient]
    refine ⟨?_, q.2⟩
    change dist (standardUnlinkNormalProjection q.1)
      (standardUnlinkNormalCenter 1) < (1 / 4 : ℝ)
    rw [dist_eq_norm, heq]
    norm_num [rightTubeStandardInnerRadius]
  · left
    rw [coordinateExteriorRightTubeClosed_offBoundary]
    have hcarrier := q.2
    change q.1 ∈ coordinateExteriorRightTubeClosedCarrier at hcarrier
    rw [coordinateExteriorRightTubeClosedCarrier_eq_compl_openTube] at hcarrier
    change ¬ ‖standardUnlinkNormalProjection q.1 - standardUnlinkNormalCenter 1‖ ≤
      (1 / 8 : ℝ)
    change ¬ ‖standardUnlinkNormalProjection q.1 - standardUnlinkNormalCenter 1‖ <
      (1 / 8 : ℝ) at hcarrier
    change ‖standardUnlinkNormalProjection q.1 - standardUnlinkNormalCenter 1‖ ≠
      (1 / 8 : ℝ) at heq
    exact fun hle ↦ hcarrier (lt_of_le_of_ne hle heq)

@[simp] private theorem coordinateExteriorRightTubeStandardCollarAmbient_normal
    (p : CoordinateExteriorRightTubeClosedCollarDomain) :
    standardUnlinkNormalProjection (coordinateExteriorRightTubeStandardCollarAmbient p) =
      standardUnlinkNormalCenter 1 +
        unlinkExteriorCollarRadiusValue p.2.2 • p.2.1.1 :=
  standardUnlinkNormalProjection_exteriorCollarHomeomorph
    1 (by norm_num) (by norm_num) p

private def rightTubeStandardPositiveCollarOpens :
    Opens CoordinateExteriorRightTubeClosedCollarDomain :=
  ⟨{p | rightTubeStandardInnerRadius < unlinkExteriorCollarRadiusValue p.2.2},
    isOpen_lt continuous_const
      (continuous_unlinkExteriorCollarRadiusValue.comp
        (continuous_snd.comp continuous_snd))⟩

private def rightTubeStandardPuncturedOverlapOpens :
    Opens (StandardUnlinkPuncturedTube 1 (1 / 4 : ℝ)) :=
  ⟨{q | rightTubeStandardInnerRadius <
      (standardUnlinkPuncturedTubePolarCoordinates 1 (by norm_num) q).2.2},
    isOpen_lt continuous_const
      ((contMDiff_standardUnlinkPuncturedTubePolarCoordinates 1 (by norm_num)).continuous
        |>.snd.snd)⟩

private abbrev RightTubeStandardPuncturedOverlap :=
  rightTubeStandardPuncturedOverlapOpens

private def rightTubeStandardPuncturedOverlapPolarCollar
    (q : RightTubeStandardPuncturedOverlap) :
    CoordinateExteriorRightTubeClosedCollarDomain := by
  let polar := standardUnlinkPuncturedTubePolarCoordinates 1 (by norm_num) q.1
  have hlower : (1 / 8 : ℝ) < polar.2.2 := q.2
  have hupper : polar.2.2 < (1 / 4 : ℝ) := by
    rw [standardUnlinkPuncturedTubePolarCoordinates_radius]
    have hmem := q.1.1.2
    change standardUnlinkNormalProjection q.1.1.1 ∈
      ball (standardUnlinkNormalCenter 1) (1 / 4 : ℝ) at hmem
    simpa only [mem_ball, dist_eq_norm] using hmem
  exact (polar.1, (polar.2.1, ⟨⟨polar.2.2, hlower.le, hupper.le⟩, hupper⟩))

private theorem contMDiff_rightTubeStandardPuncturedOverlapPolarCollar :
    ContMDiff (modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4)))
      coordinateUnlinkExteriorModel ∞
      rightTubeStandardPuncturedOverlapPolarCollar := by
  rw [ContinuousLinearEquiv.contMDiff_transContinuousLinearEquiv_right]
  have hraw :=
    (contMDiff_standardUnlinkPuncturedTubePolarCoordinates 1 (by norm_num)).comp
      (contMDiff_subtype_val : ContMDiff
        (modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4)))
        (modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4))) ∞
        (Subtype.val : RightTubeStandardPuncturedOverlap →
          StandardUnlinkPuncturedTube 1 (1 / 4 : ℝ)))
  have hbase := contMDiff_fst.comp hraw
  have hdirection := contMDiff_fst.comp (contMDiff_snd.comp hraw)
  have hradiusReal := contMDiff_snd.comp (contMDiff_snd.comp hraw)
  have hradius : ContMDiff
      (modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4)))
      (modelWithCornersEuclideanHalfSpace 1) ∞
      (fun q : RightTubeStandardPuncturedOverlap ↦
        (rightTubeStandardPuncturedOverlapPolarCollar q).2.2) := by
    apply (ContMDiff.subtypeVal_comp_iff
      (unlinkExteriorCollarRadius (1 / 8 : ℝ) (1 / 4 : ℝ)) _).mp
    rw [contMDiff_iff_comp_subtypeVal_Icc]
    constructor
    · apply Continuous.subtype_mk
      exact hradiusReal.continuous.congr fun _ ↦ rfl
    · exact hradiusReal.congr fun _ ↦ rfl
  exact (hbase.prodMk (hdirection.prodMk hradius)).congr fun _ ↦ rfl

private def rightTubeStandardStrictCollarOpens : Opens (Sphere 4) := by
  let ρ : Sphere 4 → ℝ := fun q ↦
    ‖standardUnlinkNormalProjection q - standardUnlinkNormalCenter 1‖
  have hρ : Continuous ρ := continuous_norm.comp
    (continuous_standardUnlinkNormalProjection.sub continuous_const)
  exact ⟨{q | rightTubeStandardInnerRadius < ρ q ∧ ρ q < (1 / 4 : ℝ)},
    (isOpen_lt continuous_const hρ).inter (isOpen_lt hρ continuous_const)⟩

private theorem mem_rightTubeStandardStrictCollarOpens_iff (q : Sphere 4) :
    q ∈ rightTubeStandardStrictCollarOpens ↔
      rightTubeStandardInnerRadius <
          ‖standardUnlinkNormalProjection q - standardUnlinkNormalCenter 1‖ ∧
        ‖standardUnlinkNormalProjection q - standardUnlinkNormalCenter 1‖ <
          (1 / 4 : ℝ) := by rfl

private def rightTubeStandardStrictCollarAsExteriorCollar
    (q : rightTubeStandardStrictCollarOpens) :
    StandardUnlinkExteriorCollar 1 (1 / 8 : ℝ) (1 / 4 : ℝ) := by
  refine ⟨q.1, ?_⟩
  rw [mem_standardUnlinkExteriorCollarSet_iff 1 (by norm_num) (by norm_num)]
  exact ⟨q.2.1.le, q.2.2⟩

private def rightTubeStandardStrictCollarToPuncturedOverlap
    (q : rightTubeStandardStrictCollarOpens) : RightTubeStandardPuncturedOverlap := by
  have hq := (mem_rightTubeStandardStrictCollarOpens_iff q.1).mp q.2
  let qtube : StandardUnlinkOpenTubeSpace 1 (1 / 4 : ℝ) := by
    refine ⟨q.1, ?_⟩
    change dist (standardUnlinkNormalProjection q.1)
      (standardUnlinkNormalCenter 1) < (1 / 4 : ℝ)
    simpa only [dist_eq_norm] using hq.2
  let qpunct : StandardUnlinkPuncturedTube 1 (1 / 4 : ℝ) := by
    refine ⟨qtube, ?_⟩
    intro heq
    have hzero : ‖standardUnlinkNormalProjection q.1 - standardUnlinkNormalCenter 1‖ = 0 := by
      change ‖standardUnlinkNormalProjection qtube.1 - standardUnlinkNormalCenter 1‖ = 0
      rw [heq, sub_self, norm_zero]
    have hpos : 0 < ‖standardUnlinkNormalProjection q.1 - standardUnlinkNormalCenter 1‖ :=
      lt_of_lt_of_le (by norm_num : (0 : ℝ) < rightTubeStandardInnerRadius) hq.1.le
    exact hpos.ne' hzero
  refine ⟨qpunct, ?_⟩
  change rightTubeStandardInnerRadius <
    (standardUnlinkPuncturedTubePolarCoordinates 1 (by norm_num) qpunct).2.2
  rw [standardUnlinkPuncturedTubePolarCoordinates_radius]
  exact hq.1

private theorem contMDiff_rightTubeStandardStrictCollarToPuncturedOverlap :
    letI := coordinateUnlinkExteriorCommonModelSphereChartedSpace
    ContMDiff coordinateUnlinkExteriorModel
      (modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4))) ∞
      rightTubeStandardStrictCollarToPuncturedOverlap := by
  let _ := coordinateUnlinkExteriorCommonModelSphereChartedSpace
  apply (ContMDiff.subtypeVal_comp_iff rightTubeStandardPuncturedOverlapOpens _).mp
  apply (ContMDiff.subtypeVal_comp_iff
    (standardUnlinkPuncturedTubeOpens 1 (1 / 4 : ℝ)) _).mp
  apply (ContMDiff.subtypeVal_comp_iff
    (standardUnlinkOpenTubeOpens 1 (1 / 4 : ℝ)) _).mp
  apply (coordinateUnlinkExteriorCommonModelToStandardSphereIdentityDiffeomorph.contMDiff.comp
    contMDiff_subtype_val).congr
  intro q
  change q.1 = q.1
  rfl

private def rightTubeStandardPositiveCollarToStrictCollar
    (p : rightTubeStandardPositiveCollarOpens) : rightTubeStandardStrictCollarOpens := by
  refine ⟨coordinateExteriorRightTubeStandardCollarAmbient p.1, ?_⟩
  change rightTubeStandardInnerRadius <
      ‖standardUnlinkNormalProjection
          (coordinateExteriorRightTubeStandardCollarAmbient p.1) -
        standardUnlinkNormalCenter 1‖ ∧
    ‖standardUnlinkNormalProjection
          (coordinateExteriorRightTubeStandardCollarAmbient p.1) -
        standardUnlinkNormalCenter 1‖ < (1 / 4 : ℝ)
  rw [coordinateExteriorRightTubeStandardCollarAmbient_normal,
    add_sub_cancel_left, norm_smul, Real.norm_eq_abs,
    abs_of_pos (lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1 / 8)
      (unlinkExteriorCollarRadiusValue_lower p.1.2.2)),
    mem_sphere_zero_iff_norm.mp p.1.2.1.2, mul_one]
  exact ⟨p.2, unlinkExteriorCollarRadiusValue_lt_upper p.1.2.2⟩

private def rightTubeStandardStrictCollarToPositiveCollar
    (q : rightTubeStandardStrictCollarOpens) : rightTubeStandardPositiveCollarOpens := by
  have hq := (mem_rightTubeStandardStrictCollarOpens_iff q.1).mp q.2
  let z := rightTubeStandardStrictCollarAsExteriorCollar q
  let p := (standardUnlinkExteriorEighthCollarHomeomorph 1).symm z
  refine ⟨p, ?_⟩
  have happ := congrArg Subtype.val
    ((standardUnlinkExteriorEighthCollarHomeomorph 1).apply_symm_apply z)
  have hnorm :
      ‖standardUnlinkNormalProjection q.1 - standardUnlinkNormalCenter 1‖ =
        unlinkExteriorCollarRadiusValue p.2.2 := by
    change ‖standardUnlinkNormalProjection z.1 - standardUnlinkNormalCenter 1‖ = _
    rw [← happ]
    change ‖standardUnlinkNormalProjection
        (standardUnlinkExteriorCollarHomeomorph 1
          (r := (1 / 8 : ℝ)) (R := (1 / 4 : ℝ))
          (by norm_num) (by norm_num) p).1 - standardUnlinkNormalCenter 1‖ = _
    rw [standardUnlinkNormalProjection_exteriorCollarHomeomorph,
      add_sub_cancel_left, norm_smul, Real.norm_eq_abs,
      abs_of_pos (lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1 / 8)
        (unlinkExteriorCollarRadiusValue_lower p.2.2)),
      mem_sphere_zero_iff_norm.mp p.2.1.2, mul_one]
  change rightTubeStandardInnerRadius < unlinkExteriorCollarRadiusValue p.2.2
  rw [← hnorm]
  exact hq.1

@[simp] private theorem rightTubeStandardStrictCollarToPositiveCollar_val
    (q : rightTubeStandardStrictCollarOpens) :
    (rightTubeStandardStrictCollarToPositiveCollar q).1 =
      (standardUnlinkExteriorEighthCollarHomeomorph 1).symm
        (rightTubeStandardStrictCollarAsExteriorCollar q) := by rfl

@[simp] private theorem rightTubeStandardPositiveCollarToStrictCollar_val
    (p : rightTubeStandardPositiveCollarOpens) :
    (rightTubeStandardPositiveCollarToStrictCollar p).1 =
      coordinateExteriorRightTubeStandardCollarAmbient p.1 := by rfl

private theorem rightTubeStandardStrictCollarToPositiveCollar_eq_polar
    (q : rightTubeStandardStrictCollarOpens) :
    (rightTubeStandardStrictCollarToPositiveCollar q).1 =
      rightTubeStandardPuncturedOverlapPolarCollar
        (rightTubeStandardStrictCollarToPuncturedOverlap q) := by
  let z := rightTubeStandardStrictCollarAsExteriorCollar q
  let p := (standardUnlinkExteriorEighthCollarHomeomorph 1).symm z
  have happ := (standardUnlinkExteriorEighthCollarHomeomorph 1).apply_symm_apply z
  have hpunct :
      (rightTubeStandardStrictCollarToPuncturedOverlap q).1 =
        standardUnlinkExteriorCollarToPuncturedTube 1
          (by norm_num) (by norm_num)
          (standardUnlinkExteriorEighthCollarHomeomorph 1 p) := by
    apply Subtype.ext
    apply Subtype.ext
    change q.1 = (standardUnlinkExteriorEighthCollarHomeomorph 1 p : Sphere 4)
    exact (congrArg Subtype.val happ).symm
  have hpolar := standardUnlinkPuncturedTubePolarCoordinates_exteriorCollar
    1 (r := (1 / 8 : ℝ)) (R := (1 / 4 : ℝ))
      (by norm_num) (by norm_num) p
  have hpolar' :
      standardUnlinkPuncturedTubePolarCoordinates 1 (by norm_num)
          (rightTubeStandardStrictCollarToPuncturedOverlap q).1 =
        (p.1, (p.2.1, unlinkExteriorCollarRadiusValue p.2.2)) := by
    rw [hpunct]
    exact hpolar
  have hinvVal : (rightTubeStandardStrictCollarToPositiveCollar q).1 = p := by
    rw [rightTubeStandardStrictCollarToPositiveCollar_val]
  rw [hinvVal]
  apply Prod.ext
  · exact (congrArg Prod.fst hpolar').symm
  · apply Prod.ext
    · exact (congrArg (fun z ↦ z.2.1) hpolar').symm
    · apply Subtype.ext
      apply Subtype.ext
      exact (congrArg (fun z ↦ z.2.2) hpolar').symm

private theorem contMDiff_rightTubeStandardStrictCollarToPositiveCollar :
    letI := coordinateUnlinkExteriorCommonModelSphereChartedSpace
    ContMDiff coordinateUnlinkExteriorModel coordinateUnlinkExteriorModel ∞
      rightTubeStandardStrictCollarToPositiveCollar := by
  let _ := coordinateUnlinkExteriorCommonModelSphereChartedSpace
  apply (ContMDiff.subtypeVal_comp_iff rightTubeStandardPositiveCollarOpens _).mp
  have hpolar := contMDiff_rightTubeStandardPuncturedOverlapPolarCollar.comp
    contMDiff_rightTubeStandardStrictCollarToPuncturedOverlap
  exact hpolar.congr rightTubeStandardStrictCollarToPositiveCollar_eq_polar

private theorem contMDiff_rightTubeStandardPositiveCollarToStrictCollar :
    letI := coordinateUnlinkExteriorCommonModelSphereChartedSpace
    ContMDiff coordinateUnlinkExteriorModel coordinateUnlinkExteriorModel ∞
      rightTubeStandardPositiveCollarToStrictCollar := by
  let _ := coordinateUnlinkExteriorCommonModelSphereChartedSpace
  apply (ContMDiff.subtypeVal_comp_iff rightTubeStandardStrictCollarOpens _).mp
  have hstandard : ContMDiff coordinateUnlinkExteriorModel
      (modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4))) ∞
      (fun p : rightTubeStandardPositiveCollarOpens ↦
        coordinateExteriorRightTubeStandardCollarAmbient p.1) := by
    rw [ContinuousLinearEquiv.contMDiff_transContinuousLinearEquiv_left]
    exact (contMDiff_standardUnlinkExteriorEighthCollarHomeomorph_ambient 1).comp
      contMDiff_subtype_val
  exact
    (standardToCoordinateUnlinkExteriorCommonModelSphereIdentityDiffeomorph.contMDiff.comp
      hstandard).congr fun _ ↦ rfl

private theorem rightTubeStandardStrictCollarToPositiveCollar_forward
    (p : rightTubeStandardPositiveCollarOpens) :
    rightTubeStandardStrictCollarToPositiveCollar
      (rightTubeStandardPositiveCollarToStrictCollar p) = p := by
  apply Subtype.ext
  have hz : rightTubeStandardStrictCollarAsExteriorCollar
      (rightTubeStandardPositiveCollarToStrictCollar p) =
        standardUnlinkExteriorEighthCollarHomeomorph 1 p.1 := by
    apply Subtype.ext
    rfl
  rw [rightTubeStandardStrictCollarToPositiveCollar_val]
  change (standardUnlinkExteriorEighthCollarHomeomorph 1).symm
      (rightTubeStandardStrictCollarAsExteriorCollar
        (rightTubeStandardPositiveCollarToStrictCollar p)) = p.1
  rw [hz]
  exact (standardUnlinkExteriorEighthCollarHomeomorph 1).symm_apply_apply p.1

private theorem rightTubeStandardPositiveCollarToStrictCollar_forward
    (q : rightTubeStandardStrictCollarOpens) :
    rightTubeStandardPositiveCollarToStrictCollar
      (rightTubeStandardStrictCollarToPositiveCollar q) = q := by
  apply Subtype.ext
  rw [rightTubeStandardPositiveCollarToStrictCollar_val,
    rightTubeStandardStrictCollarToPositiveCollar_val]
  exact congrArg Subtype.val
    ((standardUnlinkExteriorEighthCollarHomeomorph 1).apply_symm_apply
      (rightTubeStandardStrictCollarAsExteriorCollar q))

section CommonModelSphere

attribute [local instance] coordinateUnlinkExteriorCommonModelSphereChartedSpace

local instance : IsManifold coordinateUnlinkExteriorModel ∞ (Sphere 4) :=
  isManifold_coordinateUnlinkExteriorCommonModelSphere

private theorem isLocalDiffeomorph_rightTubeStandardPositiveCollarRestricted :
    IsLocalDiffeomorph coordinateUnlinkExteriorModel coordinateUnlinkExteriorModel ∞
      (coordinateExteriorRightTubeStandardCollarAmbient ∘
        (Subtype.val : rightTubeStandardPositiveCollarOpens →
          CoordinateExteriorRightTubeClosedCollarDomain)) := by
  intro p
  let e : rightTubeStandardPositiveCollarOpens ≃ₘ^∞⟮coordinateUnlinkExteriorModel,
      coordinateUnlinkExteriorModel⟯ rightTubeStandardStrictCollarOpens :=
    { toFun := rightTubeStandardPositiveCollarToStrictCollar
      invFun := rightTubeStandardStrictCollarToPositiveCollar
      left_inv := rightTubeStandardStrictCollarToPositiveCollar_forward
      right_inv := rightTubeStandardPositiveCollarToStrictCollar_forward
      contMDiff_toFun := contMDiff_rightTubeStandardPositiveCollarToStrictCollar
      contMDiff_invFun := contMDiff_rightTubeStandardStrictCollarToPositiveCollar }
  have h₁ := e.isLocalDiffeomorph p
  have h₂ := isLocalDiffeomorph_opensSubtypeVal
    coordinateUnlinkExteriorModel rightTubeStandardStrictCollarOpens (e p)
  have hcomp := h₁.comp coordinateUnlinkExteriorModel (Sphere 4) h₂
  rcases hcomp with ⟨Φ, hpΦ, hΦ⟩
  refine ⟨Φ, hpΦ, ?_⟩
  intro q hq
  calc
    (coordinateExteriorRightTubeStandardCollarAmbient ∘ Subtype.val) q =
        (Subtype.val ∘ e) q := by
      change coordinateExteriorRightTubeStandardCollarAmbient q.1 =
        (rightTubeStandardPositiveCollarToStrictCollar q).1
      exact (rightTubeStandardPositiveCollarToStrictCollar_val q).symm
    _ = Φ q := hΦ hq

private theorem isLocalDiffeomorphAt_coordinateExteriorRightTubeStandardCollarAmbient_of_positive
    (p : CoordinateExteriorRightTubeClosedCollarDomain)
    (hp : rightTubeStandardInnerRadius < unlinkExteriorCollarRadiusValue p.2.2) :
    IsLocalDiffeomorphAt coordinateUnlinkExteriorModel coordinateUnlinkExteriorModel ∞
      coordinateExteriorRightTubeStandardCollarAmbient p := by
  let u : rightTubeStandardPositiveCollarOpens := ⟨p, hp⟩
  exact isLocalDiffeomorphAt_of_localDiffeomorph_parametrization
    coordinateUnlinkExteriorModel coordinateUnlinkExteriorModel
    coordinateExteriorRightTubeStandardCollarAmbient
    (Subtype.val : rightTubeStandardPositiveCollarOpens →
      CoordinateExteriorRightTubeClosedCollarDomain)
    (isLocalDiffeomorph_opensSubtypeVal
      coordinateUnlinkExteriorModel rightTubeStandardPositiveCollarOpens)
    isLocalDiffeomorph_rightTubeStandardPositiveCollarRestricted u

private theorem coordinateExteriorRightTubeStandardCollarAmbient_mem_offBoundary_iff
    (p : CoordinateExteriorRightTubeClosedCollarDomain) :
    coordinateExteriorRightTubeStandardCollarAmbient p ∈
        collaredCutSideOffBoundary coordinateExteriorRightTubeClosedCarrier
          coordinateExteriorRightTubeBoundary ↔
      rightTubeStandardInnerRadius < unlinkExteriorCollarRadiusValue p.2.2 := by
  rw [coordinateExteriorRightTubeClosed_offBoundary]
  simp only [standardUnlinkClosedTube, mem_compl_iff, mem_preimage,
    mem_closedBall, dist_eq_norm, not_le]
  change (1 / 8 : ℝ) <
    ‖standardUnlinkNormalProjection (coordinateExteriorRightTubeStandardCollarAmbient p) -
      standardUnlinkNormalCenter 1‖ ↔ _
  rw [coordinateExteriorRightTubeStandardCollarAmbient_normal,
    add_sub_cancel_left, norm_smul, Real.norm_eq_abs,
    abs_of_pos (lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1 / 8)
      (unlinkExteriorCollarRadiusValue_lower p.2.2)),
    mem_sphere_zero_iff_norm.mp p.2.1.2, mul_one]

private theorem isLocalDiffeomorphOn_coordinateExteriorRightTubeStandardCollarAmbient :
    IsLocalDiffeomorphOn coordinateUnlinkExteriorModel coordinateUnlinkExteriorModel ∞
      coordinateExteriorRightTubeStandardCollarAmbient
      (coordinateExteriorRightTubeStandardCollarAmbient ⁻¹'
        collaredCutSideOffBoundary coordinateExteriorRightTubeClosedCarrier
          coordinateExteriorRightTubeBoundary) := by
  intro p
  apply isLocalDiffeomorphAt_coordinateExteriorRightTubeStandardCollarAmbient_of_positive p.1
  exact (coordinateExteriorRightTubeStandardCollarAmbient_mem_offBoundary_iff p.1).mp p.2

/-- The direct atlas generated by the ambient interior and literal standard radial collar. -/
@[instance_reducible]
noncomputable def coordinateExteriorRightTubeStandardChartedSpace :
    ChartedSpace CoordinateUnlinkExteriorModelSpace CoordinateExteriorRightTubeClosed :=
  collaredCutSideChartedSpace
    coordinateExteriorRightTubeClosedCarrier coordinateExteriorRightTubeBoundary
    isOpen_coordinateExteriorRightTubeClosed_offBoundary
    coordinateExteriorRightTubeStandardCollarAmbient
    range_coordinateExteriorRightTubeStandardCollarAmbient_subset
    isOpenEmbedding_coordinateExteriorRightTubeStandardBoundaryCollar
    coordinateExteriorRightTubeClosed_offBoundary_or_standardCollar

/-- The direct standard-collar atlas makes the closed right-tube exterior a smooth manifold. -/
theorem isManifold_coordinateExteriorRightTubeStandard :
    letI := coordinateExteriorRightTubeStandardChartedSpace
    IsManifold coordinateUnlinkExteriorModel ∞ CoordinateExteriorRightTubeClosed := by
  let _ := coordinateExteriorRightTubeStandardChartedSpace
  exact isManifold_collaredCutSideChartedSpace_of_localDiffeomorphOn
    coordinateUnlinkExteriorModel ∞
    coordinateExteriorRightTubeClosedCarrier coordinateExteriorRightTubeBoundary
    isOpen_coordinateExteriorRightTubeClosed_offBoundary
    coordinateExteriorRightTubeStandardCollarAmbient
    range_coordinateExteriorRightTubeStandardCollarAmbient_subset
    isOpenEmbedding_coordinateExteriorRightTubeStandardBoundaryCollar
    coordinateExteriorRightTubeClosed_offBoundary_or_standardCollar
    isLocalDiffeomorphOn_coordinateExteriorRightTubeStandardCollarAmbient

end CommonModelSphere

section StandardPowerPullback

attribute [local instance] coordinateExteriorRightTubeStandardChartedSpace

local instance : IsManifold coordinateUnlinkExteriorModel ∞
    CoordinateExteriorRightTubeClosed := isManifold_coordinateExteriorRightTubeStandard

/-- Pull the direct standard-collar atlas back along the cyclic power-cover projection. -/
abbrev coordinateExteriorRightTubePowerPullbackStandardChartedSpace
    (m : ℕ) [NeZero m] :
    ChartedSpace CoordinateUnlinkExteriorModelSpace
      (CoordinateExteriorRightTubePowerPullback m) :=
  SplittingSpheres.IsCoveringMap.pullbackChartedSpace
    (isCoveringMap_coordinateExteriorRightTubePowerPullbackProj m)

/-- The power pullback with the standard-collar atlas is a smooth manifold. -/
theorem isManifold_coordinateExteriorRightTubePowerPullbackStandard
    (m : ℕ) [NeZero m] :
    letI := coordinateExteriorRightTubePowerPullbackStandardChartedSpace m
    IsManifold coordinateUnlinkExteriorModel ∞
      (CoordinateExteriorRightTubePowerPullback m) := by
  let _ := coordinateExteriorRightTubePowerPullbackStandardChartedSpace m
  exact SplittingSpheres.IsCoveringMap.isManifold_pullbackChartedSpace
    coordinateUnlinkExteriorModel ∞
      (isCoveringMap_coordinateExteriorRightTubePowerPullbackProj m)

/-- The power-cover projection is a local diffeomorphism for the standard-collar atlas. -/
theorem isLocalDiffeomorph_coordinateExteriorRightTubePowerPullbackProj_standard
    (m : ℕ) [NeZero m] :
    letI := coordinateExteriorRightTubePowerPullbackStandardChartedSpace m
    letI : IsManifold coordinateUnlinkExteriorModel ∞
        (CoordinateExteriorRightTubePowerPullback m) :=
      isManifold_coordinateExteriorRightTubePowerPullbackStandard m
    IsLocalDiffeomorph coordinateUnlinkExteriorModel coordinateUnlinkExteriorModel ∞
      (coordinateExteriorRightTubePowerPullbackProj m) := by
  let _ := coordinateExteriorRightTubePowerPullbackStandardChartedSpace m
  let _ : IsManifold coordinateUnlinkExteriorModel ∞
      (CoordinateExteriorRightTubePowerPullback m) :=
    isManifold_coordinateExteriorRightTubePowerPullbackStandard m
  exact SplittingSpheres.IsCoveringMap.isLocalDiffeomorph_pullbackChartedSpace
    coordinateUnlinkExteriorModel ∞
      (isCoveringMap_coordinateExteriorRightTubePowerPullbackProj m)

end StandardPowerPullback

end SplittingSpheres
