/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import SplittingSpheres.Foundations.CollaredTopologicalPushoutBoundary
public import SplittingSpheres.Foundations.DiscreteProductChartedSpace
public import SplittingSpheres.Foundations.LocalDiffeomorphismRecognition
public import SplittingSpheres.Handlebody.CoordinateExteriorPlanarNeckSmoothCapping

/-!
# Diffeomorphism recognition for the direct smooth planar neck cappings

The direct capping atlas is generated by its signed seam and the two coprojections away from the
attaching sphere family.  This file records that a comparison homeomorphism is a diffeomorphism
as soon as its composites with those three generators are local diffeomorphisms.  It then
specializes the criterion to the right capping and to the labelled left capping, using the natural
one-handle atlas on the targets.

No comparison homeomorphism is constructed here.  In particular, the recognition statements do
not transport an atlas through a homeomorphism and make no smoothness claim about the existing
point-set capping comparisons.
-/

@[expose] public section

noncomputable section

open Function Set Topology TopologicalSpace
open scoped ContDiff Manifold

namespace SplittingSpheres

variable {A X Y N H K E F M : Type}
variable [TopologicalSpace A] [TopologicalSpace X] [TopologicalSpace Y]
variable [TopologicalSpace N] [TopologicalSpace H] [TopologicalSpace K]
variable [TopologicalSpace M]
variable [Nonempty H]
variable [NormedAddCommGroup E] [NormedSpace ℝ E]
variable [NormedAddCommGroup F] [NormedSpace ℝ F]
variable [ChartedSpace H X] [ChartedSpace H Y] [ChartedSpace H N]
variable [ChartedSpace K M]
variable (I : ModelWithCorners ℝ E H) (J : ModelWithCorners ℝ F K)
variable (n : ℕ∞ω)
variable (f : C(A, X)) (g : C(A, Y))

/-- A homeomorphism out of a generated collared pushout is a diffeomorphism when its composites
with the seam and the two off-seam coprojections are local diffeomorphisms. -/
noncomputable def diffeomorphOfCollaredPushoutHomeomorph
    [IsManifold I n X] [IsManifold I n Y] [IsManifold I n N]
    (hf : IsClosedEmbedding f) (hg : IsClosedEmbedding g)
    (seam : N → TopologicalPushout f g) (hseam : IsOpenEmbedding seam)
    (hattach : ∀ a, ∃ q, seam q = topologicalPushoutInl f g (f a))
    (hpushout :
      letI := topologicalPushoutChartedSpace (H := H)
        f g hf hg seam hseam hattach
      IsManifold I n (TopologicalPushout f g))
    (e : TopologicalPushout f g ≃ₜ M)
    (hseamTarget : IsLocalDiffeomorph I J n (e ∘ seam))
    (hleftTarget : IsLocalDiffeomorph I J n
      (e ∘ topologicalPushoutInlOffSeamMap' f g hf))
    (hrightTarget : IsLocalDiffeomorph I J n
      (e ∘ topologicalPushoutInrOffSeamMap' f g hg)) :
    letI := topologicalPushoutChartedSpace (H := H)
      f g hf hg seam hseam hattach
    TopologicalPushout f g ≃ₘ^n⟮I, J⟯ M := by
  let _ := topologicalPushoutChartedSpace (H := H)
    f g hf hg seam hseam hattach
  let hP : IsManifold I n (TopologicalPushout f g) := hpushout
  have hcompat : ∀ i j : TopologicalPushoutAtlasIndex f g N,
      (topologicalPushoutAtlasChart (H := H)
        f g hf hg seam hseam i).symm.trans
          (topologicalPushoutAtlasChart (H := H)
            f g hf hg seam hseam j) ∈
        contDiffGroupoid n I := by
    intro i j
    exact hP.compatible ⟨i, rfl⟩ ⟨j, rfl⟩
  have hseamSource : IsLocalDiffeomorph I I n seam :=
    isLocalDiffeomorph_topologicalPushoutSeamMap I n f g
      hf hg seam hseam hattach hcompat
  have hleftSource : IsLocalDiffeomorph I I n
      (topologicalPushoutInlOffSeamMap' f g hf) :=
    isLocalDiffeomorph_topologicalPushoutInlOffSeamMap' I n f g
      hf hg seam hseam hattach hcompat
  have hrightSource : IsLocalDiffeomorph I I n
      (topologicalPushoutInrOffSeamMap' f g hg) :=
    isLocalDiffeomorph_topologicalPushoutInrOffSeamMap' I n f g
      hf hg seam hseam hattach hcompat
  have hcover : ∀ z : TopologicalPushout f g,
      (∃ q : N, seam q = z) ∨
      (∃ x : ↑(topologicalPushoutInlOffSeamOpens f hf),
        topologicalPushoutInlOffSeamMap' f g hf x = z) ∨
      (∃ y : ↑(topologicalPushoutInrOffSeamOpens g hg),
        topologicalPushoutInrOffSeamMap' f g hg y = z) := by
    intro z
    rcases topologicalPushout_jointly_surjective f g z with ⟨x, rfl⟩ | ⟨y, rfl⟩
    · by_cases hx : x ∈ range f
      · obtain ⟨a, rfl⟩ := hx
        obtain ⟨q, hq⟩ := hattach a
        exact Or.inl ⟨q, hq⟩
      · exact Or.inr <| Or.inl ⟨⟨x, hx⟩, rfl⟩
    · by_cases hy : y ∈ range g
      · obtain ⟨a, rfl⟩ := hy
        obtain ⟨q, hq⟩ := hattach a
        exact Or.inl ⟨q, hq.trans (topologicalPushout_condition f g a)⟩
      · exact Or.inr <| Or.inr ⟨⟨y, hy⟩, rfl⟩
  apply diffeomorphOfHomeomorphIsLocalDiffeomorph I J e
  apply isLocalDiffeomorph_of_three_localDiffeomorph_parametrizations I J
    e seam
    (topologicalPushoutInlOffSeamMap' f g hf)
    (topologicalPushoutInrOffSeamMap' f g hg)
    hseamSource hleftSource hrightSource
    hseamTarget hleftTarget hrightTarget
  exact hcover

/-- Recognize a comparison from the direct right capping to the natural one-handle as a
diffeomorphism by checking it on the three generators of the direct capping atlas. -/
noncomputable def
coordinateUnlinkExteriorPlanarNeckRightSmoothCappingDiffeomorphOneHandleOfGenerators
    (m : ℕ) [NeZero m]
    (e : CoordinateUnlinkExteriorPlanarNeckRightSmoothCapping m ≃ₜ OneHandlePiece)
    (hseam :
      letI := signedSeamFamilyCommonModelChartedSpace m
      IsLocalDiffeomorph coordinateUnlinkExteriorModel oneHandlePieceModel ∞
        (e ∘ coordinateUnlinkExteriorPlanarNeckRightSmoothCappingSeamMap m))
    (hcut :
      letI := compactNeckRightCutChartedSpace m
      IsLocalDiffeomorph coordinateUnlinkExteriorModel oneHandlePieceModel ∞
        (e ∘ topologicalPushoutInlOffSeamMap'
          (coordinateUnlinkExteriorPlanarNeckRightCutAttachingMap m)
          (coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
          (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckRightCutAttachingMap m)))
    (hcap :
      letI :=
        coordinateUnlinkExteriorCommonModelEuclideanFourBallFamilyChartedSpace m
      IsLocalDiffeomorph coordinateUnlinkExteriorModel oneHandlePieceModel ∞
        (e ∘ topologicalPushoutInrOffSeamMap'
          (coordinateUnlinkExteriorPlanarNeckRightCutAttachingMap m)
          (coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
          (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m))) :
    letI := coordinateUnlinkExteriorPlanarNeckRightSmoothCappingChartedSpace m
    CoordinateUnlinkExteriorPlanarNeckRightSmoothCapping m
      ≃ₘ^∞⟮coordinateUnlinkExteriorModel, oneHandlePieceModel⟯ OneHandlePiece := by
  let _ := signedSeamFamilyCommonModelChartedSpace m
  let _ : IsManifold coordinateUnlinkExteriorModel ∞
      (CoordinateUnlinkExteriorPlanarNeckSmoothCappingSignedCollar m) :=
    isManifold_signedSeamFamilyCommonModel m
  let _ := compactNeckRightCutChartedSpace m
  let _ : IsManifold coordinateUnlinkExteriorModel ∞ (CompactNeckRightCut m) :=
    isManifold_compactNeckRightCut m
  let _ :=
    coordinateUnlinkExteriorCommonModelEuclideanFourBallFamilyChartedSpace m
  let _ : IsManifold coordinateUnlinkExteriorModel ∞
      (ZMod m × EuclideanFourBall) :=
    isManifold_coordinateUnlinkExteriorCommonModelEuclideanFourBallFamily m
  exact diffeomorphOfCollaredPushoutHomeomorph
    coordinateUnlinkExteriorModel oneHandlePieceModel ∞
    (coordinateUnlinkExteriorPlanarNeckRightCutAttachingMap m)
    (coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
    (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckRightCutAttachingMap m)
    (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
    (coordinateUnlinkExteriorPlanarNeckRightSmoothCappingSeamMap m)
    (isOpenEmbedding_coordinateUnlinkExteriorPlanarNeckRightSmoothCappingSeamMap m)
    (coordinateUnlinkExteriorPlanarNeckRightSmoothCappingSeamMap_attaching_coverage m)
    (isManifold_coordinateUnlinkExteriorPlanarNeckRightSmoothCapping m)
    e hseam hcut hcap

/-- Recognize a comparison from the direct left capping to the naturally charted labelled family
of one-handles by checking it on the three generators of the direct capping atlas. -/
noncomputable def
coordinateUnlinkExteriorPlanarNeckLeftSmoothCappingDiffeomorphOneHandleOfGenerators
    (m : ℕ) [NeZero m]
    (e : CoordinateUnlinkExteriorPlanarNeckLeftSmoothCapping m ≃ₜ
      ZMod m × OneHandlePiece)
    (hseam :
      letI := discreteProductChartedSpace OneHandleModelSpace (ZMod m) OneHandlePiece
      letI := signedSeamFamilyCommonModelChartedSpace m
      IsLocalDiffeomorph coordinateUnlinkExteriorModel oneHandlePieceModel ∞
        (e ∘ coordinateUnlinkExteriorPlanarNeckLeftSmoothCappingSeamMap m))
    (hcut :
      letI := discreteProductChartedSpace OneHandleModelSpace (ZMod m) OneHandlePiece
      letI := compactNeckLeftCutChartedSpace m
      IsLocalDiffeomorph coordinateUnlinkExteriorModel oneHandlePieceModel ∞
        (e ∘ topologicalPushoutInlOffSeamMap'
          (coordinateUnlinkExteriorPlanarNeckLeftCutAttachingMap m)
          (coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
          (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckLeftCutAttachingMap m)))
    (hcap :
      letI := discreteProductChartedSpace OneHandleModelSpace (ZMod m) OneHandlePiece
      letI :=
        coordinateUnlinkExteriorCommonModelEuclideanFourBallFamilyChartedSpace m
      IsLocalDiffeomorph coordinateUnlinkExteriorModel oneHandlePieceModel ∞
        (e ∘ topologicalPushoutInrOffSeamMap'
          (coordinateUnlinkExteriorPlanarNeckLeftCutAttachingMap m)
          (coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
          (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m))) :
    letI := discreteProductChartedSpace OneHandleModelSpace (ZMod m) OneHandlePiece
    letI := coordinateUnlinkExteriorPlanarNeckLeftSmoothCappingChartedSpace m
    CoordinateUnlinkExteriorPlanarNeckLeftSmoothCapping m
      ≃ₘ^∞⟮coordinateUnlinkExteriorModel, oneHandlePieceModel⟯
        ZMod m × OneHandlePiece := by
  let _ := discreteProductChartedSpace OneHandleModelSpace (ZMod m) OneHandlePiece
  let _ : IsManifold oneHandlePieceModel ∞ (ZMod m × OneHandlePiece) :=
    isManifold_discreteProductChartedSpace oneHandlePieceModel ∞
      (ZMod m) OneHandlePiece
  let _ := signedSeamFamilyCommonModelChartedSpace m
  let _ : IsManifold coordinateUnlinkExteriorModel ∞
      (CoordinateUnlinkExteriorPlanarNeckSmoothCappingSignedCollar m) :=
    isManifold_signedSeamFamilyCommonModel m
  let _ := compactNeckLeftCutChartedSpace m
  let _ : IsManifold coordinateUnlinkExteriorModel ∞ (CompactNeckLeftCut m) :=
    isManifold_compactNeckLeftCut m
  let _ :=
    coordinateUnlinkExteriorCommonModelEuclideanFourBallFamilyChartedSpace m
  let _ : IsManifold coordinateUnlinkExteriorModel ∞
      (ZMod m × EuclideanFourBall) :=
    isManifold_coordinateUnlinkExteriorCommonModelEuclideanFourBallFamily m
  exact diffeomorphOfCollaredPushoutHomeomorph
    coordinateUnlinkExteriorModel oneHandlePieceModel ∞
    (coordinateUnlinkExteriorPlanarNeckLeftCutAttachingMap m)
    (coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
    (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckLeftCutAttachingMap m)
    (isClosedEmbedding_coordinateUnlinkExteriorPlanarNeckEuclideanFourBallAttachingMap m)
    (coordinateUnlinkExteriorPlanarNeckLeftSmoothCappingSeamMap m)
    (isOpenEmbedding_coordinateUnlinkExteriorPlanarNeckLeftSmoothCappingSeamMap m)
    (coordinateUnlinkExteriorPlanarNeckLeftSmoothCappingSeamMap_attaching_coverage m)
    (isManifold_coordinateUnlinkExteriorPlanarNeckLeftSmoothCapping m)
    e hseam hcut hcap

end SplittingSpheres

end
