/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import SplittingSpheres.Foundations.RelationMappingClass
public import SplittingSpheres.Handlebody.SmoothCoreDiffeotopyExtension

/-!
# Mapping classes of core-supported one-handle diffeomorphisms

The source group is a proper subgroup of the boundary-relative diffeomorphism group, so its
mapping-class relation must remember that every slice of a witnessing family stays in that same
core-supported subgroup.  We form the quotient generated by precisely those jointly smooth
families and descend smooth capping to the ordinary empty-relative mapping-class group of the
four-sphere.

No claim is made that an arbitrary boundary-relative isotopy stays core-supported.
-/

@[expose] public section

noncomputable section

open Set
open scoped ContDiff Manifold

namespace SplittingSpheres

/-- Two core-supported one-handle diffeomorphisms are related when a genuine jointly smooth
core-supported family joins them. -/
def OneHandleCoreSmoothlyDiffeotopic (rho : ℝ)
    (f g : OneHandleCoreSupportedRelativeDiff rho) : Prop :=
  Nonempty (OneHandleCoreDiffeotopy rho f g)

/-- Constant families make the core-supported endpoint relation reflexive. -/
theorem OneHandleCoreSmoothlyDiffeotopic.refl (rho : ℝ)
    (f : OneHandleCoreSupportedRelativeDiff rho) :
    OneHandleCoreSmoothlyDiffeotopic rho f f :=
  ⟨OneHandleCoreDiffeotopy.refl rho f⟩

/-- The mapping-class group generated only by jointly smooth families that remain in the fixed
core-supported subgroup at every time. -/
abbrev OneHandleCoreMappingClass (rho : ℝ) :=
  RelationMappingClass (OneHandleCoreSmoothlyDiffeotopic rho)

/-- Canonical projection to the constrained core-supported mapping-class group. -/
def oneHandleCoreMappingClassMk (rho : ℝ) :
    OneHandleCoreSupportedRelativeDiff rho →* OneHandleCoreMappingClass rho :=
  relationMappingClassMk (OneHandleCoreSmoothlyDiffeotopic rho)

@[simp]
theorem oneHandleCoreMappingClassMk_one (rho : ℝ) :
    oneHandleCoreMappingClassMk rho 1 = 1 :=
  map_one _

/-- The endpoints of every genuine core-supported diffeotopy have equal constrained classes. -/
theorem OneHandleCoreDiffeotopy.mappingClass_eq
    {rho : ℝ} {f g : OneHandleCoreSupportedRelativeDiff rho}
    (H : OneHandleCoreDiffeotopy rho f g) :
    oneHandleCoreMappingClassMk rho f = oneHandleCoreMappingClassMk rho g :=
  relationMappingClassMk_eq ⟨H⟩

/-- The ordinary joint-smoothness relation on empty-relative sphere diffeomorphisms. -/
def SphereEmptyRelativeSmoothlyDiffeotopic
    (F G : TauCeti.RelativeDiff
      (I := modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4)))
      (Sphere 4) ∞ (∅ : Set (Sphere 4))) : Prop :=
  Nonempty (RelativeDiffeotopy (∅ : Set (Sphere 4)) F G)

/-- The generic endpoint-difference generators for the empty-relative sphere relation are
definitionally the existing relative-diffeotopy generators. -/
theorem endpointDifferenceRelators_sphereEmptyRelative :
    endpointDifferenceRelators SphereEmptyRelativeSmoothlyDiffeotopic =
      relativeDiffeotopyRelators
        (IM := modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4)))
        (∅ : Set (Sphere 4)) :=
  rfl

/-- Smooth core extension sends every constrained source diffeotopy to a genuine empty-relative
sphere diffeotopy. -/
theorem smoothOneHandleCoreExtension_preservesEndpointRelation
    {rho : ℝ} (hrho : rho < 1) :
    PreservesEndpointRelation
      (OneHandleCoreSmoothlyDiffeotopic rho)
      SphereEmptyRelativeSmoothlyDiffeotopic
      (smoothOneHandleCoreExtensionRelativeHom hrho) := by
  intro f g hfg
  obtain ⟨H⟩ := hfg
  exact ⟨H.extension hrho⟩

/-- Smooth capping descends from the constrained core-supported mapping-class group to the
ordinary empty-relative smooth mapping-class group of the four-sphere. -/
def smoothOneHandleCoreMappingClassExtension
    {rho : ℝ} (hrho : rho < 1) :
    OneHandleCoreMappingClass rho →*
      RelativeMappingClass
        (IM := modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4)))
        (∅ : Set (Sphere 4)) :=
  relationMappingClassMap
    (smoothOneHandleCoreExtensionRelativeHom hrho)
    (smoothOneHandleCoreExtension_preservesEndpointRelation hrho)

/-- Representative formula for the induced constrained mapping-class homomorphism. -/
@[simp]
theorem smoothOneHandleCoreMappingClassExtension_mk
    {rho : ℝ} (hrho : rho < 1)
    (f : OneHandleCoreSupportedRelativeDiff rho) :
    smoothOneHandleCoreMappingClassExtension hrho
        (oneHandleCoreMappingClassMk rho f) =
      relativeMappingClassMk
        (IM := modelWithCornersSelf ℝ (EuclideanSpace ℝ (Fin 4)))
        (∅ : Set (Sphere 4))
        (smoothOneHandleCoreExtensionRelativeHom hrho f) :=
  relationMappingClassMap_mk _ _ f

@[simp]
theorem smoothOneHandleCoreMappingClassExtension_one
    {rho : ℝ} (hrho : rho < 1) :
    smoothOneHandleCoreMappingClassExtension hrho 1 = 1 :=
  map_one _

end SplittingSpheres
